##Load necessary packages:##

In [ ]:
!pip install drug-smile-fet
!pip install rdkit

Collecting drug-smile-fet
  Downloading drug_smile_fet-1.0.5-py3-none-any.whl.metadata (3.0 kB)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (from drug-smile-fet) (1.6.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from drug-smile-fet) (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas->drug-smile-fet) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->drug-smile-fet) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->drug-smile-fet) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->drug-smile-fet) (2025.2)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->drug-smile-fet) (1.16.1)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->drug-smile-fet) (1.5.1)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->drug-smile-fet) (3.6.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->drug-smile-fet) (1.17.0)
Downloading drug_smile_fet-1.0.5-py3-none-any.whl (7.1 kB)
Installing collected packages: drug-smile-fet
Successfully installed drug-smile-fet-1.0.5
Collecting rdkit
  Downloading rdkit-2025.3.5-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (4.1 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from rdkit) (2.0.2)
Requirement already satisfied: Pillow in /usr/local/lib/python3.12/dist-packages (from rdkit) (11.3.0)
Downloading rdkit-2025.3.5-cp312-cp312-manylinux_2_28_x86_64.whl (36.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 36.2/36.2 MB 47.0 MB/s eta 0:00:00
Installing collected packages: rdkit
Successfully installed rdkit-2025.3.5

##NLP methods to extract Drug SMILES data:

Load external Smiles:

In [ ]:
import pandas as pd
drugdataset = pd.read_csv('/content/drive/MyDrive/MACSynDCR/Data/Test_and_validation/independent/independent_input.csv')
ext_smailes =  pd.concat([drugdataset['drug1'], drugdataset['drug2']]).unique()
ext_smiles_df = pd.DataFrame(data=ext_smailes)
ext_smiles_df = ext_smiles_df.rename(columns={0: 'SMILES'})

ext_smiles_df.to_csv('/content/drive/MyDrive/MACSynDCR/Data/Drug/ext_smiles.csv', index=False)
ext_smiles_df

                                               SMILES
0   CNC(=O)CN1CCC(CC1)Oc2cc3c(cc2OC)ncnc3Nc4cccc(c...
1   C[C@@H]1CN(C[C@@H](N1)C)c2ccc(cc2)C(=O)Nc3cc(n...
2   CS(=O)(=O)N1CCN(CC1)Cc2cc3c(s2)c(nc(n3)c4cccc5...
3   CC(c1cc(cc2c1oc(cc2=O)N3CCOCC3)C(=O)N(C)C)Nc4c...
4   c1c(c(cnc1N)c2cc(nc(n2)N3CCOCC3)N4CCOCC4)C(F)(F)F
5   CN(CC[C@H](CSc1ccccc1)Nc2ccc(cc2S(=O)(=O)C(F)(...
6        Cn1cnc2c1cc(c(c2F)Nc3ccc(cc3Cl)Br)C(=O)NOCCO
7   COc1cc(ccc1Nc2ncc(c(n2)c3c[nH]c4c3cccc4)Cl)N5C...
8   C[C@H]1COCCN1c2c3ccc(nc3nc(n2)N4CCOC[C@@H]4C)c...
9   C[C@@H]1COCCN1c2cc(nc(n2)c3ccnc4c3cc[nH]4)C5(C...
10  CN(C)CC#Cc1ccc(OCCCc2sc(nc2C(=O)O)N3CCc4cccc(C...
11  CC(=O)Nc1cc(ccc1N(C)CCN)Nc2cc(n3c(n2)c(cn3)C#N...
12                c1cn(c(=O)nc1N)C2C(C(C(O2)CO)O)(F)F
13  CN(C)C/C=C/C(=O)Nc1cc2c(cc1O[C@H]3CCOC3)ncnc2N...
14   COc1cc2c(cc1OCCCN3CCOCC3)c(ncn2)Nc4ccc(c(c4)Cl)F
15  c1cc(ccc1c2ccc3c(c2)cco3)c4nc5cnccc5n4C[C@@H]6...
16  C[C@H]1COCCN1c2c3ccc(nc3nc(n2)N4CCOC[C@@H]4C)c...
17    CN1CCC(CC1)COc2cc3c(cc2OC)c(ncn3)Nc4ccc(cc4F)Br
18  c1ccc(cc1)c2cccc(c2N3CCC[C@H](C3)N)/C=C\4/C(=O...
19  c1ccc2c(c1)c3cccc(c3s2)c4cccc5c4oc(cc5=O)N6CCOCC6
20  Cc1c(sc(n1)NC(=O)N2CCC[C@H]2C(=O)N)c3ccnc(c3)C...
21  c1ccc(cc1)c2cc3c(ccn4c3n[nH]c4=O)nc2c5ccc(cc5)...
22  C[C@H](C(=O)N1CCC(CC1)c2ccc(c(c2)OC)Nc3ncc(c(n...
23  Cc1c(cn(n1)C)Nc2cc(c(cn2)C(F)(F)F)Nc3ccccc3C(=...
24               COc1cc(cnc1)Nc2cncc(n2)c3cnc4n3cccc4
25  COc1cc2c(cc1OC)C3(CCN(CC3)c4c5c([nH]nc5Br)ncn4...
26  c1ccc2c(c1)c(n[nH]c2=O)Cc3ccc(c(c3)C(=O)N4CCN(...
27  c1cc(cc(c1)F)c2cc(c(s2)C(=O)N[C@H]3CCCNC3)NC(=O)N
28  COc1cc(ccc1Nc2ncc(c(n2)c3cnc4n3cccc4)F)N5CCN(C...
29  COC1CCN(CC1)C(=O)c2cc(ccc2F)Cc3c4ccccc4c(=O)[n...
30       CS(=O)(=O)c1ccc(cc1)Nc2cncc(n2)c3cnc4n3cccc4
31  C[C@H](c1c(ccc(c1Cl)F)Cl)Oc2cc(cnc2N)c3cnn(c3)...
32  CCc1c2cc(ccc2nc-3c1Cn4c3cc5c(c4=O)COC(=O)[C@@]...
33  c1cc(c(c(c1)OCC2CC2)c3cc(c4c(n3)NC(=O)OC4)C5CC...
34  CCN1CCN(CC1)CC(=O)Nc2ccc(c3c2c4ccccc4s3)c5cccc...
35  Cc1c(cn(n1)C)Nc2cc(c(cn2)C(F)(F)F)Nc3ccc(cc3C(...
36  CC1(C(=O)Nc2c(ccc(n2)Nc3c(cnc(n3)Nc4cc(c(c(c4)...
37  CN1CCN(CC1)CCOc2cc3c(c(c2)OC4CCOCC4)c(ncn3)Nc5...
38  C[C@]1(C[C@@H](C1)c2n3c(c(ncc3)N)c(n2)c4cc5nc(...
39  CC1=C2C(=C(N(C1=O)C)NC3=C(C=C(C=C3)I)F)C(=O)N(...
40  CC(=O)Nc1cc(ccc1N(C)CCN(C)C)Nc2cc(n3c(n2)c(cn3...
41     c1cc2cc(ccc2nc1)Cn3c4c(ncc(n4)c5cnn(c5)CCO)nn3
42  Cc1c2c(c(n(c1=O)C)Nc3ccc(cc3F)I)c(=O)n(c(=O)n2...
43  Cc1cc(n[nH]1)Nc2c(cnc(n2)N[C@@H](C)c3ncc(cn3)F)Cl
44  c1cc(ccc1[C@H](CCO)NC(=O)C2(CCN(CC2)c3c4cc[nH]...
45  CC1(CCC(=C(C1)CN2CCN(CC2)c3ccc(cc3)C(=O)NS(=O)...
46  CN1CCN(CC1)C2CCN(CC2)c3ccc(c(c3)OC)Nc4ncc(c(n4...
47  CCCS(=O)(=O)Nc1ccc(c(c1F)C(=O)c2c[nH]c3c2cc(cn...
48  CC1C(C(CC(O1)OC2CC(Cc3c2c(c4c(c3O)C(=O)c5cccc(...
49  C[C@@H]1COCCN1c2cc(nc(n2)c3cccc4c3cc[nH]4)C5(C...
50  C[C@@H]1CN(C[C@@H](O1)C)CC(=O)Nc2ccc3c(c2)Cc4c...
51  CS(=O)(=O)C1(CC1)c2cc(nc(n2)c3cccc4c3cc[nH]4)N...

In [ ]:
# @title
unique_values = pd.concat([drugdataset['drug1'], drugdataset['drug2']]).unique()
drug2 = pd.DataFrame(data=unique_values)
drug2

                                                    0
0   CNC(=O)CN1CCC(CC1)Oc2cc3c(cc2OC)ncnc3Nc4cccc(c...
1   C[C@@H]1CN(C[C@@H](N1)C)c2ccc(cc2)C(=O)Nc3cc(n...
2   CS(=O)(=O)N1CCN(CC1)Cc2cc3c(s2)c(nc(n3)c4cccc5...
3   CC(c1cc(cc2c1oc(cc2=O)N3CCOCC3)C(=O)N(C)C)Nc4c...
4   c1c(c(cnc1N)c2cc(nc(n2)N3CCOCC3)N4CCOCC4)C(F)(F)F
5   CN(CC[C@H](CSc1ccccc1)Nc2ccc(cc2S(=O)(=O)C(F)(...
6        Cn1cnc2c1cc(c(c2F)Nc3ccc(cc3Cl)Br)C(=O)NOCCO
7   COc1cc(ccc1Nc2ncc(c(n2)c3c[nH]c4c3cccc4)Cl)N5C...
8   C[C@H]1COCCN1c2c3ccc(nc3nc(n2)N4CCOC[C@@H]4C)c...
9   C[C@@H]1COCCN1c2cc(nc(n2)c3ccnc4c3cc[nH]4)C5(C...
10  CN(C)CC#Cc1ccc(OCCCc2sc(nc2C(=O)O)N3CCc4cccc(C...
11  CC(=O)Nc1cc(ccc1N(C)CCN)Nc2cc(n3c(n2)c(cn3)C#N...
12                c1cn(c(=O)nc1N)C2C(C(C(O2)CO)O)(F)F
13  CN(C)C/C=C/C(=O)Nc1cc2c(cc1O[C@H]3CCOC3)ncnc2N...
14   COc1cc2c(cc1OCCCN3CCOCC3)c(ncn2)Nc4ccc(c(c4)Cl)F
15  c1cc(ccc1c2ccc3c(c2)cco3)c4nc5cnccc5n4C[C@@H]6...
16  C[C@H]1COCCN1c2c3ccc(nc3nc(n2)N4CCOC[C@@H]4C)c...
17    CN1CCC(CC1)COc2cc3c(cc2OC)c(ncn3)Nc4ccc(cc4F)Br
18  c1ccc(cc1)c2cccc(c2N3CCC[C@H](C3)N)/C=C\4/C(=O...
19  c1ccc2c(c1)c3cccc(c3s2)c4cccc5c4oc(cc5=O)N6CCOCC6
20  Cc1c(sc(n1)NC(=O)N2CCC[C@H]2C(=O)N)c3ccnc(c3)C...
21  c1ccc(cc1)c2cc3c(ccn4c3n[nH]c4=O)nc2c5ccc(cc5)...
22  C[C@H](C(=O)N1CCC(CC1)c2ccc(c(c2)OC)Nc3ncc(c(n...
23  Cc1c(cn(n1)C)Nc2cc(c(cn2)C(F)(F)F)Nc3ccccc3C(=...
24               COc1cc(cnc1)Nc2cncc(n2)c3cnc4n3cccc4
25  COc1cc2c(cc1OC)C3(CCN(CC3)c4c5c([nH]nc5Br)ncn4...
26  c1ccc2c(c1)c(n[nH]c2=O)Cc3ccc(c(c3)C(=O)N4CCN(...
27  c1cc(cc(c1)F)c2cc(c(s2)C(=O)N[C@H]3CCCNC3)NC(=O)N
28  COc1cc(ccc1Nc2ncc(c(n2)c3cnc4n3cccc4)F)N5CCN(C...
29  COC1CCN(CC1)C(=O)c2cc(ccc2F)Cc3c4ccccc4c(=O)[n...
30       CS(=O)(=O)c1ccc(cc1)Nc2cncc(n2)c3cnc4n3cccc4
31  C[C@H](c1c(ccc(c1Cl)F)Cl)Oc2cc(cnc2N)c3cnn(c3)...
32  CCc1c2cc(ccc2nc-3c1Cn4c3cc5c(c4=O)COC(=O)[C@@]...
33  c1cc(c(c(c1)OCC2CC2)c3cc(c4c(n3)NC(=O)OC4)C5CC...
34  CCN1CCN(CC1)CC(=O)Nc2ccc(c3c2c4ccccc4s3)c5cccc...
35  Cc1c(cn(n1)C)Nc2cc(c(cn2)C(F)(F)F)Nc3ccc(cc3C(...
36  CC1(C(=O)Nc2c(ccc(n2)Nc3c(cnc(n3)Nc4cc(c(c(c4)...
37  CN1CCN(CC1)CCOc2cc3c(c(c2)OC4CCOCC4)c(ncn3)Nc5...
38  C[C@]1(C[C@@H](C1)c2n3c(c(ncc3)N)c(n2)c4cc5nc(...
39  CC1=C2C(=C(N(C1=O)C)NC3=C(C=C(C=C3)I)F)C(=O)N(...
40  CC(=O)Nc1cc(ccc1N(C)CCN(C)C)Nc2cc(n3c(n2)c(cn3...
41     c1cc2cc(ccc2nc1)Cn3c4c(ncc(n4)c5cnn(c5)CCO)nn3
42  Cc1c2c(c(n(c1=O)C)Nc3ccc(cc3F)I)c(=O)n(c(=O)n2...
43  Cc1cc(n[nH]1)Nc2c(cnc(n2)N[C@@H](C)c3ncc(cn3)F)Cl
44  c1cc(ccc1[C@H](CCO)NC(=O)C2(CCN(CC2)c3c4cc[nH]...
45  CC1(CCC(=C(C1)CN2CCN(CC2)c3ccc(cc3)C(=O)NS(=O)...
46  CN1CCN(CC1)C2CCN(CC2)c3ccc(c(c3)OC)Nc4ncc(c(n4...
47  CCCS(=O)(=O)Nc1ccc(c(c1F)C(=O)c2c[nH]c3c2cc(cn...
48  CC1C(C(CC(O1)OC2CC(Cc3c2c(c4c(c3O)C(=O)c5cccc(...
49  C[C@@H]1COCCN1c2cc(nc(n2)c3cccc4c3cc[nH]4)C5(C...
50  C[C@@H]1CN(C[C@@H](O1)C)CC(=O)Nc2ccc3c(c2)Cc4c...
51  CS(=O)(=O)C1(CC1)c2cc(nc(n2)c3cccc4c3cc[nH]4)N...

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
from dsfet import fe_1mol

test_smile = ext_smiles_df
test_smile_df = pd.DataFrame(test_smile)

#Example 1: to call NLP-based feature extraction method
#Train, Test, feature_sequences, feature_to_token_map = fe_1mol.oneMolFeatureExtraction(trainSMILES=train_smiles_df, testSMILES=train_smiles_df,ngram_list=[1,2,3,4,5,6,7,8])
Train, Test, feature_sequences, feature_to_token_map = fe_1mol.oneMolFeatureExtraction(trainSMILES=ext_smiles_df,
                                testSMILES=None,ngram_list=[1,2,3,4,5,6,7,8])
feature_to_token_map

number of drug selected: 52
number of features created: 1424

  Molecule tokenName
0        F      mol1
1        O      mol2
2       Cl      mol3
3        C      mol4
4        I      mol5
5        B      mol6
6        N      mol7
7       Cn      mol8
8        S      mol9
9       Sc     mol10

In [ ]:
df=Train.iloc[:,6:]
df.to_csv('/content/drive/MyDrive/MACSynDCR/Data/Drug/ext_smileNumData.csv', index=False)
df

,mol2,mol1,mol9,mol10,mol8,mol3,mol6,mol5,mol4 mol7,mol7 mol4,...,mol2 mol4 mol4 mol4 mol2 mol7 mol4 mol9,mol4 mol4 mol4 mol2 mol7 mol4 mol9 mol2,mol4 mol4 mol2 mol7 mol4 mol9 mol2 mol7,mol4 mol2 mol7 mol4 mol9 mol2 mol7 mol4,mol2 mol7 mol4 mol9 mol2 mol7 mol4 mol4,mol7 mol4 mol9 mol2 mol7 mol4 mol4 mol2,mol4 mol9 mol2 mol7 mol4 mol4 mol2 mol4,mol9 mol2 mol7 mol4 mol4 mol2 mol4 mol4,mol4 mol9 mol2 mol2 mol4 mol4 mol4 mol7,mol9 mol2 mol2 mol4 mol4 mol4 mol7 mol4
0,-0.162516,-0.363359,0.396606,-0.176559,-0.237372,0.166933,-0.188300,-0.397274,-0.315199,-0.140028,...,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028
1,-0.292279,-0.363359,0.539895,-0.176559,-0.237372,0.006930,-0.188300,-0.397274,-0.315199,-0.140028,...,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028
2,-0.162516,-0.363359,0.396606,-0.176559,-0.237372,0.166933,-0.188300,1.043508,-0.315199,-0.140028,...,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,7.141428,-0.140028,-0.140028
3,-0.004736,-0.363359,0.249898,-0.176559,-0.237372,0.361481,-0.188300,-0.397274,-0.315199,-0.140028,...,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028
4,-0.623277,-0.363359,0.330176,-0.176559,-0.237372,0.385192,-0.188300,-0.397274,1.285512,-0.140028,...,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028
5,0.212243,-0.363359,0.176495,-0.176559,-0.237372,-0.238648,-0.188300,1.354483,1.423512,-0.140028,...,-0.140028,-0.140028,-0.140028,7.141428,-0.140028,-0.140028,7.141428,-0.140028,-0.140028,-0.140028
6,1.815783,4.261405,-2.488178,-0.176559,5.532101,1.079501,2.989074,-0.397274,-0.315199,-0.140028,...,-0.140028,7.141428,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028
7,-0.977884,3.076395,0.031925,-0.176559,-0.237372,1.432646,-0.188300,-0.397274,-0.315199,-0.140028,...,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028
8,-0.410687,-0.363359,0.626006,-0.176559,-0.237372,-0.139071,-0.188300,-0.397274,-0.315199,-0.140028,...,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028
9,-0.567793,-0.363359,0.677615,-0.176559,-0.237372,-0.332789,-0.188300,1.259452,-0.315199,-0.140028,...,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028
10,-0.085656,-0.363359,0.542863,-0.176559,-0.237372,-0.297220,-0.188300,-0.397274,-0.315199,-0.140028,...,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028
11,-1.317604,-0.363359,-0.378128,-0.176559,-0.237372,2.325964,-0.188300,-0.397274,-0.315199,-0.140028,...,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028
12,1.952447,-0.363359,-0.958198,-0.176559,-0.237372,-0.786805,-0.188300,-0.397274,-0.315199,-0.140028,...,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028
13,-0.292279,-0.363359,0.539895,-0.176559,-0.237372,0.006930,-0.188300,-0.397274,-0.315199,-0.140028,...,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028
14,0.232191,2.289797,0.250516,-0.176559,-0.237372,-0.222251,-0.188300,-0.397274,-0.315199,-0.140028,...,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028
15,-1.205810,-0.363359,1.021971,-0.176559,-0.237372,-1.119488,-0.188300,-0.397274,-0.315199,-0.140028,...,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028
16,0.227989,-0.363359,0.481552,-0.176559,-0.237372,-0.662777,-0.188300,-0.397274,-0.315199,-0.140028,...,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028
17,-0.430934,-0.363359,0.513303,-0.176559,3.182477,-0.164037,-0.188300,-0.397274,-0.315199,-0.140028,...,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028
18,-0.603294,-0.363359,0.455313,-0.176559,-0.237372,0.422153,-0.188300,1.215264,-0.315199,-0.140028,...,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028
19,0.856666,-0.363359,0.011556,-0.176559,-0.237372,-0.275186,-0.188300,-0.397274,-0.315199,-0.140028,...,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028
20,-0.842878,-0.363359,0.424437,-0.176559,-0.237372,-0.020972,-0.188300,-0.397274,2.100644,-0.140028,...,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028
21,-0.367544,-0.363359,0.866149,-0.176559,-0.237372,-1.973993,-0.188300,-0.397274,-0.315199,-0.140028,...,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028
22,0.044469,2.056079,0.455313,-0.176559,-0.237372,-0.376563,-0.188300,-0.397274,-0.315199,-0.140028,...,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028
23,-0.947006,-0.363359,-1.034761,-0.176559,-0.237372,1.546867,-0.188300,-0.397274,4.387618,-0.140028,...,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028
24,1.746346,-0.363359,-2.584804,-0.176559,-0.237372,2.520629,-0.188300,-0.397274,-0.315199,-0.140028,...,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028
25,-0.545039,-0.363359,0.820101,-0.176559,2.916639,-1.139363,-0.188300,-0.397274,-0.315199,-0.140028,...,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028
26,-0.124848,-0.363359,0.571330,-0.176559,-0.237372,-0.515745,-0.188300,-0.397274,-0.315199,-0.140028,...,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028
27,-0.307939,-0.363359,0.091028,-0.176559,-0.237372,0.968428,-0.188300,-0.397274,-0.315199,-0.140028,...,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028
28,-0.307939,-0.363359,0.091028,-0.176559,-0.237372,0.968428,-0.188300,-0.397274,-0.315199,-0.140028,...,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028
29,0.288280,-0.363359,0.458650,-0.176559,-0.237372,-1.075069,-0.188300,-0.397274,-0.315199,-0.140028,...,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028
30,2.873822,-0.363359,-4.336548,-0.176559,-0.237372,0.968428,-0.188300,5.543224,-0.315199,-0.140028,...,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028
31,-1.149531,2.435282,0.684134,-0.176559,-0.237372,-0.126195,-0.188300,-0.397274,-0.315199,-0.140028,...,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028
32,1.447388,-0.363359,-0.206973,-0.176559,-0.237372,-1.973993,-0.188300,-0.397274,-0.315199,-0.140028,...,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028
33,0.227989,-0.363359,0.481552,-0.176559,-0.237372,-0.662777,-0.188300,-0.397274,-0.315199,-0.140028,...,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028
34,-0.441832,-0.363359,0.452645,-0.176559,-0.237372,0.421365,-0.188300,-0.397274,-0.315199,-0.140028,...,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028
35,-0.180472,-0.363359,-1.679319,-0.176559,-0.237372,1.204185,-0.188300,-0.397274,4.387618,-0.140028,...,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028
36,1.847619,-0.363359,-1.401206,-0.176559,-0.237372,0.797705,-0.188300,-0.397274,-0.315199,7.141428,...,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028
37,0.182717,-0.363359,0.453135,-0.176559,-0.237372,-0.434027,-0.188300,-0.397274,-0.315199,-0.140028,...,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028
38,-0.683764,-0.363359,0.796812,-0.176559,-0.237372,-0.475786,-0.188300,-0.397274,-0.315199,-0.140028,...,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028
39,-0.956987,-0.363359,0.861703,2.018686,-0.237372,-0.522352,-0.188300,-0.397274,-0.315199,-0.140028,...,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028
40,-1.396535,-0.363359,0.031249,-0.176559,-0.237372,1.742014,-0.188300,-0.397274,-0.315199,-0.140028,...,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028
41,0.678702,-0.363359,-0.483737,-0.176559,-0.237372,-1.973993,6.425931,-0.397274,-0.315199,-0.140028,...,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028
42,1.098332,-0.363359,-0.358536,6.809277,-0.237372,-0.126195,-0.188300,-0.397274,-0.315199,-0.140028,...,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028
43,-1.898819,-0.363359,0.011556,-0.176559,-0.237372,1.423622,-0.188300,-0.397274,-0.315199,-0.140028,...,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028
44,-0.710950,-0.363359,0.607660,-0.176559,-0.237372,0.223036,-0.188300,-0.397274,-0.315199,-0.140028,...,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028
45,-0.358711,0.595376,0.558127,-0.176559,-0.237372,-0.391484,-0.188300,0.880706,0.914255,-0.140028,...,7.141428,-0.140028,7.141428,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,7.141428,-0.140028
46,-1.363306,1.636820,0.539895,-0.176559,-0.237372,0.667238,-0.188300,-0.397274,-0.315199,-0.140028,...,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028
47,1.672698,-0.363359,-1.444803,-0.176559,-0.237372,0.227913,-0.188300,1.825457,-0.315199,-0.140028,...,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,7.141428,-0.140028,-0.140028,-0.140028,-0.140028
48,1.829437,-0.363359,-0.582615,-0.176559,-0.237372,-1.556077,-0.188300,-0.397274,-0.315199,-0.140028,...,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028
49,0.288280,-0.363359,0.458650,-0.176559,-0.237372,-1.075069,-0.188300,1.417578,-0.315199,-0.140028,...,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028
50,-0.090311,-0.363359,0.521810,-0.176559,-0.237372,-0.301525,-0.188300,0.728250,-0.315199,-0.140028,...,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028,7.141428
51,0.288280,-0.363359,0.458650,-0.176559,-0.237372,-1.075069,-0.188300,1.417578,-0.315199,-0.140028,...,-0.140028,-0.140028,-0.140028,-0.140028,7.141428,-0.140028,-0.140028,-0.140028,-0.140028,-0.140028

# Feature Extraction with Molecular position:

In [ ]:
!pip install rdkit torch dgl

Requirement already satisfied: rdkit in /usr/local/lib/python3.12/dist-packages (2025.3.5)
Requirement already satisfied: torch in /usr/local/lib/python3.12/dist-packages (2.8.0+cu126)
Collecting dgl
  Downloading dgl-2.1.0-cp312-cp312-manylinux1_x86_64.whl.metadata (553 bytes)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from rdkit) (2.0.2)
Requirement already satisfied: Pillow in /usr/local/lib/python3.12/dist-packages (from rdkit) (11.3.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch) (3.19.1)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch) (4.14.1)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch) (1.13.3)
Requirement already satisfied: networkx in /usr/local/lib/python3.12/dist-packages (from torch) (3.5)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch) (3.1.6)
Requirement already satisfied: fsspec in /usr/local/lib/python3.12/dist-packages (from torch) (2025.3.0)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch) (12.6.77)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch) (12.6.77)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.6.80 in /usr/local/lib/python3.12/dist-packages (from torch) (12.6.80)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.6.4.1 in /usr/local/lib/python3.12/dist-packages (from torch) (12.6.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.0.4 in /usr/local/lib/python3.12/dist-packages (from torch) (11.3.0.4)
Requirement already satisfied: nvidia-curand-cu12==10.3.7.77 in /usr/local/lib/python3.12/dist-packages (from torch) (10.3.7.77)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.1.2 in /usr/local/lib/python3.12/dist-packages (from torch) (11.7.1.2)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.4.2 in /usr/local/lib/python3.12/dist-packages (from torch) (12.5.4.2)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.3 in /usr/local/lib/python3.12/dist-packages (from torch) (2.27.3)
Requirement already satisfied: nvidia-nvtx-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch) (12.6.77)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.6.85 in /usr/local/lib/python3.12/dist-packages (from torch) (12.6.85)
Requirement already satisfied: nvidia-cufile-cu12==1.11.1.6 in /usr/local/lib/python3.12/dist-packages (from torch) (1.11.1.6)
Requirement already satisfied: triton==3.4.0 in /usr/local/lib/python3.12/dist-packages (from torch) (3.4.0)
Requirement already satisfied: scipy>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from dgl) (1.16.1)
Requirement already satisfied: requests>=2.19.0 in /usr/local/lib/python3.12/dist-packages (from dgl) (2.32.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from dgl) (4.67.1)
Requirement already satisfied: psutil>=5.8.0 in /usr/local/lib/python3.12/dist-packages (from dgl) (5.9.5)
Requirement already satisfied: torchdata>=0.5.0 in /usr/local/lib/python3.12/dist-packages (from dgl) (0.11.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->dgl) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->dgl) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->dgl) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->dgl) (2025.8.3)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch) (3.0.2)
Downloading dgl-2.1.0-cp312-cp312-manylinux1_x86_64.whl (8.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.6/8.6 MB 18.2 MB/s eta 0:00:00
Installing collected packages: dgl
Successfully installed dgl-2.1.0

In [ ]:
!pip install rdkit-pypi torch
!pip install rdkit-pypi networkx numpy scipy

ERROR: Could not find a version that satisfies the requirement rdkit-pypi (from versions: none)
ERROR: No matching distribution found for rdkit-pypi
ERROR: Could not find a version that satisfies the requirement rdkit-pypi (from versions: none)
ERROR: No matching distribution found for rdkit-pypi

In [ ]:
# @title
import torch
import numpy as np
from rdkit import Chem
from rdkit.Chem import rdmolops

def atom_features(atom) -> torch.Tensor:
    """Extract a binary/numerical feature vector for one atom."""
    features = [
        atom.GetDegree(),                                # Num neighboring atoms
        atom.GetTotalNumHs(),                            # Num hydrogen atoms
        atom.GetTotalValence(),              # Valence
        int(atom.GetIsotope() > 0),                      # Isotope
        int(atom.GetIsAromatic())                        # Aromaticity
    ]
    return torch.tensor(features, dtype=torch.float32)

def build_molecular_graph(smiles: str):
    """Construct graph and features from SMILES using RDKit."""
    mol = Chem.MolFromSmiles(smiles)
    mol = Chem.AddHs(mol)
    n_atoms = mol.GetNumAtoms()

    A = torch.zeros((n_atoms, n_atoms))
    atom_feats = []

    for atom in mol.GetAtoms():
        atom_feats.append(atom_features(atom))

    for bond in mol.GetBonds():
        i = bond.GetBeginAtomIdx()
        j = bond.GetEndAtomIdx()
        A[i, j] = 1
        A[j, i] = 1

    atom_feats = torch.stack(atom_feats)  # Shape: (n_atoms, q)
    return A, atom_feats

def laplacian_positional_encoding(A: torch.Tensor, k: int = None) -> torch.Tensor:
    """Compute Laplacian eigenvectors for position encoding."""
    n = A.shape[0]
    D = torch.diag(A.sum(dim=1))
    D_inv_sqrt = torch.linalg.inv(torch.sqrt(D))
    L = torch.eye(n) - D_inv_sqrt @ A @ D_inv_sqrt

    eigvals, eigvecs = torch.linalg.eigh(L)  # Sorted ascending
    return eigvecs  # Shape: (n, n)

class PositionalEncoder(torch.nn.Module):
    """Linear layer for projecting positional encoding."""
    def __init__(self, input_dim: int, output_dim: int):
        super().__init__()
        self.linear = torch.nn.Linear(input_dim, output_dim)

    def forward(self, U: torch.Tensor) -> torch.Tensor:
        return self.linear(U)

def prepare_drug_input(smiles: str, feature_dim: int = 5, pos_dim: int = 5) -> torch.Tensor:
    A, z = build_molecular_graph(smiles)  # Adjacency matrix and atom features
    U = laplacian_positional_encoding(A)  # Positional encodings

    linear = PositionalEncoder(input_dim=U.shape[1], output_dim=feature_dim)
    U_proj = linear(U)  # Shape: (n_atoms, q)

    X0 = z + U_proj  # x(0)_v = z_v + Linear(U_v)
    return X0  # Shape: (n_atoms, q)

# 🔬 Example
if __name__ == "__main__":
    smiles = "CC(=O)Oc1ccccc1C(=O)O"  # Aspirin
    X_0 = prepare_drug_input(smiles)
    print("X(0) shape:", X_0.shape)
    print("X(0) matrix:\n", X_0)

X(0) shape: torch.Size([21, 5])
X(0) matrix:
 tensor([[ 3.8778e+00,  7.0342e-02,  4.2268e+00,  4.7345e-03,  6.2768e-03],
        [ 3.0052e+00,  1.9345e-01,  4.0983e+00,  2.2650e-01, -1.4823e-01],
        [ 6.1611e-01,  1.2761e-02,  2.1805e+00, -3.6623e-02,  3.3531e-02],
        [ 1.9687e+00, -1.0321e-03,  2.1962e+00, -2.0753e-01, -7.8937e-02],
        [ 2.6946e+00,  8.3468e-02,  4.1573e+00,  3.0372e-02,  8.1067e-01],
        [ 2.9235e+00,  1.2335e-01,  4.4094e+00,  1.2856e-01,  9.7656e-01],
        [ 2.7722e+00,  1.1132e-01,  4.2432e+00, -3.2260e-02,  8.8513e-01],
        [ 2.9654e+00,  7.4532e-02,  4.2220e+00,  9.7432e-02,  8.5436e-01],
        [ 2.7682e+00,  7.7170e-02,  4.2855e+00,  1.0031e-01,  1.1980e+00],
        [ 2.8962e+00, -6.9725e-02,  4.0133e+00,  1.0813e-01,  8.6980e-01],
        [ 2.9442e+00,  1.3742e-01,  4.5848e+00,  1.3115e-01, -4.3057e-01],
        [ 1.0161e+00,  1.1043e-01,  2.4483e+00,  2.5031e-01, -7.4074e-02],
        [ 1.9483e+00,  7.1605e-02,  2.1912e+00,  1.1941e-01, -1.6781e-01],
        [ 9.8361e-01,  5.5051e-02,  1.3034e+00, -1.0050e-01, -3.1587e-01],
        [ 1.0006e+00,  1.8392e-01,  1.3454e+00, -1.2916e-01, -1.3223e-01],
        [ 6.7394e-01,  1.7133e-01,  1.3717e+00, -5.0352e-02, -1.9168e-01],
        [ 9.2046e-01,  2.2382e-01,  1.1195e+00,  7.2349e-02, -7.7600e-02],
        [ 7.0404e-01,  3.6201e-01,  9.3644e-01, -2.1085e-02, -1.9846e-01],
        [ 8.2538e-01, -2.3668e-02,  1.2116e+00, -1.6324e-01, -1.3725e-01],
        [ 8.2921e-01,  1.5505e-01,  1.2729e+00,  5.7798e-02, -1.3024e-01],
        [ 9.6240e-01,  3.5001e-01,  1.2256e+00,  1.7390e-01, -1.6918e-01]],
       grad_fn=<AddBackward0>)

In [ ]:
# @title
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
import pandas as pd
from rdkit import Chem
import random
from tqdm import tqdm
import argparse

# ---------- Feature Functions ----------
def atom_features(atom):
    return torch.tensor([
        atom.GetDegree(),
        atom.GetTotalNumHs(),
        atom.GetTotalValence(),
        int(atom.GetIsotope() > 0),
        int(atom.GetIsAromatic())
    ], dtype=torch.float32)

def bond_features(bond):
    return torch.tensor([
        int(bond.GetBondTypeAsDouble()),
        int(bond.GetIsConjugated())
    ], dtype=torch.float32)

def smiles_to_graph(smiles):
    mol = Chem.MolFromSmiles(smiles)
    mol = Chem.AddHs(mol)
    n = mol.GetNumAtoms()

    node_feats = []
    edge_index = []
    edge_feats = []

    for atom in mol.GetAtoms():
        node_feats.append(atom_features(atom))

    for bond in mol.GetBonds():
        i = bond.GetBeginAtomIdx()
        j = bond.GetEndAtomIdx()
        edge_index.append([i, j])
        edge_index.append([j, i])
        edge_feats.append(bond_features(bond))
        edge_feats.append(bond_features(bond))

    node_feats = torch.stack(node_feats)
    edge_index = torch.tensor(edge_index).T
    edge_feats = torch.stack(edge_feats)

    adj = torch.zeros((n, n))
    for i, j in edge_index.T:
        adj[i, j] = 1

    return node_feats, edge_index, edge_feats, adj

def laplacian_positional_encoding(adj, k=32):
    n = adj.size(0)
    D = torch.diag(adj.sum(dim=1))
    D_inv_sqrt = torch.linalg.inv(torch.sqrt(D))
    L = torch.eye(n) - D_inv_sqrt @ adj @ D_inv_sqrt
    _, eigvecs = torch.linalg.eigh(L)

    if n >= k:
        return eigvecs[:, :k]
    else:
        padding = torch.zeros(n, k - n, device=eigvecs.device)
        return torch.cat([eigvecs, padding], dim=1)

# ---------- MGTN and GRAN Layers ----------
class GRANLayer(nn.Module):
    def __init__(self, in_dim, edge_dim, hidden_dim, num_samples=3):
        super().__init__()
        self.num_samples = num_samples
        self.hidden_dim = hidden_dim
        self.edge_dim = edge_dim
        self.attn_fc = nn.Linear(2 * in_dim + edge_dim, hidden_dim)
        self.lambda_param = nn.Parameter(torch.empty(hidden_dim))
        self.message_mlp = nn.Sequential(
            nn.Linear(in_dim, hidden_dim),
            nn.ReLU(),
            nn.Linear(hidden_dim, in_dim)
        )
        nn.init.xavier_uniform_(self.lambda_param.view(1, -1))

    def forward(self, x, edge_index, edge_attr):
        n = x.size(0)
        device = x.device
        adj_list = [[] for _ in range(n)]
        edge_dict = {}

        for idx in range(edge_index.shape[1]):
            i, j = edge_index[:, idx]
            adj_list[i.item()].append(j.item())
            edge_dict[(i.item(), j.item())] = edge_attr[idx]

        x_gran = torch.zeros_like(x)

        for v in range(n):
            sampled = random.sample(adj_list[v], min(len(adj_list[v]), self.num_samples)) if adj_list[v] else []
            agg_messages = []
            attn_scores = []

            for u in sampled:
                e = edge_dict.get((v, u), torch.zeros(self.edge_dim, device=device))
                h = torch.cat([x[v], e, x[u]], dim=0)
                phi = F.leaky_relu(self.attn_fc(h))
                alpha = torch.dot(self.lambda_param, phi)
                attn_scores.append(alpha)
                agg_messages.append(self.message_mlp(F.relu(x[u])))

            if attn_scores:
                weights = F.softmax(torch.stack(attn_scores), dim=0)
                weighted_sum = sum(w * m for w, m in zip(weights, agg_messages))
                x_gran[v] = weighted_sum + x[v]

        return x_gran

class MGTNLayer(nn.Module):
    def __init__(self, in_dim):
        super().__init__()
        self.q_fc = nn.Linear(in_dim, in_dim)
        self.k_fc = nn.Linear(in_dim, in_dim)
        self.v_fc = nn.Linear(in_dim, in_dim)
        self.combine = nn.Linear(in_dim, in_dim)

    def forward(self, x):
        Q = self.q_fc(x)
        K = self.k_fc(x)
        V = self.v_fc(x)
        scores = torch.matmul(Q, K.T) / (Q.shape[-1] ** 0.5)
        attn = F.softmax(scores, dim=-1)
        context = torch.matmul(attn, V)
        return self.combine(context)

# ---------- Encoder ----------
class MGTNSynDrugEncoder(nn.Module):
    def __init__(self, feat_dim, pos_dim, edge_dim, hidden_dim):
        super().__init__()
        self.atom_fc = nn.Linear(5, feat_dim)
        self.linear_pos = nn.Linear(pos_dim, feat_dim)
        self.gran = GRANLayer(in_dim=feat_dim, edge_dim=edge_dim, hidden_dim=hidden_dim)
        self.mgtn = MGTNLayer(in_dim=feat_dim)
        self.encoder = nn.Linear(feat_dim * 2, feat_dim)

    def forward(self, smiles):
        x, edge_index, edge_attr, adj = smiles_to_graph(smiles)
        x = self.atom_fc(x)
        U = laplacian_positional_encoding(adj, k=32)
        U_proj = self.linear_pos(U)
        x0 = x + U_proj
        x_gran = self.gran(x0, edge_index, edge_attr)
        x_mgtn = self.mgtn(x0)
        x_comb = torch.cat([x_gran, x_mgtn], dim=-1)
        return F.relu(self.encoder(x_comb))

# ---------- VAE ----------
class DrugComboVAE(nn.Module):
    def __init__(self, feat_dim=64, latent_dim=128, pos_dim=32, edge_dim=2, hidden_dim=128):
        super().__init__()
        self.encoder = MGTNSynDrugEncoder(feat_dim, pos_dim, edge_dim, hidden_dim)
        self.fc_mu = nn.Linear(feat_dim, latent_dim)
        self.fc_logvar = nn.Linear(feat_dim, latent_dim)
        self.decoder = nn.Sequential(
            nn.Linear(latent_dim, 128),
            nn.ReLU(),
            nn.Linear(128, feat_dim)
        )
        self.classifier = nn.Sequential(
            nn.Linear(latent_dim * 2, 128),
            nn.ReLU(),
            nn.Linear(128, 1)
        )

    def encode(self, smiles):
        x = self.encoder(smiles)
        h = x.mean(dim=0)
        mu = self.fc_mu(h)
        logvar = self.fc_logvar(h)
        std = torch.exp(0.5 * logvar)
        eps = torch.randn_like(std)
        z = mu + eps * std
        return z, mu, logvar, h

    def forward(self, s1, s2):
        z1, mu1, lv1, h1 = self.encode(s1)
        z2, mu2, lv2, h2 = self.encode(s2)
        r1 = self.decoder(z1)
        r2 = self.decoder(z2)
        out = self.classifier(torch.cat([z1, z2], dim=-1))
        return out, (r1, h1), (r2, h2), (mu1, lv1), (mu2, lv2)

# ---------- Dataset ----------
class DrugComboDataset(Dataset):
    def __init__(self, csv_path):
        df = pd.read_csv(csv_path)
        self.smiles1 = df['drug_a_name'].tolist()
        self.smiles2 = df['drug_b_name'].tolist()
        self.labels = df['SynClass'].tolist()

    def __len__(self):
        return len(self.labels)

    def __getitem__(self, idx):
        return self.smiles1[idx], self.smiles2[idx], torch.tensor(self.labels[idx], dtype=torch.float32)

# ---------- Loss ----------
def combo_vae_loss(pred, label, r1, h1, r2, h2, mu1, lv1, mu2, lv2):
    pred_loss = F.mse_loss(pred.view(-1), label.view(-1))
    recon_loss = F.mse_loss(r1, h1) + F.mse_loss(r2, h2)
    kl = -0.5 * torch.sum(1 + lv1 - mu1.pow(2) - lv1.exp()) - 0.5 * torch.sum(1 + lv2 - mu2.pow(2) - lv2.exp())
    return pred_loss + recon_loss + 1e-3 * kl

# ---------- Training ----------
def train(args):
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    temp_csv_path = 'temp_drug_combinations.csv'
    args.data.to_csv(temp_csv_path, index=False)
    dataset = DrugComboDataset(csv_path=temp_csv_path)
    loader = DataLoader(dataset, batch_size=1, shuffle=True)
    model = DrugComboVAE().to(device)
    optimizer = torch.optim.Adam(model.parameters(), lr=args.lr)

    for epoch in range(args.epochs):
        model.train()
        total_loss = 0
        for s1, s2, y in tqdm(loader):
            s1, s2, y = s1[0], s2[0], y.to(device)
            try:
                out, (r1, h1), (r2, h2), (mu1, lv1), (mu2, lv2) = model(s1, s2)
                loss = combo_vae_loss(out, y, r1, h1, r2, h2, mu1, lv1, mu2, lv2)
                optimizer.zero_grad()
                loss.backward()
                optimizer.step()
                total_loss += loss.item()
            except Exception as e:
                print(f"Error in combo: {e}")
        print(f"Epoch {epoch+1}, Loss: {total_loss / len(loader):.4f}")

In [ ]:
# @title
import pandas as pd
DataID = pd.read_csv('/content/drive/MyDrive/MACSynDCR/Data/drug_cell_id.csv')
DataID = pd.DataFrame(data=DataID)
#smiles_list=smiles.iloc[:,2]
DataID

,drug_id,drug_name,drug_smiles,cell_id,cell_name
0,0.0,5-FU,O=c1[nH]cc(F)c(=O)[nH]1,0,A2058
1,1.0,ABT-888,CC1(c2nc3c(C(N)=O)cccc3[nH]2)CCCN1,1,A2780
2,2.0,AZD1775,C=CCn1c(=O)c2cnc(Nc3ccc(N4CCN(C)CC4)cc3)nc2n1-...,2,A375
3,3.0,BEZ-235,Cn1c(=O)n(-c2ccc(C(C)(C)C#N)cc2)c2c3cc(-c4cnc5...,3,A427
4,4.0,BORTEZOMIB,CC(C)CC(NC(=O)C(Cc1ccccc1)NC(=O)c1cnccn1)B(O)O,4,CAOV3
5,5.0,CARBOPLATIN,N.N.O=C(O)C1(C(=O)O)CCC1.[Pt],5,COLO320DM
6,6.0,CYCLOPHOSPHAMIDE,O=P1(N(CCCl)CCCl)NCCCO1,6,DLD1
7,7.0,DASATINIB,Cc1nc(Nc2ncc(C(=O)Nc3c(C)cccc3Cl)s2)cc(N2CCN(C...,7,EFM192B
8,8.0,DEXAMETHASONE,CC1CC2C3CCC4=CC(=O)C=CC4(C)C3(F)C(O)CC2(C)C1(O...,8,ES2
9,9.0,DINACICLIB,CCc1cnn2c(NCc3ccc[n+]([O-])c3)cc(N3CCCCC3CCO)nc12,9,HCT116
10,10.0,DOXORUBICIN,COc1cccc2c1C(=O)c1c(O)c3c(c(O)c1C2=O)CC(O)(C(=...,10,HT144
11,11.0,ERLOTINIB,C#Cc1cccc(Nc2ncnc3cc(OCCOC)c(OCCOC)cc23)c1,11,HT29
12,12.0,ETOPOSIDE,COc1cc(C2c3cc4c(cc3C(OC3OC5COC(C)OC5C(O)C3O)C3...,12,KPL1
13,13.0,GELDANAMYCIN,COC1=C2CC(C)CC(OC)C(O)C(C)C=C(C)C(OC(N)=O)C(OC...,13,LNCAP
14,14.0,GEMCITABINE,Nc1ccn(C2OC(CO)C(O)C2(F)F)c(=O)n1,14,LOVO
15,15.0,L778123,N#Cc1ccc(Cn2cncc2CN2CCN(c3cccc(Cl)c3)C(=O)C2)cc1,15,MDAMB436
16,16.0,LAPATINIB,CS(=O)(=O)CCNCc1ccc(-c2ccc3ncnc(Nc4ccc(OCc5ccc...,16,MSTO
17,17.0,METFORMIN,CN(C)C(=N)N=C(N)N,17,NCIH1650
18,18.0,METHOTREXATE,CN(Cc1cnc2nc(N)nc(N)c2n1)c1ccc(C(=O)NC(CCC(=O)...,18,NCIH2122
19,19.0,MITOMYCINE,COC12C(COC(N)=O)C3=C(C(=O)C(C)=C(N)C3=O)N1CC1NC12,19,NCIH23
20,20.0,MK-2206,NC1(c2ccc(-c3nc4ccn5c(=O)[nH]nc5c4cc3-c3ccccc3...,20,NCIH460
21,21.0,MK-4541,CN1C(=O)C=CC2(C)C3CCC4(C)C(NC(=O)OCC(F)(F)F)CC...,21,NCIH520
22,22.0,MK-4827,NC(=O)c1cccc2cn(-c3ccc(C4CCCNC4)cc3)nc12,22,OCUBM
23,23.0,MK-5108,O=C(O)C1(Cc2cccc(Nc3nccs3)n2)CCC(Oc2cccc(Cl)c2...,23,OV90
24,24.0,MK-8669,COC1CC2CCC(C)C(O)(O2)C(=O)C(=O)N2CCCCC2C(=O)OC...,24,OVCAR3
25,25.0,MK-8776,Cn1cc(-c2cnn3c(N)c(Br)c(C4CCCNC4)nc23)cn1,25,PA1
26,26.0,MRK-003,O=S1(=O)NC2(CN1CC(F)(F)F)C1CCC2Cc2cc(C=CCN3CCC...,26,RKO
27,27.0,OXALIPLATIN,NC1CCCCC1N.O=C(O)C(=O)O.[Pt+2],27,RPMI7951
28,28.0,PACLITAXEL,CC(=O)OC1C(=O)C2(C)C(O)CC3OCC3(OC(C)=O)C2C(OC(...,28,SKMEL30
29,29.0,PD325901,O=C(NOCC(O)CO)c1ccc(F)c(F)c1Nc1ccc(I)cc1F,29,SKMES1
30,30.0,SN-38,CCc1c2c(nc3ccc(O)cc13)-c1cc3c(c(=O)n1C2)COC(=O...,30,SKOV3
31,31.0,SORAFENIB,CNC(=O)c1cc(Oc2ccc(NC(=O)Nc3ccc(Cl)c(C(F)(F)F)...,31,SW620
32,32.0,SUNITINIB,CCN(CC)CCNC(=O)c1c(C)[nH]c(C=C2C(=O)Nc3ccc(F)c...,32,SW837
33,33.0,TEMOZOLOMIDE,Cn1nnc2c(C(N)=O)ncn2c1=O,33,T47D
34,34.0,TOPOTECAN,CCC1(O)C(=O)OCc2c1cc1n(c2=O)Cc2cc3c(CN(C)C)c(O...,34,UACC62
35,35.0,VINBLASTINE,CCC1(O)CC2CN(CCc3c([nH]c4ccccc34)C(C(=O)OC)(c3...,35,UWB1289
36,36.0,VINORELBINE,CCC1=CC2CN(C1)Cc1c([nH]c3ccccc13)C(C(=O)OC)(c1...,36,UWB1289BRCA1
37,37.0,ZOLINZA,O=C(CCCCCCC(=O)Nc1ccccc1)NO,37,VCAP
38,NaN,NaN,NaN,38,ZR751

In [ ]:
# @title
import pandas as pd
DrugData = pd.read_csv('/content/drive/MyDrive/MACSynDCR/Data/OneilDataset_0to10.csv')
DrugCombinations = pd.DataFrame(data=DrugData[['drug_a_name', 	'drug_b_name','SynClass']])
DrugCombinations.head()

  drug_a_name drug_b_name  SynClass
0        5-FU     ABT-888         0
1        5-FU     ABT-888         0
2        5-FU     ABT-888         0
3        5-FU     ABT-888         0
4        5-FU     ABT-888         1

In [ ]:
# @title
# prompt: Using dataframe DrugCombinations: replace the values of 'drug_a_name' and 'drug_b_name' using corespoding drug_smiles in DataID dataframe

# Define the mapping from drug name to drug smiles
drug_mapping = DataID.set_index('drug_name')['drug_smiles'].to_dict()

# Replace drug_a_name and drug_b_name with drug smiles
DrugCombinations['drug_a_name'] = DrugCombinations['drug_a_name'].map(drug_mapping)
DrugCombinations['drug_b_name'] = DrugCombinations['drug_b_name'].map(drug_mapping)
DrugCombinations.head()

               drug_a_name                         drug_b_name  SynClass
0  O=c1[nH]cc(F)c(=O)[nH]1  CC1(c2nc3c(C(N)=O)cccc3[nH]2)CCCN1         0
1  O=c1[nH]cc(F)c(=O)[nH]1  CC1(c2nc3c(C(N)=O)cccc3[nH]2)CCCN1         0
2  O=c1[nH]cc(F)c(=O)[nH]1  CC1(c2nc3c(C(N)=O)cccc3[nH]2)CCCN1         0
3  O=c1[nH]cc(F)c(=O)[nH]1  CC1(c2nc3c(C(N)=O)cccc3[nH]2)CCCN1         0
4  O=c1[nH]cc(F)c(=O)[nH]1  CC1(c2nc3c(C(N)=O)cccc3[nH]2)CCCN1         1

In [ ]:
# @title
class Args:
    def __init__(self, epochs, lr,data):
        self.epochs = epochs
        self.lr = lr
        self.data = data

args = Args(epochs=10, lr=1e-3, data=DrugCombinations) # Set your desired epoch and learning rate here

train(args)

  0%|          | 2/16771 [00:00<1:07:17,  4.15it/s]

Error in combo: linalg.inv: The diagonal element 13 is zero, the inversion could not be completed because the input matrix is singular.
Error in combo: linalg.inv: The diagonal element 15 is zero, the inversion could not be completed because the input matrix is singular.

  0%|          | 6/16771 [00:00<33:31,  8.33it/s]

Error in combo: linalg.inv: The diagonal element 15 is zero, the inversion could not be completed because the input matrix is singular.

  0%|          | 50/16771 [00:10<47:03,  5.92it/s]

Error in combo: linalg.inv: The diagonal element 15 is zero, the inversion could not be completed because the input matrix is singular.

  0%|          | 54/16771 [00:11<58:42,  4.75it/s]

Error in combo: linalg.inv: The diagonal element 13 is zero, the inversion could not be completed because the input matrix is singular.

  0%|          | 61/16771 [00:12<43:39,  6.38it/s]

Error in combo: linalg.inv: The diagonal element 13 is zero, the inversion could not be completed because the input matrix is singular.

  0%|          | 74/16771 [00:15<55:02,  5.06it/s]

Error in combo: linalg.inv: The diagonal element 13 is zero, the inversion could not be completed because the input matrix is singular.

  1%|          | 90/16771 [00:17<37:36,  7.39it/s]

Error in combo: linalg.inv: The diagonal element 15 is zero, the inversion could not be completed because the input matrix is singular.

  1%|          | 95/16771 [00:18<1:05:35,  4.24it/s]

Error in combo: linalg.inv: The diagonal element 13 is zero, the inversion could not be completed because the input matrix is singular.

  1%|          | 97/16771 [00:19<1:00:48,  4.57it/s]

Error in combo: linalg.inv: The diagonal element 13 is zero, the inversion could not be completed because the input matrix is singular.

  1%|          | 109/16771 [00:22<43:36,  6.37it/s]

Error in combo: linalg.inv: The diagonal element 13 is zero, the inversion could not be completed because the input matrix is singular.
Error in combo: linalg.inv: The diagonal element 15 is zero, the inversion could not be completed because the input matrix is singular.

  1%|          | 138/16771 [00:27<48:33,  5.71it/s]

Error in combo: linalg.inv: The diagonal element 13 is zero, the inversion could not be completed because the input matrix is singular.

  1%|          | 146/16771 [00:28<56:42,  4.89it/s]

Error in combo: linalg.inv: The diagonal element 15 is zero, the inversion could not be completed because the input matrix is singular.
Error in combo: linalg.inv: The diagonal element 13 is zero, the inversion could not be completed because the input matrix is singular.

  1%|          | 192/16771 [00:37<36:53,  7.49it/s]

Error in combo: linalg.inv: The diagonal element 15 is zero, the inversion could not be completed because the input matrix is singular.

  1%|          | 202/16771 [00:39<39:03,  7.07it/s]

Error in combo: linalg.inv: The diagonal element 15 is zero, the inversion could not be completed because the input matrix is singular.

  1%|          | 207/16771 [00:40<38:53,  7.10it/s]

Error in combo: linalg.inv: The diagonal element 15 is zero, the inversion could not be completed because the input matrix is singular.

  1%|▏         | 218/16771 [00:42<1:09:22,  3.98it/s]

Error in combo: linalg.inv: The diagonal element 15 is zero, the inversion could not be completed because the input matrix is singular.

  1%|▏         | 227/16771 [00:45<1:15:50,  3.64it/s]

Error in combo: linalg.inv: The diagonal element 15 is zero, the inversion could not be completed because the input matrix is singular.

  2%|▏         | 253/16771 [00:50<41:09,  6.69it/s]

Error in combo: linalg.inv: The diagonal element 13 is zero, the inversion could not be completed because the input matrix is singular.

  2%|▏         | 294/16771 [00:59<1:16:22,  3.60it/s]

Error in combo: linalg.inv: The diagonal element 15 is zero, the inversion could not be completed because the input matrix is singular.

  2%|▏         | 301/16771 [01:01<1:16:47,  3.57it/s]

Error in combo: linalg.inv: The diagonal element 13 is zero, the inversion could not be completed because the input matrix is singular.

  2%|▏         | 353/16771 [01:11<56:03,  4.88it/s]

Error in combo: linalg.inv: The diagonal element 15 is zero, the inversion could not be completed because the input matrix is singular.
Error in combo: linalg.inv: The diagonal element 15 is zero, the inversion could not be completed because the input matrix is singular.

  2%|▏         | 368/16771 [01:14<51:52,  5.27it/s]

Error in combo: linalg.inv: The diagonal element 13 is zero, the inversion could not be completed because the input matrix is singular.
Error in combo: linalg.inv: The diagonal element 13 is zero, the inversion could not be completed because the input matrix is singular.

  2%|▏         | 377/16771 [01:16<44:41,  6.11it/s]

Error in combo: linalg.inv: The diagonal element 13 is zero, the inversion could not be completed because the input matrix is singular.

  2%|▏         | 385/16771 [01:17<37:02,  7.37it/s]

Error in combo: linalg.inv: The diagonal element 13 is zero, the inversion could not be completed because the input matrix is singular.

  2%|▏         | 387/16771 [01:18<41:52,  6.52it/s]

Error in combo: linalg.inv: The diagonal element 13 is zero, the inversion could not be completed because the input matrix is singular.

  2%|▏         | 396/16771 [01:19<49:17,  5.54it/s]

Error in combo: linalg.inv: The diagonal element 13 is zero, the inversion could not be completed because the input matrix is singular.

  2%|▏         | 410/16771 [01:22<52:03,  5.24it/s]

Error in combo: linalg.inv: The diagonal element 15 is zero, the inversion could not be completed because the input matrix is singular.

  2%|▏         | 414/16771 [01:22<41:43,  6.53it/s]

Error in combo: linalg.inv: The diagonal element 15 is zero, the inversion could not be completed because the input matrix is singular.

  3%|▎         | 448/16771 [01:30<41:21,  6.58it/s]

Error in combo: linalg.inv: The diagonal element 13 is zero, the inversion could not be completed because the input matrix is singular.

  3%|▎         | 465/16771 [01:33<40:57,  6.64it/s]

Error in combo: linalg.inv: The diagonal element 15 is zero, the inversion could not be completed because the input matrix is singular.

  3%|▎         | 468/16771 [01:33<32:08,  8.45it/s]

Error in combo: linalg.inv: The diagonal element 15 is zero, the inversion could not be completed because the input matrix is singular.
Error in combo: linalg.inv: The diagonal element 15 is zero, the inversion could not be completed because the input matrix is singular.

  3%|▎         | 481/16771 [01:36<50:43,  5.35it/s]

Error in combo: linalg.inv: The diagonal element 13 is zero, the inversion could not be completed because the input matrix is singular.

  3%|▎         | 495/16771 [01:38<40:20,  6.72it/s]

Error in combo: linalg.inv: The diagonal element 13 is zero, the inversion could not be completed because the input matrix is singular.
Error in combo: linalg.inv: The diagonal element 15 is zero, the inversion could not be completed because the input matrix is singular.

  3%|▎         | 506/16771 [01:41<1:12:25,  3.74it/s]

Error in combo: linalg.inv: The diagonal element 13 is zero, the inversion could not be completed because the input matrix is singular.

  3%|▎         | 519/16771 [01:43<38:52,  6.97it/s]

Error in combo: linalg.inv: The diagonal element 15 is zero, the inversion could not be completed because the input matrix is singular.

  3%|▎         | 524/16771 [01:44<39:45,  6.81it/s]

Error in combo: linalg.inv: The diagonal element 13 is zero, the inversion could not be completed because the input matrix is singular.

  3%|▎         | 531/16771 [01:45<37:20,  7.25it/s]

Error in combo: linalg.inv: The diagonal element 15 is zero, the inversion could not be completed because the input matrix is singular.

  3%|▎         | 559/16771 [01:51<59:29,  4.54it/s]

Error in combo: linalg.inv: The diagonal element 15 is zero, the inversion could not be completed because the input matrix is singular.

  3%|▎         | 569/16771 [01:53<59:41,  4.52it/s]

Error in combo: linalg.inv: The diagonal element 13 is zero, the inversion could not be completed because the input matrix is singular.

  4%|▎         | 601/16771 [02:01<59:09,  4.56it/s]

Error in combo: linalg.inv: The diagonal element 15 is zero, the inversion could not be completed because the input matrix is singular.

  4%|▎         | 604/16771 [02:01<56:21,  4.78it/s]

Error in combo: linalg.inv: The diagonal element 15 is zero, the inversion could not be completed because the input matrix is singular.

  4%|▎         | 606/16771 [02:02<53:25,  5.04it/s]

Error in combo: linalg.inv: The diagonal element 13 is zero, the inversion could not be completed because the input matrix is singular.

  4%|▎         | 610/16771 [02:03<57:04,  4.72it/s]

Error in combo: linalg.inv: The diagonal element 15 is zero, the inversion could not be completed because the input matrix is singular.

  4%|▎         | 624/16771 [02:06<47:44,  5.64it/s]

Error in combo: linalg.inv: The diagonal element 15 is zero, the inversion could not be completed because the input matrix is singular.

  4%|▍         | 674/16771 [02:17<52:43,  5.09it/s]

Error in combo: linalg.inv: The diagonal element 13 is zero, the inversion could not be completed because the input matrix is singular.

  4%|▍         | 696/16771 [02:22<1:18:24,  3.42it/s]

Error in combo: linalg.inv: The diagonal element 13 is zero, the inversion could not be completed because the input matrix is singular.

  5%|▍         | 768/16771 [02:37<58:21,  4.57it/s]

Error in combo: linalg.inv: The diagonal element 13 is zero, the inversion could not be completed because the input matrix is singular.

  5%|▍         | 784/16771 [02:39<39:47,  6.70it/s]

Error in combo: linalg.inv: The diagonal element 15 is zero, the inversion could not be completed because the input matrix is singular.

  5%|▍         | 784/16771 [02:40<54:26,  4.89it/s]

KeyboardInterrupt:

In [ ]:
# @title
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
import pandas as pd
from rdkit import Chem
import random
from tqdm import tqdm
import argparse
import os

# ---------- Feature Functions ----------
def atom_features(atom):
    return torch.tensor([
        atom.GetDegree(),
        atom.GetTotalNumHs(),
        atom.GetTotalValence(),
        int(atom.GetIsotope() > 0),
        int(atom.GetIsAromatic())
    ], dtype=torch.float32)

def bond_features(bond):
    return torch.tensor([
        int(bond.GetBondTypeAsDouble()),
        int(bond.GetIsConjugated())
    ], dtype=torch.float32)

def smiles_to_graph(smiles):
    mol = Chem.MolFromSmiles(smiles)
    # Handle cases where SMILES are invalid
    if mol is None:
        # Return empty tensors or handle as appropriate for your model
        return torch.empty(0, 5), torch.empty(2, 0, dtype=torch.long), torch.empty(0, 2), torch.empty(0, 0)

    mol = Chem.AddHs(mol)
    n = mol.GetNumAtoms()

    node_feats = []
    edge_index = []
    edge_feats = []

    for atom in mol.GetAtoms():
        node_feats.append(atom_features(atom))

    for bond in mol.GetBonds():
        i = bond.GetBeginAtomIdx()
        j = bond.GetEndAtomIdx()
        edge_index.append([i, j])
        edge_index.append([j, i])
        edge_feats.append(bond_features(bond))
        edge_feats.append(bond_features(bond))

    if not node_feats: # Handle empty list if no atoms
        node_feats = torch.empty(0, 5)
    else:
        node_feats = torch.stack(node_feats)

    if not edge_index: # Handle empty list if no bonds
        edge_index = torch.empty(2, 0, dtype=torch.long)
        edge_feats = torch.empty(0, 2)
        adj = torch.empty(n, n) # Initialize adjacency for a molecule with no bonds
    else:
        edge_index = torch.tensor(edge_index).T
        edge_feats = torch.stack(edge_feats)
        adj = torch.zeros((n, n))
        for i, j in edge_index.T:
            adj[i, j] = 1


    return node_feats, edge_index, edge_feats, adj


def laplacian_positional_encoding(adj, k=32):
    n = adj.size(0)
    if n == 0: # Handle empty adjacency matrix
        return torch.zeros(0, k, device=adj.device) # Ensure device consistency
    D = torch.diag(adj.sum(dim=1))
    # Handle potential division by zero if a node has no neighbors by adding epsilon
    D_inv_sqrt = torch.linalg.inv(torch.sqrt(D + 1e-8)) # Add small epsilon for stability
    L = torch.eye(n, device=adj.device) - D_inv_sqrt @ adj @ D_inv_sqrt

    # Ensure L is symmetric before eigh
    L = (L + L.T) * 0.5

    try:
        eigvals, eigvecs = torch.linalg.eigh(L)
    except Exception as e:
        print(f"Error during eigendecomposition: {e}")
        # Return a zero tensor of expected size in case of an error
        return torch.zeros(n, k, device=adj.device)


    if n >= k:
        return eigvecs[:, :k]
    else:
        padding = torch.zeros(n, k - n, device=eigvecs.device)
        return torch.cat([eigvecs, padding], dim=1)

# ---------- MGTN and GRAN Layers ----------
class GRANLayer(nn.Module):
    def __init__(self, in_dim, edge_dim, hidden_dim, num_samples=3):
        super().__init__()
        self.num_samples = num_samples
        self.hidden_dim = hidden_dim
        self.edge_dim = edge_dim
        self.attn_fc = nn.Linear(2 * in_dim + edge_dim, hidden_dim)
        self.lambda_param = nn.Parameter(torch.empty(hidden_dim))
        self.message_mlp = nn.Sequential(
            nn.Linear(in_dim, hidden_dim),
            nn.ReLU(),
            nn.Linear(hidden_dim, in_dim)
        )
        nn.init.xavier_uniform_(self.lambda_param.view(1, -1))

    def forward(self, x, edge_index, edge_attr):
        n = x.size(0)
        if n == 0: # Handle empty input
            return torch.empty_like(x)

        device = x.device
        adj_list = [[] for _ in range(n)]
        edge_dict = {}

        # Check if edge_index is empty
        if edge_index.numel() > 0:
            for idx in range(edge_index.shape[1]):
                i, j = edge_index[:, idx]
                adj_list[i.item()].append(j.item())
                edge_dict[(i.item(), j.item())] = edge_attr[idx]

        x_gran = torch.zeros_like(x)

        for v in range(n):
            sampled = random.sample(adj_list[v], min(len(adj_list[v]), self.num_samples)) if adj_list[v] else []
            agg_messages = []
            attn_scores = []

            for u in sampled:
                e = edge_dict.get((v, u), torch.zeros(self.edge_dim, device=device))
                h = torch.cat([x[v], e, x[u]], dim=0)
                phi = F.leaky_relu(self.attn_fc(h))
                alpha = torch.dot(self.lambda_param, phi)
                attn_scores.append(alpha)
                agg_messages.append(self.message_mlp(F.relu(x[u])))

            if attn_scores:
                weights = F.softmax(torch.stack(attn_scores), dim=0)
                weighted_sum = sum(w * m for w, m in zip(weights, agg_messages))
                x_gran[v] = weighted_sum + x[v]
            else:
                # If no neighbors were sampled (e.g., isolated node), the message is zero
                 x_gran[v] = x[v]


        return x_gran

class MGTNLayer(nn.Module):
    def __init__(self, in_dim):
        super().__init__()
        self.q_fc = nn.Linear(in_dim, in_dim)
        self.k_fc = nn.Linear(in_dim, in_dim)
        self.v_fc = nn.Linear(in_dim, in_dim)
        self.combine = nn.Linear(in_dim, in_dim)

    def forward(self, x):
        if x.size(0) == 0: # Handle empty input
            return torch.empty_like(x)
        Q = self.q_fc(x)
        K = self.k_fc(x)
        V = self.v_fc(x)
        scores = torch.matmul(Q, K.T) / (Q.shape[-1] ** 0.5)
        attn = F.softmax(scores, dim=-1)
        context = torch.matmul(attn, V)
        return self.combine(context)

# ---------- Encoder ----------
class MGTNSynDrugEncoder(nn.Module):
    def __init__(self, feat_dim, pos_dim, edge_dim, hidden_dim):
        super().__init__()
        self.atom_fc = nn.Linear(5, feat_dim)
        self.linear_pos = nn.Linear(pos_dim, feat_dim)
        self.gran = GRANLayer(in_dim=feat_dim, edge_dim=edge_dim, hidden_dim=hidden_dim)
        self.mgtn = MGTNLayer(in_dim=feat_dim)
        self.encoder = nn.Linear(feat_dim * 2, feat_dim)

    def forward(self, smiles):
        x, edge_index, edge_attr, adj = smiles_to_graph(smiles)
        if x.size(0) == 0: # Handle cases where smiles_to_graph returns empty tensors
            # Return a zero tensor of appropriate size for the rest of the pipeline
            return torch.zeros(self.encoder.out_features, device=self.atom_fc.weight.device)

        x = self.atom_fc(x)
        U = laplacian_positional_encoding(adj, k=32)

        # Ensure U has the correct number of dimensions (n_atoms, pos_dim)
        # If smiles_to_graph returns empty, U might be (0, k), need to handle proj
        if U.size(0) == 0:
             return torch.zeros(self.encoder.out_features, device=self.atom_fc.weight.device)

        U_proj = self.linear_pos(U)

        # Ensure x0, x_gran, x_mgtn are not empty before concatenation
        if x.size(0) == 0:
            return torch.zeros(self.encoder.out_features, device=self.atom_fc.weight.device)

        x0 = x + U_proj

        x_gran = self.gran(x0, edge_index, edge_attr)
        x_mgtn = self.mgtn(x0)

        # Ensure the concatenated tensor is not empty
        if x_gran.size(0) == 0 or x_mgtn.size(0) == 0:
             return torch.zeros(self.encoder.out_features, device=self.atom_fc.weight.device)


        x_comb = torch.cat([x_gran, x_mgtn], dim=-1)
        # Aggregate node features to get a single graph-level feature vector
        # Ensure x_comb is not empty before calling mean
        if x_comb.size(0) == 0:
             return torch.zeros(self.encoder.out_features, device=self.atom_fc.weight.device)


        graph_feat = F.relu(self.encoder(x_comb)).mean(dim=0)
        return graph_feat

# ---------- VAE ----------
class DrugComboVAE(nn.Module):
    def __init__(self, feat_dim=64, latent_dim=128, pos_dim=32, edge_dim=2, hidden_dim=128):
        super().__init__()
        # Encoder is now a graph-level encoder
        self.encoder = MGTNSynDrugEncoder(feat_dim, pos_dim, edge_dim, hidden_dim)
        self.fc_mu = nn.Linear(feat_dim, latent_dim)
        self.fc_logvar = nn.Linear(feat_dim, latent_dim)
        self.decoder = nn.Sequential(
            nn.Linear(latent_dim, 128),
            nn.ReLU(),
            # The decoder output needs to match the input to the encoder's final aggregation
            # Since we are aggregating to a single vector, the decoder reconstructs this vector
            nn.Linear(128, feat_dim)
        )
        self.classifier = nn.Sequential(
            nn.Linear(latent_dim * 2, 128),
            nn.ReLU(),
            nn.Linear(128, 1)
        )

    def encode(self, smiles):
        # The encoder directly returns a graph-level feature vector
        h = self.encoder(smiles)
        # Ensure h has a batch dimension for linear layers if needed
        if h.ndim == 1:
            h = h.unsqueeze(0)

        # Handle cases where the encoder returns a zero tensor (e.g., for invalid SMILES)
        if h.size(0) == 0:
             # Return zero tensors of appropriate size
             mu = torch.zeros(1, self.fc_mu.out_features, device=self.fc_mu.weight.device)
             logvar = torch.zeros(1, self.fc_logvar.out_features, device=self.fc_logvar.weight.device)
             z = torch.zeros(1, self.fc_mu.out_features, device=self.fc_mu.weight.device)
             return z, mu, logvar, torch.zeros(1, self.encoder.encoder.out_features, device=self.encoder.encoder.weight.device)


        mu = self.fc_mu(h)
        logvar = self.fc_logvar(h)

        std = torch.exp(0.5 * logvar)
        eps = torch.randn_like(std)
        z = mu + eps * std
        return z, mu, logvar, h # h is the graph-level feature before mu/logvar layers

    def forward(self, s1, s2):
        z1, mu1, lv1, h1 = self.encode(s1)
        z2, mu2, lv2, h2 = self.encode(s2)
        # The decoder reconstructs the graph-level feature vectors h1 and h2
        r1 = self.decoder(z1)
        r2 = self.decoder(z2)

        # Ensure z1 and z2 have the same size for concatenation, handling empty graphs
        if z1.size(0) == 0 and z2.size(0) == 0:
             out = torch.zeros(1, 1, device=self.classifier[0].weight.device)
        elif z1.size(0) == 0:
             z1 = torch.zeros(1, self.fc_mu.out_features, device=z2.device)
             out = self.classifier(torch.cat([z1, z2], dim=-1))
        elif z2.size(0) == 0:
             z2 = torch.zeros(1, self.fc_mu.out_features, device=z1.device)
             out = self.classifier(torch.cat([z1, z2], dim=-1))
        else:
            out = self.classifier(torch.cat([z1, z2], dim=-1))


        return out, (r1, h1), (r2, h2), (mu1, lv1), (mu2, lv2)

# ---------- Dataset ----------
class DrugComboDataset(Dataset):
    def __init__(self, csv_path):
        df = pd.read_csv(csv_path)
        # Ensure the column names are correct
        self.smiles1 = df['drug1'].tolist()
        self.smiles2 = df['drug2'].tolist()
        self.labels = df['label'].tolist()

    def __len__(self):
        return len(self.labels)

    def __getitem__(self, idx):
        return self.smiles1[idx], self.smiles2[idx], torch.tensor(self.labels[idx], dtype=torch.float32)

# ---------- Loss ----------
def combo_vae_loss(pred, label, r1, h1, r2, h2, mu1, lv1, mu2, lv2):
    # Ensure all tensors have the same number of dimensions for F.mse_loss
    # Add batch dimension to single-sample tensors if needed by mse_loss or other operations
    if pred.ndim == 0: pred = pred.unsqueeze(0)
    if label.ndim == 0: label = label.unsqueeze(0)
    if r1.ndim == 1: r1 = r1.unsqueeze(0)
    if h1.ndim == 1: h1 = h1.unsqueeze(0)
    if r2.ndim == 1: r2 = r2.unsqueeze(0)
    if h2.ndim == 1: h2 = h2.unsqueeze(0)
    if mu1.ndim == 1: mu1 = mu1.unsqueeze(0)
    if lv1.ndim == 1: lv1 = lv1.unsqueeze(0)
    if mu2.ndim == 1: mu2 = mu2.unsqueeze(0)
    if lv2.ndim == 1: lv2 = lv2.unsqueeze(0)


    pred_loss = F.mse_loss(pred.view(-1), label.view(-1))

    # Handle cases where h1 or h2 might be zero tensors from empty graphs
    recon_loss = 0
    if h1.numel() > 0:
        recon_loss += F.mse_loss(r1, h1)
    if h2.numel() > 0:
        recon_loss += F.mse_loss(r2, h2)

    # Handle cases where mu or logvar might be zero tensors
    kl = 0
    if mu1.numel() > 0 and lv1.numel() > 0:
         kl += -0.5 * torch.sum(1 + lv1 - mu1.pow(2) - lv1.exp())
    if mu2.numel() > 0 and lv2.numel() > 0:
         kl += -0.5 * torch.sum(1 + lv2 - mu2.pow(2) - lv2.exp())


    return pred_loss + recon_loss + 1e-3 * kl

In [ ]:
# @title
# ---------- Training ----------
def train(args, model):
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    temp_csv_dir = '.' # Use current directory for temp files
    temp_csv_path = os.path.join(temp_csv_dir, 'temp_drug_combinations.csv')

    # Rename columns to match expected dataset format
    renamed_data = args.data.rename(columns={'drug_a_name': 'drug1', 'drug_b_name': 'drug2', 'SynClass': 'label'})
    renamed_data.to_csv(temp_csv_path, index=False)

    dataset = DrugComboDataset(csv_path=temp_csv_path)
    # Use batch_size 1 as the smiles_to_graph handles one SMILES string at a time
    loader = DataLoader(dataset, batch_size=1, shuffle=True)
    model.to(device)
    optimizer = torch.optim.Adam(model.parameters(), lr=args.lr)

    for epoch in range(args.epochs):
        model.train()
        total_loss = 0
        # Added enumerate to get batch_idx for potential debugging or logging
        for batch_idx, (s1, s2, y) in enumerate(tqdm(loader)):
            # Dataloader with batch_size=1 will return tensors of shape (1, ...)
            # Extract the single item from the batch
            s1, s2, y = s1[0], s2[0], y.to(device)

            try:
                out, (r1, h1), (r2, h2), (mu1, lv1), (mu2, lv2) = model(s1, s2)
                # Ensure out, y, r1, h1, r2, h2, mu1, lv1, mu2, lv2 are correctly shaped for the loss function
                # Squeeze any extra batch dimensions if batch_size is 1
                loss = combo_vae_loss(out.squeeze(0).squeeze(-1), y.squeeze(0), r1.squeeze(0), h1.squeeze(0), r2.squeeze(0), h2.squeeze(0), mu1.squeeze(0), lv1.squeeze(0), mu2.squeeze(0), lv2.squeeze(0))
                optimizer.zero_grad()
                loss.backward()
                optimizer.step()
                total_loss += loss.item()
            except Exception as e:
                print(f"Error processing combo (SMILES: {s1}, {s2}) in batch {batch_idx}: {e}")
                # Optionally, you can skip the batch or log the error
                continue # Skip to the next batch

        # Calculate average loss per sample or per batch
        avg_loss = total_loss / len(loader) if len(loader) > 0 else 0
        print(f"Epoch {epoch+1}, Loss: {avg_loss:.4f}")

    # Clean up the temporary CSV file
    if os.path.exists(temp_csv_path):
        os.remove(temp_csv_path)

In [ ]:
# @title
class Args:
    def __init__(self, epochs, lr,data):
        self.epochs = epochs
        self.lr = lr
        self.data = data
model = DrugComboVAE()
DrugCombinations_subset = DrugCombinations.iloc[:].copy()
args = Args(epochs=100, lr=1e-3, data=DrugCombinations_subset) # Set your desired epoch and learning rate here

train(args,model)

  2%|▏         | 315/16771 [01:07<58:48,  4.66it/s]

KeyboardInterrupt:

In [ ]:
# @title
def extract_features_for_batch(model, smiles1_list, smiles2_list):
    model.eval()
    features = []
    with torch.no_grad():
        for s1, s2 in zip(smiles1_list, smiles2_list):
            z1, _, _, _ = model.encode(s1)
            z2, _, _, _ = model.encode(s2)
            combo_feat = torch.cat([z1, z2], dim=-1)
            features.append(combo_feat.cpu().numpy())
    return features

Feature_X = extract_features_for_batch(model,DrugCombinations_subset['drug_a_name'], DrugCombinations_subset['drug_b_name'])
Feature_X[0].shape

(1, 256)

In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
import pandas as pd
from rdkit import Chem
import random
from tqdm import tqdm
import argparse
import os

# ---------- Feature Functions ----------
def atom_features(atom):
    return torch.tensor([
        atom.GetDegree(),
        atom.GetTotalNumHs(),
        atom.GetTotalValence(),
        int(atom.GetIsotope() > 0),
        int(atom.GetIsAromatic())
    ], dtype=torch.float32)

def bond_features(bond):
    return torch.tensor([
        int(bond.GetBondTypeAsDouble()),
        int(bond.GetIsConjugated())
    ], dtype=torch.float32)

def smiles_to_graph(smiles):
    mol = Chem.MolFromSmiles(smiles)
    # Handle cases where SMILES are invalid
    if mol is None:
        # Return empty tensors or handle as appropriate for your model
        return torch.empty(0, 5), torch.empty(2, 0, dtype=torch.long), torch.empty(0, 2), torch.empty(0, 0)

    mol = Chem.AddHs(mol)
    n = mol.GetNumAtoms()

    node_feats = []
    edge_index = []
    edge_feats = []

    for atom in mol.GetAtoms():
        node_feats.append(atom_features(atom))

    for bond in mol.GetBonds():
        i = bond.GetBeginAtomIdx()
        j = bond.GetEndAtomIdx()
        edge_index.append([i, j])
        edge_index.append([j, i])
        edge_feats.append(bond_features(bond))
        edge_feats.append(bond_features(bond))

    if not node_feats: # Handle empty list if no atoms
        node_feats = torch.empty(0, 5)
    else:
        node_feats = torch.stack(node_feats)

    if not edge_index: # Handle empty list if no bonds
        edge_index = torch.empty(2, 0, dtype=torch.long)
        edge_feats = torch.empty(0, 2)
        adj = torch.empty(n, n) # Initialize adjacency for a molecule with no bonds
    else:
        edge_index = torch.tensor(edge_index).T
        edge_feats = torch.stack(edge_feats)
        adj = torch.zeros((n, n))
        for i, j in edge_index.T:
            adj[i, j] = 1


    return node_feats, edge_index, edge_feats, adj


def laplacian_positional_encoding(adj, k=64):
    n = adj.size(0)
    if n == 0: # Handle empty adjacency matrix
        return torch.zeros(0, k, device=adj.device) # Ensure device consistency
    D = torch.diag(adj.sum(dim=1))
    # Handle potential division by zero if a node has no neighbors by adding epsilon
    D_inv_sqrt = torch.linalg.inv(torch.sqrt(D + 1e-8)) # Add small epsilon for stability
    L = torch.eye(n, device=adj.device) - D_inv_sqrt @ adj @ D_inv_sqrt

    # Ensure L is symmetric before eigh
    L = (L + L.T) * 0.5

    try:
        eigvals, eigvecs = torch.linalg.eigh(L)
    except Exception as e:
        print(f"Error during eigendecomposition: {e}")
        # Return a zero tensor of expected size in case of an error
        return torch.zeros(n, k, device=adj.device)


    if n >= k:
        return eigvecs[:, :k]
    else:
        padding = torch.zeros(n, k - n, device=eigvecs.device)
        return torch.cat([eigvecs, padding], dim=1)

# ---------- MGTN and GRAN Layers ----------
class GRANLayer(nn.Module):
    def __init__(self, in_dim, edge_dim, hidden_dim, num_samples=3):
        super().__init__()
        self.num_samples = num_samples
        self.hidden_dim = hidden_dim
        self.edge_dim = edge_dim
        self.attn_fc = nn.Linear(2 * in_dim + edge_dim, hidden_dim)
        self.lambda_param = nn.Parameter(torch.empty(hidden_dim))
        self.message_mlp = nn.Sequential(
            nn.Linear(in_dim, hidden_dim),
            nn.ReLU(),
            nn.Linear(hidden_dim, in_dim)
        )
        nn.init.xavier_uniform_(self.lambda_param.view(1, -1))

    def forward(self, x, edge_index, edge_attr):
        n = x.size(0)
        if n == 0: # Handle empty input
            return torch.empty_like(x)

        device = x.device
        adj_list = [[] for _ in range(n)]
        edge_dict = {}

        # Check if edge_index is empty
        if edge_index.numel() > 0:
            for idx in range(edge_index.shape[1]):
                i, j = edge_index[:, idx]
                adj_list[i.item()].append(j.item())
                edge_dict[(i.item(), j.item())] = edge_attr[idx]

        x_gran = torch.zeros_like(x)

        for v in range(n):
            sampled = random.sample(adj_list[v], min(len(adj_list[v]), self.num_samples)) if adj_list[v] else []
            agg_messages = []
            attn_scores = []

            for u in sampled:
                e = edge_dict.get((v, u), torch.zeros(self.edge_dim, device=device))
                h = torch.cat([x[v], e, x[u]], dim=0)
                phi = F.leaky_relu(self.attn_fc(h))
                alpha = torch.dot(self.lambda_param, phi)
                attn_scores.append(alpha)
                agg_messages.append(self.message_mlp(F.relu(x[u])))

            if attn_scores:
                weights = F.softmax(torch.stack(attn_scores), dim=0)
                weighted_sum = sum(w * m for w, m in zip(weights, agg_messages))
                x_gran[v] = weighted_sum + x[v]
            else:
                # If no neighbors were sampled (e.g., isolated node), the message is zero
                 x_gran[v] = x[v]
        return x_gran

class MGTNLayer(nn.Module):
    def __init__(self, in_dim):
        super().__init__()
        self.q_fc = nn.Linear(in_dim, in_dim)
        self.k_fc = nn.Linear(in_dim, in_dim)
        self.v_fc = nn.Linear(in_dim, in_dim)
        self.combine = nn.Linear(in_dim, in_dim)

    def forward(self, x):
        if x.size(0) == 0: # Handle empty input
            return torch.empty_like(x)
        Q = self.q_fc(x)
        K = self.k_fc(x)
        V = self.v_fc(x)
        scores = torch.matmul(Q, K.T) / (Q.shape[-1] ** 0.5)
        attn = F.softmax(scores, dim=-1)
        context = torch.matmul(attn, V)
        return self.combine(context)

# ---------- Encoder ----------
class MGTNSynDrugEncoder(nn.Module):
    def __init__(self, feat_dim, pos_dim, edge_dim, hidden_dim):
        super().__init__()
        self.atom_fc = nn.Linear(5, feat_dim)
        self.linear_pos = nn.Linear(pos_dim, feat_dim)
        self.gran = GRANLayer(in_dim=feat_dim, edge_dim=edge_dim, hidden_dim=hidden_dim)
        self.mgtn = MGTNLayer(in_dim=feat_dim)
        self.encoder = nn.Linear(feat_dim * 2, feat_dim)

    def forward(self, smiles):
        x, edge_index, edge_attr, adj = smiles_to_graph(smiles)
        if x.size(0) == 0: # Handle cases where smiles_to_graph returns empty tensors
            # Return a zero tensor of appropriate size for the rest of the pipeline
            return torch.zeros(self.encoder.out_features, device=self.atom_fc.weight.device)

        x = self.atom_fc(x)
        U = laplacian_positional_encoding(adj, k=64)

        # Ensure U has the correct number of dimensions (n_atoms, pos_dim)
        # If smiles_to_graph returns empty, U might be (0, k), need to handle proj
        if U.size(0) == 0:
             return torch.zeros(self.encoder.out_features, device=self.atom_fc.weight.device)

        U_proj = self.linear_pos(U)

        # Ensure x0, x_gran, x_mgtn are not empty before concatenation
        if x.size(0) == 0:
            return torch.zeros(self.encoder.out_features, device=self.atom_fc.weight.device)

        x0 = x + U_proj

        x_gran = self.gran(x0, edge_index, edge_attr)
        x_mgtn = self.mgtn(x0)

        # Ensure the concatenated tensor is not empty
        if x_gran.size(0) == 0 or x_mgtn.size(0) == 0:
             return torch.zeros(self.encoder.out_features, device=self.atom_fc.weight.device)


        x_comb = torch.cat([x_gran, x_mgtn], dim=-1)
        # Aggregate node features to get a single graph-level feature vector
        # Ensure x_comb is not empty before calling mean
        if x_comb.size(0) == 0:
             return torch.zeros(self.encoder.out_features, device=self.atom_fc.weight.device)


        graph_feat = F.relu(self.encoder(x_comb)).mean(dim=0)
        return graph_feat

In [ ]:
# Define dimensions used by the encoder backbone
feat_dim = 64
pos_dim = 64
edge_dim = 2
hidden_dim = 128

class DrugVAEEncoder(nn.Module):
    def __init__(self):
        super().__init__()
        # Ensure input dimension matches the output of MGTNSynDrugEncoder's mean pooling
        self.fc1 = nn.Linear(feat_dim, 256)
        self.fc_mu = nn.Linear(256, 128)
        self.fc_logvar = nn.Linear(256, 128)

    def forward(self, x):
        h = F.relu(self.fc1(x))
        mu = self.fc_mu(h)
        logvar = self.fc_logvar(h)
        return mu, logvar

def reparameterize(mu, logvar):
    std = torch.exp(0.5 * logvar)
    eps = torch.randn_like(std)
    return mu + eps * std

class DrugVAEDecoder(nn.Module):
    def __init__(self):
        super().__init__()
        self.fc1 = nn.Linear(128, 256)
        # Decoder output should match the input to the VAEEncoder, which is the pooled graph feature
        self.fc2 = nn.Linear(256, feat_dim)

    def forward(self, z):
        h = F.relu(self.fc1(z))
        return self.fc2(h)

class DrugVAE(nn.Module):
    def __init__(self, feat_dim, pos_dim, edge_dim, hidden_dim): # Initialize with dimension parameters
        super().__init__()
        # The encoder backbone is an instance of MGTNSynDrugEncoder
        self.encoder_backbone = MGTNSynDrugEncoder(feat_dim, pos_dim, edge_dim, hidden_dim)
        self.vae_encoder = DrugVAEEncoder()
        self.decoder = DrugVAEDecoder()

    def forward(self, smiles):
        # The encoder_backbone directly returns the graph-level feature vector
        X_pool = self.encoder_backbone(smiles)       # [feat_dim]

        # Handle cases where the encoder_backbone returns a zero tensor (e.g., for invalid SMILES)
        if X_pool.numel() == 0:
             # Return zero tensors of appropriate size
             mu = torch.zeros(1, self.vae_encoder.fc_mu.out_features, device=X_pool.device)
             logvar = torch.zeros(1, self.vae_encoder.fc_logvar.out_features, device=X_pool.device)
             z = torch.zeros(1, self.vae_encoder.fc_mu.out_features, device=X_pool.device)
             X_recon = torch.zeros(1, self.decoder.fc2.out_features, device=X_pool.device)
             return z.squeeze(0), mu.squeeze(0), logvar.squeeze(0), X_recon.squeeze(0) # Remove batch dim as it's single sample

        # Ensure X_pool has a batch dimension for the linear layers if needed
        if X_pool.ndim == 1:
            X_pool = X_pool.unsqueeze(0)

        mu, logvar = self.vae_encoder(X_pool)   # [1, 128], [1, 128]
        z = reparameterize(mu, logvar)          # [1, 128]
        X_recon = self.decoder(z)               # [1, feat_dim] (reconstructed pooled embedding)

        # Remove the batch dimension before returning
        return z.squeeze(0), mu.squeeze(0), logvar.squeeze(0), X_recon.squeeze(0)


def loss_fn(X_recon, X_pool, mu, logvar):
    # Ensure all tensors have the same number of dimensions for F.mse_loss
    if X_recon.ndim == 1: X_recon = X_recon.unsqueeze(0)
    if X_pool.ndim == 1: X_pool = X_pool.unsqueeze(0)
    if mu.ndim == 1: mu = mu.unsqueeze(0)
    if logvar.ndim == 1: logvar = logvar.unsqueeze(0)

    recon_loss = F.mse_loss(X_recon, X_pool)

    # Handle cases where mu or logvar might be zero tensors
    kl = 0
    if mu.numel() > 0 and logvar.numel() > 0:
         kl = -0.5 * torch.sum(1 + logvar - mu.pow(2) - logvar.exp())

    return recon_loss + 0.001 * kl

# Instantiate the DrugVAE model correctly

In [ ]:
feat_dim = 64
pos_dim = 64
edge_dim = 2
hidden_dim = 128
smiles="CC(=O)Oc1ccccc1C(=O)O"
def Laplacian_MGAN(smiles):
    model = DrugVAE(feat_dim, pos_dim, edge_dim, hidden_dim)
    model.eval()
    with torch.no_grad():
          z, _, _, _ = model(smiles)  # z ∈ [128]
    return z

Laplacian_MGAN(smiles)

tensor([ 0.2218, -0.2982, -0.1104,  1.4155, -1.0506, -0.9348,  0.0066,  0.7715,
         1.3413,  0.0360, -0.9395, -0.2150,  0.1379,  0.0885,  1.0264, -0.1418,
         0.3730, -1.2735,  0.9373, -0.0364,  1.6346, -0.6629, -0.6707, -0.1071,
         1.3962,  1.8611, -0.8456, -0.3397, -1.3660,  0.0423,  0.6947,  0.2634,
         0.1357,  0.2487,  0.6656,  0.3856,  0.5827, -0.3673, -1.4391,  0.8340,
         1.4247,  1.0366,  2.2577, -1.5937, -0.1241,  0.9163,  0.7757,  0.2567,
         0.0149, -0.4553, -2.0257,  1.6099, -1.3317,  1.0787, -0.7118, -0.4363,
        -0.5176,  2.2323, -0.2941,  1.6702, -1.0562, -1.2856,  0.4823,  1.0786,
         1.0747, -1.2597, -0.1599,  0.9833, -0.6596,  0.1349, -0.6698,  1.5059,
        -0.6500, -0.8280,  0.5697,  1.0991, -0.9391,  1.2000,  1.7433, -3.0586,
         1.3620, -1.0377, -0.6637,  1.7702,  0.1793,  0.9556,  0.2320, -0.8069,
        -0.3200,  0.4796, -0.4896, -1.5259, -2.2617, -1.9127, -0.2970, -0.1302,
        -1.1535, -1.5772,  0.6566, -1.4396, -1.0516,  0.4004,  0.4699,  1.7116,
        -0.8713, -0.4013,  1.7443,  1.3880, -0.5447, -0.0416, -0.9599,  0.6107,
        -0.2356,  0.0722,  2.5664, -0.3683, -1.8804, -0.1443,  0.5618,  1.3840,
        -0.4232,  0.0587, -1.4953,  2.0181,  1.3366, -1.2679,  0.1997, -0.4131])

In [ ]:
ext_smiles_df.head()

,SMILES,WORDS,WordMap
0,CNC(=O)CN1CCC(CC1)Oc2cc3c(cc2OC)ncnc3Nc4cccc(c...,"[C, N, C, O, C, N, C, C, C, C, C, O, O, C, N, ...","[mol8, mol7, mol8, mol9, mol8, mol7, mol8, mol..."
1,C[C@@H]1CN(C[C@@H](N1)C)c2ccc(cc2)C(=O)Nc3cc(n...,"[C, C, C, N, C, C, N, C, C, O, N, C, C, O, C, ...","[mol8, mol8, mol8, mol7, mol8, mol8, mol7, mol..."
2,CS(=O)(=O)N1CCN(CC1)Cc2cc3c(s2)c(nc(n3)c4cccc5...,"[C, S, O, O, N, C, C, N, C, C, C, N, C, C, O, ...","[mol8, mol5, mol9, mol9, mol7, mol8, mol8, mol..."
3,CC(c1cc(cc2c1oc(cc2=O)N3CCOCC3)C(=O)N(C)C)Nc4c...,"[C, C, O, N, C, C, O, C, C, C, O, N, C, C, N, F]","[mol8, mol8, mol9, mol7, mol8, mol8, mol9, mol..."
4,c1c(c(cnc1N)c2cc(nc(n2)N3CCOCC3)N4CCOCC4)C(F)(F)F,"[N, N, C, C, O, C, C, N, C, C, O, C, C, C, F, F]","[mol7, mol7, mol8, mol8, mol9, mol8, mol8, mol..."

In [ ]:
import pandas as pd
import numpy as np
from rdkit import Chem
drug_LapMGAN=[]
for drug in ext_smiles_df.SMILES:
  drug_LapMGAN.append(Laplacian_MGAN(drug).numpy())
drug_LapMGAN_data=pd.DataFrame(drug_LapMGAN)
drug_LapMGAN_data.to_csv('/content/drive/MyDrive/MACSynDCR/Data/Drug/ext_drug_LapMGAN_data.csv')
np.save('/content/drive/MyDrive/MACSynDCR/Data/Drug/ext_Lap_MGAN_features_128', drug_LapMGAN)
drug_LapMGAN128= np.load('/content/drive/MyDrive/MACSynDCR/Data/Drug/ext_Lap_MGAN_features_128.npy')
drug_LapMGAN128.shape
#drug_LapMGAN_data

(52, 128)

##NLP based Morgan Fingerprint extraction:

In [ ]:
#nBits is the number of bits in the fingerprint
result= fe_1mol.morganFingerPrint(ext_smiles_df, nBits=1024)
print(result.iloc[:3,6:])
df=result.iloc[:,6:]
df.to_csv('/content/drive/MyDrive/MACSynDCR/Data/Drug/ext_FingerPrintNumData.csv', index=False)

   F3  F4  F5  F6  F7  F8  F9  F10  F11  F12  ...  F1015  F1016  F1017  F1018  \
0   0   0   0   0   0   0   0    0    0    0  ...      0      0      0      0
1   0   0   0   0   0   1   0    0    0    0  ...      0      0      0      0
2   0   0   0   0   0   0   0    0    0    0  ...      1      0      0      0

   F1019  F1020  F1021  F1022  F1023  F1024
0      0      1      0      0      0      0
1      0      1      0      0      0      0
2      0      0      0      0      0      0

[3 rows x 1022 columns]

##Variational AutoEncoder for Feature extraction from NLP based Features (SMILES and Morgan FingerPrint):

In [ ]:
import torch
import torch.nn as nn
import numpy as np
from tqdm import tqdm
import torchvision
from torch.utils.data import Dataset, DataLoader
import numpy as np
import math

In [ ]:
label = (np.random.randint(0, 3, 1500).astype(int))
print(label.shape)
label

(1500,)

array([1, 0, 1, ..., 1, 0, 2])

In [ ]:
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
os.environ["KERAS_BACKEND"] = "jax"

import tensorflow as tf
from keras.layers import Input, Dense, Lambda, Layer, Activation
from tensorflow.keras.layers import BatchNormalization
from keras.models import Model
import tensorflow.keras.backend as K
from keras import metrics, optimizers
from keras.callbacks import Callback
import keras

import pydot
import graphviz
from tensorflow.keras.utils import plot_model
from IPython.display import SVG
from tensorflow.keras.utils import model_to_dot

##**Load NLP based SMILES data to Extract Drug ext_Smiles_features_128.npy:**

In [ ]:
import torch.nn.functional as F
class SM_Dataset(Dataset):
    def __init__(self):
        xy = np.loadtxt('/content/drive/MyDrive/MACSynDCR/Data/Drug/ext_smileNumData.csv', delimiter=',', dtype=np.float32, skiprows=1)
        self.n_samples = xy.shape[0]
        self.x_data = torch.from_numpy(xy[:,:]) # size [n_samples, n_features]
        min_val = self.x_data.min()
        max_val = self.x_data.max()
        self.x_data = (self.x_data - min_val) / (max_val - min_val)
        #self.x_data = F.normalize(self.x_data)
       # self.y_data = torch.from_numpy(xy[:, [0]]) # size [n_samples, 1]


    def __getitem__(self, index):
        return self.x_data[index] #,self.y_data[index]
    def __len__(self):
        return self.n_samples
#xy = np.loadtxt('/content/drive/MyDrive/MACSynDCR/Data/Drug/FingerPrintNumData.csv', delimiter=',', dtype=np.float32, skiprows=1)
sm_dataset = SM_Dataset()
sm_dataloader = DataLoader(dataset=sm_dataset, shuffle=True,num_workers=2)
sm_dataloader.dataset.x_data

tensor([[0.3637, 0.3462, 0.4124,  ..., 0.3656, 0.3656, 0.3656],
        [0.3524, 0.3462, 0.4249,  ..., 0.3656, 0.3656, 0.3656],
        [0.3637, 0.3462, 0.4124,  ..., 1.0000, 0.3656, 0.3656],
        ...,
        [0.4029, 0.3462, 0.4178,  ..., 0.3656, 0.3656, 0.3656],
        [0.3699, 0.3462, 0.4233,  ..., 0.3656, 0.3656, 1.0000],
        [0.4029, 0.3462, 0.4178,  ..., 0.3656, 0.3656, 0.3656]])

In [ ]:
sm_dataloader.dataset.x_data.shape

torch.Size([52, 1422])

In [ ]:
# Model Hyperparameters
cuda = True
DEVICE = torch.device("cpu")
batch_size = 52

x_dim  = 1422
hidden_dim = 400
latent_dim = 128

lr = 1e-3

epochs = 500

In [ ]:
"""
    A simple implementation of Gaussian MLP Encoder and Decoder
"""

class Encoder(nn.Module):

    def __init__(self, input_dim, hidden_dim, latent_dim):
        super(Encoder, self).__init__()

        self.FC_input = nn.Linear(input_dim, hidden_dim)
        self.FC_input2 = nn.Linear(hidden_dim, hidden_dim)
        self.FC_mean  = nn.Linear(hidden_dim, latent_dim)
        self.FC_var   = nn.Linear (hidden_dim, latent_dim)

        self.LeakyReLU = nn.LeakyReLU(0.2)

        self.training = True

    def forward(self, x):
        h_       = self.LeakyReLU(self.FC_input(x))
        h_       = self.LeakyReLU(self.FC_input2(h_))
        mean     = self.FC_mean(h_)
        log_var  = self.FC_var(h_)                     # encoder produces mean and log of variance
                                                       #             (i.e., parateters of simple tractable normal distribution "q"

        return mean, log_var

class Decoder(nn.Module):
    def __init__(self, latent_dim, hidden_dim, output_dim):
        super(Decoder, self).__init__()
        self.FC_hidden = nn.Linear(latent_dim, hidden_dim)
        self.FC_hidden2 = nn.Linear(hidden_dim, hidden_dim)
        self.FC_output = nn.Linear(hidden_dim, output_dim)

        self.LeakyReLU = nn.LeakyReLU(0.2)

    def forward(self, x):
        h     = self.LeakyReLU(self.FC_hidden(x))
        h     = self.LeakyReLU(self.FC_hidden2(h))

        x_hat = torch.sigmoid(self.FC_output(h))
        return x_hat

class VAE(nn.Module):
    def __init__(self, Encoder, Decoder):
        super(VAE, self).__init__()
        self.Encoder = Encoder
        self.Decoder = Decoder

    def reparameterization(self, mean, var):
        epsilon = torch.randn_like(var).to(DEVICE)        # sampling epsilon
        z = mean + var*epsilon                          # reparameterization trick
        return z


    def forward(self, x):
        mean, log_var = self.Encoder(x)
        z = self.reparameterization(mean, torch.exp(0.5 * log_var)) # takes exponential function (log var -> var)
        x_hat  = self.Decoder(z)

        return x_hat, mean, log_var

In [ ]:
encoder = Encoder(input_dim=x_dim, hidden_dim=hidden_dim, latent_dim=latent_dim)
decoder = Decoder(latent_dim=latent_dim, hidden_dim = hidden_dim, output_dim = x_dim)
model = VAE(Encoder=encoder, Decoder=decoder).to(DEVICE)

In [ ]:
from torch.optim import Adam
import torch.nn.functional as F

BCE_loss = nn.BCELoss()
def loss_function(x, x_hat, mean, log_var):
    reproduction_loss = nn.functional.binary_cross_entropy(x_hat, x, reduction='sum')
    KLD      = - 0.5 * torch.sum(1+ log_var - mean.pow(2) - log_var.exp())

    return reproduction_loss + KLD

optimizer = Adam(model.parameters(), lr=lr)

In [ ]:
import torch

# Example 2D tensor
tensor = torch.tensor([[1.0, 2.0], [-3.0, -4.0]])

# Min-max normalization
min_val = tensor.min()
max_val = tensor.max()
normalized_tensor = (tensor - min_val) / (max_val - min_val)

print(normalized_tensor)

tensor([[0.8333, 1.0000],
        [0.1667, 0.0000]])

In [ ]:
from sklearn.preprocessing import normalize
import torch.nn.functional as F


print("Start training VAE...")
model.train()
for epoch in range(epochs):
   # model.train()
    overall_loss = 0
    for x in sm_dataloader:
       # x = x.view(batch_size, x_dim)
        x = F.normalize(x)
        x = x.to(DEVICE)

        optimizer.zero_grad()

        x_hat, mean, log_var = model(x)

        loss = loss_function(x, x_hat, mean, log_var)

        overall_loss += loss.item()

        loss.backward()
        optimizer.step()

      # print(f"Epoch {epoch+1}, Loss: {overall_loss / len(train_loader.dataset)}")
    if (epoch + 1) % 50 == 0:
         print(f"Epoch {epoch+1}, Loss: {overall_loss / len(sm_dataloader.dataset)}")

    #print("\tEpoch", epoch + 1, "complete!", "\tAverage Loss: ", overall_loss / (batch_idx*batch_size))

print("Finish!!")

Start training VAE...
Epoch 50, Loss: 176.3306482755221
Epoch 100, Loss: 173.29638935969427
Epoch 150, Loss: 172.81450447669397
Epoch 200, Loss: 172.43399576040414
Epoch 250, Loss: 172.239868750939
Epoch 300, Loss: 171.88319485004132
Epoch 350, Loss: 172.12055294330304
Epoch 400, Loss: 171.3272050710825
Epoch 450, Loss: 171.38100169255182
Epoch 500, Loss: 171.18006046001727
Finish!!

In [ ]:
model.eval()
import pandas as pd
with torch.no_grad():
    drug_sm_features, _ = model.Encoder(sm_dataset.x_data)

VAE_data=pd.DataFrame(drug_sm_features.numpy())
drug_sm_data=pd.DataFrame(drug_sm_features.numpy())
drug_sm_data.to_csv('/content/drive/MyDrive/MACSynDCR/Data/Drug/ext_drug_sm_VAE_data.csv')
np.save('/content/drive/MyDrive/MACSynDCR/Data/Drug/ext_smiles_features_128', drug_sm_features.numpy())
ext_smf80= np.load('/content/drive/MyDrive/MACSynDCR/Data/Drug/ext_smiles_features_128.npy')
ext_smf80.shape

(52, 128)

In [ ]:
import pandas as pd
import numpy as np
ext_smf80= np.load('/content/drive/MyDrive/MACSynDCR/Data/Drug/ext_smiles_features_128.npy')
ext_smf80.shape

(52, 128)

##**Load NLP based Fingerprint data to Extract Drug ext_fp_features_128.npy:**

In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import DataLoader, TensorDataset

In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import DataLoader, TensorDataset

class VAE(nn.Module):
    def __init__(self, input_dim, latent_dim):
        super(VAE, self).__init__()
        # Encoder
        self.fc1 = nn.Linear(input_dim, 512)
        self.fc2 = nn.Linear(512, 256)
        self.fc3_mean = nn.Linear(256, latent_dim)  # For mean
        self.fc3_logvar = nn.Linear(256, latent_dim)  # For log variance

        # Decoder
        self.fc4 = nn.Linear(latent_dim, 256)
        self.fc5 = nn.Linear(256, 512)
        self.fc6 = nn.Linear(512, input_dim)

    def encode(self, x):
        h = F.relu(self.fc1(x))
        h = F.relu(self.fc2(h))
        return self.fc3_mean(h), self.fc3_logvar(h)

    def reparameterize(self, mu, log_var):
        std = torch.exp(0.5*log_var)
        eps = torch.randn_like(std)
        return mu + eps*std

    def decode(self, z):
        h = F.relu(self.fc4(z))
        h = F.relu(self.fc5(h))
        return torch.sigmoid(self.fc6(h))

    def forward(self, x):
        mu, log_var = self.encode(x)
        z = self.reparameterize(mu, log_var)
        return self.decode(z), mu, log_var

def loss_function(recon_x, x, mu, log_var):
        BCE = F.binary_cross_entropy(recon_x, x, reduction='sum')
        KLD = -0.5 * torch.sum(1 + log_var - mu.pow(2) - log_var.exp())
        return BCE + KLD

In [ ]:
# Parameter settings
input_dim = 1022  # adjust this based on your dataset
latent_dim = 128  # desired dimension of latent space
learning_rate = 1e-3
batch_size = 5
epochs = 500
import numpy as np


X_train = np.loadtxt('/content/drive/MyDrive/MACSynDCR/Data/Drug/ext_FingerPrintNumData.csv', delimiter=',', skiprows=1)
#import pandas as pd
#train_data = pd.read_csv('/content/FingerPrintNumData.csv')
#X_train = pd.DataFrame(data=train_data)
# Data preparation
# Assuming X_train is your gene expression data with samples as rows
# Convert your data into PyTorch tensors and then into a DataLoader
X_train_tensor = torch.tensor(X_train, dtype=torch.float32)
train_dataset = TensorDataset(X_train_tensor, X_train_tensor)  # input and target are the same
train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)

# Model, optimizer, and training
model = VAE(input_dim=input_dim, latent_dim=latent_dim)
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)

train_loss = []
model.train()
for epoch in range(epochs):
    overall_loss = 0
    for batch_idx, (data, _) in enumerate(train_loader):
        optimizer.zero_grad()
        recon_batch, mu, log_var = model(data)
        loss = loss_function(recon_batch, data, mu, log_var)
        loss.backward()
        overall_loss += loss.item()
        optimizer.step()


   # print(f"Epoch {epoch+1}, Loss: {overall_loss / len(train_loader.dataset)}")
    if (epoch + 1) % 50 == 0:
         print(f"Epoch {epoch+1}, Loss: {overall_loss / len(train_loader.dataset)}")

Epoch 50, Loss: 101.23976546067458
Epoch 100, Loss: 49.75381088256836
Epoch 150, Loss: 39.663279680105354
Epoch 200, Loss: 34.929202006413384
Epoch 250, Loss: 31.467283982496994
Epoch 300, Loss: 32.89227368281438
Epoch 350, Loss: 23.329874919011043
Epoch 400, Loss: 27.05071280552791

In [ ]:
X_train.shape

(52, 1022)

In [ ]:
import pandas as pd

model.eval()

with torch.no_grad():
    fp_features, _ = model.encode(X_train_tensor)
fp_VAE_data=pd.DataFrame(fp_features.numpy())
fp_VAE_data.to_csv('/content/drive/MyDrive/MACSynDCR/Data/Drug/ext_drug_fp_VAE_data.csv')
np.save('/content/drive/MyDrive/MACSynDCR/Data/Drug/ext_fp_features_128', fp_features.numpy())
fp_features.shape

In [ ]:
ext_fpf80= np.load('/content/drive/MyDrive/MACSynDCR/Data/Drug/ext_fp_features_128.npy')
ext_fpf80.shape

##**Load drug descriptor data to Extract Drug desc_features_128.npy:**

---

In [ ]:
# @title
from rdkit import Chem
from rdkit.Chem import Descriptors

smiles = "CC(=O)Oc1ccccc1C(=O)O"  # Example SMILES
mol = Chem.MolFromSmiles(smiles)

# Example: Molecular weight
mol_weight = Descriptors.MolWt(mol)
print(f"Molecular Weight: {mol_weight}")

    # Example: Aromatic ring count
aromatic_rings = Descriptors.NumAromaticRings(mol)
print(f"Aromatic Rings: {aromatic_rings}")


from rdkit.Chem import Crippen

mol_logp = Crippen.MolLogP(mol)
mol_mw = Descriptors.MolWt(mol)
print(f"LogP: {mol_logp}, Molecular Weight: {mol_mw}")

from rdkit.Chem import AllChem

smarts = "[#6]-[#6]=[#8]" # Example: Ketone group
pattern = Chem.MolFromSmarts(smarts)
matches = mol.GetSubstructMatches(pattern)
print(f"Number of ketone groups found: {len(matches)}")

Molecular Weight: 180.15899999999996
Aromatic Rings: 1
LogP: 1.3101, Molecular Weight: 180.15899999999996
Number of ketone groups found: 2

In [ ]:
# @title
from drug_smile_fet import oneMolFeatureExtraction
import pandas as pd

    # Assuming you have a DataFrame with a 'SMILES' column
data = {'DRUG_NAME': ['Aspirin'], 'SMILES': ['CC(=O)Oc1ccccc1C(=O)O']}
df = pd.DataFrame(data)
features_df = oneMolFeatureExtraction(df)
print(features_df)

ModuleNotFoundError: No module named 'drug_smile_fet'

In [ ]:
# @title
# Assuming oneMolFeatureExtraction is within the dsfet module
from dsfet import fe_1mol # Keep the previous import
# If oneMolFeatureExtraction is directly under dsfet, use:
# from dsfet import oneMolFeatureExtraction
# However, based on the original notebook, it seems to be within fe_1mol
from dsfet.fe_1mol import oneMolFeatureExtraction

import pandas as pd

# Assuming you have a DataFrame with a 'SMILES' column
data = {'DRUG_NAME': ['Aspirin'], 'SMILES': ['CC(=O)Oc1ccccc1C(=O)O']}
df = pd.DataFrame(data)

# The function oneMolFeatureExtraction expects trainSMILES and testSMILES arguments
# Based on previous usage, it expects DataFrames with a 'SMILES' column
# If you only have one set of SMILES, you can pass the same DataFrame for both

# Define the ngram_list explicitly in this cell
ngram_list = [1,2,3,4,5,6,7,8]

# The ValueError is likely because the input DataFrame 'df' is too small (only 1 row)
# for CountVectorizer to build a meaningful vocabulary of n-grams.
# To fix this, use a larger DataFrame with multiple diverse SMILES strings as input.
# For demonstration purposes, we keep the original call, but be aware it might fail
# with the same error if the input data is too limited.

# Example of how the call should look based on the traceback:
# If you have a larger DataFrame, replace 'df' with your larger DataFrame.
# features_df_train, features_df_test, _, _ = oneMolFeatureExtraction(trainSMILES=your_large_dataframe, testSMILES=your_large_dataframe, ngram_list=ngram_list)

# Using the original small dataframe, which is expected to cause issues for CountVectorizer
try:
    features_df_train, features_df_test, _, _ = oneMolFeatureExtraction(trainSMILES=df, testSMILES=df, ngram_list=ngram_list)
    # Depending on what you want to use, you might take features from features_df_train or features_df_test
    # Assuming you want features for the input df, you can use features_df_train
    print(features_df_train)
except ValueError as e:
    print(f"Caught expected error due to small input data: {e}")
    print("Please provide a larger DataFrame with more diverse SMILES strings to resolve this issue.")

Caught expected error due to small input data: empty vocabulary; perhaps the documents only contain stop words
Please provide a larger DataFrame with more diverse SMILES strings to resolve this issue.

In [ ]:
# @title
# Assuming ext_smiles_df from a previous cell is available and contains multiple unique SMILES
# and is formatted correctly (DataFrame with a 'SMILES' column).

# Use the larger DataFrame ext_smiles_df as input
# Define the ngram_list explicitly
ngram_list = [1,2,3,4,5,6,7,8]

print(f"Attempting feature extraction with a larger dataset of size: {ext_smiles_df.shape}")

try:
    # Pass the larger DataFrame to the function
    features_df_train, features_df_test, _, _ = fe_1mol.oneMolFeatureExtraction(
        trainSMILES=ext_smiles_df,
        testSMILES=ext_smiles_df, # Or None if you only need features for the train set
        ngram_list=ngram_list
    )
    print("Feature extraction successful.")
    print("Train features shape:", features_df_train.shape)
    # print("Test features shape:", features_df_test.shape) # Uncomment if testSMILES was not None
    print(features_df_train.head()) # Display head of the resulting feature DataFrame

except ValueError as e:
    print(f"Error during feature extraction: {e}")
    print("Ensure the input DataFrame 'ext_smiles_df' contains valid SMILES strings and is not empty.")
except Exception as e:
    print(f"An unexpected error occurred: {e}")

Attempting feature extraction with a larger dataset of size: (44, 1)
number of drug selected: 44
number of features created: 1201
Feature extraction successful.
Train features shape: (44, 1205)
   index                                             SMILES  \
0      0  CNC(=O)CN1CCC(CC1)Oc2cc3c(cc2OC)ncnc3Nc4cccc(c...
1      1  C[C@@H]1CN(C[C@@H](N1)C)c2ccc(cc2)C(=O)Nc3cc(n...
2      2  CS(=O)(=O)N1CCN(CC1)Cc2cc3c(s2)c(nc(n3)c4cccc5...
3      3  CC(c1cc(cc2c1oc(cc2=O)N3CCOCC3)C(=O)N(C)C)Nc4c...
4      4  c1c(c(cnc1N)c2cc(nc(n2)N3CCOCC3)N4CCOCC4)C(F)(F)F

                                               WORDS  \
0  [C, N, C, O, C, N, C, C, C, C, C, O, O, C, N, ...
1  [C, C, C, N, C, C, N, C, C, O, N, C, C, O, C, ...
2  [C, S, O, O, N, C, C, N, C, C, C, N, C, C, O, ...
3   [C, C, O, N, C, C, O, C, C, C, O, N, C, C, N, F]
4   [N, N, C, C, O, C, C, N, C, C, O, C, C, C, F, F]

                                             WordMap     mol10      mol9  \
0  [mol10, mol9, mol10, mol4, mol10, mol9, mol10,... -0.152499  0.404544
1  [mol10, mol10, mol10, mol9, mol10, mol10, mol9... -0.152499  0.541905
2  [mol10, mol5, mol4, mol4, mol9, mol10, mol10, ... -0.152499  0.404544
3  [mol10, mol10, mol4, mol9, mol10, mol10, mol4,... -0.152499  0.263905
4  [mol9, mol9, mol10, mol10, mol4, mol10, mol10,... -0.152499  0.340861

      mol4      mol3      mol5      mol1  ...  \
0 -0.34613  0.110814 -0.128437 -0.287536  ...
1 -0.34613 -0.666385 -0.259497 -0.287536  ...
2 -0.34613 -0.666385 -0.128437  1.182205  ...
3 -0.34613  0.181439  0.030921 -0.287536  ...
4 -0.34613  1.046478 -0.593805 -0.287536  ...

   mol10 mol10 mol9 mol10 mol9 mol9 mol10 mol10  \
0                                     -0.152499
1                                     -0.152499
2                                     -0.152499
3                                     -0.152499
4                                     -0.152499

   mol10 mol9 mol10 mol9 mol9 mol10 mol10 mol10  \
0                                     -0.152499
1                                     -0.152499
2                                     -0.152499
3                                     -0.152499
4                                     -0.152499

   mol10 mol4 mol10 mol9 mol3 mol6 mol4 mol4  \
0                                  -0.152499
1                                  -0.152499
2                                  -0.152499
3                                  -0.152499
4                                  -0.152499

   mol4 mol10 mol9 mol3 mol6 mol4 mol4 mol9  \
0                                 -0.152499
1                                 -0.152499
2                                 -0.152499
3                                 -0.152499
4                                 -0.152499

   mol10 mol9 mol3 mol6 mol4 mol4 mol9 mol10  \
0                                  -0.152499
1                                  -0.152499
2                                  -0.152499
3                                  -0.152499
4                                  -0.152499

   mol9 mol3 mol6 mol4 mol4 mol9 mol10 mol4  \
0                                 -0.218153
1                                 -0.218153
2                                 -0.218153
3                                 -0.218153
4                                 -0.218153

   mol3 mol6 mol4 mol4 mol9 mol10 mol4 mol10  \
0                                  -0.152499
1                                  -0.152499
2                                  -0.152499
3                                  -0.152499
4                                   6.557439

   mol6 mol4 mol4 mol9 mol10 mol4 mol10 mol10  \
0                                   -0.152499
1                                   -0.152499
2                                   -0.152499
3                                   -0.152499
4                                   -0.152499

   mol4 mol4 mol9 mol10 mol4 mol10 mol10 mol10  \
0                                    -0.152499
1                                    -0.152499
2                                    -0.152499
3                                    -0.152499
4                                    -0.152499

   mol4 mol9 mol10 mol4 mol10 mol10 mol10 mol10
0                                     -0.152499
1                                     -0.152499
2                                     -0.152499
3                                     -0.152499
4                                     -0.152499

[5 rows x 1205 columns]

In [ ]:
# @title
drug_des = pd.read_csv('/content/drive/MyDrive/MACSynDCR/Data/Drug/drug_des.csv')
drug_des_x_train=drug_des.iloc[:,1:]
drug_des

,drug,MaxEStateIndex,MinEStateIndex,MaxAbsEStateIndex,MinAbsEStateIndex,qed,MolWt,HeavyAtomMolWt,ExactMolWt,NumValenceElectrons,...,fr_sulfide,fr_sulfonamd,fr_sulfone,fr_term_acetylene,fr_tetrazole,fr_thiazole,fr_thiocyan,fr_thiophene,fr_unbrch_alkane,fr_urea
0,5-FU,11.984815,-1.001157,11.984815,0.707037,0.482565,130.078,127.054,130.017856,48,...,0,0,0,0,0,0,0,0,0,0
1,ABT-888,11.377987,-0.441496,11.377987,0.131016,0.743254,244.298,228.170,244.132411,94,...,0,0,0,0,0,0,0,0,0,0
2,AZD1775,13.181204,-1.138383,13.181204,0.242184,0.373518,500.607,468.351,500.264822,192,...,0,0,0,0,0,0,0,0,0,0
3,BEZ-235,13.407466,-0.609468,13.407466,0.148733,0.323630,469.548,446.364,469.190260,174,...,0,0,0,0,0,0,0,0,0,0
4,BORTEZOMIB,12.826667,-1.694984,12.826667,0.091931,0.463046,384.245,359.045,384.196886,148,...,0,0,0,0,0,0,0,0,0,0
5,CARBOPLATIN,10.364167,-1.444444,10.364167,0.000000,0.523123,373.266,359.154,373.060148,82,...,0,0,0,0,0,0,0,0,0,0
6,CYCLOPHOSPHAMIDE,12.188549,-2.842184,12.188549,0.422539,0.605721,261.089,245.969,260.024820,84,...,0,0,0,0,0,0,0,0,0,0
7,DASATINIB,12.693082,-0.266614,12.693082,0.173118,0.465717,488.017,461.809,487.155722,174,...,0,0,0,0,0,1,0,0,0,0
8,DEXAMETHASONE,16.859063,-1.980464,16.859063,0.067556,0.667213,392.467,363.235,392.199902,154,...,0,0,0,0,0,0,0,0,0,0
9,DINACICLIB,11.548679,0.185132,11.548679,0.185132,0.470170,396.495,368.271,396.227374,154,...,0,0,0,0,0,0,0,0,0,0
10,DOXORUBICIN,13.643057,-2.240737,13.643057,0.017252,0.235263,543.525,514.293,543.174061,208,...,0,0,0,0,0,0,0,0,0,0
11,ERLOTINIB,5.857397,0.392174,5.857397,0.392174,0.417884,393.443,370.259,393.168856,150,...,0,0,0,1,0,0,0,0,2,0
12,ETOPOSIDE,13.385114,-1.436270,13.385114,0.030064,0.429829,588.562,556.306,588.184291,226,...,0,0,0,0,0,0,0,0,0,0
13,GELDANAMYCIN,13.325348,-1.002013,13.325348,0.080112,0.345972,560.644,520.324,560.273381,220,...,0,0,0,0,0,0,0,0,0,0
14,GEMCITABINE,13.700872,-3.713275,13.700872,0.114056,0.612087,263.200,252.112,263.071762,100,...,0,0,0,0,0,0,0,0,0,0
15,L778123,12.673665,0.066365,12.673665,0.066365,0.652854,405.889,385.729,405.135638,146,...,0,0,0,0,0,0,0,0,0,0
16,LAPATINIB,13.430803,-3.018996,13.430803,0.066362,0.179479,581.069,554.861,580.134732,206,...,0,0,1,0,0,0,0,0,1,0
17,METFORMIN,7.052222,-0.089167,7.052222,0.050926,0.281874,129.167,118.079,129.101445,52,...,0,0,0,0,0,0,0,0,0,0
18,METHOTREXATE,12.370387,-1.299841,12.370387,0.013755,0.294720,454.447,432.271,454.171316,172,...,0,0,0,0,0,0,0,0,0,0
19,MITOMYCINE,12.770676,-0.957338,12.770676,0.058604,0.410670,334.332,316.188,334.127720,128,...,0,0,0,0,0,0,0,0,0,0
20,MK-2206,12.022437,-0.259690,12.022437,0.184105,0.468068,407.477,386.309,407.174610,152,...,0,0,0,0,0,0,0,0,0,0
21,MK-4541,12.347714,-4.520186,12.347714,0.051527,0.714202,428.495,397.247,428.228678,168,...,0,0,0,0,0,0,0,0,0,0
22,MK-4827,11.547430,-0.452781,11.547430,0.452781,0.778874,320.396,300.236,320.163711,122,...,0,0,0,0,0,0,0,0,0,0
23,MK-5108,14.128791,-0.931009,14.128791,0.005098,0.468513,461.946,440.778,461.097618,162,...,0,0,0,0,0,1,0,0,0,0
24,MK-8669,14.484260,-2.789734,14.484260,0.011682,0.103503,990.222,905.550,989.562943,390,...,0,0,0,0,0,0,0,0,0,0
25,MK-8776,6.294704,0.363031,6.294704,0.363031,0.714098,376.262,358.118,375.080706,120,...,0,0,0,0,0,0,0,0,0,0
26,MRK-003,13.052592,-4.608639,13.052592,0.076133,0.559206,551.597,520.349,551.204118,206,...,0,0,0,0,0,0,0,0,0,0
27,OXALIPLATIN,9.099537,-1.824074,9.099537,0.000000,0.401958,399.304,383.176,399.074701,90,...,0,0,0,0,0,0,0,0,0,0
28,PACLITAXEL,15.483795,-2.390958,15.483795,0.002885,0.129786,853.918,802.510,853.330955,328,...,0,0,0,0,0,0,0,0,0,0
29,PD325901,14.168820,-1.369451,14.168820,0.152234,0.359960,482.196,468.084,481.995040,140,...,0,0,0,0,0,0,0,0,0,0
30,SN-38,13.224198,-1.832033,13.224198,0.110337,0.507960,392.411,372.251,392.137222,148,...,0,0,0,0,0,0,0,0,0,0
31,SORAFENIB,12.938877,-4.641865,12.938877,0.065939,0.461340,464.831,448.703,464.086303,166,...,0,0,0,0,0,0,0,0,0,1
32,SUNITINIB,13.650463,-0.403882,13.650463,0.143172,0.626303,398.482,371.266,398.211804,154,...,0,0,0,0,0,0,0,0,0,0
33,TEMOZOLOMIDE,11.395484,-0.740692,11.395484,0.060000,0.560119,194.154,188.106,194.055223,72,...,0,0,0,0,0,0,0,0,0,0
34,TOPOTECAN,13.230323,-1.840670,13.230323,0.104072,0.486542,421.453,398.269,421.163771,160,...,0,0,0,0,0,0,0,0,0,0
35,VINBLASTINE,15.321994,-2.301098,15.321994,0.098623,0.179801,810.989,752.525,810.420379,316,...,0,0,0,0,0,0,0,0,0,0
36,VINORELBINE,15.171732,-2.274490,15.171732,0.028414,0.195690,778.947,724.515,778.394165,302,...,0,0,0,0,0,0,0,0,0,0
37,ZOLINZA,11.591415,-0.359425,11.591415,0.013242,0.383220,264.325,244.165,264.147393,104,...,0,0,0,0,0,0,0,0,3,0

In [ ]:
# @title
import numpy as np
from sklearn.preprocessing import normalize
def to01(array):
    a = array.min()
    # ignore the Runtime Warning
    with np.errstate(divide='ignore'):
        b = 1. /(array.max() - array.min())
    if not(np.isfinite(b)):
        b = 0
    return np.vectorize(lambda x: b * (x - a))(array)

In [ ]:
# @title
# Parameter settings
input_dim = 200
latent_dim = 128  # desired dimension of latent space
learning_rate = 1e-4
batch_size = 5
epochs = 1000
import numpy as np
from sklearn.preprocessing import normalize

drug_des_x_train = pd.read_csv('/content/drive/MyDrive/MACSynDCR/Data/Drug/drug_des.csv')
drug_des_x_train=drug_des_x_train.iloc[:,1:]
drug_des_x_train=np.array(drug_des_x_train)

drug_des_x_train[np.isnan(drug_des_x_train)] = 0
normed_drug_des = to01(drug_des_x_train)
#normed_matrix = normalize(drug_sm_x_train, axis=1, norm='l1')
#result = drug_sm_x_train/ np.linalg.norm(drug_sm_x_train, axis=-1)[:, np.newaxis]

drug_sm_x_train_tensor = torch.tensor(normed_drug_des, dtype=torch.float32)
train_dataset = TensorDataset(drug_sm_x_train_tensor, drug_sm_x_train_tensor)  # input and target are the same
train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)

# Model, optimizer, and training
model = VAE(input_dim=input_dim, latent_dim=latent_dim)
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)

model.train()
for epoch in range(epochs):
    overall_loss = 0
    for batch_idx, (data, _) in enumerate(train_loader):
        optimizer.zero_grad()
        recon_batch, mu, log_var = model(data)
        loss = loss_function(recon_batch, data, mu, log_var)
        loss.backward()
        overall_loss += loss.item()
        optimizer.step()


   # print(f"Epoch {epoch+1}, Loss: {overall_loss / len(train_loader.dataset)}")
    if (epoch + 1) % 50 == 0:
         print(f"Epoch {epoch+1}, Loss: {overall_loss / len(train_loader.dataset)}")

Epoch 50, Loss: 0.6701714176880685
Epoch 100, Loss: 0.2135306981049086
Epoch 150, Loss: 0.16680898046807238
Epoch 200, Loss: 0.1814193619709266
Epoch 250, Loss: 0.15939540808138095
Epoch 300, Loss: 0.13662971360118767
Epoch 350, Loss: 0.1497280040853902
Epoch 400, Loss: 0.16577103106599106
Epoch 450, Loss: 0.128433469486864
Epoch 500, Loss: 0.15181522737992437
Epoch 550, Loss: 0.14562949714692017
Epoch 600, Loss: 0.14329478085825317
Epoch 650, Loss: 0.137568543812162
Epoch 700, Loss: 0.13724662481169952
Epoch 750, Loss: 0.14697163846147687
Epoch 800, Loss: 0.14667096224270368
Epoch 850, Loss: 0.12617726800473114
Epoch 900, Loss: 0.13098428280729996
Epoch 950, Loss: 0.13491125404834747
Epoch 1000, Loss: 0.13520634213560506

In [ ]:
# @title
import pandas as pd

model.eval()
with torch.no_grad():
    desc_features, _ = model.encode(drug_sm_x_train_tensor)
des_VAE_data=pd.DataFrame(desc_features.numpy())
des_VAE_data.to_csv('/content/drive/MyDrive/MACSynDCR/Data/Drug/drug_des_VAE_data.csv')
np.save('/content/drive/MyDrive/MACSynDCR/Data/Drug/desc_features_128', desc_features.numpy())
desc_features.shape

torch.Size([38, 128])

In [ ]:
# @title
descf128= np.load('/content/drive/MyDrive/MACSynDCR/Data/Drug/desc_features_128.npy')
descf128.shape

(38, 128)

##**Load drug descriptor data to Extract DTI_features_128.npy:**

In [ ]:
# @title
import pandas as pd
DT = pd.read_csv('/content/drive/MyDrive/MACSynDCR/Data/Drug/drug_target.csv')
#drug_des_x_train=drug_des.iloc[:,1:]
print(DT.shape)
DT

(38, 567)

,ABCA1,ABCB1,ABCB11,ABCB4,ABCC1,ABCC2,ABCC3,ABCC4,ABCG2,ABL1,...,XBP1,XIAP,XRCC1,YES1,ZEB1,ZFHX4,ZFP36L1,FNTA,PGGT1B,CHURC1-FNTB
0,0,1,0,0,1,1,1,1,1,0,...,1,1,1,1,0,0,0,0,0,0
1,0,1,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,1,...,0,0,0,1,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,1,0,0,1,1,0,1,0,1,...,1,1,0,1,0,0,0,0,0,0
5,0,1,0,1,1,1,0,0,1,0,...,0,0,0,0,0,0,1,0,0,0
6,0,1,0,0,1,1,1,1,1,0,...,0,0,1,0,0,0,1,0,0,0
7,1,1,1,0,0,0,1,0,1,1,...,0,0,0,1,0,0,0,0,0,0
8,1,1,1,1,1,1,1,1,1,0,...,0,1,1,0,1,1,1,0,1,0
9,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10,0,1,1,0,1,1,1,1,1,0,...,0,0,1,0,1,0,0,0,0,0
11,0,1,0,0,0,0,0,0,1,1,...,0,0,0,1,0,0,0,0,0,0
12,0,1,0,0,1,1,1,0,1,0,...,0,0,1,0,0,0,1,0,0,0
13,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
14,0,1,0,0,0,0,0,0,1,0,...,1,1,1,0,0,0,0,0,0,0
15,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,1,1
16,0,1,1,1,0,0,0,0,1,0,...,0,0,0,1,0,0,0,0,0,0
17,0,1,1,1,0,1,1,1,0,1,...,1,0,1,0,0,0,0,0,0,0
18,1,1,0,1,1,1,1,1,1,0,...,1,0,0,0,1,1,0,0,0,0
19,0,1,0,0,1,0,0,0,0,0,...,0,1,0,0,0,0,1,0,0,0
20,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,1,0,0,0,0,0
21,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
22,0,1,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
23,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
24,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
25,1,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
26,0,0,0,0,0,1,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
27,0,1,1,1,1,1,1,1,1,1,...,1,1,0,0,1,0,0,0,0,0
28,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
29,0,1,0,0,1,1,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
30,0,1,1,0,1,1,1,1,1,1,...,1,1,0,1,1,0,0,0,0,0
31,1,1,0,0,0,1,0,1,1,0,...,1,0,1,1,0,1,0,1,0,0
32,1,1,0,0,1,1,1,1,1,0,...,1,1,1,0,0,1,1,0,0,0
33,1,1,0,1,0,1,0,1,1,0,...,0,1,0,0,1,1,1,0,0,0
34,0,1,1,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
35,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
36,1,1,0,1,0,0,0,0,1,1,...,0,1,1,0,0,1,0,0,0,0
37,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
# @title
import pandas as pd
merckdataset = pd.read_csv('/content/drive/MyDrive/MACSynDCR/Data/OneilDataset_-10to20.csv')
cell = merckdataset['cell_line'].unique()
cell_df = pd.DataFrame(data=cell)
cell_df = cell_df.rename(columns={0: 'cell'})
cell_df

In [ ]:
import pandas as pd
drugdataset = pd.read_csv('/content/drive/MyDrive/MACSynDCR/Data/Test_and_validation/independent/independent_input.csv')
ext_cell = drugdataset['cell'].unique()
ext_cell_df = pd.DataFrame(data=ext_cell)
ext_cell_df = ext_cell_df.rename(columns={0: 'cell'})
ext_cell_df

       cell
0       J82
1     SW780
2    TCCSUP
3   HCC1187
4   HCC1806
5     HCC70
6   HCC1428
7   HCC1143
8   HCC1395
9   HCC1937
10    HCC38
11    SW948
12  HCC1569
13  HCC1954
14     MCF7
15    SW900
16     A549
17  HCC1419
18      RT4
19     SW48
20      C32
21    22RV1
22  HCC1500
23  KATOIII

In [ ]:
common_cells

In [ ]:
# prompt: Using dataframe ext_cell_df: find common data with cell df

common_cells = pd.merge(cell_df, ext_cell_df, on='cell', how='inner')
common_cells

Empty DataFrame
Columns: [cell]
Index: []

Cell feature data for ArestaZeneca cell line

In [ ]:
import pandas as pd
ExtGex = pd.read_csv('/content/drive/MyDrive/MACSynDCR/Data/Test_and_validation/cell_features_954.csv')
#drug_des_x_train=drug_des.iloc[:,1:]
print(ExtGex.shape)
ExtGex

(1020, 955)

,gene_id,ENSG00000116237,ENSG00000162413,ENSG00000171603,ENSG00000160049,ENSG00000065526,ENSG00000117118,ENSG00000053371,ENSG00000076864,ENSG00000070831,...,ENSG00000156299,ENSG00000142166,ENSG00000159228,ENSG00000159231,ENSG00000183527,ENSG00000182093,ENSG00000182240,ENSG00000157617,ENSG00000160208,ENSG00000141959
0,transcript_id,ENST00000343813.5,ENST00000377658.4,ENST00000361311.4,ENST00000377036.2,ENST00000375759.3,ENST00000375499.3,ENST00000235835.3,ENST00000290101.4,ENST00000315554.8,...,ENST00000286827.3,ENST00000270139.3,ENST00000290349.6,ENST00000290354.5,ENST00000331573.3,ENST00000333781.5,ENST00000328735.6,ENST00000329623.7,ENST00000340648.4,ENST00000349048.4
1,X22RV1_PROSTATE,57.81,6.73,26.89,10.13,28.07,146.83,31.51,4.44,2.32,...,0.03,19.72,29.36,4.42,7.2,33.97,0,1.39,20.86,80.13
2,X2313287_STOMACH,39.68,5.81,22.47,6.72,15.59,135.07,36.62,0.72,1.99,...,0.05,15.38,101.64,1.42,7.68,27.77,0.92,0.47,17.47,68.26
3,X253JBV_URINARY_TRACT,14.88,6.55,9.14,24.81,8.84,92.43,29.56,0,2.05,...,1.7,6.42,224.96,11.24,2.46,10.58,1.17,1.75,18.74,30.9
4,X253J_URINARY_TRACT,13.19,3.68,6.89,7.6,5.45,69.25,25.88,0,0.7,...,0.56,5.6,202.03,6.53,0.92,15.5,1.11,1.89,8.11,27.76
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1015,YD8_UPPER_AERODIGESTIVE_TRACT,15.74,6.83,32.57,9.79,13.92,75.22,32.07,0,1.04,...,2.87,12.22,79.2,11.77,2.11,11.91,0,0.77,15.02,78.85
1016,YH13_CENTRAL_NERVOUS_SYSTEM,63.83,20.43,44.2,15.41,16.1,81.04,57.77,0,0.18,...,4.19,17.39,89.84,22.15,5.41,17.1,0,3.45,16.38,60.6
1017,YKG1_CENTRAL_NERVOUS_SYSTEM,41.25,23.28,55.37,10.4,11.68,102.11,70.71,0.21,1.64,...,11.94,19.13,110.93,35.15,4.96,27.35,1.11,1.72,18.24,71.48
1018,ZR751_BREAST,30.69,4.72,5.34,6.82,7.33,78.93,23.91,0,4.27,...,2.18,6.97,1.24,8.24,0.87,13.65,0,0.77,6.8,36.37
1019,ZR7530_BREAST,25.04,7.31,12.12,4.67,7.58,38.21,24.03,1.81,0.61,...,0.53,7.19,0.42,55.51,1.52,8.59,0.56,5.44,10.06,73.45

In [ ]:
import pandas as pd
DT = pd.read_csv('/content/drive/MyDrive/MACSynDCR/Data/Drug/drug_target.csv')
#drug_des_x_train=drug_des.iloc[:,1:]
print(DT.shape)
DT

(38, 567)

,ABCA1,ABCB1,ABCB11,ABCB4,ABCC1,ABCC2,ABCC3,ABCC4,ABCG2,ABL1,...,XBP1,XIAP,XRCC1,YES1,ZEB1,ZFHX4,ZFP36L1,FNTA,PGGT1B,CHURC1-FNTB
0,0,1,0,0,1,1,1,1,1,0,...,1,1,1,1,0,0,0,0,0,0
1,0,1,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,1,...,0,0,0,1,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,1,0,0,1,1,0,1,0,1,...,1,1,0,1,0,0,0,0,0,0
5,0,1,0,1,1,1,0,0,1,0,...,0,0,0,0,0,0,1,0,0,0
6,0,1,0,0,1,1,1,1,1,0,...,0,0,1,0,0,0,1,0,0,0
7,1,1,1,0,0,0,1,0,1,1,...,0,0,0,1,0,0,0,0,0,0
8,1,1,1,1,1,1,1,1,1,0,...,0,1,1,0,1,1,1,0,1,0
9,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10,0,1,1,0,1,1,1,1,1,0,...,0,0,1,0,1,0,0,0,0,0
11,0,1,0,0,0,0,0,0,1,1,...,0,0,0,1,0,0,0,0,0,0
12,0,1,0,0,1,1,1,0,1,0,...,0,0,1,0,0,0,1,0,0,0
13,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
14,0,1,0,0,0,0,0,0,1,0,...,1,1,1,0,0,0,0,0,0,0
15,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,1,1
16,0,1,1,1,0,0,0,0,1,0,...,0,0,0,1,0,0,0,0,0,0
17,0,1,1,1,0,1,1,1,0,1,...,1,0,1,0,0,0,0,0,0,0
18,1,1,0,1,1,1,1,1,1,0,...,1,0,0,0,1,1,0,0,0,0
19,0,1,0,0,1,0,0,0,0,0,...,0,1,0,0,0,0,1,0,0,0
20,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,1,0,0,0,0,0
21,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
22,0,1,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
23,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
24,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
25,1,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
26,0,0,0,0,0,1,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
27,0,1,1,1,1,1,1,1,1,1,...,1,1,0,0,1,0,0,0,0,0
28,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
29,0,1,0,0,1,1,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
30,0,1,1,0,1,1,1,1,1,1,...,1,1,0,1,1,0,0,0,0,0
31,1,1,0,0,0,1,0,1,1,0,...,1,0,1,1,0,1,0,1,0,0
32,1,1,0,0,1,1,1,1,1,0,...,1,1,1,0,0,1,1,0,0,0
33,1,1,0,1,0,1,0,1,1,0,...,0,1,0,0,1,1,1,0,0,0
34,0,1,1,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
35,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
36,1,1,0,1,0,0,0,0,1,1,...,0,1,1,0,0,1,0,0,0,0
37,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

#DTI features

In [ ]:
!pip install torch_geometric
!pip install rdkit

Collecting torch_geometric
  Downloading torch_geometric-2.6.1-py3-none-any.whl.metadata (63 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 63.1/63.1 kB 3.5 MB/s eta 0:00:00
Requirement already satisfied: aiohttp in /usr/local/lib/python3.12/dist-packages (from torch_geometric) (3.12.15)
Requirement already satisfied: fsspec in /usr/local/lib/python3.12/dist-packages (from torch_geometric) (2025.3.0)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch_geometric) (3.1.6)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from torch_geometric) (2.0.2)
Requirement already satisfied: psutil>=5.8.0 in /usr/local/lib/python3.12/dist-packages (from torch_geometric) (5.9.5)
Requirement already satisfied: pyparsing in /usr/local/lib/python3.12/dist-packages (from torch_geometric) (3.2.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from torch_geometric) (2.32.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from torch_geometric) (4.67.1)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->torch_geometric) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->torch_geometric) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->torch_geometric) (25.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp->torch_geometric) (1.7.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp->torch_geometric) (6.6.4)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->torch_geometric) (0.3.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->torch_geometric) (1.20.1)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch_geometric) (3.0.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->torch_geometric) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->torch_geometric) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->torch_geometric) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->torch_geometric) (2025.8.3)
Requirement already satisfied: typing-extensions>=4.2 in /usr/local/lib/python3.12/dist-packages (from aiosignal>=1.4.0->aiohttp->torch_geometric) (4.14.1)
Downloading torch_geometric-2.6.1-py3-none-any.whl (1.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 16.2 MB/s eta 0:00:00
Installing collected packages: torch_geometric
Successfully installed torch_geometric-2.6.1
Collecting rdkit
  Downloading rdkit-2025.3.5-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (4.1 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from rdkit) (2.0.2)
Requirement already satisfied: Pillow in /usr/local/lib/python3.12/dist-packages (from rdkit) (11.3.0)
Downloading rdkit-2025.3.5-cp312-cp312-manylinux_2_28_x86_64.whl (36.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 36.2/36.2 MB 24.4 MB/s eta 0:00:00
Installing collected packages: rdkit
Successfully installed rdkit-2025.3.5

In [ ]:
import pandas as pd
ext_DT = pd.read_csv('/content/drive/MyDrive/MACSynDCR/Data/Cell/independent_cell_features_954.csv')
#drug_des_x_train=drug_des.iloc[:,1:]
print(ext_DT.shape)
ext_DT.iloc[:, 0] = ext_DT.iloc[:, 0].astype(str).apply(lambda x: x.split('_')[0])
ext_DT=ext_DT.iloc[1:,:]
ext_DT

(1020, 955)

,gene_id,ENSG00000116237,ENSG00000162413,ENSG00000171603,ENSG00000160049,ENSG00000065526,ENSG00000117118,ENSG00000053371,ENSG00000076864,ENSG00000070831,...,ENSG00000156299,ENSG00000142166,ENSG00000159228,ENSG00000159231,ENSG00000183527,ENSG00000182093,ENSG00000182240,ENSG00000157617,ENSG00000160208,ENSG00000141959
1,X22RV1,57.81,6.73,26.89,10.13,28.07,146.83,31.51,4.44,2.32,...,0.03,19.72,29.36,4.42,7.2,33.97,0,1.39,20.86,80.13
2,X2313287,39.68,5.81,22.47,6.72,15.59,135.07,36.62,0.72,1.99,...,0.05,15.38,101.64,1.42,7.68,27.77,0.92,0.47,17.47,68.26
3,X253JBV,14.88,6.55,9.14,24.81,8.84,92.43,29.56,0,2.05,...,1.7,6.42,224.96,11.24,2.46,10.58,1.17,1.75,18.74,30.9
4,X253J,13.19,3.68,6.89,7.6,5.45,69.25,25.88,0,0.7,...,0.56,5.6,202.03,6.53,0.92,15.5,1.11,1.89,8.11,27.76
5,X42MGBA,79.58,34.03,30.23,20.08,15.16,100.59,35.83,0,5.44,...,5.21,10.5,214.9,50.74,8.42,13.3,3.06,8.61,23.28,166.13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1015,YD8,15.74,6.83,32.57,9.79,13.92,75.22,32.07,0,1.04,...,2.87,12.22,79.2,11.77,2.11,11.91,0,0.77,15.02,78.85
1016,YH13,63.83,20.43,44.2,15.41,16.1,81.04,57.77,0,0.18,...,4.19,17.39,89.84,22.15,5.41,17.1,0,3.45,16.38,60.6
1017,YKG1,41.25,23.28,55.37,10.4,11.68,102.11,70.71,0.21,1.64,...,11.94,19.13,110.93,35.15,4.96,27.35,1.11,1.72,18.24,71.48
1018,ZR751,30.69,4.72,5.34,6.82,7.33,78.93,23.91,0,4.27,...,2.18,6.97,1.24,8.24,0.87,13.65,0,0.77,6.8,36.37
1019,ZR7530,25.04,7.31,12.12,4.67,7.58,38.21,24.03,1.81,0.61,...,0.53,7.19,0.42,55.51,1.52,8.59,0.56,5.44,10.06,73.45

In [ ]:
ext_smailes

array(['CNC(=O)CN1CCC(CC1)Oc2cc3c(cc2OC)ncnc3Nc4cccc(c4F)Cl',
       'C[C@@H]1CN(C[C@@H](N1)C)c2ccc(cc2)C(=O)Nc3cc(n[nH]3)CCc4cc(cc(c4)OC)OC',
       'CS(=O)(=O)N1CCN(CC1)Cc2cc3c(s2)c(nc(n3)c4cccc5c4cn[nH]5)N6CCOCC6',
       'CC(c1cc(cc2c1oc(cc2=O)N3CCOCC3)C(=O)N(C)C)Nc4cc(cc(c4)F)F',
       'c1c(c(cnc1N)c2cc(nc(n2)N3CCOCC3)N4CCOCC4)C(F)(F)F',
       'CN(CC[C@H](CSc1ccccc1)Nc2ccc(cc2S(=O)(=O)C(F)(F)F)S(=O)(=O)NC(=O)c3ccc(cc3)N4CCC(CC4)[C@H](c5ccccc5c6ccc(cc6)Cl)O)CCO',
       'Cn1cnc2c1cc(c(c2F)Nc3ccc(cc3Cl)Br)C(=O)NOCCO',
       'COc1cc(ccc1Nc2ncc(c(n2)c3c[nH]c4c3cccc4)Cl)N5CCC(CC5)N',
       'C[C@H]1COCCN1c2c3ccc(nc3nc(n2)N4CCOC[C@@H]4C)c5cccc(c5)C(=O)NC',
       'C[C@@H]1COCCN1c2cc(nc(n2)c3ccnc4c3cc[nH]4)C5(CC5)[S@](=N)(=O)C',
       'CN(C)CC#Cc1ccc(OCCCc2sc(nc2C(=O)O)N3CCc4cccc(C(=O)Nc5nc6ccccc6s5)c4C3)cc1',
       'CC(=O)Nc1cc(ccc1N(C)CCN)Nc2cc(n3c(n2)c(cn3)C#N)NC4CC4',
       'c1cn(c(=O)nc1N)C2C(C(C(O2)CO)O)(F)F',
       'CN(C)C/C=C/C(=O)Nc1cc2c(cc1O[C@H]3CCOC3)ncnc2Nc4ccc(c(c4)Cl)F',
       'COc1cc2c(cc1OCCCN3CCOCC3)c(ncn2)Nc4ccc(c(c4)Cl)F',
       'c1cc(ccc1c2ccc3c(c2)cco3)c4nc5cnccc5n4C[C@@H]6CCN(C6)C(=O)C7CC7',
       'C[C@H]1COCCN1c2c3ccc(nc3nc(n2)N4CCOC[C@@H]4C)c5ccc(c(c5)CO)OC',
       'CN1CCC(CC1)COc2cc3c(cc2OC)c(ncn3)Nc4ccc(cc4F)Br',
       'c1ccc(cc1)c2cccc(c2N3CCC[C@H](C3)N)/C=C\\4/C(=O)NC(=O)S4',
       'c1ccc2c(c1)c3cccc(c3s2)c4cccc5c4oc(cc5=O)N6CCOCC6',
       'Cc1c(sc(n1)NC(=O)N2CCC[C@H]2C(=O)N)c3ccnc(c3)C(C)(C)C(F)(F)F',
       'c1ccc(cc1)c2cc3c(ccn4c3n[nH]c4=O)nc2c5ccc(cc5)C6(CCC6)N',
       'C[C@H](C(=O)N1CCC(CC1)c2ccc(c(c2)OC)Nc3ncc(c(n3)c4cnc5n4cccc5)Cl)O',
       'Cc1c(cn(n1)C)Nc2cc(c(cn2)C(F)(F)F)Nc3ccccc3C(=O)NC',
       'COc1cc(cnc1)Nc2cncc(n2)c3cnc4n3cccc4',
       'COc1cc2c(cc1OC)C3(CCN(CC3)c4c5c([nH]nc5Br)ncn4)C[C@H]2N',
       'c1ccc2c(c1)c(n[nH]c2=O)Cc3ccc(c(c3)C(=O)N4CCN(CC4)C(=O)C5CC5)F',
       'c1cc(cc(c1)F)c2cc(c(s2)C(=O)N[C@H]3CCCNC3)NC(=O)N',
       'COc1cc(ccc1Nc2ncc(c(n2)c3cnc4n3cccc4)F)N5CCN(CC5)CCO',
       'COC1CCN(CC1)C(=O)c2cc(ccc2F)Cc3c4ccccc4c(=O)[nH]n3',
       'CS(=O)(=O)c1ccc(cc1)Nc2cncc(n2)c3cnc4n3cccc4',
       'C[C@H](c1c(ccc(c1Cl)F)Cl)Oc2cc(cnc2N)c3cnn(c3)C4CCNCC4',
       'CCc1c2cc(ccc2nc-3c1Cn4c3cc5c(c4=O)COC(=O)[C@@]5(CC)O)O',
       'c1cc(c(c(c1)OCC2CC2)c3cc(c4c(n3)NC(=O)OC4)C5CCCNC5)O',
       'CCN1CCN(CC1)CC(=O)Nc2ccc(c3c2c4ccccc4s3)c5cccc6c5oc(cc6=O)N7CCOCC7',
       'Cc1c(cn(n1)C)Nc2cc(c(cn2)C(F)(F)F)Nc3ccc(cc3C(=O)NOC)F',
       'CC1(C(=O)Nc2c(ccc(n2)Nc3c(cnc(n3)Nc4cc(c(c(c4)OC)OC)OC)F)O1)C',
       'CN1CCN(CC1)CCOc2cc3c(c(c2)OC4CCOCC4)c(ncn3)Nc5c(ccc6c5OCO6)Cl',
       'C[C@]1(C[C@@H](C1)c2n3c(c(ncc3)N)c(n2)c4cc5nc(ccc5cc4)c6ccccc6)O',
       'CC1=C2C(=C(N(C1=O)C)NC3=C(C=C(C=C3)I)F)C(=O)N(C(=O)N2C4=CC(=CC=C4)NC(=O)C)C5CC5',
       'CC(=O)Nc1cc(ccc1N(C)CCN(C)C)Nc2cc(n3c(n2)c(cn3)C#N)NC4CC4',
       'c1cc2cc(ccc2nc1)Cn3c4c(ncc(n4)c5cnn(c5)CCO)nn3',
       'Cc1c2c(c(n(c1=O)C)Nc3ccc(cc3F)I)c(=O)n(c(=O)n2c4cccc(c4)NC(=O)C)C5CC5',
       'Cc1cc(n[nH]1)Nc2c(cnc(n2)N[C@@H](C)c3ncc(cn3)F)Cl'], dtype=object)

In [ ]:
df_indexed = ext_DT.set_index('gene_id')
df_indexed

,ENSG00000116237,ENSG00000162413,ENSG00000171603,ENSG00000160049,ENSG00000065526,ENSG00000117118,ENSG00000053371,ENSG00000076864,ENSG00000070831,ENSG00000133216,...,ENSG00000156299,ENSG00000142166,ENSG00000159228,ENSG00000159231,ENSG00000183527,ENSG00000182093,ENSG00000182240,ENSG00000157617,ENSG00000160208,ENSG00000141959
gene_id,,,,,,,,,,,,,,,,,,,,,
X22RV1,57.81,6.73,26.89,10.13,28.07,146.83,31.51,4.44,2.32,0,...,0.03,19.72,29.36,4.42,7.2,33.97,0,1.39,20.86,80.13
X2313287,39.68,5.81,22.47,6.72,15.59,135.07,36.62,0.72,1.99,0,...,0.05,15.38,101.64,1.42,7.68,27.77,0.92,0.47,17.47,68.26
X253JBV,14.88,6.55,9.14,24.81,8.84,92.43,29.56,0,2.05,0.02,...,1.7,6.42,224.96,11.24,2.46,10.58,1.17,1.75,18.74,30.9
X253J,13.19,3.68,6.89,7.6,5.45,69.25,25.88,0,0.7,0.01,...,0.56,5.6,202.03,6.53,0.92,15.5,1.11,1.89,8.11,27.76
X42MGBA,79.58,34.03,30.23,20.08,15.16,100.59,35.83,0,5.44,0.33,...,5.21,10.5,214.9,50.74,8.42,13.3,3.06,8.61,23.28,166.13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
YD8,15.74,6.83,32.57,9.79,13.92,75.22,32.07,0,1.04,0.35,...,2.87,12.22,79.2,11.77,2.11,11.91,0,0.77,15.02,78.85
YH13,63.83,20.43,44.2,15.41,16.1,81.04,57.77,0,0.18,0.05,...,4.19,17.39,89.84,22.15,5.41,17.1,0,3.45,16.38,60.6
YKG1,41.25,23.28,55.37,10.4,11.68,102.11,70.71,0.21,1.64,0.08,...,11.94,19.13,110.93,35.15,4.96,27.35,1.11,1.72,18.24,71.48
ZR751,30.69,4.72,5.34,6.82,7.33,78.93,23.91,0,4.27,0,...,2.18,6.97,1.24,8.24,0.87,13.65,0,0.77,6.8,36.37
ZR7530,25.04,7.31,12.12,4.67,7.58,38.21,24.03,1.81,0.61,0,...,0.53,7.19,0.42,55.51,1.52,8.59,0.56,5.44,10.06,73.45

Create a mapping using UniProt API in Python:

In [ ]:
import pandas as pd
import numpy as np
from rdkit import Chem
from rdkit.Chem import AllChem
from sklearn.decomposition import PCA
import os

# -------------------------
# 1. Load your data
# -------------------------
#expr_file = "expression_matrix.csv"  # rows=cell lines, columns=genes
#expr = pd.read_csv(expr_file, index_col=0)

# Ensure numeric
#expr = expr.apply(pd.to_numeric, errors='coerce').fillna(0)

expr=df_indexed
expr = expr.apply(pd.to_numeric, errors='coerce')

# Fill any NaN with 0 (or other strategy)
expr = expr.fillna(0)

# Z-score normalization by gene
expr_norm = (expr - expr.mean()) / expr.std(ddof=1).replace(0,1)

# Rescale to [0,1]
expr_norm = (expr_norm - expr_norm.min().min()) / (expr_norm.max().max() - expr_norm.min().min())

# Drug SMILES list
smiles_list = ext_smiles_df['SMILES']
drug_ids = [f"D{str(i+1).zfill(4)}" for i in range(len(smiles_list))]

drug_id_to_smiles = dict(zip(drug_ids, smiles_list))



# -------------------------
# 2. Encode drugs (Morgan fingerprints)
# -------------------------
def smiles_to_morgan(smiles, radius=2, nBits=1024):
    mol = Chem.MolFromSmiles(smiles)
    if mol is None:
        return np.zeros(nBits)
    fp = AllChem.GetMorganFingerprintAsBitVect(mol, radius, nBits=nBits)
    arr = np.zeros((nBits,), dtype=np.float32)
    AllChem.DataStructs.ConvertToNumpyArray(fp, arr)
    return arr

drug_features = {drug_id: smiles_to_morgan(smi) for drug_id, smi in zip(drug_ids, smiles_list)}

# -------------------------
# 3. Reduce drug fingerprints to 128-d via PCA
# -------------------------
from sklearn.random_projection import GaussianRandomProjection
all_drug_fp = np.stack(list(drug_features.values()), axis=0)
transformer = GaussianRandomProjection(n_components=128, random_state=42)
all_drug_reduced = transformer.fit_transform(all_drug_fp)
drug_features_reduced = {drug_id: vec for drug_id, vec in zip(drug_ids, all_drug_reduced)}

# -------------------------
# 4. Reduce cell line expression to 128-d via PCA
# -------------------------
cell_pca = PCA(n_components=128)
expr_reduced = pd.DataFrame(
    cell_pca.fit_transform(expr),
    index=expr.index,
    columns=[f"Gene_PC{i+1}" for i in range(128)]
)

# -------------------------
# 5. Fuse drug + cell line features
# -------------------------
feature_dict = {}
for drug_id, dvec in drug_features_reduced.items():
    for cell_id in expr_reduced.index:
        cvec = expr_reduced.loc[cell_id].values
        feature_vec = dvec * cvec  # element-wise product
        feature_dict[(drug_id, cell_id)] = feature_vec

# -------------------------
# 6. Save as DataFrame
# -------------------------
df_features = pd.DataFrame.from_dict(feature_dict, orient="index")
df_features.index = pd.MultiIndex.from_tuples(df_features.index, names=["DrugID", "CellLine"])

os.makedirs("drug_cell_features", exist_ok=True)
df_features.to_csv("drug_cell_features/drug_cell_128d.csv")

print("Feature matrix shape:", df_features.shape)
print("Saved to drug_cell_features/drug_cell_128d.csv")

[12:41:57] DEPRECATION WARNING: please use MorganGenerator
[12:41:57] DEPRECATION WARNING: please use MorganGenerator
[12:41:57] DEPRECATION WARNING: please use MorganGenerator
[12:41:57] DEPRECATION WARNING: please use MorganGenerator
[12:41:57] DEPRECATION WARNING: please use MorganGenerator
[12:41:57] DEPRECATION WARNING: please use MorganGenerator
[12:41:57] DEPRECATION WARNING: please use MorganGenerator
[12:41:57] DEPRECATION WARNING: please use MorganGenerator
[12:41:57] DEPRECATION WARNING: please use MorganGenerator
[12:41:57] DEPRECATION WARNING: please use MorganGenerator
[12:41:57] DEPRECATION WARNING: please use MorganGenerator
[12:41:57] DEPRECATION WARNING: please use MorganGenerator
[12:41:57] DEPRECATION WARNING: please use MorganGenerator
[12:41:57] DEPRECATION WARNING: please use MorganGenerator
[12:41:57] DEPRECATION WARNING: please use MorganGenerator
[12:41:57] DEPRECATION WARNING: please use MorganGenerator
[12:41:57] DEPRECATION WARNING: please use MorganGenerator
[12:41:57] DEPRECATION WARNING: please use MorganGenerator
[12:41:57] DEPRECATION WARNING: please use MorganGenerator
[12:41:57] DEPRECATION WARNING: please use MorganGenerator
[12:41:57] DEPRECATION WARNING: please use MorganGenerator
[12:41:57] DEPRECATION WARNING: please use MorganGenerator
[12:41:57] DEPRECATION WARNING: please use MorganGenerator
[12:41:57] DEPRECATION WARNING: please use MorganGenerator
[12:41:57] DEPRECATION WARNING: please use MorganGenerator
[12:41:57] DEPRECATION WARNING: please use MorganGenerator
[12:41:57] DEPRECATION WARNING: please use MorganGenerator
[12:41:57] DEPRECATION WARNING: please use MorganGenerator
[12:41:57] DEPRECATION WARNING: please use MorganGenerator
[12:41:57] DEPRECATION WARNING: please use MorganGenerator
[12:41:57] DEPRECATION WARNING: please use MorganGenerator
[12:41:57] DEPRECATION WARNING: please use MorganGenerator
[12:41:57] DEPRECATION WARNING: please use MorganGenerator
[12:41:57] DEPRECATION WARNING: please use MorganGenerator
[12:41:57] DEPRECATION WARNING: please use MorganGenerator
[12:41:57] DEPRECATION WARNING: please use MorganGenerator
[12:41:57] DEPRECATION WARNING: please use MorganGenerator
[12:41:57] DEPRECATION WARNING: please use MorganGenerator
[12:41:57] DEPRECATION WARNING: please use MorganGenerator
[12:41:57] DEPRECATION WARNING: please use MorganGenerator
[12:41:57] DEPRECATION WARNING: please use MorganGenerator
[12:41:57] DEPRECATION WARNING: please use MorganGenerator
[12:41:57] DEPRECATION WARNING: please use MorganGenerator
[12:41:57] DEPRECATION WARNING: please use MorganGenerator
[12:41:57] DEPRECATION WARNING: please use MorganGenerator
[12:41:57] DEPRECATION WARNING: please use MorganGenerator
[12:41:57] DEPRECATION WARNING: please use MorganGenerator
[12:41:57] DEPRECATION WARNING: please use MorganGenerator
[12:41:57] DEPRECATION WARNING: please use MorganGenerator
[12:41:57] DEPRECATION WARNING: please use MorganGenerator
[12:41:57] DEPRECATION WARNING: please use MorganGenerator
[12:41:57] DEPRECATION WARNING: please use MorganGenerator

Feature matrix shape: (52936, 128)
Saved to drug_cell_features/drug_cell_128d.csv

In [ ]:
feature_dict = {}
for smi, dvec in zip(smiles_list, all_drug_reduced):  # all_drug_reduced from Random Projection or PCA
    for cell_id in expr_reduced.index:
        cvec = expr_reduced.loc[cell_id].values
        feature_vec = dvec * cvec
        feature_dict[(smi, cell_id)] = feature_vec  # use SMILES as first index

# Convert to DataFrame
df_features = pd.DataFrame.from_dict(feature_dict, orient="index")
df_features.index = pd.MultiIndex.from_tuples(df_features.index, names=["SMILES", "CellLine"])

drug_smi = "CNC(=O)CN1CCC(CC1)Oc2cc3c(cc2OC)ncnc3Nc4cccc(c4F)Cl"
cell_line = "X22RV1"


#feature_vector = df_features.loc[(drug_smi, cell_line)].values
#feature_list = feature_vector.tolist()

feature_vector = df_features.loc[(drug_smi, cell_line)].values.astype(float)

print("Feature vector shape:", feature_vector.shape)
print("Feature vector:", feature_vector)

Feature vector shape: (128,)
Feature vector: [-4.14772585e+02 -2.37726851e+02 -7.56742098e+01  6.67339445e+01
  1.82416680e+01  1.39519359e+02  1.21619940e+01 -1.30480368e+02
  3.67842665e+01  6.88663550e+01 -3.30770219e+01 -4.48729182e+01
  1.21282592e+01 -8.63446884e+01  5.44985665e+00 -1.18992226e+02
 -1.74804120e+02  1.73998175e+01  1.20136722e+02  2.18164165e+01
 -1.46040151e+02  6.64641740e+00  7.46658934e+01 -1.06948326e+01
  2.38027308e+01 -7.80496439e+00 -1.56988575e+01 -2.88183623e+01
 -3.87293312e-01 -5.99338076e+01  8.40838862e+01  2.42963592e+02
 -2.14204739e+01 -2.69623497e+02  8.54160144e+01  6.61525255e+01
 -1.08429511e+02 -9.69721131e+00 -1.31182895e+02 -7.09480206e+00
 -2.06003523e+01  8.69028283e+01  9.66975411e+01 -1.73508727e+01
 -3.09963154e-01  8.39906175e+00  5.48733973e+01  6.47055111e+00
 -9.39037153e+00 -2.74318149e+01 -9.36795852e+00 -1.05509573e+02
 -2.38321025e+02  3.40128797e+01 -9.37055655e+01 -3.92871330e+01
 -3.78155007e+00 -7.98840031e+01 -2.47261440e-01  1.32253533e+02
  1.17504974e+02 -8.08521982e+01 -4.96874680e+00 -2.02717144e+00
 -9.82603663e-02 -2.64045506e+00 -3.27744112e+01 -5.26880428e+01
 -5.84204650e+01 -7.42874241e+01 -7.46643946e+01 -4.32068081e+01
  7.67451660e+01 -2.35698644e+00  1.27630914e+01  1.77966453e+02
  2.42399489e+01 -4.39505888e+01  6.47835119e-01 -6.82172781e+01
 -2.89718062e+01  1.15437047e+02  9.09722607e+00  1.88035165e+01
 -1.33321421e+01 -2.19547652e+00  1.39978340e+01  2.35752160e+00
 -7.09690997e+01 -1.80773807e+00 -2.03881213e+00  8.37560469e+00
  1.22466435e+00  1.71930105e+01  2.70720602e+01  1.68670389e+01
 -3.84284649e-02 -3.29963316e+01  1.41087294e-01 -1.67630692e+00
  4.34647627e+01  5.73757090e-02 -2.85874306e+01  6.18748300e+00
  4.61813972e+00 -5.95656286e+00  5.46538129e+01  7.00608077e+00
  2.02795168e+01  5.68430888e-01 -1.14908190e+01 -8.86687235e+00
 -2.37674882e+01  3.67393480e+00  3.59795265e+01  7.56158252e-01
 -1.14540076e+01  9.88539591e+00 -5.04766265e+00  1.32196141e+01
  4.11420999e-01 -1.80746218e+01 -1.87967478e+01  2.09907557e-01
  3.25513604e+01 -3.87082071e+01  2.07590574e+01  2.81043047e+00]

In [ ]:
# @title
import pandas as pd
from rdkit import Chem
from rdkit.Chem import AllChem
import requests

# 1. Load expression data
#expr = pd.read_csv("expression_matrix.csv", index_col=0)
# rows = cell lines, cols = Ensembl IDs
expr=df_indexed

# 2. Load SMILES
drugs = pd.read_csv("drug_smiles.csv")
# columns: DrugID, SMILES

# 3. Map Ensembl → UniProt
def ensembl_to_uniprot(ensembl_id):
    url = f"https://rest.uniprot.org/idmapping/run"
    params = {"from": "Ensembl", "to": "UniProtKB", "ids": ensembl_id}
    r = requests.post(url, data=params)
    # (handle response, return UniProt ID)
    return "P04637"  # dummy

# Example mapping
gene2uniprot = {g: ensembl_to_uniprot(g) for g in expr.columns}

# 4. Fetch UniProt sequence
def get_protein_seq(uniprot_id):
    url = f"https://rest.uniprot.org/uniprotkb/{uniprot_id}.fasta"
    r = requests.get(url)
    if r.ok and r.text.startswith(">"):
        return "".join(r.text.split("\n")[1:])
    return None

# 5. Encode drug (Morgan fingerprint as baseline)
def smiles_to_fp(smiles):
    mol = Chem.MolFromSmiles(smiles)
    return AllChem.GetMorganFingerprintAsBitVect(mol, 2, nBits=1024)

# 6. Placeholder DTI prediction (drug x protein)
def predict_dti(drug_fp, protein_seq):
    # TODO: Replace with trained model (e.g., DeepDTA)
    return 0.5

# 7. Build Drug–Cell features
features = {}
for _, row in drugs.iterrows():
    dname, smiles = row["DrugID"], row["SMILES"]
    drug_fp = smiles_to_fp(smiles)
    for cell in expr.index:
        score_sum = 0.0
        for gene, exp in expr.loc[cell].items():
            uni_id = gene2uniprot.get(gene)
            if uni_id:
                seq = get_protein_seq(uni_id)
                if seq:
                    dti_score = predict_dti(drug_fp, seq)
                    score_sum += dti_score * exp
        features[(dname, cell)] = score_sum

# Final feature matrix
df_features = pd.DataFrame.from_dict(features, orient="index", columns=["DTI_Cell_Feature"])
df_features.to_csv("drug_cell_features.csv")

DTI_Function_call:

In [ ]:
drug_smi = "CNC(=O)CN1CCC(CC1)Oc2cc3c(cc2OC)ncnc3Nc4cccc(c4F)Cl"
cell_line = "J82"

def DTI_feature_128(drug_smi,cell_line):
  feature_vector = df_features.loc[(drug_smi, cell_line)].values.astype(float)
  return feature_vector
feature_vector=DTI_feature_128(drug_smi,cell_line)
feature_vector

array([ 1.38893838e+02,  6.26034267e+02,  3.83051958e+01, -2.70305991e+02,
        3.16971325e+02,  2.72187539e+02,  1.32983211e+02, -1.77535639e+02,
        4.01369420e+01,  1.03133257e+02, -1.79403706e+01, -2.52359346e+01,
        2.55513002e+01, -8.55664021e+01, -2.19152214e+00, -8.71576014e+00,
        3.24712192e+01,  3.57593355e+01, -4.34663341e+01,  1.30655014e+02,
        3.08315624e+01,  4.15160726e+01, -2.23498925e+01,  1.54286464e+01,
        9.63785429e+00, -4.39861435e+00, -8.44291536e+01, -3.64680695e+01,
        2.31295192e+01,  1.43239464e+01, -8.78699232e+01,  1.10726471e+02,
       -9.14716323e+00,  1.00590679e+02, -1.13007068e+01, -4.08702846e+01,
       -1.16617823e+01, -1.37052641e+02, -2.56776916e+01, -4.91131646e+00,
        1.02244080e+01,  6.74099693e+01, -1.31330335e+01,  9.04779606e+00,
        3.71820836e+00,  5.36121179e+01,  3.87233579e+01,  1.24716523e+01,
       -1.56680687e+01, -9.80653649e+01, -4.62480647e+00, -5.18640337e+01,
       -7.77940450e+01, -3.98135342e+01,  4.05493521e+00,  9.67858352e-01,
       -1.31911710e+00,  3.59082317e+01, -6.08512941e-01, -2.23251851e+01,
       -3.58043867e+01,  1.01519889e+01,  3.85382370e-01,  1.02680416e+00,
        7.26694116e+01, -1.61697292e+00, -1.61762212e+01,  9.78240100e+00,
       -5.30688583e+01,  4.88320213e+01,  2.93132327e+01,  1.38711210e+01,
        3.85964185e+01, -1.11834339e-01, -1.19897589e+01, -5.89204675e+01,
        9.13885635e+00, -1.52299361e+00,  2.47325348e-01,  3.94989666e+01,
       -3.19014594e+01, -1.09820346e-01,  9.83992263e+00,  1.62091951e+01,
        7.17537111e+00, -3.10685158e+01,  1.34907878e+01, -8.73990595e-01,
       -9.11763855e+01, -7.07705372e-01, -6.35029480e+00, -2.14540018e+01,
       -3.76387380e-01, -8.42646374e+00,  1.85471675e+00,  1.86985119e+01,
        4.72443016e-02,  1.80788676e+01, -5.53063764e+00,  5.23243263e+00,
       -3.94441727e+01,  1.34044570e+00, -8.86177455e+00, -1.48443632e+01,
        1.53493391e+00,  1.74419951e+00,  5.83141077e+01, -1.45975981e+01,
       -1.66091786e+01,  5.92016995e+00,  7.69798411e-01,  1.04017775e+00,
       -1.24625232e+01, -3.88369972e+00,  7.99671097e+00,  3.41806631e-01,
        1.14012802e+00,  3.64069942e+01,  4.42410173e+00,  4.79759234e+00,
       -5.89273341e+00,  3.84339686e+01,  3.36696294e+00, -1.77284625e+00,
       -2.52035638e+01,  2.17182831e+01, -1.61555556e+01, -2.39638561e+00])

#DTI for main dataset:

In [ ]:
# @title
import pandas as pd
gexf = pd.read_csv('/content/drive/MyDrive/MACSynDCR/Data/Cell/vae_expression256.csv')
gexf = pd.DataFrame(data=gexf)
cell_id=gexf.iloc[:,0]
gexf=gexf.iloc[:,1:]
gexf256=gexf.to_numpy()
gexf256.shape
cell_id=cell_id.values
cell_id

array(['A2058', 'A2780', 'A375', 'A427', 'CAOV3', 'COLO320DM', 'DLD1',
       'EFM192B', 'ES2', 'HCT116', 'HT144', 'HT29', 'KPL1', 'LNCAP',
       'LOVO', 'MDAMB436', 'MSTO', 'NCIH1650', 'NCIH2122', 'NCIH23',
       'NCIH460', 'NCIH520', 'OCUBM', 'OV90', 'OVCAR3', 'PA1', 'RKO',
       'RPMI7951', 'SKMEL30', 'SKMES1', 'SKOV3', 'SW620', 'SW837', 'T47D',
       'UACC62', 'UWB1289', 'UWB1289BRCA1', 'VCAP', 'ZR751'], dtype=object)

In [ ]:
gexf = pd.read_csv('/content/drive/MyDrive/MACSynDCR/Data/Cell/vae_expression256.csv')
gexf = pd.DataFrame(data=gexf)
df_indexed = gexf.set_index('0')
df_indexed

,1,2,3,4,5,6,7,8,9,10,...,247,248,249,250,251,252,253,254,255,256
0,,,,,,,,,,,,,,,,,,,,,
A2058,1.008463,-0.633239,-0.581294,-0.828721,-0.832303,-1.079179,-0.853821,1.115694,0.782153,1.252797,...,0.306000,-0.078424,0.203904,-0.646406,1.569443,-0.199801,1.811743,-0.140013,-0.627125,1.364369
A2780,-0.409289,0.626775,-1.233335,0.106096,-0.070181,-1.412210,0.092814,-2.144871,-0.408076,2.703564,...,-0.504590,0.453343,0.734939,-0.208517,-1.439862,0.729823,0.033447,1.225800,0.084599,0.403672
A375,-0.845913,-0.354963,0.047458,-1.773561,0.701157,0.942922,1.097723,1.031356,-0.457829,-0.176219,...,0.206184,0.387873,-1.060164,0.556257,0.758225,-0.963955,-2.500923,2.084381,0.945947,0.606648
A427,0.790530,-1.182029,-1.469445,-0.026199,-0.437515,-0.494521,1.245911,-0.628469,0.322270,-0.265965,...,1.095960,0.613003,-0.571660,-0.352669,-0.375494,-1.195854,-0.401794,-0.349261,0.645583,0.210045
CAOV3,1.607286,-1.783013,-0.830908,-0.855314,0.401553,0.304421,1.769188,0.066801,1.793905,0.087195,...,-0.125054,-0.753762,-1.712396,-0.750839,-1.031157,-0.256976,-1.500412,-0.700102,0.113286,-2.279251
COLO320DM,-0.237314,-0.131516,0.716285,-0.081374,1.496700,0.815799,0.021692,0.813621,-2.224994,-0.927542,...,-1.256468,-0.548944,0.553333,0.556520,-1.978858,2.240246,1.595531,-0.254526,-0.303953,1.082341
DLD1,0.216206,0.409799,2.045992,-0.619401,1.192813,0.519249,0.758434,-1.676354,-0.075681,1.496435,...,0.831800,0.650883,-1.729927,0.706999,-1.256171,-0.759366,0.795831,1.279080,-0.474029,0.830565
EFM192B,0.713590,0.203275,-0.891264,-1.486913,0.434243,0.649606,0.420553,-0.897684,-0.772473,0.237723,...,0.741661,-1.798565,0.970371,-0.922455,0.516777,-2.258331,0.941864,0.605374,2.497112,-0.369070
ES2,-0.406310,-0.051282,0.591417,-0.527330,1.541235,2.566736,0.136017,-0.004425,0.419672,1.575714,...,1.613860,-0.730096,-1.919510,-0.432191,1.624294,-0.747398,0.949834,0.475296,-0.978009,1.835636
HCT116,-0.563037,-0.393750,-1.437948,-0.424216,0.265635,0.714396,0.415921,-2.618591,-0.101854,0.186061,...,0.205041,-0.297404,0.781316,0.421002,0.277438,-1.086784,1.976959,1.290448,0.140773,2.382826
HT144,-0.898935,1.371789,-0.925794,-1.568504,-2.527549,0.688906,0.742000,0.159544,-0.938649,0.771816,...,0.836752,0.269899,0.712812,-0.482126,0.109203,1.141191,0.217447,0.814643,-0.231760,-0.069485
HT29,-1.296147,-1.971025,0.837560,0.202125,1.180576,-0.284167,1.021882,-0.297043,-0.625242,1.356353,...,-0.369201,1.910770,0.519493,1.462577,-0.053817,-0.189571,0.296367,-0.782220,0.614196,-0.725104
KPL1,-0.996665,0.090012,0.506290,0.281740,-0.600175,-1.017771,-0.763051,2.285594,0.155890,-0.050858,...,-0.667724,-0.110532,-0.302374,-0.877719,0.557435,0.672070,0.950665,0.094079,1.518425,-0.462214
LNCAP,0.154960,-0.196223,0.457000,-0.473815,-0.670460,0.393239,-0.441328,0.565059,-1.611146,0.343903,...,-1.599407,0.011832,-1.587230,0.901390,0.770226,-0.251421,0.046996,-0.905166,-0.442228,1.931022
LOVO,0.795998,0.445113,3.033891,-0.152411,-0.768985,-0.490468,0.297568,0.282588,0.138900,1.398245,...,-0.290373,0.877687,1.054029,1.266274,-1.385768,-0.928387,1.034726,-1.347705,0.408004,0.771989
MDAMB436,-2.676954,-1.233657,-0.164574,1.163358,1.345815,-1.622747,1.453251,-1.238518,-0.249156,-0.681323,...,-0.341750,-0.917365,0.847023,-0.024624,0.698356,1.410150,-1.897928,-1.137942,-0.388664,0.337783
MSTO,0.094307,0.656431,-0.843506,-0.299747,-0.491324,0.009965,-2.139943,1.066845,0.400430,-1.738557,...,-0.940431,2.831363,-0.161006,-2.367849,-1.640043,-1.104735,-1.455094,1.027293,0.673649,-0.681683
NCIH1650,-1.039389,-0.305851,0.651203,-0.233522,1.031477,0.121611,-0.923388,-0.426649,-0.172995,0.615078,...,0.740820,1.268318,0.706773,0.765071,0.144191,-1.674255,1.321488,1.380883,0.635721,0.844174
NCIH2122,0.767335,-0.796202,-0.235132,-0.146284,-1.803571,-1.028649,-0.104362,-1.728298,1.562739,0.852333,...,0.751044,0.552765,0.172498,1.110748,0.338813,-0.248029,0.793279,-1.439653,1.567246,-1.866551
NCIH23,1.066376,-1.950267,0.483527,0.397732,0.353979,-0.399718,0.867979,1.106509,-1.749117,-1.994805,...,-0.188440,0.498535,-0.201691,0.461085,-0.231621,-0.949695,-0.515960,-0.312501,-2.297789,0.637844
NCIH460,1.042356,-2.213773,0.006124,-1.014395,-0.669615,-1.007818,-0.040534,-0.683118,-2.705488,0.425604,...,0.436294,0.565820,0.004663,-0.572429,0.058764,0.262429,-0.491370,-1.988076,2.718454,2.392099
NCIH520,0.264940,-0.877804,-0.607543,0.811995,0.837803,-0.107074,-1.394929,1.035335,1.713840,-0.425351,...,0.282193,-1.027490,-1.378612,-1.375404,-2.337817,1.520460,-0.040021,-1.129883,-0.708052,1.426073
OCUBM,0.171993,-0.568424,0.134803,1.182816,-1.281696,-1.266230,0.031747,1.114263,-0.398576,-0.031703,...,-0.292454,0.417067,-1.090414,-0.278803,-0.191768,1.541618,0.934644,0.830380,-0.526341,2.120528
OV90,-0.397810,0.821021,-1.045601,-1.771059,-0.174684,-1.586304,-0.901259,-1.835096,-0.593864,-0.239294,...,-0.761294,0.563200,0.644914,0.235682,-1.633138,-0.989410,-0.232322,0.128001,-0.057938,-0.272677
OVCAR3,1.302691,-0.197357,0.072235,1.020989,-0.311295,-0.916331,-0.350814,0.356341,-0.052643,1.639692,...,0.776697,0.439364,-0.281089,-2.159445,0.789625,-1.234407,-0.086095,0.503236,1.359822,-1.024969
PA1,2.211543,-0.634098,-1.894709,0.617911,-0.145418,-1.518552,0.813479,0.643433,1.044457,-0.428858,...,-0.072334,-1.034488,-2.275445,0.320693,-1.209083,-0.087146,-1.193826,-0.443204,2.055458,0.067000
RKO,0.662904,-1.748913,-1.838380,0.347145,1.136272,1.912147,-0.228645,0.754059,-1.304497,-1.243579,...,-0.919469,-0.882416,-1.522737,-0.395665,2.015861,1.344616,-1.755065,1.313503,0.257867,-0.082352
RPMI7951,0.185072,1.685882,-0.050056,-0.278347,-0.414908,0.083327,-2.213381,0.919185,-1.466386,0.121728,...,-1.155079,0.460358,-0.584962,1.037969,-0.687279,-0.918626,-0.424782,-0.347300,-1.442003,-0.333412
SKMEL30,1.010802,2.914836,1.324930,-0.952944,0.922489,0.082478,0.866267,0.314656,0.978554,0.102531,...,-0.229574,0.803484,0.402575,-0.755182,0.185694,0.023852,0.199654,1.182958,0.275956,-0.752374
SKMES1,0.068413,-0.061865,-0.337472,-0.597177,-1.208218,-0.788168,0.549129,0.391895,1.499362,1.007036,...,0.223139,-0.498062,-1.112744,0.588673,-0.789251,-0.253238,1.022532,-0.937013,-1.306061,-0.019844
SKOV3,1.492267,0.134580,-0.703671,-1.152007,-0.354256,-0.440367,-0.011040,-0.359605,-0.193613,1.624141,...,-0.755152,-1.939957,-0.587343,0.958351,-1.036116,-1.019277,0.361290,-0.966037,-0.377497,0.364628
SW620,-1.803985,0.563516,-0.650393,0.296190,-0.018746,1.365608,2.101271,-0.523970,-0.296628,1.275066,...,2.101280,0.125948,-0.102807,-0.435444,-0.519358,0.703330,0.901235,-0.981688,-0.850908,0.552486
SW837,-1.159982,-0.773417,1.201562,0.540821,-0.638110,0.606511,-0.962410,0.744314,0.670498,-0.240045,...,-2.022361,-0.402594,1.096236,-0.273781,-0.359185,0.582960,-1.210207,0.849093,-0.362312,1.117010
T47D,-0.489450,-2.806405,1.616348,-0.264567,-0.230296,1.229315,0.741150,-1.675580,-0.819529,-0.255082,...,-0.156031,-0.186885,-0.880379,0.688349,0.408588,-0.228846,0.503537,-1.097227,0.816500,-0.307506
UACC62,0.420210,0.924626,1.311751,1.275972,1.423066,0.685853,-0.995978,-0.358843,-0.019944,-0.807454,...,-0.914037,-0.422022,0.076352,1.277246,-0.469113,-0.234227,0.927865,-0.185524,-2.377368,0.535794
UWB1289,0.780656,-0.908012,0.887508,1.626479,-2.173676,0.321674,-0.303640,0.053286,1.307125,0.073340,...,-1.059872,-0.451175,0.846062,-0.656620,-0.306886,0.131899,0.325331,-1.309709,0.764341,-1.114043
UWB1289BRCA1,-0.878867,0.695232,1.633320,0.689104,0.187339,-0.365543,1.153236,0.764340,-0.287996,-1.244012,...,0.735856,1.148196,0.521960,-0.049249,-0.514625,1.285614,-0.721397,-2.552514,0.303358,-0.556892
VCAP,-1.112811,-0.016150,-1.178326,1.711280,-0.328718,-0.634824,0.028922,0.414212,-0.474209,0.174223,...,-1.819901,-0.624975,1.380855,0.491035,0.656756,1.325721,-0.420649,0.605902,0.263374,0.410761
ZR751,1.069284,-1.761503,-2.234184,1.112628,-0.910215,-1.827074,-0.472170,0.924508,0.355266,0.227075,...,1.207094,-0.281069,0.245286,-0.752462,0.596635,0.023164,0.087704,0.322978,2.194433,-0.784335

In [ ]:
import pandas as pd
OneilData = pd.read_csv('/content/drive/MyDrive/MACSynDCR/Data/MFSynDCPData.csv')
MerckOneilDataset = pd.DataFrame(data=OneilData)
ext_smailes =  pd.concat([MerckOneilDataset['drug1'], MerckOneilDataset['drug2']]).unique()
drugs_list = pd.DataFrame(data=ext_smailes)
drugs_list = drugs_list.rename(columns={0: 'SMILES'})
drugs_lists=drugs_list['SMILES'].values
drugs_lists

array(['O=c1[nH]cc(F)c(=O)[nH]1', 'CC1(c2nc3c(C(N)=O)cccc3[nH]2)CCCN1',
       'C=CCn1c(=O)c2cnc(Nc3ccc(N4CCN(C)CC4)cc3)nc2n1-c1cccc(C(C)(C)O)n1',
       'Cn1c(=O)n(-c2ccc(C(C)(C)C#N)cc2)c2c3cc(-c4cnc5ccccc5c4)ccc3ncc21',
       'CC(C)CC(NC(=O)C(Cc1ccccc1)NC(=O)c1cnccn1)B(O)O',
       'O=P1(N(CCCl)CCCl)NCCCO1',
       'Cc1nc(Nc2ncc(C(=O)Nc3c(C)cccc3Cl)s2)cc(N2CCN(CCO)CC2)n1',
       'CC1CC2C3CCC4=CC(=O)C=CC4(C)C3(F)C(O)CC2(C)C1(O)C(=O)CO',
       'CCc1cnn2c(NCc3ccc[n+]([O-])c3)cc(N3CCCCC3CCO)nc12',
       'COc1cccc2c1C(=O)c1c(O)c3c(c(O)c1C2=O)CC(O)(C(=O)CO)CC3OC1CC(N)C(O)C(C)O1',
       'C#Cc1cccc(Nc2ncnc3cc(OCCOC)c(OCCOC)cc23)c1',
       'COc1cc(C2c3cc4c(cc3C(OC3OC5COC(C)OC5C(O)C3O)C3COC(=O)C23)OCO4)cc(OC)c1O',
       'COC1=C2CC(C)CC(OC)C(O)C(C)C=C(C)C(OC(N)=O)C(OC)C=CC=C(C)C(=O)NC(=CC1=O)C2=O',
       'Nc1ccn(C2OC(CO)C(O)C2(F)F)c(=O)n1',
       'N#Cc1ccc(Cn2cncc2CN2CCN(c3cccc(Cl)c3)C(=O)C2)cc1',
       'CS(=O)(=O)CCNCc1ccc(-c2ccc3ncnc(Nc4ccc(OCc5cccc(F)c5)c(Cl)c4)c3c2)o1',
       'CN(C)C(=N)N=C(N)N',
       'CN(Cc1cnc2nc(N)nc(N)c2n1)c1ccc(C(=O)NC(CCC(=O)O)C(=O)O)cc1',
       'COC12C(COC(N)=O)C3=C(C(=O)C(C)=C(N)C3=O)N1CC1NC12',
       'NC1(c2ccc(-c3nc4ccn5c(=O)[nH]nc5c4cc3-c3ccccc3)cc2)CCC1',
       'CN1C(=O)C=CC2(C)C3CCC4(C)C(NC(=O)OCC(F)(F)F)CCC4C3CCC12',
       'NC(=O)c1cccc2cn(-c3ccc(C4CCCNC4)cc3)nc12',
       'O=C(O)C1(Cc2cccc(Nc3nccs3)n2)CCC(Oc2cccc(Cl)c2F)CC1',
       'COC1CC2CCC(C)C(O)(O2)C(=O)C(=O)N2CCCCC2C(=O)OC(C(C)CC2CCC(OP(C)(C)=O)C(OC)C2)CC(=O)C(C)C=C(C)C(O)C(OC)C(=O)C(C)CC(C)C=CC=CC=C1C',
       'O=S1(=O)NC2(CN1CC(F)(F)F)C1CCC2Cc2cc(C=CCN3CCC(C(F)(F)F)CC3)ccc2C1',
       'CC(=O)OC1C(=O)C2(C)C(O)CC3OCC3(OC(C)=O)C2C(OC(=O)c2ccccc2)C2(O)CC(OC(=O)C(O)C(NC(=O)c3ccccc3)c3ccccc3)C(C)=C1C2(C)C',
       'O=C(NOCC(O)CO)c1ccc(F)c(F)c1Nc1ccc(I)cc1F',
       'CCc1c2c(nc3ccc(O)cc13)-c1cc3c(c(=O)n1C2)COC(=O)C3(O)CC',
       'CNC(=O)c1cc(Oc2ccc(NC(=O)Nc3ccc(Cl)c(C(F)(F)F)c3)cc2)ccn1',
       'CCN(CC)CCNC(=O)c1c(C)[nH]c(C=C2C(=O)Nc3ccc(F)cc32)c1C',
       'Cn1nnc2c(C(N)=O)ncn2c1=O',
       'CCC1(O)C(=O)OCc2c1cc1n(c2=O)Cc2cc3c(CN(C)C)c(O)ccc3nc2-1',
       'CCC1(O)CC2CN(CCc3c([nH]c4ccccc34)C(C(=O)OC)(c3cc4c(cc3OC)N(C)C3C(O)(C(=O)OC)C(OC(C)=O)C5(CC)C=CCN6CCC43C65)C2)C1',
       'CCC1=CC2CN(C1)Cc1c([nH]c3ccccc13)C(C(=O)OC)(c1cc3c(cc1OC)N(C)C1C(O)(C(=O)OC)C(OC(C)=O)C4(CC)C=CCN5CCC31C54)C2',
       'O=C(CCCCCCC(=O)Nc1ccccc1)NO',
       'Cn1cc(-c2cnn3c(N)c(Br)c(C4CCCNC4)nc23)cn1'], dtype=object)

In [ ]:
import pandas as pd
import numpy as np
from rdkit import Chem
from rdkit.Chem import AllChem, DataStructs
from sklearn.random_projection import GaussianRandomProjection

# -------------------------
# 1. Normalize cell line expression
# -------------------------
expr = df_indexed.copy()
expr = expr.apply(pd.to_numeric, errors="coerce").fillna(0)

# Z-score normalization by gene
expr_norm = (expr - expr.mean()) / expr.std(ddof=1).replace(0, 1)

# Rescale to [0,1]
expr_norm = (expr_norm - expr_norm.min().min()) / (
    expr_norm.max().max() - expr_norm.min().min()
)

# -------------------------
# 2. Prepare drug SMILES
# -------------------------
smiles_list = drugs_list["SMILES"].tolist()

# Canonicalize SMILES
def canonicalize(smiles):
    mol = Chem.MolFromSmiles(smiles)
    return Chem.MolToSmiles(mol, canonical=True) if mol else smiles

smiles_list = [canonicalize(smi) for smi in smiles_list]

# -------------------------
# 3. Encode drugs (Morgan fingerprints)
# -------------------------
def smiles_to_morgan(smiles, radius=2, nBits=1024):
    mol = Chem.MolFromSmiles(smiles)
    if mol is None:
        return np.zeros(nBits)
    fp = AllChem.GetMorganFingerprintAsBitVect(mol, radius, nBits=nBits)
    arr = np.zeros((nBits,), dtype=np.float32)
    DataStructs.ConvertToNumpyArray(fp, arr)
    return arr

drug_features = {smi: smiles_to_morgan(smi) for smi in smiles_list}

# -------------------------
# 4. Reduce drug fingerprints to 128-d (Random Projection)
# -------------------------
all_drug_fp = np.stack(list(drug_features.values()), axis=0)
drug_transformer = GaussianRandomProjection(n_components=128, random_state=42)
all_drug_reduced = drug_transformer.fit_transform(all_drug_fp)
drug_features_reduced = dict(zip(smiles_list, all_drug_reduced))

# -------------------------
# 5. Reduce cell line expression to 128-d (Random Projection)
# -------------------------
cell_transformer = GaussianRandomProjection(n_components=128, random_state=42)
expr_reduced = pd.DataFrame(
    cell_transformer.fit_transform(expr_norm),
    index=expr_norm.index,
    columns=[f"Cell_PC{i+1}" for i in range(128)],
)

# -------------------------
# 6. Fuse drug + cell line features into DTI
# -------------------------
feature_dict = {}
for smi, dvec in drug_features_reduced.items():
    for cell_id in expr_reduced.index:
        cvec = expr_reduced.loc[cell_id].values
        feature_vec = dvec * cvec
        feature_dict[(smi, cell_id)] = feature_vec

df_features = pd.DataFrame.from_dict(feature_dict, orient="index")
df_features.index = pd.MultiIndex.from_tuples(df_features.index, names=["SMILES", "CellLine"])

# -------------------------
# 7. Lookup function
# -------------------------
def get_dti_vector(drug_smi, cell_line):
    """Return fused DTI feature vector for given SMILES + cell line"""
    smi_canon = canonicalize(drug_smi)
    if smi_canon not in df_features.index.get_level_values("SMILES"):
        raise ValueError(f"SMILES {drug_smi} not found. Try canonicalized: {smi_canon}")

    if cell_line not in df_features.index.get_level_values("CellLine"):
        raise ValueError(f"Cell line {cell_line} not found in expression index.")

    return df_features.loc[(smi_canon, cell_line)].values.astype(float)

# -------------------------
# Example
# -------------------------
drug_smi = "Cn1nnc2c(C(N)=O)ncn2c1=O"
cell_line = "SKMES1"   # ✅ must match expr.index

vec = get_dti_vector(drug_smi, cell_line)
print("Feature vector shape:", vec.shape)
print("Feature vector:", vec)

Feature vector shape: (128,)
Feature vector: [ 0.03567861  0.00248386 -0.08002628 -0.78357048  0.98563244 -0.17508905
  0.14291901  0.10266641  0.00162044 -0.07219061  0.22315801  0.08523337
 -0.1119507   0.04588787 -0.4141091  -0.50888682  0.45982525  0.13707585
 -0.11348156  0.34773715  0.36592235 -0.12637975 -1.48269961  0.6435216
 -0.00801199  0.08767292  0.19174113  0.09376031 -0.12069743 -0.38465375
 -0.35564748 -0.08710953  0.09656497 -0.10701808  0.36290542  0.50331575
  0.13325567  0.00908568 -0.03282667 -0.02934775 -0.29693551 -0.00736058
 -0.28352261 -0.15292492  0.09259123  0.09255182 -0.10238937  0.09227743
  0.04168026 -0.10198909  0.00347754 -0.10266077  0.30123055 -0.01079292
  0.25108632  0.00419867 -0.08478676  0.03183579 -0.07595392  0.12934035
 -0.15404855  0.10599057 -0.74510966 -0.20778479 -0.00676939  0.08454407
 -0.21132751  0.16205855 -0.23881615  0.27968168  0.24213957  0.0353847
  0.00211295 -0.02297115  0.01562548  0.27049259 -0.03419251 -0.02497569
 -0.03558224  0.01851884 -0.00486161 -0.22303029  0.15663105 -0.00466109
 -0.19725355  0.26976156  0.29704182 -0.07277469 -0.50609903  0.68563244
 -0.16462032 -0.10581185  0.12732056  0.21513492  0.08799463  0.22678096
 -0.53038479  0.05263627 -0.03907519  0.54509044  0.14906019 -0.29385845
 -0.07302357 -0.43193244  0.01790674 -0.06060317 -0.32112773  0.0549509
  0.17713834  0.06755772 -0.52606037 -0.35277183 -0.52102721 -0.03273812
 -0.05158586 -0.02141274  0.12377788  0.12255041 -0.29649275  0.113118
 -0.17625477 -0.14954825  0.08841563  0.18782811 -0.1202923   0.63776253
  0.07728412 -0.3288659 ]

[12:29:53] DEPRECATION WARNING: please use MorganGenerator
[12:29:53] DEPRECATION WARNING: please use MorganGenerator
[12:29:53] DEPRECATION WARNING: please use MorganGenerator
[12:29:53] DEPRECATION WARNING: please use MorganGenerator
[12:29:53] DEPRECATION WARNING: please use MorganGenerator
[12:29:53] DEPRECATION WARNING: please use MorganGenerator
[12:29:53] DEPRECATION WARNING: please use MorganGenerator
[12:29:53] DEPRECATION WARNING: please use MorganGenerator
[12:29:53] DEPRECATION WARNING: please use MorganGenerator
[12:29:53] DEPRECATION WARNING: please use MorganGenerator
[12:29:53] DEPRECATION WARNING: please use MorganGenerator
[12:29:53] DEPRECATION WARNING: please use MorganGenerator
[12:29:53] DEPRECATION WARNING: please use MorganGenerator
[12:29:53] DEPRECATION WARNING: please use MorganGenerator
[12:29:53] DEPRECATION WARNING: please use MorganGenerator
[12:29:53] DEPRECATION WARNING: please use MorganGenerator
[12:29:53] DEPRECATION WARNING: please use MorganGenerator
[12:29:53] DEPRECATION WARNING: please use MorganGenerator
[12:29:53] DEPRECATION WARNING: please use MorganGenerator
[12:29:53] DEPRECATION WARNING: please use MorganGenerator
[12:29:53] DEPRECATION WARNING: please use MorganGenerator
[12:29:53] DEPRECATION WARNING: please use MorganGenerator
[12:29:53] DEPRECATION WARNING: please use MorganGenerator
[12:29:53] DEPRECATION WARNING: please use MorganGenerator
[12:29:53] DEPRECATION WARNING: please use MorganGenerator
[12:29:53] DEPRECATION WARNING: please use MorganGenerator
[12:29:53] DEPRECATION WARNING: please use MorganGenerator
[12:29:53] DEPRECATION WARNING: please use MorganGenerator
[12:29:53] DEPRECATION WARNING: please use MorganGenerator
[12:29:53] DEPRECATION WARNING: please use MorganGenerator
[12:29:53] DEPRECATION WARNING: please use MorganGenerator
[12:29:53] DEPRECATION WARNING: please use MorganGenerator
[12:29:53] DEPRECATION WARNING: please use MorganGenerator
[12:29:53] DEPRECATION WARNING: please use MorganGenerator
[12:29:53] DEPRECATION WARNING: please use MorganGenerator
[12:29:53] DEPRECATION WARNING: please use MorganGenerator

In [ ]:
drug_smi = "Cn1nnc2c(C(N)=O)ncn2c1=O"
cell_line = "SKMES1"

def DTI_feature_128(drug_smi,cell_line):
  feature_vector = df_features.loc[(drug_smi, cell_line)].values.astype(float)
  return feature_vector
feature_vector=DTI_feature_128(drug_smi,cell_line)
feature_vector

array([ 0.03567861,  0.00248386, -0.08002628, -0.78357048,  0.98563244,
       -0.17508905,  0.14291901,  0.10266641,  0.00162044, -0.07219061,
        0.22315801,  0.08523337, -0.1119507 ,  0.04588787, -0.4141091 ,
       -0.50888682,  0.45982525,  0.13707585, -0.11348156,  0.34773715,
        0.36592235, -0.12637975, -1.48269961,  0.6435216 , -0.00801199,
        0.08767292,  0.19174113,  0.09376031, -0.12069743, -0.38465375,
       -0.35564748, -0.08710953,  0.09656497, -0.10701808,  0.36290542,
        0.50331575,  0.13325567,  0.00908568, -0.03282667, -0.02934775,
       -0.29693551, -0.00736058, -0.28352261, -0.15292492,  0.09259123,
        0.09255182, -0.10238937,  0.09227743,  0.04168026, -0.10198909,
        0.00347754, -0.10266077,  0.30123055, -0.01079292,  0.25108632,
        0.00419867, -0.08478676,  0.03183579, -0.07595392,  0.12934035,
       -0.15404855,  0.10599057, -0.74510966, -0.20778479, -0.00676939,
        0.08454407, -0.21132751,  0.16205855, -0.23881615,  0.27968168,
        0.24213957,  0.0353847 ,  0.00211295, -0.02297115,  0.01562548,
        0.27049259, -0.03419251, -0.02497569, -0.03558224,  0.01851884,
       -0.00486161, -0.22303029,  0.15663105, -0.00466109, -0.19725355,
        0.26976156,  0.29704182, -0.07277469, -0.50609903,  0.68563244,
       -0.16462032, -0.10581185,  0.12732056,  0.21513492,  0.08799463,
        0.22678096, -0.53038479,  0.05263627, -0.03907519,  0.54509044,
        0.14906019, -0.29385845, -0.07302357, -0.43193244,  0.01790674,
       -0.06060317, -0.32112773,  0.0549509 ,  0.17713834,  0.06755772,
       -0.52606037, -0.35277183, -0.52102721, -0.03273812, -0.05158586,
       -0.02141274,  0.12377788,  0.12255041, -0.29649275,  0.113118  ,
       -0.17625477, -0.14954825,  0.08841563,  0.18782811, -0.1202923 ,
        0.63776253,  0.07728412, -0.3288659 ])

In [ ]:
# @title
# prompt: select only common gene_id in ext_dt and cell in cell_df values

ext_dt_genes = ext_DT['gene_id'].unique()
cell_genes = cell_df['cell'].unique()
common_genes = pd.DataFrame({'gene_id': list(set(ext_dt_genes) & set(cell_genes))})
print(ext_dt_genes.shape)
common_genes

(1018,)

     gene_id
0      A2780
1   NCIH1650
2      CAOV3
3      HT144
4       A427
5   NCIH2122
6      SW620
7    NCIH520
8      ZR751
9       OV90
10      LOVO
11       ES2
12   SKMEL30
13      HT29
14  MDAMB436
15   NCIH460
16    UACC62
17      T47D
18      KPL1
19    HCT116
20  RPMI7951
21       RKO
22    NCIH23
23     SKOV3
24    SKMES1
25     A2058
26      VCAP
27      A375
28     SW837

In [ ]:
# @title
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import DataLoader, TensorDataset

class VAE(nn.Module):
    def __init__(self, input_dim, latent_dim):
        super(VAE, self).__init__()
        # Encoder
        self.fc1 = nn.Linear(input_dim, 512)
        self.fc2 = nn.Linear(512, 256)
        self.fc3_mean = nn.Linear(256, latent_dim)  # For mean
        self.fc3_logvar = nn.Linear(256, latent_dim)  # For log variance

        # Decoder
        self.fc4 = nn.Linear(latent_dim, 256)
        self.fc5 = nn.Linear(256, 512)
        self.fc6 = nn.Linear(512, input_dim)

    def encode(self, x):
        h = F.relu(self.fc1(x))
        h = F.relu(self.fc2(h))
        return self.fc3_mean(h), self.fc3_logvar(h)

    def reparameterize(self, mu, log_var):
        std = torch.exp(0.5*log_var)
        eps = torch.randn_like(std)
        return mu + eps*std

    def decode(self, z):
        h = F.relu(self.fc4(z))
        h = F.relu(self.fc5(h))
        return torch.sigmoid(self.fc6(h))

    def forward(self, x):
        mu, log_var = self.encode(x)
        z = self.reparameterize(mu, log_var)
        return self.decode(z), mu, log_var

def loss_function(recon_x, x, mu, log_var):
        BCE = F.binary_cross_entropy(recon_x, x, reduction='sum')
        KLD = -0.5 * torch.sum(1 + log_var - mu.pow(2) - log_var.exp())
        return BCE + KLD

In [ ]:
# @title
import numpy as np
from sklearn.preprocessing import normalize
def to01(array):
    a = array.min()
    # ignore the Runtime Warning
    with np.errstate(divide='ignore'):
        b = 1. /(array.max() - array.min())
    if not(np.isfinite(b)):
        b = 0
    return np.vectorize(lambda x: b * (x - a))(array)

In [ ]:
# @title
# Parameter settings
input_dim = 567
latent_dim = 128  # desired dimension of latent space
learning_rate = 1e-4
batch_size = 38
epochs = 10000
import numpy as np
from sklearn.preprocessing import normalize

drug_des_x_train = pd.read_csv('/content/drive/MyDrive/MACSynDCR/Data/Drug/drug_target.csv')
drug_des_x_train=drug_des_x_train.iloc[:,:]
drug_des_x_train=np.array(drug_des_x_train)

drug_des_x_train[np.isnan(drug_des_x_train)] = 0
normed_drug_des = to01(drug_des_x_train)
#normed_matrix = normalize(drug_sm_x_train, axis=1, norm='l1')
#result = drug_sm_x_train/ np.linalg.norm(drug_sm_x_train, axis=-1)[:, np.newaxis]

drug_sm_x_train_tensor = torch.tensor(normed_drug_des, dtype=torch.float32)
train_dataset = TensorDataset(drug_sm_x_train_tensor, drug_sm_x_train_tensor)  # input and target are the same
train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)

# Model, optimizer, and training
model = VAE(input_dim=input_dim, latent_dim=latent_dim)
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)

model.train()
for epoch in range(epochs):
    overall_loss = 0
    for batch_idx, (data, _) in enumerate(train_loader):
        optimizer.zero_grad()
        recon_batch, mu, log_var = model(data)
        loss = loss_function(recon_batch, data, mu, log_var)
        loss.backward()
        overall_loss += loss.item()
        optimizer.step()


   # print(f"Epoch {epoch+1}, Loss: {overall_loss / len(train_loader.dataset)}")
    if (epoch + 1) % 500 == 0:
         print(f"Epoch {epoch+1}, Loss: {overall_loss / len(train_loader.dataset)}")

Epoch 500, Loss: 207.39607319078948
Epoch 1000, Loss: 180.53618421052633
Epoch 1500, Loss: 121.54143965871711
Epoch 2000, Loss: 57.280183490953945
Epoch 2500, Loss: 42.33562589946546
Epoch 3000, Loss: 35.42629523026316
Epoch 3500, Loss: 32.01660798725329
Epoch 4000, Loss: 41.22814298930921
Epoch 4500, Loss: 30.973343698601973
Epoch 5000, Loss: 27.552994577508223
Epoch 5500, Loss: 33.49653384560033
Epoch 6000, Loss: 24.419199090254935
Epoch 6500, Loss: 27.214535361842106
Epoch 7000, Loss: 35.222200092516445
Epoch 7500, Loss: 29.87482974403783
Epoch 8000, Loss: 22.368385716488486
Epoch 8500, Loss: 22.24180201480263
Epoch 9000, Loss: 22.288487484580592
Epoch 9500, Loss: 27.595658151726973
Epoch 10000, Loss: 20.710086220189144

In [ ]:
# @title
import pandas as pd

model.eval()
with torch.no_grad():
    desc_features, _ = model.encode(drug_sm_x_train_tensor)
des_VAE_data=pd.DataFrame(desc_features.numpy())
des_VAE_data.to_csv('/content/drive/MyDrive/MACSynDCR/Data/Drug/DTI_VAE_data.csv')
np.save('/content/drive/MyDrive/MACSynDCR/Data/Drug/DTI_features_128', desc_features.numpy())
desc_features.shape

torch.Size([38, 128])

In [ ]:
# @title
dtif128= np.load('/content/drive/MyDrive/MACSynDCR/Data/Drug/DTI_features_128.npy')
dtif128.shape

(38, 128)

###Load drug physicochemical data to Extract Drug phyc_features_128.npy:**

In [ ]:
# @title
drug_physico = pd.read_csv('/content/drive/MyDrive/MACSynDCR/Data/Drug/redkit_drug.csv')
drug_desdrug_physico=drug_physico.iloc[:,:]
drug_physico

,5-FU,5.85739678,0.392174356,5.85739678.1,0.392174356.1,0.417884098,393.443,370.259,393.1688562,150,...,0.91,0.92,0.93,1.5,0.94,0.95,0.96,0.97,2.6,0.98
0,ABT-888,13.181204,-1.138383,13.181204,0.242184,0.373518,500.607,468.351,500.264822,192,...,0,0,0,0,0,0,0,0,0,0
1,AZD1775,15.483795,-2.390958,15.483795,0.002885,0.129786,853.918,802.510,853.330955,328,...,0,0,0,0,0,0,0,0,0,0
2,BEZ-235,12.826667,-1.694984,12.826667,0.091931,0.463046,384.245,359.045,384.196886,148,...,0,0,0,0,0,0,0,0,0,0
3,BORTEZOMIB,11.377987,-0.441496,11.377987,0.131016,0.743254,244.298,228.170,244.132411,94,...,0,0,0,0,0,0,0,0,0,0
4,CARBOPLATIN,16.859063,-1.980464,16.859063,0.067556,0.667213,392.467,363.235,392.199902,154,...,0,0,0,0,0,0,0,0,0,0
5,CYCLOPHOSPHAMIDE,13.230323,-1.840670,13.230323,0.104072,0.486542,421.453,398.269,421.163771,160,...,0,0,0,0,0,0,0,0,0,0
6,DASATINIB,15.321994,-2.301098,15.321994,0.098623,0.179801,810.989,752.525,810.420379,316,...,0,0,0,0,0,0,0,0,0,0
7,DEXAMETHASONE,15.171732,-2.274490,15.171732,0.028414,0.195690,778.947,724.515,778.394165,302,...,0,0,0,0,0,0,0,0,0,0
8,DINACICLIB,13.650463,-0.403882,13.650463,0.143172,0.626303,398.482,371.266,398.211804,154,...,0,0,0,0,0,0,0,0,0,0
9,DOXORUBICIN,13.224198,-1.832033,13.224198,0.110337,0.507960,392.411,372.251,392.137222,148,...,0,0,0,0,0,0,0,0,0,0
10,ERLOTINIB,11.548679,0.185132,11.548679,0.185132,0.470170,396.495,368.271,396.227374,154,...,0,0,0,0,0,0,0,0,0,0
11,ETOPOSIDE,7.052222,-0.089167,7.052222,0.050926,0.281874,129.167,118.079,129.101445,52,...,0,0,0,0,0,0,0,0,0,0
12,GELDANAMYCIN,12.370387,-1.299841,12.370387,0.013755,0.294720,454.447,432.271,454.171316,172,...,0,0,0,0,0,0,0,0,0,0
13,GEMCITABINE,12.347714,-4.520186,12.347714,0.051527,0.714202,428.495,397.247,428.228678,168,...,0,0,0,0,0,0,0,0,0,0
14,L778123,12.938877,-4.641865,12.938877,0.065939,0.461340,464.831,448.703,464.086303,166,...,0,0,0,0,0,0,0,0,0,1
15,LAPATINIB,12.770676,-0.957338,12.770676,0.058604,0.410670,334.332,316.188,334.127720,128,...,0,0,0,0,0,0,0,0,0,0
16,METFORMIN,13.325348,-1.002013,13.325348,0.080112,0.345972,560.644,520.324,560.273381,220,...,0,0,0,0,0,0,0,0,0,0
17,METHOTREXATE,14.484260,-2.789734,14.484260,0.011682,0.103503,990.222,905.550,989.562943,390,...,0,0,0,0,0,0,0,0,0,0
18,MITOMYCINE,13.385114,-1.436270,13.385114,0.030064,0.429829,588.562,556.306,588.184291,226,...,0,0,0,0,0,0,0,0,0,0
19,MK-2206,13.643057,-2.240737,13.643057,0.017252,0.235263,543.525,514.293,543.174061,208,...,0,0,0,0,0,0,0,0,0,0
20,MK-4541,13.430803,-3.018996,13.430803,0.066362,0.179479,581.069,554.861,580.134732,206,...,0,0,1,0,0,0,0,0,1,0
21,MK-4827,12.693082,-0.266614,12.693082,0.173118,0.465717,488.017,461.809,487.155722,174,...,0,0,0,0,0,1,0,0,0,0
22,MK-5108,13.407466,-0.609468,13.407466,0.148733,0.323630,469.548,446.364,469.190260,174,...,0,0,0,0,0,0,0,0,0,0
23,MK-8669,6.294704,0.363031,6.294704,0.363031,0.714098,376.262,358.118,375.080706,120,...,0,0,0,0,0,0,0,0,0,0
24,MK-8776,11.395484,-0.740692,11.395484,0.060000,0.560119,194.154,188.106,194.055223,72,...,0,0,0,0,0,0,0,0,0,0
25,MRK-003,12.673665,0.066365,12.673665,0.066365,0.652854,405.889,385.729,405.135638,146,...,0,0,0,0,0,0,0,0,0,0
26,OXALIPLATIN,10.364167,-1.444444,10.364167,0.000000,0.523123,373.266,359.154,373.060148,82,...,0,0,0,0,0,0,0,0,0,0
27,PACLITAXEL,11.547430,-0.452781,11.547430,0.452781,0.778874,320.396,300.236,320.163711,122,...,0,0,0,0,0,0,0,0,0,0
28,PD325901,12.022437,-0.259690,12.022437,0.184105,0.468068,407.477,386.309,407.174610,152,...,0,0,0,0,0,0,0,0,0,0
29,SN-38,9.099537,-1.824074,9.099537,0.000000,0.401958,399.304,383.176,399.074701,90,...,0,0,0,0,0,0,0,0,0,0
30,SORAFENIB,13.700872,-3.713275,13.700872,0.114056,0.612087,263.200,252.112,263.071762,100,...,0,0,0,0,0,0,0,0,0,0
31,SUNITINIB,11.591415,-0.359425,11.591415,0.013242,0.383220,264.325,244.165,264.147393,104,...,0,0,0,0,0,0,0,0,3,0
32,TEMOZOLOMIDE,14.168820,-1.369451,14.168820,0.152234,0.359960,482.196,468.084,481.995040,140,...,0,0,0,0,0,0,0,0,0,0
33,TOPOTECAN,14.128791,-0.931009,14.128791,0.005098,0.468513,461.946,440.778,461.097618,162,...,0,0,0,0,0,1,0,0,0,0
34,VINBLASTINE,12.188549,-2.842184,12.188549,0.422539,0.605721,261.089,245.969,260.024820,84,...,0,0,0,0,0,0,0,0,0,0
35,VINORELBINE,13.052592,-4.608639,13.052592,0.076133,0.559206,551.597,520.349,551.204118,206,...,0,0,0,0,0,0,0,0,0,0
36,ZOLINZA,11.984815,-1.001157,11.984815,0.707037,0.482565,130.078,127.054,130.017856,48,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
!pip install mordred

Collecting mordred
  Downloading mordred-1.2.0.tar.gz (128 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 128.8/128.8 kB 3.3 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: six==1.* in /usr/local/lib/python3.12/dist-packages (from mordred) (1.17.0)
ERROR: Operation cancelled by user
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/pip/_internal/cli/base_command.py", line 179, in exc_logging_wrapper
    status = run_func(*args)
             ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pip/_internal/cli/req_command.py", line 67, in wrapper
    return func(self, options, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pip/_internal/commands/install.py", line 377, in run
    requirement_set = resolver.resolve(
                      ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pip/_internal/resolution/resolvelib/resolver.py", line 95, in resolve
    result = self._result = resolver.resolve(
                            ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pip/_vendor/resolvelib/resolvers.py", line 546, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pip/_vendor/resolvelib/resolvers.py", line 427, in resolve
    failure_causes = self._attempt_to_pin_criterion(name)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pip/_vendor/resolvelib/resolvers.py", line 239, in _attempt_to_pin_criterion
    criteria = self._get_updated_criteria(candidate)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pip/_vendor/resolvelib/resolvers.py", line 230, in _get_updated_criteria
    self._add_to_criteria(criteria, requirement, parent=candidate)
  File "/usr/local/lib/python3.12/dist-packages/pip/_vendor/resolvelib/resolvers.py", line 173, in _add_to_criteria
    if not criterion.candidates:
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pip/_vendor/resolvelib/structs.py", line 156, in __bool__
    return bool(self._sequence)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 174, in __bool__
    return any(self)
           ^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 162, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
                       ^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 49, in _iter_built
    for version, func in infos:
                         ^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pip/_internal/resolution/resolvelib/factory.py", line 300, in iter_index_candidate_infos
    result = self._finder.find_best_candidate(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pip/_internal/index/package_finder.py", line 884, in find_best_candidate
    candidates = self.find_all_candidates(project_name)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pip/_internal/index/package_finder.py", line 825, in find_all_candidates
    page_candidates = list(page_candidates_it)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pip/_internal/index/sources.py", line 194, in page_candidates
    yield from self._candidates_from_page(self._link)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pip/_internal/index/package_finder.py", line 785, in process_project_url
    index_response = self._link_collector.fetch_response(project_url)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pip/_internal/index/collector.py", line 448, in fetch_response
    return _get_index_content(location, session=self.session)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pip/_internal/index/collector.py", line 352, in _get_index_content
    resp = _get_simple_response(url, session=session)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pip/_internal/index/collector.py", line 131, in _get_simple_response
    resp = session.get(
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pip/_vendor/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pip/_internal/network/session.py", line 522, in request
    return super().request(method, url, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pip/_vendor/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pip/_vendor/requests/sessions.py", line 746, in send
    r.content
  File "/usr/local/lib/python3.12/dist-packages/pip/_vendor/requests/models.py", line 902, in content
    self._content = b"".join(self.iter_content(CONTENT_CHUNK_SIZE)) or b""
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pip/_vendor/requests/models.py", line 820, in generate
    yield from self.raw.stream(chunk_size, decode_content=True)
  File "/usr/local/lib/python3.12/dist-packages/pip/_vendor/urllib3/response.py", line 622, in stream
    data = self.read(amt=amt, decode_content=decode_content)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pip/_vendor/urllib3/response.py", line 561, in read
    data = self._fp_read(amt) if not fp_closed else b""
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pip/_vendor/urllib3/response.py", line 527, in _fp_read
    return self._fp.read(amt) if amt is not None else self._fp.read()
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pip/_vendor/cachecontrol/filewrapper.py", line 98, in read
    data: bytes = self.__fp.read(amt)
                  ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/http/client.py", line 479, in read
    s = self.fp.read(amt)
        ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/socket.py", line 720, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/ssl.py", line 1251, in recv_into
    return self.read(nbytes, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/ssl.py", line 1103, in read
    return self._sslobj.read(len, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/pip3", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pip/_internal/cli/main.py", line 80, in main
    return command.main(cmd_args)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pip/_internal/cli/base_command.py", line 100, in main
    return self._main(args)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pip/_internal/cli/base_command.py", line 232, in _main
    return run(options, args)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pip/_internal/cli/base_command.py", line 215, in exc_logging_wrapper
    logger.critical("Operation cancelled by user")
  File "/usr/lib/python3.12/logging/__init__.py", line 1586, in critical
    self._log(CRITICAL, msg, args, **kwargs)
  File "/usr/lib/python3.12/logging/__init__.py", line 1684, in _log
    self.handle(record)
  File "/usr/lib/python3.12/logging/__init__.py", line 1700, in handle
    self.callHandlers(record)
  File "/usr/lib/python3.12/logging/__init__.py", line 1762, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python3.12/logging/__init__.py", line 1028, in handle
    self.emit(record)
  File "/usr/lib/python3.12/logging/handlers.py", line 75, in emit
    logging.FileHandler.emit(self, record)
  File "/usr/lib/python3.12/logging/__init__.py", line 1280, in emit
    StreamHandler.emit(self, record)
  File "/usr/lib/python3.12/logging/__init__.py", line 1160, in emit
    msg = self.format(record)
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/logging/__init__.py", line 999, in format
    return fmt.format(record)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pip/_internal/utils/logging.py", line 120, in format
    formatted = "".join([prefix + line for line in formatted.splitlines(True)])
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
^C

KeyboardInterrupt:

##**DDI using GAT from Drug SMILES Data [ddi_features_128.npy]:**

---

In [ ]:
pip install torch-geometric

Collecting torch-geometric
  Downloading torch_geometric-2.6.1-py3-none-any.whl.metadata (63 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 63.1/63.1 kB 1.5 MB/s eta 0:00:00
Requirement already satisfied: aiohttp in /usr/local/lib/python3.12/dist-packages (from torch-geometric) (3.12.15)
Requirement already satisfied: fsspec in /usr/local/lib/python3.12/dist-packages (from torch-geometric) (2025.3.0)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch-geometric) (3.1.6)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from torch-geometric) (2.0.2)
Requirement already satisfied: psutil>=5.8.0 in /usr/local/lib/python3.12/dist-packages (from torch-geometric) (5.9.5)
Requirement already satisfied: pyparsing in /usr/local/lib/python3.12/dist-packages (from torch-geometric) (3.2.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from torch-geometric) (2.32.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from torch-geometric) (4.67.1)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->torch-geometric) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->torch-geometric) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->torch-geometric) (25.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp->torch-geometric) (1.7.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp->torch-geometric) (6.6.4)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->torch-geometric) (0.3.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->torch-geometric) (1.20.1)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch-geometric) (3.0.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->torch-geometric) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->torch-geometric) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->torch-geometric) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->torch-geometric) (2025.8.3)
Requirement already satisfied: typing-extensions>=4.2 in /usr/local/lib/python3.12/dist-packages (from aiosignal>=1.4.0->aiohttp->torch-geometric) (4.14.1)
Downloading torch_geometric-2.6.1-py3-none-any.whl (1.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 17.5 MB/s eta 0:00:00
Installing collected packages: torch-geometric
Successfully installed torch-geometric-2.6.1

In [ ]:
import pandas as pd
esmiles = pd.read_csv('/content/drive/MyDrive/MACSynDCR/Data/Drug/ext_smiles.csv')

ext_smiles = pd.DataFrame(data=esmiles)
#smiles_list=smiles.iloc[:,2]
ext_smiles
#external_smiles_list=ext_smiles_df.iloc[:,0]
#external_smiles_list

                                               SMILES
0   CNC(=O)CN1CCC(CC1)Oc2cc3c(cc2OC)ncnc3Nc4cccc(c...
1   C[C@@H]1CN(C[C@@H](N1)C)c2ccc(cc2)C(=O)Nc3cc(n...
2   CS(=O)(=O)N1CCN(CC1)Cc2cc3c(s2)c(nc(n3)c4cccc5...
3   CC(c1cc(cc2c1oc(cc2=O)N3CCOCC3)C(=O)N(C)C)Nc4c...
4   c1c(c(cnc1N)c2cc(nc(n2)N3CCOCC3)N4CCOCC4)C(F)(F)F
5   CN(CC[C@H](CSc1ccccc1)Nc2ccc(cc2S(=O)(=O)C(F)(...
6        Cn1cnc2c1cc(c(c2F)Nc3ccc(cc3Cl)Br)C(=O)NOCCO
7   COc1cc(ccc1Nc2ncc(c(n2)c3c[nH]c4c3cccc4)Cl)N5C...
8   C[C@H]1COCCN1c2c3ccc(nc3nc(n2)N4CCOC[C@@H]4C)c...
9   C[C@@H]1COCCN1c2cc(nc(n2)c3ccnc4c3cc[nH]4)C5(C...
10  CN(C)CC#Cc1ccc(OCCCc2sc(nc2C(=O)O)N3CCc4cccc(C...
11  CC(=O)Nc1cc(ccc1N(C)CCN)Nc2cc(n3c(n2)c(cn3)C#N...
12                c1cn(c(=O)nc1N)C2C(C(C(O2)CO)O)(F)F
13  CN(C)C/C=C/C(=O)Nc1cc2c(cc1O[C@H]3CCOC3)ncnc2N...
14   COc1cc2c(cc1OCCCN3CCOCC3)c(ncn2)Nc4ccc(c(c4)Cl)F
15  c1cc(ccc1c2ccc3c(c2)cco3)c4nc5cnccc5n4C[C@@H]6...
16  C[C@H]1COCCN1c2c3ccc(nc3nc(n2)N4CCOC[C@@H]4C)c...
17    CN1CCC(CC1)COc2cc3c(cc2OC)c(ncn3)Nc4ccc(cc4F)Br
18  c1ccc(cc1)c2cccc(c2N3CCC[C@H](C3)N)/C=C\4/C(=O...
19  c1ccc2c(c1)c3cccc(c3s2)c4cccc5c4oc(cc5=O)N6CCOCC6
20  Cc1c(sc(n1)NC(=O)N2CCC[C@H]2C(=O)N)c3ccnc(c3)C...
21  c1ccc(cc1)c2cc3c(ccn4c3n[nH]c4=O)nc2c5ccc(cc5)...
22  C[C@H](C(=O)N1CCC(CC1)c2ccc(c(c2)OC)Nc3ncc(c(n...
23  Cc1c(cn(n1)C)Nc2cc(c(cn2)C(F)(F)F)Nc3ccccc3C(=...
24               COc1cc(cnc1)Nc2cncc(n2)c3cnc4n3cccc4
25  COc1cc2c(cc1OC)C3(CCN(CC3)c4c5c([nH]nc5Br)ncn4...
26  c1ccc2c(c1)c(n[nH]c2=O)Cc3ccc(c(c3)C(=O)N4CCN(...
27  c1cc(cc(c1)F)c2cc(c(s2)C(=O)N[C@H]3CCCNC3)NC(=O)N
28  COc1cc(ccc1Nc2ncc(c(n2)c3cnc4n3cccc4)F)N5CCN(C...
29  COC1CCN(CC1)C(=O)c2cc(ccc2F)Cc3c4ccccc4c(=O)[n...
30       CS(=O)(=O)c1ccc(cc1)Nc2cncc(n2)c3cnc4n3cccc4
31  C[C@H](c1c(ccc(c1Cl)F)Cl)Oc2cc(cnc2N)c3cnn(c3)...
32  CCc1c2cc(ccc2nc-3c1Cn4c3cc5c(c4=O)COC(=O)[C@@]...
33  c1cc(c(c(c1)OCC2CC2)c3cc(c4c(n3)NC(=O)OC4)C5CC...
34  CCN1CCN(CC1)CC(=O)Nc2ccc(c3c2c4ccccc4s3)c5cccc...
35  Cc1c(cn(n1)C)Nc2cc(c(cn2)C(F)(F)F)Nc3ccc(cc3C(...
36  CC1(C(=O)Nc2c(ccc(n2)Nc3c(cnc(n3)Nc4cc(c(c(c4)...
37  CN1CCN(CC1)CCOc2cc3c(c(c2)OC4CCOCC4)c(ncn3)Nc5...
38  C[C@]1(C[C@@H](C1)c2n3c(c(ncc3)N)c(n2)c4cc5nc(...
39  CC1=C2C(=C(N(C1=O)C)NC3=C(C=C(C=C3)I)F)C(=O)N(...
40  CC(=O)Nc1cc(ccc1N(C)CCN(C)C)Nc2cc(n3c(n2)c(cn3...
41     c1cc2cc(ccc2nc1)Cn3c4c(ncc(n4)c5cnn(c5)CCO)nn3
42  Cc1c2c(c(n(c1=O)C)Nc3ccc(cc3F)I)c(=O)n(c(=O)n2...
43  Cc1cc(n[nH]1)Nc2c(cnc(n2)N[C@@H](C)c3ncc(cn3)F)Cl
44  c1cc(ccc1[C@H](CCO)NC(=O)C2(CCN(CC2)c3c4cc[nH]...
45  CC1(CCC(=C(C1)CN2CCN(CC2)c3ccc(cc3)C(=O)NS(=O)...
46  CN1CCN(CC1)C2CCN(CC2)c3ccc(c(c3)OC)Nc4ncc(c(n4...
47  CCCS(=O)(=O)Nc1ccc(c(c1F)C(=O)c2c[nH]c3c2cc(cn...
48  CC1C(C(CC(O1)OC2CC(Cc3c2c(c4c(c3O)C(=O)c5cccc(...
49  C[C@@H]1COCCN1c2cc(nc(n2)c3cccc4c3cc[nH]4)C5(C...
50  C[C@@H]1CN(C[C@@H](O1)C)CC(=O)Nc2ccc3c(c2)Cc4c...
51  CS(=O)(=O)C1(CC1)c2cc(nc(n2)c3cccc4c3cc[nH]4)N...

In [ ]:
!pip install torch_geometric
!pip install rdkit

Collecting torch_geometric
  Downloading torch_geometric-2.6.1-py3-none-any.whl.metadata (63 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 63.1/63.1 kB 1.7 MB/s eta 0:00:00
Requirement already satisfied: aiohttp in /usr/local/lib/python3.12/dist-packages (from torch_geometric) (3.12.15)
Requirement already satisfied: fsspec in /usr/local/lib/python3.12/dist-packages (from torch_geometric) (2025.3.0)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch_geometric) (3.1.6)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from torch_geometric) (2.0.2)
Requirement already satisfied: psutil>=5.8.0 in /usr/local/lib/python3.12/dist-packages (from torch_geometric) (5.9.5)
Requirement already satisfied: pyparsing in /usr/local/lib/python3.12/dist-packages (from torch_geometric) (3.2.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from torch_geometric) (2.32.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from torch_geometric) (4.67.1)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->torch_geometric) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->torch_geometric) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->torch_geometric) (25.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp->torch_geometric) (1.7.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp->torch_geometric) (6.6.4)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->torch_geometric) (0.3.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->torch_geometric) (1.20.1)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch_geometric) (3.0.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->torch_geometric) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->torch_geometric) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->torch_geometric) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->torch_geometric) (2025.8.3)
Requirement already satisfied: typing-extensions>=4.2 in /usr/local/lib/python3.12/dist-packages (from aiosignal>=1.4.0->aiohttp->torch_geometric) (4.14.1)
Downloading torch_geometric-2.6.1-py3-none-any.whl (1.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 17.7 MB/s eta 0:00:00
Installing collected packages: torch_geometric
Successfully installed torch_geometric-2.6.1
Requirement already satisfied: rdkit in /usr/local/lib/python3.12/dist-packages (2025.3.5)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from rdkit) (2.0.2)
Requirement already satisfied: Pillow in /usr/local/lib/python3.12/dist-packages (from rdkit) (11.3.0)

In [ ]:
import torch
from torch_geometric.data import Data, DataLoader
from torch_geometric.nn import GATConv
from torch.nn import Linear, Sequential, ReLU, BatchNorm1d
from rdkit import Chem
import numpy as np

def smiles_to_graph(smiles):
    mol = Chem.MolFromSmiles(smiles)
    atoms = mol.GetAtoms()
    x = torch.tensor([atom.GetAtomicNum() for atom in atoms], dtype=torch.float).view(-1, 1)
    x = torch.nn.functional.one_hot(x.to(torch.int64).view(-1) - 1, num_classes=128).to(torch.float)

    edges = []
    for bond in mol.GetBonds():
        edges.append([bond.GetBeginAtomIdx(), bond.GetEndAtomIdx()])
        edges.append([bond.GetEndAtomIdx(), bond.GetBeginAtomIdx()])

    edge_index = torch.tensor(edges, dtype=torch.long).t().contiguous()

    return Data(x=x, edge_index=edge_index)

In [ ]:
import torch
import torch.nn.functional as F

def mol_resize(tensor,target_size):
    # Calculate padding
    padding_needed = target_size - tensor.size(0)
    # Pad only the first dimension (top and bottom)
    pad = (0, 0, padding_needed, 0)  # (left, right, top, bottom) for 2D
    # Apply padding
    padded_tensor = F.pad(tensor, pad, "constant", 0)  # Adding zeros
    return padded_tensor

In [ ]:
class DDIModel(torch.nn.Module):
    def __init__(self):
        super(DDIModel, self).__init__()
        self.conv1 = GATConv(in_channels=128, out_channels=32, heads=4, concat=True)
        self.conv2 = GATConv(in_channels=32*4, out_channels=128, heads=1, concat=False)
        self.fc = Sequential(Linear(2*128, 256), ReLU(), BatchNorm1d(256), Linear(256, 128))

    def forward(self, data1, data2):
        x1, edge_index1 = data1.x, data1.edge_index
        x2, edge_index2 = data2.x, data2.edge_index

        x1 = self.conv1(x1, edge_index1)
        x1 = torch.relu(x1)
        x1 = self.conv2(x1, edge_index1)

        x2 = self.conv1(x2, edge_index2)
        x2 = torch.relu(x2)
        x2 = self.conv2(x2, edge_index2)
        if x1.shape[0]>x2.shape[0]:
            x2=mol_resize(x2,x1.shape[0])
        elif x1.shape[0]<x2.shape[0]:
            x1=mol_resize(x1,x2.shape[0])

        # Concatenate the features from both drugs
        #x1 = torch.mean(x1, dim=0)
        #x2 = torch.mean(x2, dim=0)
        x = torch.cat([x1, x2], dim=1)
        x = self.fc(x)
        return x

In [ ]:
def extract_ddi_features(smiles1, smiles2, model):
    graph1 = smiles_to_graph(smiles1)
    graph2 = smiles_to_graph(smiles2)
    features = model(graph1, graph2)
    f=torch.mean(features,dim=0)
    return f.detach().numpy()

In [ ]:
# Initialize model and example
def DDI_features_128(smiles1,smiles2):
    model = DDIModel()
    # Example SMILES for two drugs
    #smiles1 = 'COCCCCC' # Ethanol
    #smiles2 = 'CCOO' # Isopropanol
    # Extract features
    DDI_features = extract_ddi_features(smiles1, smiles2, model)
    #print(DDI_features.shape)  # Should be (128,)
    return DDI_features
DDI_features_128('CO', 'CCOO')

array([-0.00777793,  0.02557307, -0.03770041,  0.05531486, -0.01172279,
       -0.00853889,  0.03789239, -0.04094714,  0.04294996,  0.02415174,
        0.01179817,  0.0097219 , -0.05708948, -0.04717234,  0.00697791,
       -0.03577422,  0.06232277, -0.037811  , -0.02230412, -0.02732754,
        0.00075302, -0.04335418,  0.02992426,  0.0143056 , -0.01270447,
       -0.00542587,  0.01090195, -0.00033899, -0.03924794, -0.0574244 ,
        0.01047759, -0.0395016 ,  0.02025286, -0.04144488, -0.00865975,
        0.03234335, -0.05301299,  0.00194927,  0.04948732, -0.0285878 ,
       -0.03700852,  0.04890013, -0.05543392, -0.00780701,  0.00799252,
       -0.047175  , -0.05016372,  0.05642274,  0.00230142,  0.01812683,
        0.00675435,  0.00091277, -0.03403383, -0.03653819,  0.04785538,
        0.02882866,  0.00310038, -0.04177851,  0.05117042, -0.0571891 ,
       -0.04833928, -0.00934042,  0.01864444, -0.02119848,  0.05848943,
       -0.01650469,  0.04436156, -0.01551767,  0.05405957,  0.05559635,
        0.00119677, -0.04863063,  0.01722613, -0.02094873, -0.05279167,
       -0.05130406, -0.02883893, -0.01912744, -0.0584868 ,  0.03248614,
        0.01345087, -0.03629021,  0.03941692, -0.0123163 ,  0.03752889,
       -0.00911972,  0.0282523 , -0.01823199,  0.04345205,  0.04030669,
        0.01706253,  0.00324097, -0.0597981 ,  0.04651369, -0.01395911,
       -0.02818639,  0.0049994 , -0.04586853,  0.04032699,  0.04220346,
       -0.01084223, -0.01525284, -0.04477623, -0.01143456,  0.04351907,
        0.06079957,  0.05798012,  0.04334269,  0.05568108,  0.00048915,
       -0.03096561,  0.05289026, -0.05186973, -0.00131709,  0.00882712,
       -0.03092737,  0.05349235,  0.01146233, -0.04107932, -0.03267408,
       -0.03387673, -0.03947288, -0.02292574, -0.03881286, -0.00137443,
       -0.04113129, -0.03885314,  0.04805455], dtype=float32)

##**Drug molecular graph features using GAT from Drug SMILES Data [DMG\_features_128.npy]:**

In [ ]:
# @title
import pandas as pd
smiles = pd.read_csv('/content/drive/MyDrive/MACSynDCR/Data/Drug/ext_smiles.csv')
smiles = pd.DataFrame(data=smiles)
smiles_list=smiles.iloc[:,2]
smiles_list.head()

IndexError: single positional indexer is out-of-bounds

In [ ]:
# @title
import pandas as pd
smiles = pd.read_csv('/content/drive/MyDrive/MACSynDCR/Data/Drug/ext_smiles.csv')
ext_smiles_list = pd.DataFrame(data=smiles)
ext_smiles_list=smiles.iloc[:,0]
ext_smiles_list

0     CNC(=O)CN1CCC(CC1)Oc2cc3c(cc2OC)ncnc3Nc4cccc(c...
1     C[C@@H]1CN(C[C@@H](N1)C)c2ccc(cc2)C(=O)Nc3cc(n...
2     CS(=O)(=O)N1CCN(CC1)Cc2cc3c(s2)c(nc(n3)c4cccc5...
3     CC(c1cc(cc2c1oc(cc2=O)N3CCOCC3)C(=O)N(C)C)Nc4c...
4     c1c(c(cnc1N)c2cc(nc(n2)N3CCOCC3)N4CCOCC4)C(F)(F)F
5     CN(CC[C@H](CSc1ccccc1)Nc2ccc(cc2S(=O)(=O)C(F)(...
6          Cn1cnc2c1cc(c(c2F)Nc3ccc(cc3Cl)Br)C(=O)NOCCO
7     COc1cc(ccc1Nc2ncc(c(n2)c3c[nH]c4c3cccc4)Cl)N5C...
8     C[C@H]1COCCN1c2c3ccc(nc3nc(n2)N4CCOC[C@@H]4C)c...
9     C[C@@H]1COCCN1c2cc(nc(n2)c3ccnc4c3cc[nH]4)C5(C...
10    CN(C)CC#Cc1ccc(OCCCc2sc(nc2C(=O)O)N3CCc4cccc(C...
11    CC(=O)Nc1cc(ccc1N(C)CCN)Nc2cc(n3c(n2)c(cn3)C#N...
12                  c1cn(c(=O)nc1N)C2C(C(C(O2)CO)O)(F)F
13    CN(C)C/C=C/C(=O)Nc1cc2c(cc1O[C@H]3CCOC3)ncnc2N...
14     COc1cc2c(cc1OCCCN3CCOCC3)c(ncn2)Nc4ccc(c(c4)Cl)F
15    c1cc(ccc1c2ccc3c(c2)cco3)c4nc5cnccc5n4C[C@@H]6...
16    C[C@H]1COCCN1c2c3ccc(nc3nc(n2)N4CCOC[C@@H]4C)c...
17      CN1CCC(CC1)COc2cc3c(cc2OC)c(ncn3)Nc4ccc(cc4F)Br
18    c1ccc(cc1)c2cccc(c2N3CCC[C@H](C3)N)/C=C\4/C(=O...
19    c1ccc2c(c1)c3cccc(c3s2)c4cccc5c4oc(cc5=O)N6CCOCC6
20    Cc1c(sc(n1)NC(=O)N2CCC[C@H]2C(=O)N)c3ccnc(c3)C...
21    c1ccc(cc1)c2cc3c(ccn4c3n[nH]c4=O)nc2c5ccc(cc5)...
22    C[C@H](C(=O)N1CCC(CC1)c2ccc(c(c2)OC)Nc3ncc(c(n...
23    Cc1c(cn(n1)C)Nc2cc(c(cn2)C(F)(F)F)Nc3ccccc3C(=...
24                 COc1cc(cnc1)Nc2cncc(n2)c3cnc4n3cccc4
25    COc1cc2c(cc1OC)C3(CCN(CC3)c4c5c([nH]nc5Br)ncn4...
26    c1ccc2c(c1)c(n[nH]c2=O)Cc3ccc(c(c3)C(=O)N4CCN(...
27    c1cc(cc(c1)F)c2cc(c(s2)C(=O)N[C@H]3CCCNC3)NC(=O)N
28    COc1cc(ccc1Nc2ncc(c(n2)c3cnc4n3cccc4)F)N5CCN(C...
29    COC1CCN(CC1)C(=O)c2cc(ccc2F)Cc3c4ccccc4c(=O)[n...
30         CS(=O)(=O)c1ccc(cc1)Nc2cncc(n2)c3cnc4n3cccc4
31    C[C@H](c1c(ccc(c1Cl)F)Cl)Oc2cc(cnc2N)c3cnn(c3)...
32    CCc1c2cc(ccc2nc-3c1Cn4c3cc5c(c4=O)COC(=O)[C@@]...
33    c1cc(c(c(c1)OCC2CC2)c3cc(c4c(n3)NC(=O)OC4)C5CC...
34    CCN1CCN(CC1)CC(=O)Nc2ccc(c3c2c4ccccc4s3)c5cccc...
35    Cc1c(cn(n1)C)Nc2cc(c(cn2)C(F)(F)F)Nc3ccc(cc3C(...
36    CC1(C(=O)Nc2c(ccc(n2)Nc3c(cnc(n3)Nc4cc(c(c(c4)...
37    CN1CCN(CC1)CCOc2cc3c(c(c2)OC4CCOCC4)c(ncn3)Nc5...
38    C[C@]1(C[C@@H](C1)c2n3c(c(ncc3)N)c(n2)c4cc5nc(...
39    CC1=C2C(=C(N(C1=O)C)NC3=C(C=C(C=C3)I)F)C(=O)N(...
40    CC(=O)Nc1cc(ccc1N(C)CCN(C)C)Nc2cc(n3c(n2)c(cn3...
41       c1cc2cc(ccc2nc1)Cn3c4c(ncc(n4)c5cnn(c5)CCO)nn3
42    Cc1c2c(c(n(c1=O)C)Nc3ccc(cc3F)I)c(=O)n(c(=O)n2...
43    Cc1cc(n[nH]1)Nc2c(cnc(n2)N[C@@H](C)c3ncc(cn3)F)Cl
44    c1cc(ccc1[C@H](CCO)NC(=O)C2(CCN(CC2)c3c4cc[nH]...
45    CC1(CCC(=C(C1)CN2CCN(CC2)c3ccc(cc3)C(=O)NS(=O)...
46    CN1CCN(CC1)C2CCN(CC2)c3ccc(c(c3)OC)Nc4ncc(c(n4...
47    CCCS(=O)(=O)Nc1ccc(c(c1F)C(=O)c2c[nH]c3c2cc(cn...
48    CC1C(C(CC(O1)OC2CC(Cc3c2c(c4c(c3O)C(=O)c5cccc(...
49    C[C@@H]1COCCN1c2cc(nc(n2)c3cccc4c3cc[nH]4)C5(C...
50    C[C@@H]1CN(C[C@@H](O1)C)CC(=O)Nc2ccc3c(c2)Cc4c...
51    CS(=O)(=O)C1(CC1)c2cc(nc(n2)c3cccc4c3cc[nH]4)N...
Name: SMILES, dtype: object

In [ ]:
pip install torch torchvision torchaudio

Requirement already satisfied: torch in /usr/local/lib/python3.12/dist-packages (2.8.0+cu126)
Requirement already satisfied: torchvision in /usr/local/lib/python3.12/dist-packages (0.23.0+cu126)
Requirement already satisfied: torchaudio in /usr/local/lib/python3.12/dist-packages (2.8.0+cu126)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch) (3.19.1)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch) (4.14.1)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch) (1.13.3)
Requirement already satisfied: networkx in /usr/local/lib/python3.12/dist-packages (from torch) (3.5)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch) (3.1.6)
Requirement already satisfied: fsspec in /usr/local/lib/python3.12/dist-packages (from torch) (2025.3.0)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch) (12.6.77)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch) (12.6.77)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.6.80 in /usr/local/lib/python3.12/dist-packages (from torch) (12.6.80)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.6.4.1 in /usr/local/lib/python3.12/dist-packages (from torch) (12.6.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.0.4 in /usr/local/lib/python3.12/dist-packages (from torch) (11.3.0.4)
Requirement already satisfied: nvidia-curand-cu12==10.3.7.77 in /usr/local/lib/python3.12/dist-packages (from torch) (10.3.7.77)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.1.2 in /usr/local/lib/python3.12/dist-packages (from torch) (11.7.1.2)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.4.2 in /usr/local/lib/python3.12/dist-packages (from torch) (12.5.4.2)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.3 in /usr/local/lib/python3.12/dist-packages (from torch) (2.27.3)
Requirement already satisfied: nvidia-nvtx-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch) (12.6.77)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.6.85 in /usr/local/lib/python3.12/dist-packages (from torch) (12.6.85)
Requirement already satisfied: nvidia-cufile-cu12==1.11.1.6 in /usr/local/lib/python3.12/dist-packages (from torch) (1.11.1.6)
Requirement already satisfied: triton==3.4.0 in /usr/local/lib/python3.12/dist-packages (from torch) (3.4.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from torchvision) (2.0.2)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in /usr/local/lib/python3.12/dist-packages (from torchvision) (11.3.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch) (3.0.2)

In [ ]:
pip install torch_geometric

Requirement already satisfied: torch_geometric in /usr/local/lib/python3.11/dist-packages (2.6.1)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.11/dist-packages (from torch_geometric) (3.11.15)
Requirement already satisfied: fsspec in /usr/local/lib/python3.11/dist-packages (from torch_geometric) (2025.3.2)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.11/dist-packages (from torch_geometric) (3.1.6)
Requirement already satisfied: numpy in /usr/local/lib/python3.11/dist-packages (from torch_geometric) (1.26.4)
Requirement already satisfied: psutil>=5.8.0 in /usr/local/lib/python3.11/dist-packages (from torch_geometric) (5.9.5)
Requirement already satisfied: pyparsing in /usr/local/lib/python3.11/dist-packages (from torch_geometric) (3.2.3)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from torch_geometric) (2.32.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.11/dist-packages (from torch_geometric) (4.67.1)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->torch_geometric) (2.6.1)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from aiohttp->torch_geometric) (1.3.2)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->torch_geometric) (25.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.11/dist-packages (from aiohttp->torch_geometric) (1.6.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.11/dist-packages (from aiohttp->torch_geometric) (6.4.4)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->torch_geometric) (0.3.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->torch_geometric) (1.20.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from jinja2->torch_geometric) (3.0.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->torch_geometric) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->torch_geometric) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->torch_geometric) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests->torch_geometric) (2025.4.26)

In [ ]:
!pip install torch_geometric
!pip install rdkit

Requirement already satisfied: torch_geometric in /usr/local/lib/python3.12/dist-packages (2.6.1)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.12/dist-packages (from torch_geometric) (3.12.15)
Requirement already satisfied: fsspec in /usr/local/lib/python3.12/dist-packages (from torch_geometric) (2025.3.0)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch_geometric) (3.1.6)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from torch_geometric) (2.0.2)
Requirement already satisfied: psutil>=5.8.0 in /usr/local/lib/python3.12/dist-packages (from torch_geometric) (5.9.5)
Requirement already satisfied: pyparsing in /usr/local/lib/python3.12/dist-packages (from torch_geometric) (3.2.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from torch_geometric) (2.32.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from torch_geometric) (4.67.1)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->torch_geometric) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->torch_geometric) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->torch_geometric) (25.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp->torch_geometric) (1.7.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp->torch_geometric) (6.6.4)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->torch_geometric) (0.3.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->torch_geometric) (1.20.1)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch_geometric) (3.0.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->torch_geometric) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->torch_geometric) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->torch_geometric) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->torch_geometric) (2025.8.3)
Requirement already satisfied: typing-extensions>=4.2 in /usr/local/lib/python3.12/dist-packages (from aiosignal>=1.4.0->aiohttp->torch_geometric) (4.14.1)
Requirement already satisfied: rdkit in /usr/local/lib/python3.12/dist-packages (2025.3.5)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from rdkit) (2.0.2)
Requirement already satisfied: Pillow in /usr/local/lib/python3.12/dist-packages (from rdkit) (11.3.0)

In [ ]:
# @title
import torch
from torch_geometric.data import Data
from torch_geometric.nn import GATConv
from rdkit import Chem
from rdkit.Chem import AllChem
import numpy as np

class GATNet(torch.nn.Module):
    def __init__(self):
        super(GATNet, self).__init__()
        self.conv1 = GATConv(in_channels=100, out_channels=128, heads=1)
        self.linear = torch.nn.Linear(128, 128)

    def forward(self, data):
        x, edge_index = data.x, data.edge_index
        x = self.conv1(x, edge_index)
        x = torch.sigmoid(x)
        x = torch.mean(x, dim=0)
        x = self.linear(x)
       ## print(x.shape)
        return x

In [ ]:
# @title
def smiles_to_graph(smiles):
    mol = Chem.MolFromSmiles(smiles)
    atoms = mol.GetAtoms()
    num_nodes = len(atoms)
    x = torch.tensor([atom.GetAtomicNum() for atom in atoms], dtype=torch.float).view(-1, 1)
    x = torch.nn.functional.one_hot(x.to(torch.int64).view(-1) - 1, num_classes=100).to(torch.float)

    edges = []
    for bond in mol.GetBonds():
        edges.append([bond.GetBeginAtomIdx(), bond.GetEndAtomIdx()])
        edges.append([bond.GetEndAtomIdx(), bond.GetBeginAtomIdx()])

    edge_index = torch.tensor(edges, dtype=torch.long).t().contiguous()

    data = Data(x=x, edge_index=edge_index)
    return data

In [ ]:
# @title
import numpy
def extract_features(smiles):
    model = GATNet()
    data = smiles_to_graph(smiles)
    features = model(data)
    return features.detach().numpy()

# Example usage:
DMG_features=[]
for sm in ext_smiles_list:
   # print(sm)
    features = extract_features(sm)
    #print(features.shape)  # Should be (128,)
    DMG_features.append(features)
DMG_features_128=numpy.array(DMG_features)
print(DMG_features_128.shape)
len(DMG_features)

(52, 128)

52

In [ ]:
# @title
import pandas as pd
df = pd.DataFrame(DMG_features)
#print(df.to_csv(index=False, header=False))
df.to_csv('/content/drive/MyDrive/MACSynDCR/Data/Drug/ext_DMG_GAT_data.csv')
np.save('/content/drive/MyDrive/MACSynDCR/Data/Drug/ext_DMG_features_128', DMG_features_128)
DMG_features_128.shape

(52, 128)

##**Load all features and concatanation:**##

Load O'Neil dataset:

Oneil(Marck) dataset from DeepSynergy:

In [ ]:
# @title
import pandas as pd
OneilData = pd.read_csv('/content/drive/MyDrive/MACSynDCR/Data/DeepSynergyDataset.csv')
OneilData = pd.DataFrame(data=OneilData)
#smiles_list=smiles.iloc[:,2]
OneilData

      drug_a_name drug_b_name     cell_line    synergy  fold
0            5-FU     ABT-888         A2058   7.693530     2
1            5-FU     ABT-888         A2780   7.778053     2
2            5-FU     ABT-888          A375  -1.198505     2
3            5-FU     ABT-888          A427   2.595684     2
4            5-FU     ABT-888         CAOV3  -5.139971     2
...           ...         ...           ...        ...   ...
23047     ZOLINZA   TOPOTECAN        UACC62  10.223066     2
23048     ZOLINZA   TOPOTECAN  UWB1289BRCA1  20.551627     2
23049     ZOLINZA   TOPOTECAN       UWB1289  12.190316     2
23050     ZOLINZA   TOPOTECAN          VCAP  23.438547     2
23051     ZOLINZA   TOPOTECAN         ZR751  12.223791     2

[23052 rows x 5 columns]

In [ ]:
# @title
import pandas as pd
OneilData = pd.read_csv('/content/drive/MyDrive/MACSynDCR/Data/oneil.csv')
OneilData = pd.DataFrame(data=OneilData)
#smiles_list=smiles.iloc[:,2]
OneilData

         drug1      drug2          cell    synergy  fold
0         5-FU    ABT-888         A2058   7.693530     2
1         5-FU    ABT-888         A2780   7.778053     2
2         5-FU    ABT-888          A375  -1.198505     2
3         5-FU    ABT-888          A427   2.595684     2
4         5-FU    ABT-888         CAOV3  -5.139971     2
...        ...        ...           ...        ...   ...
22732  ZOLINZA  TOPOTECAN        UACC62  10.223066     2
22733  ZOLINZA  TOPOTECAN       UWB1289  12.190316     2
22734  ZOLINZA  TOPOTECAN  UWB1289BRCA1  20.551627     2
22735  ZOLINZA  TOPOTECAN          VCAP  23.438547     2
22736  ZOLINZA  TOPOTECAN         ZR751  12.223791     2

[22737 rows x 5 columns]

**Load MFSynDCP dataset:**

In [ ]:
# @title
import pandas as pd
OneilData = pd.read_csv('/content/drive/MyDrive/MACSynDCR/Data/MFSynDCPData.csv')
OneilData = pd.DataFrame(data=OneilData)
#smiles_list=smiles.iloc[:,2]
OneilData

,drug1,drug2,cell,label
0,O=c1[nH]cc(F)c(=O)[nH]1,CC1(c2nc3c(C(N)=O)cccc3[nH]2)CCCN1,A375,0
1,O=c1[nH]cc(F)c(=O)[nH]1,CC1(c2nc3c(C(N)=O)cccc3[nH]2)CCCN1,CAOV3,0
2,O=c1[nH]cc(F)c(=O)[nH]1,CC1(c2nc3c(C(N)=O)cccc3[nH]2)CCCN1,HT144,0
3,O=c1[nH]cc(F)c(=O)[nH]1,CC1(c2nc3c(C(N)=O)cccc3[nH]2)CCCN1,HT29,1
4,O=c1[nH]cc(F)c(=O)[nH]1,CC1(c2nc3c(C(N)=O)cccc3[nH]2)CCCN1,LOVO,0
...,...,...,...,...
12410,O=C(CCCCCCC(=O)Nc1ccccc1)NO,CCC1(O)C(=O)OCc2c1cc1n(c2=O)Cc2cc3c(CN(C)C)c(O...,SKOV3,1
12411,O=C(CCCCCCC(=O)Nc1ccccc1)NO,CCC1(O)C(=O)OCc2c1cc1n(c2=O)Cc2cc3c(CN(C)C)c(O...,T47D,1
12412,O=C(CCCCCCC(=O)Nc1ccccc1)NO,CCC1(O)C(=O)OCc2c1cc1n(c2=O)Cc2cc3c(CN(C)C)c(O...,UACC62,1
12413,O=C(CCCCCCC(=O)Nc1ccccc1)NO,CCC1(O)C(=O)OCc2c1cc1n(c2=O)Cc2cc3c(CN(C)C)c(O...,VCAP,1
12414,O=C(CCCCCCC(=O)Nc1ccccc1)NO,CCC1(O)C(=O)OCc2c1cc1n(c2=O)Cc2cc3c(CN(C)C)c(O...,ZR751,1

**Merck Dataset:**

In [ ]:
# @title
import pandas as pd
MerckData = pd.read_csv('/content/drive/MyDrive/MACSynDCR/Data/Merck.csv')
MerckData = pd.DataFrame(data=MerckData)
#smiles_list=smiles.iloc[:,2]
MerckData

         drug1      drug2    cell      score  label
0         5-FU    ABT-888    A375  -1.198505      0
1         5-FU    ABT-888   CAOV3  -5.139971      0
2         5-FU    ABT-888   HT144  -3.701355      0
3         5-FU    ABT-888    HT29  10.173434      1
4         5-FU    ABT-888    LOVO  -8.979214      0
...        ...        ...     ...        ...    ...
12410  ZOLINZA  TOPOTECAN   SKOV3  26.974328      1
12411  ZOLINZA  TOPOTECAN    T47D  18.985100      1
12412  ZOLINZA  TOPOTECAN  UACC62  10.223066      1
12413  ZOLINZA  TOPOTECAN    VCAP  23.438547      1
12414  ZOLINZA  TOPOTECAN   ZR751  12.223791      1

[12415 rows x 5 columns]

# External dataset : AstraZeneca

> Add blockquote

In [ ]:
ext_DT.head()

,gene_id,ENSG00000116237,ENSG00000162413,ENSG00000171603,ENSG00000160049,ENSG00000065526,ENSG00000117118,ENSG00000053371,ENSG00000076864,ENSG00000070831,...,ENSG00000156299,ENSG00000142166,ENSG00000159228,ENSG00000159231,ENSG00000183527,ENSG00000182093,ENSG00000182240,ENSG00000157617,ENSG00000160208,ENSG00000141959
1,X22RV1,57.81,6.73,26.89,10.13,28.07,146.83,31.51,4.44,2.32,...,0.03,19.72,29.36,4.42,7.2,33.97,0,1.39,20.86,80.13
2,X2313287,39.68,5.81,22.47,6.72,15.59,135.07,36.62,0.72,1.99,...,0.05,15.38,101.64,1.42,7.68,27.77,0.92,0.47,17.47,68.26
3,X253JBV,14.88,6.55,9.14,24.81,8.84,92.43,29.56,0,2.05,...,1.7,6.42,224.96,11.24,2.46,10.58,1.17,1.75,18.74,30.9
4,X253J,13.19,3.68,6.89,7.6,5.45,69.25,25.88,0,0.7,...,0.56,5.6,202.03,6.53,0.92,15.5,1.11,1.89,8.11,27.76
5,X42MGBA,79.58,34.03,30.23,20.08,15.16,100.59,35.83,0,5.44,...,5.21,10.5,214.9,50.74,8.42,13.3,3.06,8.61,23.28,166.13

In [ ]:
import pandas as pd
ExternalData = pd.read_csv('/content/drive/MyDrive/MACSynDCR/Data/Test_and_validation/independent/independent_input.csv')
ExternalData = pd.DataFrame(data=ExternalData)
#smiles_list=smiles.iloc[:,2]
ext_smailes = ExternalData['drug1'].unique()
ext_smiles_df = pd.DataFrame(data=ext_smailes)
ext_smiles_df = ext_smiles_df.rename(columns={0: 'SMILES'})
ext_smiles_df
ext_cell_line = ExternalData['cell'].unique()
print(ext_cell_line.shape)
ext_cell_line

(24,)

array(['J82', 'SW780', 'TCCSUP', 'HCC1187', 'HCC1806', 'HCC70', 'HCC1428',
       'HCC1143', 'HCC1395', 'HCC1937', 'HCC38', 'SW948', 'HCC1569',
       'HCC1954', 'MCF7', 'SW900', 'A549', 'HCC1419', 'RT4', 'SW48',
       'C32', '22RV1', 'HCC1500', 'KATOIII'], dtype=object)

implement VAE to reduce expression matrix "ext_DT" [1020,954] to [1020,512] preserving theirs index sequence.
I have drug combination data set first find common cell line from the   expression matrix. and create new expression matrix for found common cell line id in expression data

In [ ]:
_22RV1_data=ExternalData['cell'].value="22RV1"
_22RV1_data=ExternalData[ExternalData['cell']=="22RV1"]
_22RV1_data

,drug1,drug2,cell,label
283,c1ccc(cc1)c2cccc(c2N3CCC[C@H](C3)N)/C=C\4/C(=O...,c1cc(ccc1[C@H](CCO)NC(=O)C2(CCN(CC2)c3c4cc[nH]...,22RV1,1
614,c1ccc(cc1)c2cccc(c2N3CCC[C@H](C3)N)/C=C\4/C(=O...,CC(c1cc(cc2c1oc(cc2=O)N3CCOCC3)C(=O)N(C)C)Nc4c...,22RV1,1
628,Cc1cc(n[nH]1)Nc2c(cnc(n2)N[C@@H](C)c3ncc(cn3)F)Cl,c1cc(ccc1[C@H](CCO)NC(=O)C2(CCN(CC2)c3c4cc[nH]...,22RV1,1

In [ ]:
import pandas as pd
cell_array = ext_cell_line
ext_gene_expr = ext_DT[ext_DT['gene_id'].isin(cell_array)]
ext_gene_expr

,gene_id,ENSG00000116237,ENSG00000162413,ENSG00000171603,ENSG00000160049,ENSG00000065526,ENSG00000117118,ENSG00000053371,ENSG00000076864,ENSG00000070831,...,ENSG00000156299,ENSG00000142166,ENSG00000159228,ENSG00000159231,ENSG00000183527,ENSG00000182093,ENSG00000182240,ENSG00000157617,ENSG00000160208,ENSG00000141959
28,A549,28.65,4.2,21.2,10.78,7.25,92.97,17.06,0,2.88,...,0.1,8.71,129.35,4.6,6.91,17.92,0.41,1.71,24.41,12.68
67,C32,54.79,53.46,37.46,11.46,12.09,119.33,30.71,0.58,1.19,...,11.91,12.24,177.33,30.82,5.39,12.77,1.08,0.54,25.47,160.6
202,HCC1143,37.11,14.12,51.01,9.44,29.22,89,18.6,2.28,1.5,...,7.9,13.91,53.68,10.64,1.98,6.96,0.77,7.13,23.4,128.7
204,HCC1187,38.51,30.22,16.61,8.38,17.67,55.27,13.43,0.33,0.96,...,7.95,6.18,69.91,23.58,2.43,6.08,0.67,4.27,22.68,116.02
207,HCC1395,24.32,16.53,36.3,18.88,23.52,139.32,29.75,2.89,3.11,...,8.65,7.57,97.37,34.78,2.31,6.55,3.16,0.62,12.39,48.76
208,HCC1419,41.02,8.61,17.29,17.3,20.04,80.66,67.06,0,2.21,...,7.83,11.09,101.41,8.05,3.06,13.17,0.02,4.07,15.18,84.56
209,HCC1428,30.17,4.51,13.76,5.62,15.2,208.17,93.93,0.53,3.1,...,6.56,8.83,0.35,11.51,2.42,26.39,2.08,10.15,16.88,132.57
211,HCC1500,21.38,4.52,8.14,7.88,7.4,75.71,89.36,0.66,2.07,...,8.14,15.93,75.95,13.34,3.08,36.3,0,0.53,10.41,90.71
212,HCC1569,13.83,19.13,30.52,28.66,27.42,121.39,14.4,0,1.68,...,10.31,5.28,101.65,2.55,4.53,14.15,3.94,2.35,22.29,88.79
216,HCC1806,17.89,12.13,24.61,4.34,11.36,58.51,20.52,0.67,0.94,...,1.44,5.35,70.29,9.39,1.09,5.94,0.1,2.19,7.32,50.25
218,HCC1937,28.1,13.91,29.96,16.12,18.56,108.04,40.07,0.53,1.55,...,4.74,5.81,74.5,12.71,3.43,6.05,3.01,1.35,12.82,53.58
219,HCC1954,36.16,10.89,37.71,20.63,21.71,104.69,30.32,0,2.7,...,8.61,16.65,0.77,17.53,9.94,26.54,2,1.75,23.29,61.62
232,HCC38,26.91,17.05,35.74,10.64,28.65,64.04,22.39,3.2,0.99,...,7.39,11.18,81.81,21.16,2.24,12.45,1.54,1.1,19.63,57.76
238,HCC70,42.62,14.46,41.21,14.18,38.58,147.64,56.97,1,1.7,...,14.62,10.37,76.19,38.44,3.64,7.8,2.74,4.84,11.87,86.35
357,J82,35.26,15.59,35.17,21.63,13.06,116.18,28.02,0.51,4.04,...,2.02,3.91,110.36,23.43,5.19,6.81,0.12,1.42,15.39,48.48
394,KATOIII,31.44,19.52,20.81,17.91,12.83,112.35,32.86,0,2.17,...,3.32,5.9,0.13,2.12,5.2,9.52,4.32,1.43,21.58,36.3
496,MCF7,24.32,4.44,14.09,9.4,9.81,89.6,38.03,0.89,2.38,...,4.17,7.59,48.21,7.2,9.17,18.07,0,0.66,19.66,180.48
779,RT4,31.42,4.26,8.32,8.85,14.8,53.72,27.1,0.41,1.7,...,17.34,7.34,59.7,9.33,6.84,4.71,0.36,6.11,16.09,110.55
929,SW48,32.34,27.01,20.66,28.97,17.41,100.82,22.53,6.33,0.29,...,0.45,5.8,90.9,14.76,5.35,6.72,0,0.06,52.59,62.56
932,SW780,45.72,11.19,29.71,12.08,26.99,99.48,51.65,0,2.63,...,7.78,9.57,94.01,14.67,1.09,14.06,0,7.51,17.97,87.02
934,SW900,31.16,12.12,21.07,10.48,11.28,72.52,21.85,0.43,2.37,...,5.93,4.6,32.43,7.56,1.68,6.36,0.96,1.02,14.37,37.22
935,SW948,23.62,4.15,9.83,5.56,10.63,79.17,23.58,0.52,1.17,...,0.03,6.32,58.29,3.37,8.15,10.9,1.52,2.62,10.97,99.3
946,TCCSUP,41.18,12.49,30.6,8.17,23.14,67.1,28.49,0,2.61,...,2.47,9.28,75.49,4.92,2.86,13.28,0,2.46,19.69,38.54

VAE on genexpression:

In [ ]:
ext_cell_id=ext_gene_expr['gene_id'].values
print(ext_cell_id)
ext_cell_id.shape

['A549' 'C32' 'HCC1143' 'HCC1187' 'HCC1395' 'HCC1419' 'HCC1428' 'HCC1500'
 'HCC1569' 'HCC1806' 'HCC1937' 'HCC1954' 'HCC38' 'HCC70' 'J82' 'KATOIII'
 'MCF7' 'RT4' 'SW48' 'SW780' 'SW900' 'SW948' 'TCCSUP']

(23,)

In [ ]:
ext_exprdata=ext_gene_expr.iloc[:,1:]
X=ext_exprdata.to_numpy()
X[0]

array(['28.65', '4.2', '21.2', '10.78', '7.25', '92.97', '17.06', '0',
       '2.88', '0.05', '1.8', '13.36', '54.07', '42.15', '0.3', '4.85',
       '105.94', '2.35', '0.3', '3.8', '1.15', '13.72', '1.55', '34.29',
       '1.04', '167.77', '96.36', '7.96', '0.34', '15.72', '30.84', '0',
       '9.89', '1.15', '18.18', '3.29', '14.45', '1.31', '0.53', '20.7',
       '11.24', '0.08', '0.49', '65.73', '0.05', '13.28', '6.08', '25.93',
       '21.93', '0', '2.09', '1.45', '3.66', '0', '31.59', '6.43', '0.02',
       '2.37', '1.03', '21.52', '0.66', '17.25', '19.24', '561.68',
       '15.94', '8.23', '0.09', '1.76', '0', '1.2', '0.24', '0', '1',
       '9.04', '0.15', '54.19', '33.41', '52.01', '96.27', '1.68',
       '17.55', '5.46', '16.08', '17.48', '0.03', '14.78', '6.62',
       '329.87', '0', '0', '0', '2.79', '0', '17.11', '43.16', '83.45',
       '88.7', '13.95', '5.51', '48.55', '25.85', '0.07', '3.46', '11.78',
       '25.98', '1.61', '0', '7.06', '24.9', '9.24', '0.8', '0.09',
       '41.98', '57.93', '0.02', '0.59', '0', '34.57', '3.6', '0',
       '57.65', '12.6', '10.67', '8.69', '9.01', '0.4', '108.61', '30.74',
       '27.2', '51.71', '0.36', '208.27', '0.15', '0.02', '19.72',
       '47.78', '2.69', '19.35', '4.27', '0.09', '0', '51.75', '0.23',
       '0', '86.07', '0.08', '12.96', '11.23', '65.56', '62.55', '2.29',
       '0', '9.2', '3.16', '3.19', '10.32', '11.02', '5.29', '24.87',
       '3.99', '45.17', '1.86', '61.91', '14.67', '2.28', '6.99', '0.89',
       '0.48', '0', '0.01', '23.55', '27.14', '0.11', '18.69', '12.8',
       '16.33', '16.94', '5.44', '1.83', '0.04', '0', '14.07', '40.93',
       '7.46', '11.75', '4.97', '9.94', '17.38', '36.22', '0.66', '0',
       '3.21', '2.94', '1.67', '0', '1.43', '40.31', '0.94', '36.9',
       '0.58', '12.41', '0.72', '91.85', '99.5', '0.87', '146.59', '9.48',
       '1.23', '21.98', '16.6', '12.12', '0.22', '63.75', '14.22', '0',
       '2.46', '20.99', '3.05', '2.47', '6.19', '0.02', '0.16', '45.18',
       '1.56', '49.75', '4.13', '0.82', '38.37', '6.56', '5.53', '209.58',
       '31.31', '2.17', '6.36', '15.37', '4.57', '0.01', '100.37',
       '18.23', '0', '21', '45.58', '21.35', '91.99', '3.17', '0',
       '57.73', '1.71', '13.24', '0.39', '9.03', '43.3', '0', '15.56',
       '0.62', '41.79', '3.79', '4.23', '28.28', '0.63', '11.59', '0',
       '13.66', '1.55', '0.03', '0.42', '45.64', '2.46', '27.45', '73.45',
       '41.81', '22.4', '0.13', '3.39', '29.4', '0', '2.63', '61.86',
       '23.69', '20.87', '0', '14.18', '2.81', '16.87', '4.95', '117.23',
       '6.37', '324.56', '1.56', '32.67', '0.39', '26.39', '19.18',
       '0.62', '20.12', '11.27', '122.35', '4.83', '0.17', '11.39', '0',
       '7.31', '18.49', '1.57', '0', '0', '46.29', '0.14', '0', '10.11',
       '21.09', '6.85', '25.5', '32.27', '65.51', '124.45', '9.05', '0',
       '2.48', '3.78', '5.42', '1.85', '0.12', '0.07', '79.52', '0.94',
       '26.37', '1.05', '5.16', '14.24', '57.75', '13.27', '0.08',
       '12.31', '14.5', '0.08', '1.85', '0.2', '2.52', '42.27', '0.08',
       '32.33', '2.26', '45.47', '18.45', '6.41', '14.46', '2.4', '3.74',
       '0.91', '0.1', '121.32', '7.13', '0', '64.43', '0.05', '75.62',
       '1.76', '2.38', '33.02', '8.39', '2.37', '20.74', '56.89', '60.12',
       '0', '22.68', '1.19', '0.01', '0.49', '39.39', '7.62', '10.25',
       '32.63', '262.29', '50.3', '13.94', '7.08', '1.11', '10.17',
       '30.12', '5.04', '464.31', '15.82', '71.69', '2.08', '17.7',
       '59.13', '7.46', '109.24', '0.21', '10.25', '0.65', '0', '52.1',
       '0.12', '9.79', '39.46', '29.55', '5.19', '42.6', '20.97', '62.57',
       '0', '5.2', '45.4', '0.78', '3.76', '35.04', '117.5', '22.25',
       '0.19', '12.2', '33.46', '0.05', '0', '0', '81.34', '0.1',
       '142.45', '11.59', '0', '2.63', '96.43', '66.25', '0.82', '27.43',
       '20.53', '6.36', '49.99', '3.79', '21.58', '35.54', '0.09',
       '17.44', '3.25', '19.15', '42.95', '75.5', '3.78', '4.69', '10.16',
       '1.8', '69.61', '0', '25.61', '63.45', '4.22', '32.87', '3.34',
       '28.84', '82.4', '7.04', '3.66', '19.65', '7.35', '0.19', '4.67',
       '33.5', '0.28', '44.7', '23.35', '1.89', '80.64', '1010.8', '10.1',
       '0', '7.63', '5.41', '0', '0.66', '18.93', '261.17', '0', '8.84',
       '25.79', '19', '54.81', '26.24', '0.01', '33.59', '8.32', '5.63',
       '0', '0.21', '44.88', '16.36', '0.56', '3.72', '63.34', '2.25',
       '4.64', '5.71', '8.32', '6.64', '101.08', '2.05', '2.64', '43.2',
       '14.73', '27.35', '26.73', '56.41', '21.39', '15.64', '41.89',
       '8.59', '23.03', '70.94', '44.39', '1.81', '8.26', '45.27',
       '49.42', '5.94', '16.1', '106.97', '11.3', '6.07', '62.91', '4.33',
       '93', '78.88', '0.61', '63.79', '0.18', '14.41', '8.83', '62.45',
       '0', '17.18', '0.07', '0.76', '15.21', '12.12', '0.08', '24.52',
       '0.76', '8.83', '989.57', '0', '4.7', '9.34', '4.01', '1.05',
       '6.78', '4.09', '38.43', '1.59', '17.84', '14.87', '2.13', '0.38',
       '9.58', '34.3', '18.77', '0.08', '160.71', '78.47', '20.47',
       '10.42', '0.8', '1.52', '11.56', '0', '0', '20.21', '119.81',
       '62.16', '0.31', '530.92', '33.08', '17.49', '0.32', '11.78',
       '58.73', '1.89', '0', '7.57', '42.44', '0', '7.61', '67.75', '3.4',
       '206.22', '54.81', '938.69', '8.07', '0.05', '15.37', '33.62',
       '41.08', '47.62', '12.04', '15.12', '23.29', '8.97', '34.29',
       '0.55', '0.39', '10.41', '95.42', '21.99', '0.06', '0.33', '11.06',
       '1.8', '0.68', '33.26', '1.28', '61.22', '0.03', '2.25', '0.16',
       '3.81', '15.54', '0', '65.49', '3.86', '8.03', '68.86', '12.89',
       '0.23', '0.2', '0.08', '27.46', '0', '15.59', '2.14', '11.08',
       '56.55', '35.94', '11.87', '52.89', '0', '97.67', '0', '0.4',
       '21.76', '10.61', '95.98', '32.6', '1.3', '0', '31.93', '0.77',
       '12', '44.75', '7.68', '3.48', '0', '12.04', '31.18', '1.67',
       '11.34', '16.98', '1.11', '1.71', '0.7', '5.39', '0.89', '13.54',
       '12.11', '0', '31.42', '53.79', '0.74', '0.36', '6.25', '15.48',
       '33.26', '17.8', '1.56', '0', '38.05', '1.25', '0', '18.23', '0',
       '17.96', '27.42', '0', '0', '61.4', '15.05', '0.29', '25.24',
       '12.7', '11.86', '12.53', '2.24', '9.92', '79.84', '93.84',
       '58.62', '58.92', '19.98', '169.13', '54.61', '5.01', '0.11',
       '3.67', '10.64', '40.69', '10.45', '4.53', '1.01', '34.27', '2.85',
       '46.93', '62.38', '10.82', '2.05', '27.74', '5.17', '11.91',
       '94.88', '2.27', '0', '1.59', '1.38', '17.73', '60.26', '8.76',
       '43.53', '24.53', '3.08', '10.35', '8.49', '82.52', '2.21', '28.3',
       '13.68', '1.69', '6.14', '30.87', '15.83', '18.04', '3.59',
       '57.59', '8.56', '31.37', '0', '18.01', '9.17', '0.06', '22.54',
       '2.53', '1.11', '4.15', '0.09', '124.11', '28.06', '11.77', '4.43',
       '20.69', '14.02', '34.65', '2.05', '2.2', '20.85', '22.06',
       '60.51', '17.62', '0', '17.44', '38.44', '16.51', '8.88', '3.56',
       '27.57', '3.92', '23.52', '0', '23.76', '56.32', '0', '0.26',
       '45.07', '33.52', '1.48', '69.6', '4.02', '0.87', '26.97', '8.94',
       '180.32', '74.13', '13.04', '54.23', '40.32', '17.87', '69.43',
       '0.41', '32.17', '63.68', '8.54', '37.66', '0.08', '0.36', '13.97',
       '4.64', '3.66', '38.65', '157.91', '8.19', '0.72', '0.84', '14',
       '0.35', '6.17', '9.27', '52.43', '0.08', '0.15', '5.58', '9.07',
       '19.19', '10.8', '0.81', '18.9', '172.79', '21.73', '7.59', '15.7',
       '9.98', '0', '87.82', '0', '13.64', '0.38', '42.7', '2.67', '35.3',
       '0.71', '2', '0.07', '0.03', '13.52', '32.55', '18.93', '31.91',
       '5.58', '380.33', '1.27', '0.2', '26.48', '22.88', '33.46',
       '19.98', '46.4', '0.06', '28.45', '1.99', '0.21', '0.68', '19.22',
       '18.36', '15.21', '0.03', '7.81', '19.23', '0.34', '0.04', '0',
       '0.31', '16.39', '18.47', '30', '13.22', '0.03', '0.19', '0.24',
       '3.28', '0', '2.85', '5.09', '12.18', '18.15', '48.72', '2.33',
       '34.25', '15.2', '1.16', '0', '5.11', '0.06', '0.06', '2.48',
       '9.85', '1.58', '92.36', '9.04', '13.59', '1.06', '12.39', '1.09',
       '5.76', '0', '5.72', '0', '41.26', '108.84', '8.38', '10.28',
       '55.05', '11.26', '42.78', '4.74', '2.26', '5.3', '0.07', '137.93',
       '10.8', '23.73', '0.08', '68.48', '31.86', '4.18', '7.2', '0.5',
       '18.62', '26.25', '93.47', '9.42', '0.95', '2.27', '1870', '0.04',
       '17.82', '16.38', '218.47', '5.04', '20.49', '47.18', '10.96',
       '182.78', '0.12', '5.49', '10.6', '9.27', '11.67', '10.5',
       '112.12', '0.1', '8.71', '129.35', '4.6', '6.91', '17.92', '0.41',
       '1.71', '24.41', '12.68'], dtype=object)

In [ ]:
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset
from sklearn.preprocessing import StandardScaler


# Example: X is NumPy array of shape (num_samples, 954)
ext_exprdata_numeric = ext_exprdata.apply(pd.to_numeric, errors='coerce')

# 2. Fill NaNs with 0 (or another strategy)
ext_exprdata_numeric = ext_exprdata_numeric.fillna(0)

# 3. Convert to NumPy array of float32
X_array = ext_exprdata_numeric.to_numpy(dtype=np.float32)

# 4. Convert to PyTorch tensor
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X_array)  # mean=0, std=1

X_tensor = torch.tensor(X_scaled, dtype=torch.float32)

#X_tensor = torch.tensor(ext_exprdata, dtype=torch.float32)

dataset = TensorDataset(X_tensor)
dataloader = DataLoader(dataset, batch_size=32, shuffle=True)

input_dim = 954
latent_dim = 256  # target dimension
hidden_dim = 768  # intermediate layer size

class VAE(nn.Module):
    def __init__(self, input_dim, hidden_dim, latent_dim):
        super(VAE, self).__init__()
        # Encoder
        self.fc1 = nn.Linear(input_dim, hidden_dim)
        self.fc_mu = nn.Linear(hidden_dim, latent_dim)
        self.fc_logvar = nn.Linear(hidden_dim, latent_dim)
        # Decoder
        self.fc2 = nn.Linear(latent_dim, hidden_dim)
        self.fc3 = nn.Linear(hidden_dim, input_dim)
        self.relu = nn.ReLU()

    def encode(self, x):
        h = self.relu(self.fc1(x))
        mu = self.fc_mu(h)
        logvar = self.fc_logvar(h)
        return mu, logvar

    def reparameterize(self, mu, logvar):
        std = torch.exp(0.5 * logvar)
        eps = torch.randn_like(std)
        return mu + eps * std

    def decode(self, z):
        h = self.relu(self.fc2(z))
        return self.fc3(h)

    def forward(self, x):
        mu, logvar = self.encode(x)
        z = self.reparameterize(mu, logvar)
        x_recon = self.decode(z)
        return x_recon, mu, logvar
def vae_loss(recon_x, x, mu, logvar):
    recon_loss = nn.MSELoss()(recon_x, x)  # reconstruction
    kld = -0.5 * torch.sum(1 + logvar - mu.pow(2) - logvar.exp())
    return recon_loss + kld / x.size(0)

In [ ]:
vae = VAE(input_dim, hidden_dim, latent_dim)
optimizer = optim.Adam(vae.parameters(), lr=1e-3)
num_epochs = 500

vae.train()
for epoch in range(num_epochs):
    total_loss = 0
    for batch in dataloader:
        x_batch = batch[0]
        optimizer.zero_grad()
        recon_x, mu, logvar = vae(x_batch)
        loss = vae_loss(recon_x, x_batch, mu, logvar)
        loss.backward()
        optimizer.step()
        total_loss += loss.item()
    print(f"Epoch {epoch+1}, Loss: {total_loss/len(dataloader):.4f}")

Epoch 1, Loss: 12.0775
Epoch 2, Loss: 3.8668
Epoch 3, Loss: 3.2498
Epoch 4, Loss: 2.9949
Epoch 5, Loss: 2.5710
Epoch 6, Loss: 2.1914
Epoch 7, Loss: 1.9136
Epoch 8, Loss: 1.7467
Epoch 9, Loss: 1.6326
Epoch 10, Loss: 1.5753
Epoch 11, Loss: 1.5130
Epoch 12, Loss: 1.4667
Epoch 13, Loss: 1.4274
Epoch 14, Loss: 1.3796
Epoch 15, Loss: 1.3283
Epoch 16, Loss: 1.3111
Epoch 17, Loss: 1.2898
Epoch 18, Loss: 1.2429
Epoch 19, Loss: 1.2221
Epoch 20, Loss: 1.1955
Epoch 21, Loss: 1.1837
Epoch 22, Loss: 1.1766
Epoch 23, Loss: 1.1441
Epoch 24, Loss: 1.1589
Epoch 25, Loss: 1.1337
Epoch 26, Loss: 1.1146
Epoch 27, Loss: 1.1053
Epoch 28, Loss: 1.1018
Epoch 29, Loss: 1.0940
Epoch 30, Loss: 1.1183
Epoch 31, Loss: 1.0753
Epoch 32, Loss: 1.0762
Epoch 33, Loss: 1.0875
Epoch 34, Loss: 1.0874
Epoch 35, Loss: 1.0737
Epoch 36, Loss: 1.0456
Epoch 37, Loss: 1.0868
Epoch 38, Loss: 1.0585
Epoch 39, Loss: 1.0700
Epoch 40, Loss: 1.0734
Epoch 41, Loss: 1.0537
Epoch 42, Loss: 1.0478
Epoch 43, Loss: 1.0561
Epoch 44, Loss: 1.0618
Epoch 45, Loss: 1.0401
Epoch 46, Loss: 1.0363
Epoch 47, Loss: 1.0221
Epoch 48, Loss: 1.0286
Epoch 49, Loss: 1.0445
Epoch 50, Loss: 1.0365
Epoch 51, Loss: 1.0336
Epoch 52, Loss: 1.0363
Epoch 53, Loss: 1.0398
Epoch 54, Loss: 1.0361
Epoch 55, Loss: 1.0549
Epoch 56, Loss: 1.0587
Epoch 57, Loss: 1.0696
Epoch 58, Loss: 1.0289
Epoch 59, Loss: 1.0515
Epoch 60, Loss: 1.0292
Epoch 61, Loss: 1.0270
Epoch 62, Loss: 1.0442
Epoch 63, Loss: 1.0131
Epoch 64, Loss: 1.0354
Epoch 65, Loss: 1.0441
Epoch 66, Loss: 1.0455
Epoch 67, Loss: 1.0632
Epoch 68, Loss: 1.0397
Epoch 69, Loss: 1.0356
Epoch 70, Loss: 1.0412
Epoch 71, Loss: 1.0467
Epoch 72, Loss: 1.0555
Epoch 73, Loss: 1.0275
Epoch 74, Loss: 1.0538
Epoch 75, Loss: 1.0479
Epoch 76, Loss: 1.0420
Epoch 77, Loss: 1.0339
Epoch 78, Loss: 1.0397
Epoch 79, Loss: 1.0149
Epoch 80, Loss: 1.0271
Epoch 81, Loss: 1.0509
Epoch 82, Loss: 1.0365
Epoch 83, Loss: 1.0232
Epoch 84, Loss: 1.0347
Epoch 85, Loss: 1.0366
Epoch 86, Loss: 1.0337
Epoch 87, Loss: 1.0245
Epoch 88, Loss: 1.0244
Epoch 89, Loss: 1.0399
Epoch 90, Loss: 1.0393
Epoch 91, Loss: 1.0609
Epoch 92, Loss: 1.0415
Epoch 93, Loss: 1.0455
Epoch 94, Loss: 1.0471
Epoch 95, Loss: 1.0404
Epoch 96, Loss: 1.0378
Epoch 97, Loss: 1.0615
Epoch 98, Loss: 1.0550
Epoch 99, Loss: 1.0268
Epoch 100, Loss: 1.0371
Epoch 101, Loss: 1.0424
Epoch 102, Loss: 1.0257
Epoch 103, Loss: 1.0091
Epoch 104, Loss: 1.0155
Epoch 105, Loss: 1.0317
Epoch 106, Loss: 1.0399
Epoch 107, Loss: 1.0278
Epoch 108, Loss: 1.0230
Epoch 109, Loss: 1.0178
Epoch 110, Loss: 1.0334
Epoch 111, Loss: 1.0397
Epoch 112, Loss: 1.0350
Epoch 113, Loss: 1.0359
Epoch 114, Loss: 1.0290
Epoch 115, Loss: 1.0519
Epoch 116, Loss: 1.0195
Epoch 117, Loss: 1.0415
Epoch 118, Loss: 1.0448
Epoch 119, Loss: 1.0247
Epoch 120, Loss: 1.0379
Epoch 121, Loss: 1.0571
Epoch 122, Loss: 1.0512
Epoch 123, Loss: 1.0325
Epoch 124, Loss: 1.0218
Epoch 125, Loss: 1.0325
Epoch 126, Loss: 1.0336
Epoch 127, Loss: 1.0278
Epoch 128, Loss: 1.0361
Epoch 129, Loss: 1.0411
Epoch 130, Loss: 1.0552
Epoch 131, Loss: 1.0397
Epoch 132, Loss: 1.0402
Epoch 133, Loss: 1.0396
Epoch 134, Loss: 1.0377
Epoch 135, Loss: 1.0792
Epoch 136, Loss: 1.0638
Epoch 137, Loss: 1.0364
Epoch 138, Loss: 1.0199
Epoch 139, Loss: 1.0371
Epoch 140, Loss: 1.0669
Epoch 141, Loss: 1.0459
Epoch 142, Loss: 1.0379
Epoch 143, Loss: 1.0423
Epoch 144, Loss: 1.0350
Epoch 145, Loss: 1.0374
Epoch 146, Loss: 1.0220
Epoch 147, Loss: 1.0360
Epoch 148, Loss: 1.0529
Epoch 149, Loss: 1.0113
Epoch 150, Loss: 1.0498
Epoch 151, Loss: 1.0720
Epoch 152, Loss: 1.0558
Epoch 153, Loss: 1.0365
Epoch 154, Loss: 1.0433
Epoch 155, Loss: 1.0283
Epoch 156, Loss: 1.0133
Epoch 157, Loss: 1.0442
Epoch 158, Loss: 1.0204
Epoch 159, Loss: 1.0565
Epoch 160, Loss: 1.0261
Epoch 161, Loss: 1.0233
Epoch 162, Loss: 1.0082
Epoch 163, Loss: 1.0591
Epoch 164, Loss: 1.0614
Epoch 165, Loss: 1.0296
Epoch 166, Loss: 1.0400
Epoch 167, Loss: 1.0252
Epoch 168, Loss: 1.0494
Epoch 169, Loss: 1.0389
Epoch 170, Loss: 1.0454
Epoch 171, Loss: 1.0098
Epoch 172, Loss: 1.0279
Epoch 173, Loss: 1.0239
Epoch 174, Loss: 1.0219
Epoch 175, Loss: 1.0416
Epoch 176, Loss: 1.0411
Epoch 177, Loss: 1.0390
Epoch 178, Loss: 1.0441
Epoch 179, Loss: 1.0585
Epoch 180, Loss: 1.0263
Epoch 181, Loss: 1.0721
Epoch 182, Loss: 1.0513
Epoch 183, Loss: 1.0381
Epoch 184, Loss: 1.0232
Epoch 185, Loss: 1.0382
Epoch 186, Loss: 1.0455
Epoch 187, Loss: 1.0603
Epoch 188, Loss: 1.0338
Epoch 189, Loss: 1.0418
Epoch 190, Loss: 1.0369
Epoch 191, Loss: 1.0410
Epoch 192, Loss: 1.0443
Epoch 193, Loss: 1.0225
Epoch 194, Loss: 1.0280
Epoch 195, Loss: 1.0206
Epoch 196, Loss: 1.0757
Epoch 197, Loss: 1.0349
Epoch 198, Loss: 1.0458
Epoch 199, Loss: 1.0261
Epoch 200, Loss: 1.0595
Epoch 201, Loss: 1.0317
Epoch 202, Loss: 1.0304
Epoch 203, Loss: 1.0163
Epoch 204, Loss: 1.0402
Epoch 205, Loss: 1.0258
Epoch 206, Loss: 1.0417
Epoch 207, Loss: 1.0567
Epoch 208, Loss: 1.0598
Epoch 209, Loss: 1.0532
Epoch 210, Loss: 1.0328
Epoch 211, Loss: 1.0256
Epoch 212, Loss: 1.0518
Epoch 213, Loss: 1.0395
Epoch 214, Loss: 1.0507
Epoch 215, Loss: 1.0348
Epoch 216, Loss: 1.0524
Epoch 217, Loss: 1.0399
Epoch 218, Loss: 1.0537
Epoch 219, Loss: 1.0468
Epoch 220, Loss: 1.0272
Epoch 221, Loss: 1.0323
Epoch 222, Loss: 1.0367
Epoch 223, Loss: 1.0502
Epoch 224, Loss: 1.0109
Epoch 225, Loss: 1.0347
Epoch 226, Loss: 1.0424
Epoch 227, Loss: 1.0475
Epoch 228, Loss: 1.0040
Epoch 229, Loss: 1.0208
Epoch 230, Loss: 1.0410
Epoch 231, Loss: 1.0355
Epoch 232, Loss: 1.0116
Epoch 233, Loss: 1.0268
Epoch 234, Loss: 1.0665
Epoch 235, Loss: 1.0412
Epoch 236, Loss: 1.0419
Epoch 237, Loss: 1.0322
Epoch 238, Loss: 1.0437
Epoch 239, Loss: 1.0188
Epoch 240, Loss: 1.0525
Epoch 241, Loss: 1.0235
Epoch 242, Loss: 1.0320
Epoch 243, Loss: 1.0428
Epoch 244, Loss: 1.0511
Epoch 245, Loss: 1.0435
Epoch 246, Loss: 1.0315
Epoch 247, Loss: 1.0281
Epoch 248, Loss: 1.0541
Epoch 249, Loss: 1.0499
Epoch 250, Loss: 1.0417
Epoch 251, Loss: 1.0328
Epoch 252, Loss: 1.0239
Epoch 253, Loss: 1.0483
Epoch 254, Loss: 1.0704
Epoch 255, Loss: 1.0454
Epoch 256, Loss: 1.0423
Epoch 257, Loss: 1.0347
Epoch 258, Loss: 1.0284
Epoch 259, Loss: 1.0612
Epoch 260, Loss: 1.0550
Epoch 261, Loss: 1.0049
Epoch 262, Loss: 1.0321
Epoch 263, Loss: 1.0123
Epoch 264, Loss: 1.0230
Epoch 265, Loss: 0.9977
Epoch 266, Loss: 1.0547
Epoch 267, Loss: 1.0396
Epoch 268, Loss: 1.0365
Epoch 269, Loss: 1.0424
Epoch 270, Loss: 1.0348
Epoch 271, Loss: 1.0420
Epoch 272, Loss: 1.0243
Epoch 273, Loss: 1.0281
Epoch 274, Loss: 1.0696
Epoch 275, Loss: 1.0409
Epoch 276, Loss: 1.0564
Epoch 277, Loss: 1.0261
Epoch 278, Loss: 1.0238
Epoch 279, Loss: 1.0214
Epoch 280, Loss: 1.0510
Epoch 281, Loss: 1.0590
Epoch 282, Loss: 1.0309
Epoch 283, Loss: 1.0286
Epoch 284, Loss: 1.0306
Epoch 285, Loss: 1.0330
Epoch 286, Loss: 1.0269
Epoch 287, Loss: 1.0434
Epoch 288, Loss: 1.0189
Epoch 289, Loss: 1.0350
Epoch 290, Loss: 1.0349
Epoch 291, Loss: 1.0191
Epoch 292, Loss: 1.0384
Epoch 293, Loss: 1.0460
Epoch 294, Loss: 1.0403
Epoch 295, Loss: 1.0073
Epoch 296, Loss: 1.0442
Epoch 297, Loss: 1.0249
Epoch 298, Loss: 1.0166
Epoch 299, Loss: 1.0546
Epoch 300, Loss: 1.0691
Epoch 301, Loss: 1.0515
Epoch 302, Loss: 1.0269
Epoch 303, Loss: 1.0234
Epoch 304, Loss: 1.0327
Epoch 305, Loss: 1.0246
Epoch 306, Loss: 1.0599
Epoch 307, Loss: 1.0591
Epoch 308, Loss: 1.0224
Epoch 309, Loss: 1.0285
Epoch 310, Loss: 1.0581
Epoch 311, Loss: 1.0058
Epoch 312, Loss: 1.0224
Epoch 313, Loss: 1.0263
Epoch 314, Loss: 1.0409
Epoch 315, Loss: 1.0536
Epoch 316, Loss: 1.0204
Epoch 317, Loss: 1.0498
Epoch 318, Loss: 1.0460
Epoch 319, Loss: 1.0400
Epoch 320, Loss: 1.0207
Epoch 321, Loss: 1.0193
Epoch 322, Loss: 1.0512
Epoch 323, Loss: 1.0372
Epoch 324, Loss: 1.0274
Epoch 325, Loss: 1.0736
Epoch 326, Loss: 1.0456
Epoch 327, Loss: 1.0646
Epoch 328, Loss: 1.0374
Epoch 329, Loss: 1.0524
Epoch 330, Loss: 1.0641
Epoch 331, Loss: 1.0555
Epoch 332, Loss: 1.0535
Epoch 333, Loss: 1.0302
Epoch 334, Loss: 1.0402
Epoch 335, Loss: 1.0183
Epoch 336, Loss: 1.0429
Epoch 337, Loss: 1.0097
Epoch 338, Loss: 1.0359
Epoch 339, Loss: 1.0325
Epoch 340, Loss: 1.0539
Epoch 341, Loss: 1.0293
Epoch 342, Loss: 1.0177
Epoch 343, Loss: 1.0407
Epoch 344, Loss: 1.0508
Epoch 345, Loss: 1.0156
Epoch 346, Loss: 1.0359
Epoch 347, Loss: 1.0229
Epoch 348, Loss: 1.0193
Epoch 349, Loss: 1.0552
Epoch 350, Loss: 1.0258
Epoch 351, Loss: 1.0279
Epoch 352, Loss: 1.0491
Epoch 353, Loss: 1.0417
Epoch 354, Loss: 1.0369
Epoch 355, Loss: 1.0407
Epoch 356, Loss: 1.0400
Epoch 357, Loss: 1.0352
Epoch 358, Loss: 1.0531
Epoch 359, Loss: 1.0516
Epoch 360, Loss: 1.0236
Epoch 361, Loss: 1.0039
Epoch 362, Loss: 1.0384
Epoch 363, Loss: 1.0327
Epoch 364, Loss: 1.0516
Epoch 365, Loss: 1.0350
Epoch 366, Loss: 1.0703
Epoch 367, Loss: 1.0612
Epoch 368, Loss: 1.0337
Epoch 369, Loss: 1.0242
Epoch 370, Loss: 1.0209
Epoch 371, Loss: 0.9848
Epoch 372, Loss: 1.0522
Epoch 373, Loss: 1.0362
Epoch 374, Loss: 1.0321
Epoch 375, Loss: 1.0165
Epoch 376, Loss: 1.0240
Epoch 377, Loss: 1.0570
Epoch 378, Loss: 1.0232
Epoch 379, Loss: 1.0505
Epoch 380, Loss: 1.0576
Epoch 381, Loss: 1.0578
Epoch 382, Loss: 1.0171
Epoch 383, Loss: 1.0207
Epoch 384, Loss: 1.0387
Epoch 385, Loss: 1.0190
Epoch 386, Loss: 1.0476
Epoch 387, Loss: 1.0289
Epoch 388, Loss: 1.0402
Epoch 389, Loss: 1.0142
Epoch 390, Loss: 1.0320
Epoch 391, Loss: 1.0411
Epoch 392, Loss: 1.0413
Epoch 393, Loss: 1.0395
Epoch 394, Loss: 1.0376
Epoch 395, Loss: 1.0658
Epoch 396, Loss: 1.0220
Epoch 397, Loss: 1.0354
Epoch 398, Loss: 1.0354
Epoch 399, Loss: 1.0163
Epoch 400, Loss: 1.0143
Epoch 401, Loss: 1.0465
Epoch 402, Loss: 1.0508
Epoch 403, Loss: 1.0537
Epoch 404, Loss: 1.0238
Epoch 405, Loss: 1.0506
Epoch 406, Loss: 1.0296
Epoch 407, Loss: 1.0477
Epoch 408, Loss: 1.0389
Epoch 409, Loss: 1.0528
Epoch 410, Loss: 1.0389
Epoch 411, Loss: 1.0572
Epoch 412, Loss: 1.0236
Epoch 413, Loss: 1.0134
Epoch 414, Loss: 1.0437
Epoch 415, Loss: 1.0463
Epoch 416, Loss: 1.0682
Epoch 417, Loss: 1.0440
Epoch 418, Loss: 1.0422
Epoch 419, Loss: 1.0506
Epoch 420, Loss: 1.0527
Epoch 421, Loss: 1.0264
Epoch 422, Loss: 1.0221
Epoch 423, Loss: 1.0367
Epoch 424, Loss: 1.0281
Epoch 425, Loss: 1.0327
Epoch 426, Loss: 1.0083
Epoch 427, Loss: 1.0048
Epoch 428, Loss: 1.0289
Epoch 429, Loss: 1.0332
Epoch 430, Loss: 1.0473
Epoch 431, Loss: 1.0769
Epoch 432, Loss: 1.0298
Epoch 433, Loss: 1.0443
Epoch 434, Loss: 1.0284
Epoch 435, Loss: 1.0202
Epoch 436, Loss: 1.0113
Epoch 437, Loss: 1.0619
Epoch 438, Loss: 1.0398
Epoch 439, Loss: 1.0376
Epoch 440, Loss: 1.0227
Epoch 441, Loss: 1.0471
Epoch 442, Loss: 1.0346
Epoch 443, Loss: 1.0232
Epoch 444, Loss: 1.0628
Epoch 445, Loss: 1.0055
Epoch 446, Loss: 1.0485
Epoch 447, Loss: 1.0450
Epoch 448, Loss: 1.0412
Epoch 449, Loss: 1.0343
Epoch 450, Loss: 1.0375
Epoch 451, Loss: 1.0649
Epoch 452, Loss: 1.0575
Epoch 453, Loss: 1.0531
Epoch 454, Loss: 1.0560
Epoch 455, Loss: 1.0266
Epoch 456, Loss: 1.0533
Epoch 457, Loss: 1.0169
Epoch 458, Loss: 1.0626
Epoch 459, Loss: 1.0546
Epoch 460, Loss: 1.0228
Epoch 461, Loss: 1.0675
Epoch 462, Loss: 1.0328
Epoch 463, Loss: 1.0235
Epoch 464, Loss: 1.0520
Epoch 465, Loss: 1.0491
Epoch 466, Loss: 1.0685
Epoch 467, Loss: 1.0251
Epoch 468, Loss: 1.0291
Epoch 469, Loss: 1.0148
Epoch 470, Loss: 1.0222
Epoch 471, Loss: 1.0525
Epoch 472, Loss: 1.0476
Epoch 473, Loss: 1.0463
Epoch 474, Loss: 1.0583
Epoch 475, Loss: 1.0657
Epoch 476, Loss: 1.0556
Epoch 477, Loss: 1.0210
Epoch 478, Loss: 1.0531
Epoch 479, Loss: 1.0283
Epoch 480, Loss: 1.0330
Epoch 481, Loss: 1.0213
Epoch 482, Loss: 0.9993
Epoch 483, Loss: 1.0297
Epoch 484, Loss: 1.0217
Epoch 485, Loss: 1.0222
Epoch 486, Loss: 1.0188
Epoch 487, Loss: 1.0417
Epoch 488, Loss: 1.0447
Epoch 489, Loss: 1.0481
Epoch 490, Loss: 1.0422
Epoch 491, Loss: 1.0213
Epoch 492, Loss: 1.0362
Epoch 493, Loss: 1.0129
Epoch 494, Loss: 1.0436
Epoch 495, Loss: 1.0244
Epoch 496, Loss: 1.0257
Epoch 497, Loss: 1.0281
Epoch 498, Loss: 1.0084
Epoch 499, Loss: 1.0461
Epoch 500, Loss: 1.0171

In [ ]:
vae.eval()
with torch.no_grad():
    mu, logvar = vae.encode(X_tensor)
    X_reduced = mu.numpy()  # shape: (num_samples, 512)
print(X_reduced.shape)
X_reduced

(23, 256)

array([[-6.6586304e-04,  5.7075173e-05, -4.7620479e-03, ...,
         1.2206081e-03, -1.8040590e-02, -3.8015814e-03],
       [ 5.6309518e-03,  3.8516298e-03,  1.0444746e-02, ...,
        -9.7494200e-04, -1.6781222e-04,  1.9997652e-03],
       [-6.7639910e-03,  1.0883287e-03, -3.5164319e-04, ...,
         6.7631342e-04,  2.3451075e-03,  4.4585094e-03],
       ...,
       [-1.5303344e-03, -3.7886980e-03,  5.3033680e-03, ...,
         1.4708526e-03, -1.1630885e-02,  1.6189739e-03],
       [ 1.0700960e-02,  4.0647089e-03,  7.4127838e-03, ...,
        -3.3380836e-03, -8.2277320e-03, -1.2783036e-02],
       [-8.0758827e-03, -1.3659932e-03, -8.1073707e-03, ...,
        -1.0678675e-03, -1.0959148e-02,  7.0033893e-03]], dtype=float32)

In [ ]:
import pandas as pd
df = pd.DataFrame(X_reduced)
#print(df.to_csv(index=False, header=False))
df.to_csv('/content/drive/MyDrive/MACSynDCR/Data/Drug/ext_Gen_Ex_data.csv')
np.save('/content/drive/MyDrive/MACSynDCR/Data/Cell/ext_GEx_features_512', X_reduced)
X_reduced.shape

(23, 256)

In [ ]:
# @title
synclass=[]
syn=OneilData.iloc[:,3]
for s in syn:
  if s>=20:
    synclass.append(1)
  elif s<=-10:
    synclass.append(0)
  else:
    synclass.append(3)

OneilData['SynClass'] = synclass

OneilDataset = OneilData[OneilData["SynClass"]<2]
sdata=OneilDataset["synergy"]
print(sdata)

OneilDataset.to_csv('/content/drive/MyDrive/MACSynDCR/Data/OneilDeepSynDataset_-10to20.csv')
OneilDataset['SynClass'].value_counts()

NameError: name 'OneilData' is not defined

In [ ]:
# @title
synergy=[]
synclass=[]
syn=OneilData.iloc[:,3]
for s in syn:
  if s>=20:
    synergy.append(s)
  elif s<=-10:
    synergy.append(s)
  else:
    synclass.append(3)

#OneilData['SynClass'] = synclass

#OneilDataset = OneilData[OneilData["SynClass"]<2]
print(len(synergy))
df=pd.DataFrame(synergy)
df.to_csv('/content/drive/MyDrive/MACSynDCR/Data/Synergy_-10to20.csv')
synergy

7874

[-10.06884761,
 -36.45922958,
 -14.52310863,
 23.98617954,
 23.3811342,
 -32.99061919,
 33.59292588,
 25.07262477,
 33.3532584,
 70.15816882,
 55.29129934,
 20.10041374,
 21.56238672,
 -73.13840165,
 21.2679035,
 106.0071924,
 -18.59912622,
 -35.27304184,
 -10.97044616,
 -16.13012533,
 -14.56978258,
 -15.95161347,
 52.48518972,
 -15.77870569,
 -16.69626568,
 -18.99813026,
 -24.06755091,
 -20.70616808,
 -10.47941439,
 -172.8887021,
 -11.64272985,
 -17.84185108,
 -15.03075018,
 -17.45137527,
 31.12564418,
 50.60366026,
 28.34808451,
 21.43309088,
 -22.97327812,
 21.38558819,
 23.23497071,
 -31.1947196,
 21.6687261,
 42.73505144,
 57.03314711,
 33.90828352,
 30.44463084,
 21.45572644,
 -14.34742589,
 -11.87695993,
 -96.61714003,
 -13.89910152,
 -19.57332293,
 -13.58239014,
 22.16797341,
 -45.89376066,
 24.45497683,
 28.14443856,
 -11.04004585,
 29.20125585,
 20.98757258,
 21.28942476,
 22.19123604,
 24.41379314,
 22.8306176,
 -12.98670671,
 -80.63896867,
 -10.01418099,
 30.67999441,
 -15.00928456,
 -11.24456132,
 -57.88453337,
 21.15875733,
 -16.37649722,
 -55.47026432,
 41.06914178,
 23.48420717,
 26.86477535,
 -35.31198822,
 22.84385673,
 21.99868299,
 20.75862339,
 21.70836662,
 -24.4814919,
 -14.5737162,
 -54.84820211,
 -10.52634233,
 -11.5759633,
 -12.72451513,
 -13.04134069,
 -20.6434715,
 -34.44593587,
 32.33623166,
 20.62786482,
 24.55178995,
 20.51728696,
 -34.43024988,
 21.73781029,
 23.65827923,
 41.30121414,
 23.25413422,
 27.33122745,
 28.19210471,
 28.71514833,
 24.17858199,
 25.23796782,
 28.39504805,
 29.67190189,
 23.522713,
 22.09733642,
 37.92676259,
 57.10355598,
 -10.66233849,
 43.35485062,
 -28.69135036,
 24.84605685,
 58.84964574,
 -81.44128366,
 -20.52658286,
 -11.15156386,
 24.61014916,
 22.0330269,
 24.68660319,
 -144.4016546,
 46.99657957,
 -16.67220342,
 -13.39034615,
 -13.81534377,
 -13.50351384,
 -18.31547421,
 -11.36179266,
 -19.19337264,
 -15.98333594,
 -35.66063407,
 -39.7171613,
 -15.66309184,
 -24.286518,
 -13.17812058,
 -32.03551474,
 -16.14608633,
 -17.96614029,
 -16.13611503,
 -22.41858189,
 -23.41105381,
 -15.12140115,
 -55.9657771,
 -44.6178968,
 -31.48916586,
 -11.96862443,
 -51.98862044,
 -31.94692955,
 -15.10567636,
 -17.22800516,
 22.99565591,
 -20.67751276,
 24.07097148,
 29.43971431,
 26.77702751,
 48.3199691,
 23.55289621,
 24.83456937,
 24.14577087,
 29.12456296,
 78.70408281,
 24.11737313,
 42.00615065,
 24.98075461,
 28.49051729,
 21.71305205,
 26.41696531,
 27.95688569,
 29.52276092,
 23.28959911,
 117.0012793,
 32.06766556,
 29.63789318,
 27.42592944,
 44.93017733,
 -24.15595065,
 22.66972082,
 22.97216302,
 26.08846407,
 31.71762887,
 20.48955403,
 33.83147768,
 30.34189343,
 -10.74656256,
 -15.0026455,
 -27.25381749,
 -14.3043912,
 -31.47062211,
 -17.08015794,
 24.76000602,
 21.27725009,
 30.33180491,
 41.59951047,
 75.5280528,
 -16.01122021,
 23.35240873,
 -17.17202362,
 -51.21988037,
 -40.5994196,
 -85.53233701,
 -30.36395736,
 -31.4103635,
 -32.47762672,
 -18.91591586,
 -16.82213133,
 -25.65655126,
 -27.21438006,
 -22.77447668,
 -17.38778235,
 -22.07509333,
 -20.36656057,
 -27.74913591,
 -24.69461216,
 -26.72258512,
 -13.38060668,
 -34.67794411,
 -19.8337096,
 -14.05042379,
 -10.62392281,
 -16.11918667,
 37.19755244,
 27.44316256,
 29.45915958,
 41.82261363,
 30.14977964,
 23.42591491,
 28.68890188,
 21.46794278,
 21.39044581,
 22.60303623,
 33.42900164,
 33.01382776,
 31.16670432,
 30.53249026,
 23.87063157,
 29.65052395,
 20.08675206,
 39.83231175,
 24.96544956,
 -12.24364896,
 36.19616521,
 24.38215762,
 -30.05242132,
 -10.96641065,
 -16.2045174,
 -15.16316218,
 -12.71817083,
 -13.74201482,
 -20.57774761,
 -16.28525243,
 -13.17469848,
 -35.55824357,
 -21.5827409,
 -12.44712596,
 -17.67508406,
 -13.77537319,
 -18.45347178,
 -15.70654273,
 -16.73042364,
 -11.56591243,
 -10.75733812,
 -10.32331212,
 60.31694066,
 -10.38201033,
 -11.19139976,
 51.63655767,
 20.74582765,
 30.50680672,
 27.24417838,
 30.76397327,
 21.91627509,
 61.89051853,
 27.5112821,
 24.1922954,
 38.21325157,
 28.82820786,
 20.61275835,
 31.73685611,
 26.5938059,
 25.46992744,
 23.61253202,
 93.72819505,
 23.04106128,
 78.4206107,
 -17.55948042,
 -18.34661485,
 -20.03555451,
 -34.72870023,
 -10.78914679,
 -18.64255603,
 -18.92954483,
 -11.56046415,
 36.59996851,
 -19.84631947,
 -16.26938113,
 -18.820814,
 -18.59569714,
 -10.42875904,
 -11.91326085,
 -16.93259274,
 -12.67666435,
 -17.90369234,
 -15.70918499,
 -18.74799388,
 -16.28306878,
 42.07240376,
 -24.43246657,
 -11.21496757,
 34.97062024,
 63.3161055,
 63.34866372,
 39.57408252,
 20.48847426,
 29.602612,
 26.52038427,
 28.47729987,
 35.72886618,
 24.71473218,
 25.42571635,
 39.31007727,
 56.50941313,
 29.30647219,
 -29.14558342,
 39.04268663,
 24.67543309,
 42.09049498,
 22.34062331,
 25.65497092,
 52.799135,
 41.91153524,
 64.27435309,
 37.53767894,
 29.47712099,
 36.84844558,
 20.51484393,
 -23.97165911,
 -12.36585978,
 -11.37380434,
 -21.76145014,
 -15.35342803,
 -11.4558726,
 -24.27417292,
 -17.31290487,
 -10.04035301,
 -18.11300988,
 40.73011269,
 -10.32750257,
 -27.30666551,
 -14.95849747,
 23.63531282,
 26.33971849,
 71.36218648,
 -14.8467137,
 -11.43914148,
 -19.31689367,
 -16.49296861,
 -23.09594295,
 -10.08765428,
 -15.83642827,
 82.13340905,
 -20.01642439,
 -12.46712116,
 21.2157936,
 29.90778381,
 22.88571593,
 -12.22936762,
 23.42830874,
 33.69723988,
 22.17051952,
 83.04565373,
 -12.03149739,
 21.08159858,
 22.7261358,
 23.94126471,
 29.23708726,
 27.62449166,
 29.43976676,
 28.77331594,
 20.6844303,
 94.88728323,
 32.76872947,
 20.43024601,
 22.48071637,
 25.08213802,
 73.21985334,
 60.0744133,
 31.75829571,
 21.79819028,
 66.35613169,
 -11.27183824,
 -15.78427287,
 23.42185222,
 65.6475366,
 38.93836298,
 26.15576468,
 42.60021913,
 28.16870642,
 21.90470536,
 27.91268345,
 31.41552695,
 30.71813145,
 20.25239339,
 22.90490363,
 32.90502518,
 24.31792545,
 20.28457326,
 27.456432,
 36.96883119,
 20.04664176,
 34.18528448,
 25.80012437,
 30.80415567,
 29.01960223,
 33.03589298,
 29.84403079,
 20.83918079,
 46.2955311,
 23.9856736,
 28.9104439,
 31.87602611,
 97.70362184,
 69.5765509,
 54.0791044,
 66.96858448,
 67.36023191,
 21.04345891,
 35.95576605,
 42.03556396,
 42.84875816,
 48.56639788,
 45.71018599,
 57.15392118,
 26.6490564,
 47.22748984,
 42.8606636,
 42.51019114,
 27.20682943,
 39.39731819,
 33.94350197,
 40.75548759,
 65.90411961,
 32.25263687,
 42.41436244,
 40.86023862,
 58.45222688,
 32.4372578,
 64.51711716,
 63.47893218,
 22.60206325,
 28.51830428,
 43.18698553,
 29.42135148,
 78.22509908,
 36.01811775,
 -10.94954528,
 -11.92482495,
 -10.10476018,
 -21.61671093,
 21.20388388,
 -12.13394841,
 58.5643853,
 -10.10762358,
 28.30699896,
 21.85626393,
 21.00331807,
 22.54632447,
 -22.34432496,
 23.29676448,
 24.39642072,
 98.87860425,
 21.22512843,
 -80.17199576,
 66.72317518,
 21.1544437,
 -11.98206191,
 -18.69047823,
 58.97709162,
 -10.55821782,
 -17.3878998,
 -20.82927107,
 -15.88240417,
 -94.59775759,
 -17.06965137,
 40.6440856,
 -11.42575829,
 28.29835933,
 23.10043252,
 -15.47790974,
 90.99144315,
 65.61573897,
 29.54217132,
 84.87796409,
 36.46922909,
 37.37857369,
 20.16059975,
 43.08752858,
 24.48141098,
 -140.3657077,
 29.98637422,
 -109.2773148,
 22.42661342,
 36.99710833,
 23.47580691,
 41.27199381,
 22.6156485,
 22.78048997,
 28.80762531,
 67.46701741,
 39.1988903,
 -166.377562,
 103.9669876,
 25.67113205,
 -17.58187181,
 -18.52757591,
 27.20109148,
 21.65041086,
 25.76991298,
 26.38274607,
 21.49017978,
 20.91797164,
 87.76943271,
 29.91150099,
 27.15245122,
 23.69585361,
 28.44695134,
 30.14680216,
 82.50811929,
 20.69512266,
 22.36229625,
 39.22686474,
 23.76332807,
 20.49194585,
 22.03630487,
 24.81227003,
 33.15341607,
 28.1810776,
 20.2200498,
 23.48443944,
 20.93287603,
 22.02832984,
 22.33933886,
 36.98789056,
 28.91084263,
 -13.57683179,
 -15.42171027,
 -11.33553539,
 -21.12397099,
 -11.22651581,
 -18.76073137,
 -11.61664795,
 -21.03920298,
 20.49768574,
 71.13581489,
 21.58994155,
 72.65026596,
 -11.10806125,
 21.67089907,
 -20.11544403,
 27.78943825,
 87.02122222,
 -11.45222996,
 21.6596544,
 27.35302788,
 24.4102755,
 -11.53186418,
 20.73739241,
 -13.58574463,
 28.20252476,
 -24.84117669,
 38.26264078,
 101.8360377,
 -44.78519575,
 -203.7000358,
 36.82935113,
 -12.67982596,
 25.33053402,
 -11.63233672,
 -10.15485192,
 -16.71126553,
 20.41344681,
 26.88470633,
 -17.29039914,
 39.53908878,
 -20.0646923,
 -27.63468162,
 -13.08659913,
 -23.1522558,
 -35.61378794,
 -17.77242153,
 -29.55305764,
 -23.24848597,
 -18.78198328,
 -20.60522746,
 -10.75062215,
 -16.74289563,
 -21.86566212,
 -10.37374052,
 -36.35803272,
 -25.36699326,
 -21.38269258,
 -24.29165293,
 -42.04754365,
 -28.66736455,
 -29.3334622,
 -17.48055749,
 -17.38781674,
 -10.20828102,
 -11.61182111,
 -33.42437027,
 -32.0419469,
 -17.56227003,
 -33.78299517,
 -30.84448292,
 -20.94367758,
 -38.93730384,
 -21.87318412,
 -21.60681736,
 -28.27517706,
 -12.34475241,
 -17.02476713,
 -20.85491468,
 -15.58675869,
 -13.74556196,
 -30.91418954,
 -13.38945178,
 50.83693548,
 -35.69315773,
 -25.06318521,
 -41.08430335,
 -19.40727362,
 -56.43622674,
 -24.82392367,
 -36.85741473,
 -35.14950673,
 -20.84675917,
 -33.36509163,
 -54.25105653,
 -45.52184568,
 -55.58412712,
 -28.52349051,
 -65.75981373,
 -23.32659332,
 -17.34464319,
 -11.57656028,
 -16.90233122,
 34.40381568,
 20.47515367,
 114.1798682,
 -12.13689924,
 37.59401095,
 -26.76576926,
 -13.9048135,
 -11.06971667,
 -13.51387453,
 -15.07240688,
 -12.22617953,
 -15.75781949,
 -29.64125734,
 -33.73188195,
 -167.5247327,
 -18.4238796,
 -181.2876039,
 25.58225158,
 -22.29307766,
 -44.45731987,
 -18.10129902,
 -26.96549692,
 -15.86483071,
 -15.33051891,
 -22.10843367,
 -11.38392655,
 -29.32207731,
 -16.16944838,
 -194.361426,
 -14.22081134,
 -26.30370985,
 -30.67570713,
 -25.92906309,
 -17.15707226,
 -14.39687901,
 -20.66192282,
 -35.32046491,
 -10.91323151,
 -18.17370489,
 -38.45014756,
 -12.43250146,
 57.34722023,
 -19.20901352,
 -16.01517651,
 -32.03863619,
 -25.48082813,
 -21.923979,
 -32.6864961,
 -26.00293045,
 -34.93898042,
 -37.74654365,
 -10.81822536,
 -20.78255547,
 -30.64873194,
 28.09286244,
 -22.74125359,
 26.75478809,
 -36.21089519,
 -27.17578999,
 -22.62474929,
 64.75092073,
 -17.35480308,
 -36.06637464,
 -23.92654268,
 -22.38778664,
 -14.95782149,
 -13.02435125,
 -10.95026714,
 -11.00320161,
 -11.05282061,
 -12.11596686,
 -23.34921213,
 -32.20388168,
 -19.26735704,
 -11.9380773,
 -23.74510742,
 -14.24369719,
 -12.18622651,
 -16.92885239,
 -20.90589063,
 -11.89760523,
 -14.79454224,
 -10.49909452,
 -21.3325054,
 -12.67239461,
 -27.50875818,
 -10.66376469,
 -20.15788074,
 -18.67537574,
 -11.40104496,
 -20.68077486,
 -27.04694572,
 -12.18818438,
 -52.78331514,
 -11.96534425,
 -23.44329872,
 -21.45833034,
 -18.18157992,
 -16.8464289,
 21.76637409,
 -37.35306375,
 -17.17711556,
 -33.81974983,
 -22.45005136,
 -12.20427248,
 -15.35002177,
 -13.78759597,
 -28.94272555,
 -10.78558961,
 -13.31920317,
 -22.41353036,
 -27.49041399,
 39.46694008,
 -14.53498044,
 30.1128109,
 -12.84212961,
 -72.75826409,
 -10.63142524,
 20.60543285,
 43.82447818,
 70.15141306,
 22.40667404,
 61.59260176,
 26.17423208,
 27.94712378,
 25.00519336,
 35.44634659,
 26.63108275,
 33.24999869,
 28.41849182,
 51.33644168,
 30.01072674,
 29.03134626,
 29.91315518,
 42.18142697,
 62.99607998,
 27.23991968,
 26.44910871,
 21.67941966,
 34.989681,
 27.21217509,
 107.9732847,
 30.80556593,
 22.74065263,
 26.95615883,
 -15.81349783,
 -18.20108583,
 27.07714957,
 -43.53796854,
 -15.8477608,
 -15.74418934,
 22.66750473,
 -14.87691148,
 -37.4313717,
 61.6441241,
 -19.43807637,
 21.12136217,
 -13.66824762,
 -33.80801207,
 -19.53073488,
 -26.80019025,
 23.93071456,
 -20.36941743,
 -20.60228195,
 -19.2884252,
 -49.58871529,
 -10.78724735,
 -36.03757421,
 -10.43453137,
 -10.81324567,
 30.4483021,
 36.55631235,
 63.0464369,
 32.28492491,
 27.89095269,
 26.30049775,
 -31.47329527,
 -29.28648393,
 42.00388849,
 22.76505079,
 57.59637034,
 31.87699816,
 -68.82801598,
 37.28491173,
 76.83615454,
 27.80460032,
 -27.09030659,
 -33.14228116,
 29.0665221,
 -19.95747162,
 -10.53552869,
 -24.82670415,
 -15.91833179,
 -11.29425912,
 -12.7052747,
 -15.38971734,
 -11.78334128,
 -17.96937542,
 -18.91682886,
 -15.04866023,
 -27.09062181,
 -15.4178226,
 -76.6840883,
 -10.01199663,
 20.16588576,
 -12.91358398,
 -11.59287646,
 -11.30191609,
 -11.56268319,
 -17.48724963,
 -27.82929323,
 21.90614798,
 31.53383947,
 31.16733832,
 -14.69971241,
 -14.20824045,
 -17.17816444,
 -13.82894409,
 -14.84048435,
 -10.29219948,
 -11.74914405,
 37.29371495,
 -37.33862208,
 -24.43476091,
 -20.87283103,
 -71.20630142,
 -25.36372552,
 -34.84951104,
 -13.5446877,
 -17.33426569,
 -15.02989012,
 -28.37266333,
 -13.83402497,
 -31.79073985,
 -15.05626094,
 -31.01633863,
 29.26967698,
 -22.36100988,
 -21.721153,
 -15.3343322,
 21.07898694,
 -15.19171246,
 -11.09715062,
 20.22915656,
 46.60076664,
 -37.69588947,
 34.11266685,
 -31.20332341,
 -11.79848688,
 -16.99096249,
 -24.81371048,
 -16.21619077,
 35.34757486,
 21.7903119,
 -10.92221268,
 21.96812448,
 -43.91738999,
 -15.41671552,
 -10.95666922,
 -11.78191068,
 -12.05081525,
 -12.1726948,
 -18.40104179,
 -45.05215893,
 26.42622312,
 -20.01384213,
 -11.41444606,
 -20.16584465,
 -11.56481591,
 -39.25299902,
 -11.55129095,
 -10.4698957,
 -17.53249021,
 -16.66840556,
 -16.51897059,
 29.11045544,
 -15.75843953,
 22.06855018,
 27.2673244,
 25.19398167,
 23.40397281,
 41.00109484,
 26.92639087,
 51.64067036,
 20.64574526,
 25.82712639,
 21.80049825,
 27.18042222,
 28.52165788,
 32.00567581,
 35.52026131,
 28.85515546,
 38.98004749,
 24.87562939,
 20.43023896,
 22.18211015,
 -30.60922974,
 22.86833164,
 37.00291381,
 32.69822782,
 35.154463,
 33.14624389,
 -10.55765057,
 21.75454315,
 -12.78607476,
 37.76332606,
 46.47558852,
 39.09045434,
 -51.43911997,
 -31.64625021,
 -18.11821222,
 -11.69085555,
 -43.48359364,
 -11.1190136,
 23.84452938,
 -16.56370455,
 -19.4100816,
 -32.5297219,
 -17.20620842,
 -21.7294747,
 -27.46159368,
 -22.47486626,
 -33.27180552,
 -13.54425066,
 -47.16109214,
 -14.58716543,
 -32.08518594,
 -19.10266007,
 -10.05745061,
 -12.76639355,
 -15.39931953,
 -20.72438161,
 -23.04864922,
 -11.71254948,
 -13.31654234,
 -25.78553809,
 -16.76776281,
 -14.73537115,
 -35.35980954,
 -13.75971558,
 -36.57187788,
 -21.48554066,
 -15.74352148,
 -12.04613895,
 -17.01062835,
 -12.10473557,
 -16.03990738,
 -24.46010539,
 -10.18796425,
 -17.91324141,
 -12.85046281,
 -14.48081501,
 ...]

In [ ]:
# @title
synclass=[]
syn=OneilData.iloc[:,3]
for s in syn:
  if s>=20:
    synclass.append(1)
  elif s<=-20:
    synclass.append(0)
  else:
    synclass.append(3)

OneilData['SynClass'] = synclass

OneilDataset = OneilData[OneilData["SynClass"]<2]
sdata=OneilDataset["synergy"]
print(sdata)

OneilDataset.to_csv('/content/drive/MyDrive/MACSynDCR/Data/OneilDataset_-20to20.csv')
OneilDataset

28      -36.459230
43       23.986180
54       23.381134
55      -32.990619
61       33.592926
           ...
22714    20.383893
22716    22.955596
22728    26.974328
22734    20.551627
22735    23.438547
Name: synergy, Length: 5596, dtype: float64

         drug1      drug2          cell    synergy  fold  SynClass
28        5-FU    ABT-888       SKMEL30 -36.459230     2         0
43        5-FU    AZD1775         CAOV3  23.986180     1         1
54        5-FU    AZD1775      MDAMB436  23.381134     1         1
55        5-FU    AZD1775          MSTO -32.990619     1         0
61        5-FU    AZD1775         OCUBM  33.592926     1         1
...        ...        ...           ...        ...   ...       ...
22714  ZOLINZA  TOPOTECAN          MSTO  20.383893     2         1
22716  ZOLINZA  TOPOTECAN      NCIH2122  22.955596     2         1
22728  ZOLINZA  TOPOTECAN         SKOV3  26.974328     2         1
22734  ZOLINZA  TOPOTECAN  UWB1289BRCA1  20.551627     2         1
22735  ZOLINZA  TOPOTECAN          VCAP  23.438547     2         1

[5596 rows x 6 columns]

In [ ]:
# @title
synclass=[]
syn=OneilData.iloc[:,3]
for s in syn:
  if s>=30:
    synclass.append(1)
  elif s<=0:
    synclass.append(0)
  else:
    synclass.append(3)

OneilData['SynClass'] = synclass

OneilDataset = OneilData[OneilData["SynClass"]<2]
sdata=OneilDataset["synergy"]
print(sdata)
OneilDataset
OneilDataset.to_csv('/content/drive/MyDrive/MACSynDCR/Data/OneilDataset_0-30.csv')

2        -1.198505
4        -5.139971
7        -5.089853
10       -3.701355
14       -8.979214
           ...
22718   -10.915651
22720    -2.472170
22722    -1.053791
22723    -8.139633
22726    -0.999305
Name: synergy, Length: 10650, dtype: float64

**Synergy threshold -10 to 10 as additive**

In [ ]:
# @title
import pandas as pd
DataID = pd.read_csv('/content/drive/MyDrive/MACSynDCR/Data/drug_cell_id.csv')
DataID = pd.DataFrame(data=DataID)
#smiles_list=smiles.iloc[:,2]
DataID.head()

,drug_id,drug_name,drug_smiles,cell_id,cell_name
0,0.0,5-FU,O=c1[nH]cc(F)c(=O)[nH]1,0,A2058
1,1.0,ABT-888,CC1(c2nc3c(C(N)=O)cccc3[nH]2)CCCN1,1,A2780
2,2.0,AZD1775,C=CCn1c(=O)c2cnc(Nc3ccc(N4CCN(C)CC4)cc3)nc2n1-...,2,A375
3,3.0,BEZ-235,Cn1c(=O)n(-c2ccc(C(C)(C)C#N)cc2)c2c3cc(-c4cnc5...,3,A427
4,4.0,BORTEZOMIB,CC(C)CC(NC(=O)C(Cc1ccccc1)NC(=O)c1cnccn1)B(O)O,4,CAOV3

In [ ]:
# @title
synclass=[]
syn=OneilData.iloc[:,3]
for s in syn:
  if s>=10:
    synclass.append(1)
  elif s<=-10:
    synclass.append(0)
  else:
    synclass.append(3)

OneilData['SynClass'] = synclass

OneilDataset = OneilData[OneilData["SynClass"]<2]
sdata=OneilDataset["synergy"]
print(sdata)
OneilDataset
OneilDataset.to_csv('/content/drive/MyDrive/MACSynDCR/Data/OneilDataset_-10to10.csv')
OneilDataset

11       10.173434
23      -10.068848
24       17.637033
28      -36.459230
32      -14.523109
           ...
22732    10.223066
22733    12.190316
22734    20.551627
22735    23.438547
22736    12.223791
Name: synergy, Length: 11770, dtype: float64

         drug1      drug2          cell    synergy  fold  SynClass
11        5-FU    ABT-888          HT29  10.173434     2         1
23        5-FU    ABT-888          OV90 -10.068848     2         0
24        5-FU    ABT-888        OVCAR3  17.637033     2         1
28        5-FU    ABT-888       SKMEL30 -36.459230     2         0
32        5-FU    ABT-888         SW837 -14.523109     2         0
...        ...        ...           ...        ...   ...       ...
22732  ZOLINZA  TOPOTECAN        UACC62  10.223066     2         1
22733  ZOLINZA  TOPOTECAN       UWB1289  12.190316     2         1
22734  ZOLINZA  TOPOTECAN  UWB1289BRCA1  20.551627     2         1
22735  ZOLINZA  TOPOTECAN          VCAP  23.438547     2         1
22736  ZOLINZA  TOPOTECAN         ZR751  12.223791     2         1

[11770 rows x 6 columns]

In [ ]:
# @title
synclass=[]
syn=OneilData.iloc[:,3]
for s in syn:
  if s>=10:
    synclass.append(1)
  elif s<=0:
    synclass.append(0)
  else:
    synclass.append(3)

OneilData['SynClass'] = synclass

OneilDataset = OneilData[OneilData["SynClass"]<2]
sdata=OneilDataset["synergy"]
print(sdata)
OneilDataset
OneilDataset.to_csv('/content/drive/MyDrive/MACSynDCR/Data/OneilDataset_0to10.csv')
OneilDataset

2        -1.198505
4        -5.139971
7        -5.089853
10       -3.701355
11       10.173434
           ...
23047    10.223066
23048    20.551627
23049    12.190316
23050    23.438547
23051    12.223791
Name: synergy, Length: 16771, dtype: float64

      drug_a_name drug_b_name     cell_line    synergy  fold  SynClass
2            5-FU     ABT-888          A375  -1.198505     2         0
4            5-FU     ABT-888         CAOV3  -5.139971     2         0
7            5-FU     ABT-888       EFM192B  -5.089853     2         0
10           5-FU     ABT-888         HT144  -3.701355     2         0
11           5-FU     ABT-888          HT29  10.173434     2         1
...           ...         ...           ...        ...   ...       ...
23047     ZOLINZA   TOPOTECAN        UACC62  10.223066     2         1
23048     ZOLINZA   TOPOTECAN  UWB1289BRCA1  20.551627     2         1
23049     ZOLINZA   TOPOTECAN       UWB1289  12.190316     2         1
23050     ZOLINZA   TOPOTECAN          VCAP  23.438547     2         1
23051     ZOLINZA   TOPOTECAN         ZR751  12.223791     2         1

[16771 rows x 6 columns]

In [ ]:
ext_DT

,gene_id,ENSG00000116237,ENSG00000162413,ENSG00000171603,ENSG00000160049,ENSG00000065526,ENSG00000117118,ENSG00000053371,ENSG00000076864,ENSG00000070831,...,ENSG00000156299,ENSG00000142166,ENSG00000159228,ENSG00000159231,ENSG00000183527,ENSG00000182093,ENSG00000182240,ENSG00000157617,ENSG00000160208,ENSG00000141959
1,X22RV1,57.81,6.73,26.89,10.13,28.07,146.83,31.51,4.44,2.32,...,0.03,19.72,29.36,4.42,7.2,33.97,0,1.39,20.86,80.13
2,X2313287,39.68,5.81,22.47,6.72,15.59,135.07,36.62,0.72,1.99,...,0.05,15.38,101.64,1.42,7.68,27.77,0.92,0.47,17.47,68.26
3,X253JBV,14.88,6.55,9.14,24.81,8.84,92.43,29.56,0,2.05,...,1.7,6.42,224.96,11.24,2.46,10.58,1.17,1.75,18.74,30.9
4,X253J,13.19,3.68,6.89,7.6,5.45,69.25,25.88,0,0.7,...,0.56,5.6,202.03,6.53,0.92,15.5,1.11,1.89,8.11,27.76
5,X42MGBA,79.58,34.03,30.23,20.08,15.16,100.59,35.83,0,5.44,...,5.21,10.5,214.9,50.74,8.42,13.3,3.06,8.61,23.28,166.13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1015,YD8,15.74,6.83,32.57,9.79,13.92,75.22,32.07,0,1.04,...,2.87,12.22,79.2,11.77,2.11,11.91,0,0.77,15.02,78.85
1016,YH13,63.83,20.43,44.2,15.41,16.1,81.04,57.77,0,0.18,...,4.19,17.39,89.84,22.15,5.41,17.1,0,3.45,16.38,60.6
1017,YKG1,41.25,23.28,55.37,10.4,11.68,102.11,70.71,0.21,1.64,...,11.94,19.13,110.93,35.15,4.96,27.35,1.11,1.72,18.24,71.48
1018,ZR751,30.69,4.72,5.34,6.82,7.33,78.93,23.91,0,4.27,...,2.18,6.97,1.24,8.24,0.87,13.65,0,0.77,6.8,36.37
1019,ZR7530,25.04,7.31,12.12,4.67,7.58,38.21,24.03,1.81,0.61,...,0.53,7.19,0.42,55.51,1.52,8.59,0.56,5.44,10.06,73.45

In [ ]:
ext_smailes = drugdataset['drug1'].unique()
ext_smiles_df = pd.DataFrame(data=ext_smailes)
ext_smiles_df = ext_smiles_df.rename(columns={0: 'SMILES'})
ext_smiles_df

NameError: name 'drugdataset' is not defined

In [ ]:
import pandas as pd
smilesData = pd.read_csv('/content/drive/MyDrive/MACSynDCR/Data/Drug/ext_smiles.csv')
smilesData = pd.DataFrame(data=smilesData)
ext_smilesData=smilesData.iloc[:,0]
ext_smilesData

0     CNC(=O)CN1CCC(CC1)Oc2cc3c(cc2OC)ncnc3Nc4cccc(c...
1     C[C@@H]1CN(C[C@@H](N1)C)c2ccc(cc2)C(=O)Nc3cc(n...
2     CS(=O)(=O)N1CCN(CC1)Cc2cc3c(s2)c(nc(n3)c4cccc5...
3     CC(c1cc(cc2c1oc(cc2=O)N3CCOCC3)C(=O)N(C)C)Nc4c...
4     c1c(c(cnc1N)c2cc(nc(n2)N3CCOCC3)N4CCOCC4)C(F)(F)F
5     CN(CC[C@H](CSc1ccccc1)Nc2ccc(cc2S(=O)(=O)C(F)(...
6          Cn1cnc2c1cc(c(c2F)Nc3ccc(cc3Cl)Br)C(=O)NOCCO
7     COc1cc(ccc1Nc2ncc(c(n2)c3c[nH]c4c3cccc4)Cl)N5C...
8     C[C@H]1COCCN1c2c3ccc(nc3nc(n2)N4CCOC[C@@H]4C)c...
9     C[C@@H]1COCCN1c2cc(nc(n2)c3ccnc4c3cc[nH]4)C5(C...
10    CN(C)CC#Cc1ccc(OCCCc2sc(nc2C(=O)O)N3CCc4cccc(C...
11    CC(=O)Nc1cc(ccc1N(C)CCN)Nc2cc(n3c(n2)c(cn3)C#N...
12                  c1cn(c(=O)nc1N)C2C(C(C(O2)CO)O)(F)F
13    CN(C)C/C=C/C(=O)Nc1cc2c(cc1O[C@H]3CCOC3)ncnc2N...
14     COc1cc2c(cc1OCCCN3CCOCC3)c(ncn2)Nc4ccc(c(c4)Cl)F
15    c1cc(ccc1c2ccc3c(c2)cco3)c4nc5cnccc5n4C[C@@H]6...
16    C[C@H]1COCCN1c2c3ccc(nc3nc(n2)N4CCOC[C@@H]4C)c...
17      CN1CCC(CC1)COc2cc3c(cc2OC)c(ncn3)Nc4ccc(cc4F)Br
18    c1ccc(cc1)c2cccc(c2N3CCC[C@H](C3)N)/C=C\4/C(=O...
19    c1ccc2c(c1)c3cccc(c3s2)c4cccc5c4oc(cc5=O)N6CCOCC6
20    Cc1c(sc(n1)NC(=O)N2CCC[C@H]2C(=O)N)c3ccnc(c3)C...
21    c1ccc(cc1)c2cc3c(ccn4c3n[nH]c4=O)nc2c5ccc(cc5)...
22    C[C@H](C(=O)N1CCC(CC1)c2ccc(c(c2)OC)Nc3ncc(c(n...
23    Cc1c(cn(n1)C)Nc2cc(c(cn2)C(F)(F)F)Nc3ccccc3C(=...
24                 COc1cc(cnc1)Nc2cncc(n2)c3cnc4n3cccc4
25    COc1cc2c(cc1OC)C3(CCN(CC3)c4c5c([nH]nc5Br)ncn4...
26    c1ccc2c(c1)c(n[nH]c2=O)Cc3ccc(c(c3)C(=O)N4CCN(...
27    c1cc(cc(c1)F)c2cc(c(s2)C(=O)N[C@H]3CCCNC3)NC(=O)N
28    COc1cc(ccc1Nc2ncc(c(n2)c3cnc4n3cccc4)F)N5CCN(C...
29    COC1CCN(CC1)C(=O)c2cc(ccc2F)Cc3c4ccccc4c(=O)[n...
30         CS(=O)(=O)c1ccc(cc1)Nc2cncc(n2)c3cnc4n3cccc4
31    C[C@H](c1c(ccc(c1Cl)F)Cl)Oc2cc(cnc2N)c3cnn(c3)...
32    CCc1c2cc(ccc2nc-3c1Cn4c3cc5c(c4=O)COC(=O)[C@@]...
33    c1cc(c(c(c1)OCC2CC2)c3cc(c4c(n3)NC(=O)OC4)C5CC...
34    CCN1CCN(CC1)CC(=O)Nc2ccc(c3c2c4ccccc4s3)c5cccc...
35    Cc1c(cn(n1)C)Nc2cc(c(cn2)C(F)(F)F)Nc3ccc(cc3C(...
36    CC1(C(=O)Nc2c(ccc(n2)Nc3c(cnc(n3)Nc4cc(c(c(c4)...
37    CN1CCN(CC1)CCOc2cc3c(c(c2)OC4CCOCC4)c(ncn3)Nc5...
38    C[C@]1(C[C@@H](C1)c2n3c(c(ncc3)N)c(n2)c4cc5nc(...
39    CC1=C2C(=C(N(C1=O)C)NC3=C(C=C(C=C3)I)F)C(=O)N(...
40    CC(=O)Nc1cc(ccc1N(C)CCN(C)C)Nc2cc(n3c(n2)c(cn3...
41       c1cc2cc(ccc2nc1)Cn3c4c(ncc(n4)c5cnn(c5)CCO)nn3
42    Cc1c2c(c(n(c1=O)C)Nc3ccc(cc3F)I)c(=O)n(c(=O)n2...
43    Cc1cc(n[nH]1)Nc2c(cnc(n2)N[C@@H](C)c3ncc(cn3)F)Cl
44    c1cc(ccc1[C@H](CCO)NC(=O)C2(CCN(CC2)c3c4cc[nH]...
45    CC1(CCC(=C(C1)CN2CCN(CC2)c3ccc(cc3)C(=O)NS(=O)...
46    CN1CCN(CC1)C2CCN(CC2)c3ccc(c(c3)OC)Nc4ncc(c(n4...
47    CCCS(=O)(=O)Nc1ccc(c(c1F)C(=O)c2c[nH]c3c2cc(cn...
48    CC1C(C(CC(O1)OC2CC(Cc3c2c(c4c(c3O)C(=O)c5cccc(...
49    C[C@@H]1COCCN1c2cc(nc(n2)c3cccc4c3cc[nH]4)C5(C...
50    C[C@@H]1CN(C[C@@H](O1)C)CC(=O)Nc2ccc3c(c2)Cc4c...
51    CS(=O)(=O)C1(CC1)c2cc(nc(n2)c3cccc4c3cc[nH]4)N...
Name: SMILES, dtype: object

In [ ]:
import numpy as np
ext_drug_LapMGAN128= np.load('/content/drive/MyDrive/MACSynDCR/Data/Drug/ext_Lap_MGAN_features_128.npy')
ext_drug_LapMGAN128.shape

(52, 128)

In [ ]:
import numpy as np
drug_LapMGAN128= np.load('/content/drive/MyDrive/MACSynDCR/Data/Drug/Lap_MGAN_features_128.npy')
drug_LapMGAN128.shape

(38, 128)

In [ ]:
import numpy as np

ext_smilesf128= np.load('/content/drive/MyDrive/MACSynDCR/Data/Drug/ext_smiles_features_128.npy')
ext_smilesf128.shape

(52, 128)

In [ ]:
import numpy as np
smilesf128= np.load('/content/drive/MyDrive/MACSynDCR/Data/Drug/smiles_features_128.npy')
smilesf128.shape

(38, 128)

In [ ]:
import numpy as np

ext_fpf128= np.load('/content/drive/MyDrive/MACSynDCR/Data/Drug/ext_fp_features_128.npy')
ext_fpf128.shape

(52, 128)

In [ ]:
import numpy as np
fpf128= np.load('/content/drive/MyDrive/MACSynDCR/Data/Drug/fp_features_128.npy')
fpf128.shape

(38, 128)

In [ ]:
# @title
import numpy as np

descf128= np.load('/content/drive/MyDrive/MACSynDCR/Data/Drug/ext_desc_features_128.npy')
descf128.shape

FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/MyDrive/MACSynDCR/Data/Drug/ext_desc_features_128.npy'

In [ ]:
import numpy as np

ext_dmgf128= np.load('/content/drive/MyDrive/MACSynDCR/Data/Drug/ext_DMG_features_128.npy')
ext_dmgf128.shape

(52, 128)

In [ ]:
import numpy as np
dmgf128= np.load('/content/drive/MyDrive/MACSynDCR/Data/Drug/DMG_features_128.npy')
dmgf128.shape

(38, 128)

In [ ]:
# @title
import numpy as np

dtif128= np.load('/content/drive/MyDrive/MACSynDCR/Data/Drug/ext_DTI_features_128.npy')
dtif128.shape

FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/MyDrive/MACSynDCR/Data/Drug/ext_DTI_features_128.npy'

In [ ]:
import numpy as np

ext_gexf512= np.load('/content/drive/MyDrive/MACSynDCR/Data/Cell/ext_GEx_features_512.npy')
ext_gexf512.shape

(23, 256)

In [ ]:
# @title
import pandas as pd
gexf = pd.read_csv('/content/drive/MyDrive/MACSynDCR/Data/Cell/vae_expression256.csv')
gexf = pd.DataFrame(data=gexf)
cell_id=gexf.iloc[:,0]
gexf=gexf.iloc[:,1:]
gexf256=gexf.to_numpy()
gexf256.shape
cell_id=cell_id.values
cell_id

array(['A2058', 'A2780', 'A375', 'A427', 'CAOV3', 'COLO320DM', 'DLD1',
       'EFM192B', 'ES2', 'HCT116', 'HT144', 'HT29', 'KPL1', 'LNCAP',
       'LOVO', 'MDAMB436', 'MSTO', 'NCIH1650', 'NCIH2122', 'NCIH23',
       'NCIH460', 'NCIH520', 'OCUBM', 'OV90', 'OVCAR3', 'PA1', 'RKO',
       'RPMI7951', 'SKMEL30', 'SKMES1', 'SKOV3', 'SW620', 'SW837', 'T47D',
       'UACC62', 'UWB1289', 'UWB1289BRCA1', 'VCAP', 'ZR751'], dtype=object)

In [ ]:
cell=OneilData['cell'].unique()
print(cell.shape)
cell

(31,)

array(['A375', 'CAOV3', 'HT144', 'HT29', 'LOVO', 'MSTO', 'NCIH1650',
       'NCIH23', 'NCIH460', 'OV90', 'RKO', 'RPMI7951', 'SKMEL30',
       'SKMES1', 'SW837', 'T47D', 'UACC62', 'ZR751', 'A2058', 'A2780',
       'ES2', 'HCT116', 'KPL1', 'MDAMB436', 'SKOV3', 'VCAP', 'LNCAP',
       'NCIH520', 'SW620', 'A427', 'NCIH2122'], dtype=object)

In [ ]:
# @title
import pandas as pd
gmuf = pd.read_csv('/content/drive/MyDrive/MACSynDCR/Data/Cell/vae_mutation256.csv')
gmuf = pd.DataFrame(data=gmuf)
#smiles_list=smiles.iloc[:,2]
gmuf256=gmuf.to_numpy()
gmuf256
gmuf.head()

,0,1,2,3,4,5,6,7,8,9,...,246,247,248,249,250,251,252,253,254,255
0,1.008559,-0.632159,-0.582553,-0.828983,-0.833411,-1.080356,-0.852374,1.114175,0.782072,1.252288,...,0.305696,-0.078375,0.202251,-0.646159,1.569222,-0.200611,1.812180,-0.139765,-0.626483,1.365668
1,-0.410416,0.627163,-1.233319,0.106432,-0.069214,-1.412507,0.093937,-2.144694,-0.406761,2.703932,...,-0.505088,0.453303,0.734657,-0.207518,-1.438838,0.729439,0.033893,1.225495,0.085385,0.403014
2,-0.846302,-0.353818,0.046302,-1.773011,0.702163,0.944128,1.098852,1.031613,-0.456862,-0.177741,...,0.205174,0.387792,-1.060420,0.557022,0.758276,-0.964644,-2.501486,2.083748,0.946657,0.606141
3,0.790532,-1.180964,-1.470743,-0.025225,-0.438105,-0.495114,1.247222,-0.628579,0.323282,-0.268146,...,1.093617,0.613316,-0.572698,-0.351611,-0.375152,-1.196839,-0.401630,-0.348718,0.645292,0.209031
4,1.608072,-1.782630,-0.831946,-0.854945,0.401966,0.305383,1.770150,0.067022,1.792941,0.086606,...,-0.125608,-0.753935,-1.712411,-0.749203,-1.030563,-0.256837,-1.500639,-0.698106,0.113910,-2.281886

In [ ]:
# @title
import pandas as pd
gcpyf = pd.read_csv('/content/drive/MyDrive/MACSynDCR/Data/Cell/vae_copy256.csv')
gcpyf = pd.DataFrame(data=gcpyf)
#smiles_list=smiles.iloc[:,2]
gcpyf256=gcpyf.to_numpy()
gcpyf256
gcpyf.head()

,0,1,2,3,4,5,6,7,8,9,...,246,247,248,249,250,251,252,253,254,255
0,1.008496,-0.632376,-0.582575,-0.828927,-0.833375,-1.079921,-0.852308,1.114641,0.782174,1.252336,...,0.305840,-0.078607,0.202168,-0.646108,1.569124,-0.201097,1.812548,-0.139712,-0.625844,1.366595
1,-0.409985,0.627584,-1.233693,0.106616,-0.068700,-1.412522,0.093889,-2.146340,-0.406925,2.704303,...,-0.504785,0.452831,0.734120,-0.207990,-1.439129,0.729447,0.034347,1.225386,0.086091,0.403544
2,-0.846460,-0.354052,0.046727,-1.773046,0.701990,0.943929,1.098326,1.031669,-0.456745,-0.177494,...,0.205362,0.387898,-1.060533,0.556955,0.758407,-0.964796,-2.502169,2.084100,0.947193,0.606841
3,0.790628,-1.180968,-1.470607,-0.025527,-0.438024,-0.494804,1.246588,-0.628756,0.323237,-0.267835,...,1.093860,0.612723,-0.573263,-0.351838,-0.375191,-1.197070,-0.402171,-0.348799,0.646065,0.209870
4,1.607627,-1.782464,-0.831500,-0.855313,0.401519,0.305168,1.769228,0.067163,1.793234,0.086433,...,-0.125378,-0.754220,-1.713197,-0.749069,-1.031157,-0.257476,-1.500826,-0.698160,0.114329,-2.281207

In [ ]:
# @title
import pandas as pd
gprot = pd.read_csv('/content/drive/MyDrive/MACSynDCR/Data/Cell/vae_promatics256.csv')
gprot = pd.DataFrame(data=gprot)
#smiles_list=smiles.iloc[:,2]
gprotf256=gprot.to_numpy()
gprotf256
gprot.head()

,0,1,2,3,4,5,6,7,8,9,...,246,247,248,249,250,251,252,253,254,255
0,1.008310,-0.631913,-0.582233,-0.828743,-0.833388,-1.080451,-0.852349,1.114319,0.782297,1.252765,...,0.306010,-0.078309,0.202388,-0.645933,1.568928,-0.200263,1.812103,-0.139669,-0.626033,1.366463
1,-0.410215,0.627590,-1.233128,0.106698,-0.068837,-1.412944,0.093608,-2.145884,-0.407060,2.704806,...,-0.504837,0.453104,0.734221,-0.207465,-1.439199,0.729754,0.033668,1.225319,0.085896,0.403407
2,-0.846727,-0.353621,0.046730,-1.772851,0.702157,0.943595,1.098123,1.031326,-0.457024,-0.177484,...,0.205502,0.387936,-1.060364,0.556785,0.757745,-0.963967,-2.502004,2.083902,0.947373,0.606944
3,0.790438,-1.180399,-1.470177,-0.025184,-0.437992,-0.495230,1.246023,-0.629065,0.323258,-0.267850,...,1.093888,0.613182,-0.572638,-0.351686,-0.375487,-1.196213,-0.402025,-0.348792,0.646042,0.209686
4,1.607776,-1.781981,-0.831611,-0.854919,0.402126,0.304706,1.769196,0.066802,1.793636,0.086882,...,-0.125455,-0.753794,-1.712543,-0.749001,-1.031243,-0.256599,-1.500815,-0.698243,0.114191,-2.281345

In [ ]:
# @title
ldata=OneilDataset.iloc[:,5]
sydata=OneilDataset.iloc[:,3]
print(ldata)
sydata.head()
#OneilDataset.head()

IndexError: single positional indexer is out-of-bounds

In [ ]:
# @title

For DeepSynergy Data:

In [ ]:
# @title
ldata=OneilDataset.iloc[:,5]
sydata=OneilDataset.iloc[:,3]
print(ldata)
sydata.head()
#OneilDataset.head()

IndexError: single positional indexer is out-of-bounds

#Merck dataset

In [ ]:
# @title
#print(MerckData.head())
OneilDataset=MerckData
ldata=MerckData.iloc[:,4]
print(len(ldata))
OneilDataset.head()

12415

  drug1    drug2   cell      score  label
0  5-FU  ABT-888   A375  -1.198505      0
1  5-FU  ABT-888  CAOV3  -5.139971      0
2  5-FU  ABT-888  HT144  -3.701355      0
3  5-FU  ABT-888   HT29  10.173434      1
4  5-FU  ABT-888   LOVO  -8.979214      0

# External validation dataset: AstraZeneca

In [ ]:
ext_drug_list=ext_smilesData.values
ext_cell_list=ext_cell_id
print(ext_cell_list.shape)
print(ext_drug_list.shape)
ext_drug_list
ext_cell_list

(23,)
(52,)

array(['A549', 'C32', 'HCC1143', 'HCC1187', 'HCC1395', 'HCC1419',
       'HCC1428', 'HCC1500', 'HCC1569', 'HCC1806', 'HCC1937', 'HCC1954',
       'HCC38', 'HCC70', 'J82', 'KATOIII', 'MCF7', 'RT4', 'SW48', 'SW780',
       'SW900', 'SW948', 'TCCSUP'], dtype=object)

In [ ]:
#print(MerckData.head())
ldata=ExternalData.iloc[:,3]
print(len(ldata))
ExternalData.head()

665

,drug1,drug2,cell,label
0,CNC(=O)CN1CCC(CC1)Oc2cc3c(cc2OC)ncnc3Nc4cccc(c...,c1cc(ccc1[C@H](CCO)NC(=O)C2(CCN(CC2)c3c4cc[nH]...,J82,1
1,CNC(=O)CN1CCC(CC1)Oc2cc3c(cc2OC)ncnc3Nc4cccc(c...,c1cc(ccc1[C@H](CCO)NC(=O)C2(CCN(CC2)c3c4cc[nH]...,SW780,0
2,C[C@@H]1CN(C[C@@H](N1)C)c2ccc(cc2)C(=O)Nc3cc(n...,c1cc(ccc1[C@H](CCO)NC(=O)C2(CCN(CC2)c3c4cc[nH]...,SW780,0
3,C[C@@H]1CN(C[C@@H](N1)C)c2ccc(cc2)C(=O)Nc3cc(n...,c1cc(ccc1[C@H](CCO)NC(=O)C2(CCN(CC2)c3c4cc[nH]...,TCCSUP,1
4,CS(=O)(=O)N1CCN(CC1)Cc2cc3c(s2)c(nc(n3)c4cccc5...,c1ccc(cc1)c2cc3c(ccn4c3n[nH]c4=O)nc2c5ccc(cc5)...,HCC1187,1

In [ ]:
ExternalData = ExternalData[ExternalData["cell"] != "22RV1"]
# Reset index if you want a clean DataFrame
ExternalData = ExternalData.reset_index(drop=True)
ExternalData

,drug1,drug2,cell,label
0,CNC(=O)CN1CCC(CC1)Oc2cc3c(cc2OC)ncnc3Nc4cccc(c...,c1cc(ccc1[C@H](CCO)NC(=O)C2(CCN(CC2)c3c4cc[nH]...,J82,1
1,CNC(=O)CN1CCC(CC1)Oc2cc3c(cc2OC)ncnc3Nc4cccc(c...,c1cc(ccc1[C@H](CCO)NC(=O)C2(CCN(CC2)c3c4cc[nH]...,SW780,0
2,C[C@@H]1CN(C[C@@H](N1)C)c2ccc(cc2)C(=O)Nc3cc(n...,c1cc(ccc1[C@H](CCO)NC(=O)C2(CCN(CC2)c3c4cc[nH]...,SW780,0
3,C[C@@H]1CN(C[C@@H](N1)C)c2ccc(cc2)C(=O)Nc3cc(n...,c1cc(ccc1[C@H](CCO)NC(=O)C2(CCN(CC2)c3c4cc[nH]...,TCCSUP,1
4,CS(=O)(=O)N1CCN(CC1)Cc2cc3c(s2)c(nc(n3)c4cccc5...,c1ccc(cc1)c2cc3c(ccn4c3n[nH]c4=O)nc2c5ccc(cc5)...,HCC1187,1
...,...,...,...,...
660,CN1CCN(CC1)CCOc2cc3c(c(c2)OC4CCOCC4)c(ncn3)Nc5...,c1ccc(cc1)c2cccc(c2N3CCC[C@H](C3)N)/C=C\4/C(=O...,TCCSUP,1
661,CN1CCC(CC1)COc2cc3c(cc2OC)c(ncn3)Nc4ccc(cc4F)Br,CS(=O)(=O)c1ccc(cc1)Nc2cncc(n2)c3cnc4n3cccc4,SW48,1
662,CN1CCC(CC1)COc2cc3c(cc2OC)c(ncn3)Nc4ccc(cc4F)Br,CS(=O)(=O)c1ccc(cc1)Nc2cncc(n2)c3cnc4n3cccc4,SW48,1
663,c1cn(c(=O)nc1N)C2C(C(C(O2)CO)O)(F)F,C[C@@H]1COCCN1c2cc(nc(n2)c3ccnc4c3cc[nH]4)C5(C...,SW780,1
664,c1cn(c(=O)nc1N)C2C(C(C(O2)CO)O)(F)F,C[C@@H]1COCCN1c2cc(nc(n2)c3ccnc4c3cc[nH]4)C5(C...,TCCSUP,1

In [ ]:
import numpy as np
inputData=[]
ydata=[]
no_samples=ExternalData.shape[0]
print('No of samples = '+str(no_samples))

for i in range(no_samples):
    sm1 = ExternalData.iloc[i,0]
    did1 = int(np.where(ext_drug_list == sm1)[0][0])
    sm2 = ExternalData.iloc[i,1]
    did2 = int(np.where(ext_drug_list == sm2)[0][0])
    cell_name = ExternalData.iloc[i,2]
    cid = int(np.where(ext_cell_list == cell_name)[0][0])
    #print(sm1, sm2, cell_name)
#LapMGAN
    #drug(smilesf+fpf+descf+dmgf)
    ddif=DDI_features_128(sm1,sm2)
    dtif1=DTI_feature_128(sm1,cell_name)
    dtif2=DTI_feature_128(sm2,cell_name)
    #feature_vector=DTI_feature_128(drug_smi,cell_line)

    input=np.concatenate((ext_drug_LapMGAN128[did1],ext_smilesf128[did1],ext_fpf128[did1],ext_dmgf128[did1],ext_drug_LapMGAN128[did2],ext_smilesf128[did2],ext_fpf128[did2],ext_dmgf128[did2],
                          ext_gexf512[cid],ddif,dtif1, dtif2))
    inputData.append(input)
    ydata.append(ldata.iloc[i])
    if i%100==0:
      print(i)
      print(len(inputData), inputData[0].shape)
#print(len(inputData), inputData[0].shape)

No of samples = 665
0
1 (1664,)
100
101 (1664,)
200
201 (1664,)
300
301 (1664,)
400
401 (1664,)
500
501 (1664,)
600
601 (1664,)

In [ ]:
Exyernel_Ind_AstraZeneca_feature_dataset_1920=pd.DataFrame(inputData)
Exyernel_Ind_AstraZeneca_feature_dataset_1920['synargy']=ydata
Exyernel_Ind_AstraZeneca_feature_dataset_1920.to_csv('/content/drive/MyDrive/MACSynDCR/Data/Exyernel_Ind_AstraZeneca_feature_dataset_1664.csv')
Exyernel_Ind_AstraZeneca_feature_dataset_1920.head()

,0,1,2,3,4,5,6,7,8,9,...,1655,1656,1657,1658,1659,1660,1661,1662,1663,synargy
0,-0.874179,0.337785,1.196388,-0.395786,1.691320,-0.892781,-1.607152,-0.821635,0.748567,0.672847,...,-2.399447,8.864655,49.230148,4.611594,0.757010,-9.678878,-10.386772,-32.987554,-4.784277,1
1,-0.874179,0.337785,1.196388,-0.395786,1.691320,-0.892781,-1.607152,-0.821635,0.748567,0.672847,...,5.968601,-11.867944,45.292110,-2.479564,-7.836410,-0.522112,8.264476,47.547779,2.092917,0
2,1.233878,1.945651,-0.100828,-2.319923,-0.077900,-0.528188,0.372395,1.056857,-0.105184,-0.560961,...,5.968601,-11.867944,45.292110,-2.479564,-7.836410,-0.522112,8.264476,47.547779,2.092917,0
3,1.233878,1.945651,-0.100828,-2.319923,-0.077900,-0.528188,0.372395,1.056857,-0.105184,-0.560961,...,2.759862,5.177150,-50.398990,-1.671801,4.212849,-36.078353,-5.059797,28.308741,2.838379,1
4,-0.202329,-0.575806,0.774357,1.887819,-0.262787,-1.239196,-1.145158,0.672163,-0.486267,0.581769,...,-0.065966,44.518638,-13.605144,44.615081,13.914512,-7.602587,-1.494154,16.399642,-37.392134,1

All Data features of main dataset:

In [ ]:
import pandas as pd
OneilData = pd.read_csv('/content/drive/MyDrive/MACSynDCR/Data/MFSynDCPData.csv')
MerckOneilDataset = pd.DataFrame(data=OneilData)
#smiles_list=smiles.iloc[:,2]
MerckOneilDataset

,drug1,drug2,cell,label
0,O=c1[nH]cc(F)c(=O)[nH]1,CC1(c2nc3c(C(N)=O)cccc3[nH]2)CCCN1,A375,0
1,O=c1[nH]cc(F)c(=O)[nH]1,CC1(c2nc3c(C(N)=O)cccc3[nH]2)CCCN1,CAOV3,0
2,O=c1[nH]cc(F)c(=O)[nH]1,CC1(c2nc3c(C(N)=O)cccc3[nH]2)CCCN1,HT144,0
3,O=c1[nH]cc(F)c(=O)[nH]1,CC1(c2nc3c(C(N)=O)cccc3[nH]2)CCCN1,HT29,1
4,O=c1[nH]cc(F)c(=O)[nH]1,CC1(c2nc3c(C(N)=O)cccc3[nH]2)CCCN1,LOVO,0
...,...,...,...,...
12410,O=C(CCCCCCC(=O)Nc1ccccc1)NO,CCC1(O)C(=O)OCc2c1cc1n(c2=O)Cc2cc3c(CN(C)C)c(O...,SKOV3,1
12411,O=C(CCCCCCC(=O)Nc1ccccc1)NO,CCC1(O)C(=O)OCc2c1cc1n(c2=O)Cc2cc3c(CN(C)C)c(O...,T47D,1
12412,O=C(CCCCCCC(=O)Nc1ccccc1)NO,CCC1(O)C(=O)OCc2c1cc1n(c2=O)Cc2cc3c(CN(C)C)c(O...,UACC62,1
12413,O=C(CCCCCCC(=O)Nc1ccccc1)NO,CCC1(O)C(=O)OCc2c1cc1n(c2=O)Cc2cc3c(CN(C)C)c(O...,VCAP,1
12414,O=C(CCCCCCC(=O)Nc1ccccc1)NO,CCC1(O)C(=O)OCc2c1cc1n(c2=O)Cc2cc3c(CN(C)C)c(O...,ZR751,1

In [ ]:
import pandas as pd
OneilData = pd.read_csv('/content/drive/MyDrive/MACSynDCR/Data/MFSynDCPData.csv')
MerckOneilDataset = pd.DataFrame(data=OneilData)
ext_smailes =  pd.concat([MerckOneilDataset['drug1'], MerckOneilDataset['drug2']]).unique()
drugs_list = pd.DataFrame(data=ext_smailes)
drugs_list = drugs_list.rename(columns={0: 'SMILES'})
drugs_list=drugs_list['SMILES'].values
drugs_list

array(['O=c1[nH]cc(F)c(=O)[nH]1', 'CC1(c2nc3c(C(N)=O)cccc3[nH]2)CCCN1',
       'C=CCn1c(=O)c2cnc(Nc3ccc(N4CCN(C)CC4)cc3)nc2n1-c1cccc(C(C)(C)O)n1',
       'Cn1c(=O)n(-c2ccc(C(C)(C)C#N)cc2)c2c3cc(-c4cnc5ccccc5c4)ccc3ncc21',
       'CC(C)CC(NC(=O)C(Cc1ccccc1)NC(=O)c1cnccn1)B(O)O',
       'O=P1(N(CCCl)CCCl)NCCCO1',
       'Cc1nc(Nc2ncc(C(=O)Nc3c(C)cccc3Cl)s2)cc(N2CCN(CCO)CC2)n1',
       'CC1CC2C3CCC4=CC(=O)C=CC4(C)C3(F)C(O)CC2(C)C1(O)C(=O)CO',
       'CCc1cnn2c(NCc3ccc[n+]([O-])c3)cc(N3CCCCC3CCO)nc12',
       'COc1cccc2c1C(=O)c1c(O)c3c(c(O)c1C2=O)CC(O)(C(=O)CO)CC3OC1CC(N)C(O)C(C)O1',
       'C#Cc1cccc(Nc2ncnc3cc(OCCOC)c(OCCOC)cc23)c1',
       'COc1cc(C2c3cc4c(cc3C(OC3OC5COC(C)OC5C(O)C3O)C3COC(=O)C23)OCO4)cc(OC)c1O',
       'COC1=C2CC(C)CC(OC)C(O)C(C)C=C(C)C(OC(N)=O)C(OC)C=CC=C(C)C(=O)NC(=CC1=O)C2=O',
       'Nc1ccn(C2OC(CO)C(O)C2(F)F)c(=O)n1',
       'N#Cc1ccc(Cn2cncc2CN2CCN(c3cccc(Cl)c3)C(=O)C2)cc1',
       'CS(=O)(=O)CCNCc1ccc(-c2ccc3ncnc(Nc4ccc(OCc5cccc(F)c5)c(Cl)c4)c3c2)o1',
       'CN(C)C(=N)N=C(N)N',
       'CN(Cc1cnc2nc(N)nc(N)c2n1)c1ccc(C(=O)NC(CCC(=O)O)C(=O)O)cc1',
       'COC12C(COC(N)=O)C3=C(C(=O)C(C)=C(N)C3=O)N1CC1NC12',
       'NC1(c2ccc(-c3nc4ccn5c(=O)[nH]nc5c4cc3-c3ccccc3)cc2)CCC1',
       'CN1C(=O)C=CC2(C)C3CCC4(C)C(NC(=O)OCC(F)(F)F)CCC4C3CCC12',
       'NC(=O)c1cccc2cn(-c3ccc(C4CCCNC4)cc3)nc12',
       'O=C(O)C1(Cc2cccc(Nc3nccs3)n2)CCC(Oc2cccc(Cl)c2F)CC1',
       'COC1CC2CCC(C)C(O)(O2)C(=O)C(=O)N2CCCCC2C(=O)OC(C(C)CC2CCC(OP(C)(C)=O)C(OC)C2)CC(=O)C(C)C=C(C)C(O)C(OC)C(=O)C(C)CC(C)C=CC=CC=C1C',
       'O=S1(=O)NC2(CN1CC(F)(F)F)C1CCC2Cc2cc(C=CCN3CCC(C(F)(F)F)CC3)ccc2C1',
       'CC(=O)OC1C(=O)C2(C)C(O)CC3OCC3(OC(C)=O)C2C(OC(=O)c2ccccc2)C2(O)CC(OC(=O)C(O)C(NC(=O)c3ccccc3)c3ccccc3)C(C)=C1C2(C)C',
       'O=C(NOCC(O)CO)c1ccc(F)c(F)c1Nc1ccc(I)cc1F',
       'CCc1c2c(nc3ccc(O)cc13)-c1cc3c(c(=O)n1C2)COC(=O)C3(O)CC',
       'CNC(=O)c1cc(Oc2ccc(NC(=O)Nc3ccc(Cl)c(C(F)(F)F)c3)cc2)ccn1',
       'CCN(CC)CCNC(=O)c1c(C)[nH]c(C=C2C(=O)Nc3ccc(F)cc32)c1C',
       'Cn1nnc2c(C(N)=O)ncn2c1=O',
       'CCC1(O)C(=O)OCc2c1cc1n(c2=O)Cc2cc3c(CN(C)C)c(O)ccc3nc2-1',
       'CCC1(O)CC2CN(CCc3c([nH]c4ccccc34)C(C(=O)OC)(c3cc4c(cc3OC)N(C)C3C(O)(C(=O)OC)C(OC(C)=O)C5(CC)C=CCN6CCC43C65)C2)C1',
       'CCC1=CC2CN(C1)Cc1c([nH]c3ccccc13)C(C(=O)OC)(c1cc3c(cc1OC)N(C)C1C(O)(C(=O)OC)C(OC(C)=O)C4(CC)C=CCN5CCC31C54)C2',
       'O=C(CCCCCCC(=O)Nc1ccccc1)NO',
       'Cn1cc(-c2cnn3c(N)c(Br)c(C4CCCNC4)nc23)cn1'], dtype=object)

In [ ]:
import pandas as pd
gexf = pd.read_csv('/content/drive/MyDrive/MACSynDCR/Data/Cell/vae_expression256.csv')
gexf = pd.DataFrame(data=gexf)
cell_id=gexf.iloc[:,0]
gexf=gexf.iloc[:,1:]
gexf256=gexf.to_numpy()
gexf256.shape
cell_id=cell_id.values
cell_id

array(['A2058', 'A2780', 'A375', 'A427', 'CAOV3', 'COLO320DM', 'DLD1',
       'EFM192B', 'ES2', 'HCT116', 'HT144', 'HT29', 'KPL1', 'LNCAP',
       'LOVO', 'MDAMB436', 'MSTO', 'NCIH1650', 'NCIH2122', 'NCIH23',
       'NCIH460', 'NCIH520', 'OCUBM', 'OV90', 'OVCAR3', 'PA1', 'RKO',
       'RPMI7951', 'SKMEL30', 'SKMES1', 'SKOV3', 'SW620', 'SW837', 'T47D',
       'UACC62', 'UWB1289', 'UWB1289BRCA1', 'VCAP', 'ZR751'], dtype=object)

In [ ]:
# @title
synclass=[]
syn=MerckOneilDataset.iloc[:,3]
for s in syn:
  if s>=20:
    synclass.append(1)
  elif s<=-10:
    synclass.append(0)
  else:
    synclass.append(3)

MerckOneilDataset['SynClass'] = synclass

MerckOneilData = MerckOneilDataset[MerckOneilDataset["SynClass"]<2]
sdata=MerckOneilData["synergy"]

MerckOneilData.to_csv('/content/drive/MyDrive/MACSynDCR/Data/For_ext_MerckOneilDataSet_-10to20.csv')
MerckOneilData['SynClass'].value_counts()

KeyError: 'synergy'

In [ ]:
import pandas as pd
MACSynDCRP_dataset_m10to20 = pd.read_csv('/content/drive/MyDrive/MACSynDCR/Data/MerckOneilDataSet_-10to20.csv')
MACSynDCRP_dataset_m10to20 = pd.DataFrame(data=MACSynDCRP_dataset_m10to20.iloc[:,2:])
#smiles_list=smiles.iloc[:,2:]

print(MACSynDCRP_dataset_m10to20['SynClass'].value_counts())
MACSynDCRP_dataset_m10to20

SynClass
0    3948
1    3926
Name: count, dtype: int64

       drug_a_name drug_b_name  cell_line    synergy  fold  SynClass
0             5-FU     ABT-888       OV90 -10.068848     2         0
1             5-FU     ABT-888    SKMEL30 -36.459230     2         0
2             5-FU     ABT-888      SW837 -14.523109     2         0
3             5-FU     AZD1775      CAOV3  23.986180     1         1
4             5-FU     AZD1775   MDAMB436  23.381134     1         1
...            ...         ...        ...        ...   ...       ...
7869  TEMOZOLOMIDE     MK-8776       A427  91.060814     0         1
7870  TEMOZOLOMIDE     MK-8776  COLO320DM  50.726450     0         1
7871  TEMOZOLOMIDE     MK-8776   NCIH2122 -19.664582     0         0
7872  TEMOZOLOMIDE     MK-8776     NCIH23 -78.890630     0         0
7873  TEMOZOLOMIDE     MK-8776      SW620  36.645317     0         1

[7874 rows x 6 columns]

In [ ]:
cell_id

array(['A2058', 'A2780', 'A375', 'A427', 'CAOV3', 'COLO320DM', 'DLD1',
       'EFM192B', 'ES2', 'HCT116', 'HT144', 'HT29', 'KPL1', 'LNCAP',
       'LOVO', 'MDAMB436', 'MSTO', 'NCIH1650', 'NCIH2122', 'NCIH23',
       'NCIH460', 'NCIH520', 'OCUBM', 'OV90', 'OVCAR3', 'PA1', 'RKO',
       'RPMI7951', 'SKMEL30', 'SKMES1', 'SKOV3', 'SW620', 'SW837', 'T47D',
       'UACC62', 'UWB1289', 'UWB1289BRCA1', 'VCAP', 'ZR751'], dtype=object)

In [ ]:
#print(MerckData.head())
ldata=MerckOneilDataset.iloc[:,3]
print(len(ldata))

12415

In [ ]:
# @title
import numpy as np
inputData=[]
ydata=[]
no_samples=MerckOneilDataset.shape[0]
print('No of samples = '+str(no_samples))

for i in range(no_samples):
    sm1 = MerckOneilDataset.iloc[i,0]
    did1 = int(np.where(drugs_list == sm1)[0][0])
    sm2 = MerckOneilDataset.iloc[i,1]
    did2 = int(np.where(drugs_list == sm2)[0][0])
    cell_name = MerckOneilDataset.iloc[i,2]
    cid = int(np.where(cell_id == cell_name)[0][0])
    #print(sm1, sm2, cell_name)
#LapMGAN
    #drug(smilesf+fpf+descf+dmgf)
    ddif=DDI_features_128(sm1,sm2)
    dtif1=DTI_feature_128(sm1,cell_name)
    dtif2=DTI_feature_128(sm2,cell_name)
    input=np.concatenate((drug_LapMGAN128[did1],smilesf128[did1],fpf128[did1],dmgf128[did1],drug_LapMGAN128[did2],smilesf128[did2],fpf128[did2],dmgf128[did2],
                          gexf256[cid],ddif,dtif1, dtif2))
    inputData.append(input)
    ydata.append(ldata.iloc[i])
    if i%1000==0:
      print(i)
      print(len(inputData), inputData[0].shape)
#print(len(inputData), inputData[0].shape)

No of samples = 12415
0
1 (1664,)
1000
1001 (1664,)
2000
2001 (1664,)
3000
3001 (1664,)
4000
4001 (1664,)
5000
5001 (1664,)
6000
6001 (1664,)
7000
7001 (1664,)
8000
8001 (1664,)
9000
9001 (1664,)
10000
10001 (1664,)
11000
11001 (1664,)
12000
12001 (1664,)

In [ ]:
TranData_Ind_AstraZeneca_dataset_1664=pd.DataFrame(inputData)
TranData_Ind_AstraZeneca_dataset_1664['synargy']=ydata
TranData_Ind_AstraZeneca_dataset_1664.to_csv('/content/drive/MyDrive/MACSynDCR/Data/TranData_Ind_AstraZeneca_dataset_1664.csv')
TranData_Ind_AstraZeneca_dataset_1664.head()

,0,1,2,3,4,5,6,7,8,9,...,1655,1656,1657,1658,1659,1660,1661,1662,1663,synargy
0,0.994045,0.597168,-0.199996,1.945391,-0.248211,1.269142,1.268025,2.000856,-1.323158,-1.566102,...,0.161935,0.034286,0.176211,-0.080044,-0.885309,-0.023619,-0.683120,-0.111145,-0.385641,0
1,0.994045,0.597168,-0.199996,1.945391,-0.248211,1.269142,1.268025,2.000856,-1.323158,-1.566102,...,0.165626,-0.067435,0.152165,0.022673,-0.727925,0.163845,-0.701209,0.080128,-0.114653,0
2,0.994045,0.597168,-0.199996,1.945391,-0.248211,1.269142,1.268025,2.000856,-1.323158,-1.566102,...,0.186940,-0.100596,0.207191,0.047981,-0.742398,-0.491363,-0.823381,0.022369,-0.246391,0
3,0.994045,0.597168,-0.199996,1.945391,-0.248211,1.269142,1.268025,2.000856,-1.323158,-1.566102,...,0.109241,-0.018325,0.122122,-0.088350,-0.652033,0.142729,-0.801685,0.170408,-0.371853,1
4,0.994045,0.597168,-0.199996,1.945391,-0.248211,1.269142,1.268025,2.000856,-1.323158,-1.566102,...,0.180257,-0.029033,0.015621,0.069532,-0.755719,0.025639,-0.703953,0.085341,-0.418744,0

# MACSynDCR Models:

In [ ]:
num_epochs=200
learning_rate=0.0005

In [ ]:
import numpy as np
import pandas as pd
import csv
import glob
import matplotlib.pyplot as plt
import tensorflow as tf
from sklearn import preprocessing
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import MinMaxScaler
from collections import Counter
from sklearn.model_selection import train_test_split
from tensorflow.keras.utils import to_categorical

import keras
from keras import backend as K

from tensorflow.keras.layers import Input
from tensorflow.keras.models import Sequential,Model
from keras.layers import Dense, LSTM, Dropout, GRU, Bidirectional, Flatten, LSTM, Bidirectional
from keras.layers import Conv2D, MaxPooling2D, BatchNormalization
# from tensorflow.keras.layers import BatchNormalization
#from keras.layers.advanced_activations import LeakyReLU
from keras.layers import ELU, PReLU, LeakyReLU
from tensorflow.keras.optimizers import RMSprop,Adam, SGD
import tensorflow as tf
from sklearn.utils import class_weight
#from keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.callbacks import ModelCheckpoint
from sklearn.model_selection import train_test_split

import numpy as np
from sklearn.model_selection import KFold
from sklearn.metrics import roc_auc_score, accuracy_score, precision_score, recall_score, f1_score, mean_squared_error
from sklearn.metrics import average_precision_score
from scipy.stats import pearsonr
import tensorflow as tf
from tensorflow.keras import layers, models
import torch
import torch.nn as nn
from keras.models import load_model

import argparse
import os
import time
import pickle
import logging


import numpy as np
import pandas as pd
import csv
import glob
import tensorflow as tf
from sklearn import preprocessing
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import MinMaxScaler
from collections import Counter
from sklearn.model_selection import train_test_split
from tensorflow.keras.utils import to_categorical

import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score,auc,roc_auc_score,precision_recall_curve,mean_squared_error
import numpy as np
import pandas as pd
import json
import random
from torchsummary import summary
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    roc_auc_score,
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    average_precision_score,
    auc,
    precision_recall_curve,
    mean_squared_error
)
loss_func = nn.MSELoss(reduction='sum')

import warnings
warnings.filterwarnings("ignore")


from datetime import datetime

import numpy as np
from sklearn.preprocessing import normalize
def to01(array):
    a = array.min()
    # ignore the Runtime Warning
    with np.errstate(divide='ignore'):
        b = 1. /(array.max() - array.min())
    if not(np.isfinite(b)):
        b = 0
    return np.vectorize(lambda x: b * (x - a))(array)



# Py Torch ANN
class MACSynDCR_ANN(nn.Module):
    def __init__(self):
        super(MACSynDCR_ANN, self).__init__()
        self.fc1 = nn.Linear(2432, 1024)
        self.bn1 = nn.BatchNorm1d(1024)
        #self.fc2 = nn.Linear(2048, 1024)
        #self.bn2 = nn.BatchNorm1d(1024)
        self.fc3 = nn.Linear(1024, 512)
        self.bn3 = nn.BatchNorm1d(512)
        self.fc4 = nn.Linear(512, 256)
        self.bn4 = nn.BatchNorm1d(256)
        self.fc5 = nn.Linear(256, 64)
        self.bn5 = nn.BatchNorm1d(64)
        self.fc6 = nn.Linear(64, 2)

    def forward(self, x):
        x = nn.ReLU()(self.bn1(self.fc1(x)))
        #x = nn.ReLU()(self.bn2(self.fc2(x)))
        x = nn.ReLU()(self.bn3(self.fc3(x)))
        x = nn.ReLU()(self.bn4(self.fc4(x)))
        x = nn.ReLU()(self.bn5(self.fc5(x)))
        x = F.softmax(self.fc6(x), dim=1)  # Softmax for output layer
        return x


class MACSynDCR_CNN(nn.Module):
    def __init__(self):
        super(MACSynDCR_CNN, self).__init__()
        self.conv1 = nn.Conv2d(in_channels=1, out_channels=16, kernel_size=(3, 3), padding=1)
        self.conv2 = nn.Conv2d(in_channels=16, out_channels=32, kernel_size=(3, 3), padding=1)
        self.fc1 = nn.Linear(32 * 68 * 32, 128)  # Adjusted for output shape of conv layers
        self.fc2 = nn.Linear(128, 1)  # Binary output
        self.relu = nn.ReLU()
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
        x = x.unsqueeze(1)  # Add channel dimension
        x = self.relu(self.conv1(x))
        x = self.relu(self.conv2(x))
        x = x.view(x.size(0), -1)  # Flatten
        x = self.relu(self.fc1(x))
        x = self.sigmoid(self.fc2(x))
        return x


#Keras ANN
def MACSynDCR_ANN_model2():
    model = keras.Sequential([
        layers.Input(shape=(2432,)),
        layers.Dense(1024, activation='relu'),
        layers.BatchNormalization(),
        layers.Dense(512, activation='relu'),
        layers.BatchNormalization(),
        layers.Dense(256, activation='relu'),
        layers.BatchNormalization(),
        layers.Dense(1, activation='sigmoid')
    ])
    model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy', 'AUC'])
    print("MACSynDCR_ANN model:")
    model.summary()
    return model

def MACSynDCR_ANN_model():
    model = keras.Sequential([
        layers.Input(shape=(2432,)),
        layers.Dense(2048, activation='relu'),
        layers.BatchNormalization(),
        layers.Dense(1024, activation='relu'),
        layers.BatchNormalization(),
        layers.Dense(512, activation='relu'),
        layers.BatchNormalization(),
        layers.Dense(256, activation='relu'),
        layers.BatchNormalization(),
        layers.Dense(128, activation='relu'),
        layers.BatchNormalization(),
        layers.Dense(2, activation='softmax')
    ])
    #model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy', 'AUC'])
    print("MACSynDCR_ANN model:")
    model.summary()
    return model

#Keras CNN
def MACSynDCR_CNN_model():
    model1 = Sequential()
    model1.add(Conv2D(32, (3, 3), input_shape = (64,38,1), activation='relu'))
    model1.add(MaxPooling2D(pool_size = (2, 2)))
    model1.add(Dropout(0.2))
    model1.add(Conv2D(64, (3, 3), activation='relu'))
    model1.add(MaxPooling2D(pool_size = (2, 2)))
    model1.add(Dropout(0.2))
    model1.add(Conv2D(128, (3, 3), activation='relu'))
    model1.add(MaxPooling2D(pool_size = (2, 2)))
    model1.add(Dropout(0.2))
    model1.add(Flatten())
    model1.add(Dense(128, activation = 'relu'))
    model1.add(Dense(2, activation = 'softmax'))

    print("MACSynDCR_CNN model:")
    model1.summary()
    return model1






def Ensemble_MACSynDCR_model2(ann_preds, cnn_preds,y_test):
    #ensemble_pred=np.array(preds).T
    print(ensemble_pred)
    summed = np.sum(ensemble_pred, axis=0)
    # argmax across classes
    mean_pred = np.mean(ensemble_pred, axis=1)
    #ensemble=[]
    j=0
    #for i in 1:
     #   ensemble.append(ensemble_pred[j,i])
     #   j=j+1
    ensemble=mean_pred
    print(ensemble)
    ensemble = (ensemble > 0.5).astype(int)
    ensemble_pred = (ensemble_pred > 0.5).astype(int)
    accuracy1 = accuracy_score(y_test, ensemble_pred[:,0])
    accuracy2 = accuracy_score(y_test, ensemble_pred[:,1])
    #accuracy3 = accuracy_score(y_test, ensemble_pred[:,2])
    #accuracy4 = accuracy_score(y_test, ensemble_pred[:,3])
    #accuracy5 = accuracy_score(y_test, ensemble_pred[:,4])
    ensemble_accuracy = accuracy_score(y_test, ensemble)

    print('Accuracy Score for Ensemble = ', accuracy1)
    print('Accuracy Score for LSTM = ', accuracy2)
    #print('Accuracy Score for LSTM = ', accuracy3)
    #print('Accuracy Score for LSTM = ', accuracy4)
    #print('Accuracy Score for GRU = ', accuracy5)
    print('Accuracy Score for ensemble = ', ensemble_accuracy)

    #Weighted average ensemble
    weights = [0.5, 0.3, 0.2]

    #Use tensordot to sum the products of all elements over specified axes.
    weighted_preds = np.tensordot(ensemble_pred, weights, axes=((0),(0)))
    weighted_ensemble_prediction = np.argmax(weighted_preds, axis=1)

    weighted_accuracy = accuracy_score(y_test, weighted_ensemble_prediction)

    print('Accuracy Score for model1 = ', accuracy1)
    print('Accuracy Score for model2 = ', accuracy2)
    #print('Accuracy Score for model3 = ', accuracy3)
    print('Accuracy Score for average ensemble = ', ensemble_accuracy)
    print('Accuracy Score for weighted average ensemble = ', weighted_accuracy)

    import pandas as pd
    df = pd.DataFrame([])

    for w1 in range(0, 5):
      #  for w2 in range(0,5):
            for w2 in range(0,5):
                wts = [w1/10.,w2/10.]
                wted_preds1 = np.tensordot(ensemble_pred, wts, axes=((0),(0)))
                wted_ensemble_pred = np.argmax(wted_preds1, axis=1)
                weighted_accuracy = accuracy_score(y_test, wted_ensemble_pred)
                df = pd.concat([df,pd.DataFrame({'wt1':wts[0],'wt2':wts[1],
                                             'acc':weighted_accuracy*100}, index=[0])], ignore_index=True)

                #df = pd.concat([df, pd.DataFrame([new_row])], ignore_index=True)

    max_acc_row = df.iloc[df['acc'].idxmax()]
    print("Max accuracy of ", max_acc_row[0], " obained with w1=", max_acc_row[1],
          " w2=", max_acc_row[2])

    max(df['acc'])

    return ensemble

def Ensemble_MACSynDCR_model(train_pred,ann_preds,kann_preds, kcnn_preds,train_labels,y_test, fold):
    # Prepare features for stacking
    tann_preds=train_pred[0]
    tkann_preds=train_pred[1][:,1]
    tkcnn_preds=train_pred[2][:,1]

    ann_auc = roc_auc_score(y_test, ann_preds)
    ann_accuracy = accuracy_score(y_test, (ann_preds > 0.5).astype(int))
    print(f'Accuracy Score and AUC for ANN = AUC: {ann_auc:.4f}, Accuracy: {ann_accuracy:.4f}')

    kann_auc = roc_auc_score(y_test, kann_preds)
    kann_accuracy = accuracy_score(y_test, (kann_preds > 0.5).astype(int))
    print(f'Accuracy Score and AUC for KANN = AUC: {kann_auc:.4f}, Accuracy: {kann_accuracy:.4f}')

    kcnn_auc = roc_auc_score(y_test, kcnn_preds)
    kcnn_accuracy = accuracy_score(y_test, (kcnn_preds> 0.5).astype(int))
    print(f'Accuracy Score and AUC for KCNN = AUC: {kcnn_auc:.4f}, Accuracy: {kcnn_accuracy:.4f}')


    #stacked_X = np.column_stack((ann_preds,kann_preds, kcnn_preds))
    train_X = np.column_stack((tann_preds,tkann_preds, tkcnn_preds))
    test_X = np.column_stack((ann_preds,kann_preds,kann_preds))
    print(train_X.shape, type(test_X.shape))

    avg_pred=np.mean(test_X, axis=1)
    #mean_pred = np.mean(ensemble_pred, axis=1)
    max_pred=np.max(test_X, axis=1)
    avg_auc = roc_auc_score(y_test, avg_pred)
    avg_accuracy = accuracy_score(y_test, (avg_pred > 0.5).astype(int))
    print(f'Average AUC = AUC: {avg_auc:.4f}, Accuracy: {avg_accuracy:.4f}')

    max_auc = roc_auc_score(y_test, max_pred)
    max_accuracy = accuracy_score(y_test, (max_pred > 0.5).astype(int))
    print(f'MAX AUC = AUC: {max_auc:.4f}, Accuracy: {max_accuracy:.4f}')



    from sklearn.model_selection import GridSearchCV
    from sklearn.ensemble import RandomForestClassifier

    rf_model = RandomForestClassifier(random_state=42)
    param_grid = {
       'n_estimators': [50, 200],
       'max_depth': [None, 10, 30],
       'min_samples_split': [2, 10],
       'min_samples_leaf': [1, 4],
    }

    #grid_search = GridSearchCV(estimator=rf_model, param_grid=param_grid,
                              # scoring='accuracy', cv=3, verbose=0, n_jobs=-1)
    #grid_search.fit(train_X, train_labels)
   # best_rf_model = grid_search.best_estimator_
    #rf_ensemble_prob = best_rf_model.predict_proba(test_X)[:, 1]


    #{'C': [0.01, 0.1, 1, 10, 100]
    param_grid = {'C': [0.01,0.1, 1, 10,100], 'penalty': ['l1', 'l2']}
    grid_search = GridSearchCV(LogisticRegression(), param_grid, cv=5)
    grid_search.fit(train_X, train_labels)
    best_model = grid_search.best_estimator_
    #meta_model = LogisticRegression()
    #meta_model.fit(stacked_X, y_test)
    lr_ensemble_prob = best_model.predict_proba(test_X)[:,1]

    #rf_accuracy = accuracy_score(y_test, (rf_ensemble_prob> 0.5).astype(int))
    lr_accuracy = accuracy_score(y_test, (lr_ensemble_prob> 0.5).astype(int))
    if 0>=lr_accuracy:
        ensemble_prob=rf_ensemble_prob
        ensemble_pred=(ensemble_prob > 0.5).astype(int)
    else:
        ensemble_prob=lr_ensemble_prob
        ensemble_pred=(ensemble_prob > 0.5).astype(int)

    print(f"Finall ensemble results of fold_{fold+1} for MACSynDCR:")
    logging.info(f"Finall ensemble results of fold_{fold+1} for MACSynDCR:")
    logging.info("-" * 100)
    print("-" * 100)
    auc = roc_auc_score(y_test, ensemble_prob)
    accuracy = accuracy_score(y_test, ensemble_pred)
    auc_pr = average_precision_score(y_test,ensemble_prob)
    precision = precision_score(y_test, ensemble_pred)
    recall = recall_score(y_test, ensemble_pred)
    f1 = f1_score(y_test, ensemble_pred)
    yp=torch.tensor(ensemble_pred.astype(float))
    rmse = np.sqrt(loss_func(y_test.float(), yp))
    #rmse = np.sqrt(mean_squared_error(y_test, y_pred))
    pcc, _ = pearsonr(y_test, ensemble_prob)

    print(f'Ensemble Accuracy: {accuracy:.4f}, AUC-ROC: {auc:.4f} \nEnsemble AUC-PR: {auc_pr:.4f}, Precision: {precision:.4f}, \nEnsemble Recall: {recall:.4f}, F1 Score: {f1:.4f}')
    print(f'Ensemble RMSE: {rmse:.4f} , PCC: {pcc:.4f}')
    logging.info(f'Ensemble Accuracy: {accuracy:.4f}, AUC-ROC: {auc:.4f}, \nEnsemble AUC-PR: {auc_pr:.4f}, Precision: {precision:.4f}, \nEnsemble Recall: {recall:.4f}, F1 Score: {f1:.4f}, \nEnsemble RMSE: {rmse:.4f}')

    logging.info("-" * 100)
    print("-" * 100)
    return ensemble_pred, auc, accuracy, auc_pr, f1, precision, recall, rmse, pcc


def Ensemble_MACSynDCR_model3(train_pred,ann_preds,kann_preds, kcnn_preds,train_labels,y_test, fold):
    # Prepare features for stacking
    tann_preds=train_pred[0]
    tkann_preds=train_pred[1][:,1]
    tkcnn_preds=train_pred[2][:,1]
    ann_auc = roc_auc_score(y_test, ann_preds)
    ann_accuracy = accuracy_score(y_test, (ann_preds.numpy() > 0.5).astype(int))
    print(f'Accuracy Score and AUC for ANN = AUC: {ann_auc:.4f}, Accuracy: {ann_accuracy:.4f}')

    kann_auc = roc_auc_score(y_test, kann_preds)
    kann_accuracy = accuracy_score(y_test, (kann_preds > 0.5).astype(int))
    print(f'Accuracy Score and AUC for KANN = AUC: {kann_auc:.4f}, Accuracy: {kann_accuracy:.4f}')

    kcnn_auc = roc_auc_score(y_test, kcnn_preds)
    kcnn_accuracy = accuracy_score(y_test, (kcnn_preds> 0.5).astype(int))
    print(f'Accuracy Score and AUC for KCNN = AUC: {kcnn_auc:.4f}, Accuracy: {kcnn_accuracy:.4f}')


    #stacked_X = np.column_stack((ann_preds,kann_preds, kcnn_preds))
    train_X = np.column_stack((tann_preds,tkann_preds, tkcnn_preds))
    test_X = np.column_stack((ann_preds,kann_preds, kcnn_preds))

    print(train_X.shape, test_X.shape)


    from sklearn.model_selection import GridSearchCV
    from sklearn.ensemble import RandomForestClassifier

    rf_model = RandomForestClassifier(random_state=42)
    param_grid = {
       'n_estimators': [50, 200],
       'max_depth': [None, 10, 30],
       'min_samples_split': [2, 10],
       'min_samples_leaf': [1, 4],
    }

    grid_search = GridSearchCV(estimator=rf_model, param_grid=param_grid,
                               scoring='accuracy', cv=3, verbose=0, n_jobs=-1)
    grid_search.fit(train_X, train_labels)
    best_rf_model = grid_search.best_estimator_
    rf_ensemble_prob = best_rf_model.predict_proba(test_X)[:, 1]


    #{'C': [0.01, 0.1, 1, 10, 100]
    param_grid = {'C': [0.01, 1, 100], 'penalty': ['l1', 'l2']}
    grid_search = GridSearchCV(LogisticRegression(), param_grid, cv=3)
    grid_search.fit(train_X, train_labels)
    best_model = grid_search.best_estimator_
    #meta_model = LogisticRegression()
    #meta_model.fit(stacked_X, y_test)
    lr_ensemble_prob = best_model.predict_proba(test_X)[:, 1]

    rf_accuracy = accuracy_score(y_test, (rf_ensemble_prob> 0.5).astype(int))
    lr_accuracy = accuracy_score(y_test, (lr_ensemble_prob> 0.5).astype(int))
    if rf_accuracy>=lr_accuracy:
        ensemble_prob=rf_ensemble_prob
        ensemble_pred=(ensemble_prob > 0.5).astype(int)
    else:
        ensemble_prob=lr_ensemble_prob
        ensemble_pred=(ensemble_prob > 0.5).astype(int)

    print(f"Finall ensemble results of fold_{fold+1} for MACSynDCR:")
    logging.info(f"Finall ensemble results of fold_{fold+1} for MACSynDCR:")
    logging.info("-" * 100)
    print("-" * 100)
    auc = roc_auc_score(y_test, ensemble_prob)
    accuracy = accuracy_score(y_test, ensemble_pred)
    auc_pr = average_precision_score(y_test,ensemble_prob)
    precision = precision_score(y_test, ensemble_pred)
    recall = recall_score(y_test, ensemble_pred)
    f1 = f1_score(y_test, ensemble_pred)
    yp=torch.tensor(ensemble_pred.astype(float))
    rmse = np.sqrt(loss_func(y_test.float(), yp))
    #rmse = np.sqrt(mean_squared_error(y_test, y_pred))
    pcc, _ = pearsonr(y_test, ensemble_prob)

    print(f'Ensemble Accuracy: {accuracy:.4f}, AUC-ROC: {auc:.4f} \nEnsemble AUC-PR: {auc_pr:.4f}, Precision: {precision:.4f}, \nEnsemble Recall: {recall:.4f}, F1 Score: {f1:.4f}')
    print(f'Ensemble RMSE: {rmse:.4f} , PCC: {pcc:.4f}')
    logging.info(f'Ensemble Accuracy: {accuracy:.4f}, AUC-ROC: {auc:.4f}, \nEnsemble AUC-PR: {auc_pr:.4f}, Precision: {precision:.4f}, \nEnsemble Recall: {recall:.4f}, F1 Score: {f1:.4f}, \nEnsemble RMSE: {rmse:.4f}')

    logging.info("-" * 100)
    print("-" * 100)
    return ensemble_pred, auc, accuracy, auc_pr, f1, precision, recall, rmse, pcc

# MACSynDCR Training:

In [ ]:
import numpy as np
import pandas as pd
import argparse
import os
import time
import pickle
import logging
import csv
import glob
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf
from sklearn import preprocessing
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import MinMaxScaler
from collections import Counter
from sklearn.model_selection import train_test_split
from tensorflow.keras.utils import to_categorical

import keras
from keras import backend as K

from tensorflow.keras.layers import Input
from tensorflow.keras.models import Sequential,Model
from keras.layers import Dense, LSTM, Dropout, GRU, Bidirectional, Flatten, LSTM, Bidirectional
from keras.layers import Conv2D, MaxPooling2D, BatchNormalization
# from tensorflow.keras.layers import BatchNormalization
#from keras.layers.advanced_activations import LeakyReLU
from keras.layers import ELU, PReLU, LeakyReLU
from tensorflow.keras.optimizers import RMSprop,Adam, SGD
from keras.models import load_model


import tensorflow as tf
from sklearn.utils import class_weight
#from keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.callbacks import ModelCheckpoint
from sklearn.model_selection import train_test_split

import numpy as np
from sklearn.model_selection import KFold
from sklearn.metrics import roc_auc_score, accuracy_score, precision_score, recall_score, f1_score, mean_squared_error
from sklearn.metrics import average_precision_score
from scipy.stats import pearsonr
import tensorflow as tf
from tensorflow.keras import layers, models
import torch
import torch.nn as nn

from sklearn import preprocessing
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import MinMaxScaler
from collections import Counter
from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold
from sklearn.metrics import (
    roc_auc_score,
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    average_precision_score,
    auc,
    precision_recall_curve,
    mean_squared_error
)


import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset






import warnings
warnings.filterwarnings("ignore")


from datetime import datetime

def calc_stat(numbers):
    mu = sum(numbers) / len(numbers)
    sigma = (sum([(x - mu) ** 2 for x in numbers]) / len(numbers)) ** 0.5
    return mu, sigma

def save_args(args, save_to: str):
    args_dict = args.__dict__
    with open(save_to, 'w') as f:
        json.dump(args_dict, f, indent=2)


OUTPUT_DIR = 'output'
if not os.path.exists(OUTPUT_DIR):
    os.makedirs(OUTPUT_DIR)

n_delimiter = 100

import numpy as np
from sklearn.preprocessing import normalize
def to01(array):
    a = array.min()
    # ignore the Runtime Warning
    with np.errstate(divide='ignore'):
        b = 1. /(array.max() - array.min())
    if not(np.isfinite(b)):
        b = 0
    return np.vectorize(lambda x: b * (x - a))(array)



loss_func = nn.MSELoss(reduction='sum')

def Train_MACSynDCR_ANN(train_data, train_labels,val_data,val_labels, fold,ind_test):
        print("Data processing and Training of MACSynDCR_ANN model:")



        scaler = MinMaxScaler()
        train_data = scaler.fit_transform(train_data)
        val_data = scaler.fit_transform(val_data)
        ind_test = scaler.fit_transform(ind_test)

        train_data=torch.tensor(train_data).float()
        val_data=torch.tensor(val_data).float()
        ind_test=torch.tensor(ind_test).float()

        #label encoding y_train
        testy=val_labels
        label_encoder = preprocessing.LabelEncoder()
        y_train = label_encoder.fit_transform(train_labels)
        y_test = label_encoder.fit_transform(val_labels)



        y_test_cat = to_categorical(y_test,  num_classes = 2)
        y_train_cat = to_categorical(y_train, num_classes = 2)
        #print(y_test_cat.shape, y_train_cat.shape)

        model=MACSynDCR_ANN()
        optimizer = optim.Adam(model.parameters(), lr=learning_rate)
        criterion = nn.CrossEntropyLoss()

        #MSE loss
        loss_func = nn.MSELoss(reduction='sum')
        savefile="yes"
        model.train()
        best_val_acc=0.0
        for epoch in range(num_epochs):
            optimizer.zero_grad()
            outputs = model(train_data)#.detach().numpy()  # Ensure correct shape
            #print(outputs, outputs.shape)
            #v=np.argmax(outputs,axis=1).astype(float)
            #t=torch.FloatTensor(v)
            loss = criterion(outputs, train_labels.long())
            #trmse = np.sqrt(mean_squared_error(train_labels.float(), outputs.detach().numpy()))
            val_outputs = model(val_data).detach().numpy()
            val_predictions = np.argmax(val_outputs,axis=1)
            accuracy = accuracy_score(val_labels, val_predictions)
            AUC = roc_auc_score(val_labels, val_outputs[:,1])

            if accuracy > best_val_acc:
                best_preds=0.0
                best_val_acc = accuracy
                best_preds=val_outputs[:,1]
                #print(best_preds)
                train_preds=0.0
                train_pr= model(train_data).detach().numpy()
                train_preds=train_pr[:,1]

                ipreds=0.0
                i_pr= model(ind_test).detach().numpy()
                ipreds=i_pr[:,1]

                #best_model = model.state_dict()
                #torch.save(best_model, f'best_model_fold_{fold + 1}.pt')
                torch.save(model, f'/content/drive/MyDrive/MACSynDCR/saveModel/bestTANN_fold_{fold + 1}.h5')
                #torch.save(model, f'ANN_model_fold_{fold + 1}_ACC_{accuracy:.5f}_AUC_{AUC:.5f}.h5')
                #logging.info(f"ANN_model saved with Val_ACC: {accuracy:.4f}")
                print(f"ANN_model saved with Val_ACC: {accuracy:.4f} Val_AUC: {AUC:.4f}")
                logging.info("-" * n_delimiter)
                if savefile!="yes":
                    os.remove(savefile)
                #savefile=f'ANN_model_fold_{fold + 1}_ACC_{accuracy:.5f}_AUC_{AUC:.5f}.h5'

            loss.backward()
            optimizer.step()
            if (epoch%20)==0:
                print(f'fold_{fold+1}: Epoch [{epoch + 1}/{num_epochs}], Loss: {loss.item():.4f}, Val_ACC: {accuracy:.4f}, Val_AUC: {AUC:.4f}')
                logging.info(f'fold_{fold+1}: Epoch [{epoch + 1}/{num_epochs}], Loss: {loss.item():.4f}, ACC: {accuracy:.4f}, AUC: {AUC:.4f}')
        return model, best_preds,train_preds,ipreds






def Train_MACSynDCR_CNN(X,y,val_data,val_labels,fold):
    print("Data processing and Training of MACSynDCR_CNN model:")
    batch_size = 128
    #lr=0.001
    #num_epochs=100

    X_train_tensor = torch.tensor(X, dtype=torch.float32)
    y_train_tensor = torch.tensor(y, dtype=torch.float32)
    X_train_tensor=X_train_tensor.reshape(-1,64,38)

    val_data = torch.tensor(val_data, dtype=torch.float32)
    val_labels = torch.tensor(val_labels, dtype=torch.float32)
    val_data=val_data.reshape(-1,64,38)

   # print(X_train_tensor.shape)
    train_dataset = TensorDataset(X_train_tensor, y_train_tensor)
    train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)

    model = MACSynDCR_CNN()
    criterion = nn.BCELoss()
    optimizer = optim.Adam(model.parameters(), lr=lr)
    model.train()
    best_val_acc=0.0
    savefile="yes"
    for epoch in range(num_epochs):
        for inputs, labels in train_loader:
            optimizer.zero_grad()
            outputs = model(inputs)
            loss = criterion(outputs.view(-1), labels.float())
            loss.backward()
            optimizer.step()
        #print(f'Epoch [{epoch+1}/{num_epochs}], Loss: {loss.item():.4f}')
        val_outputs = model(val_data).squeeze()
        val_predictions = (val_outputs > 0.5).float()
        accuracy = accuracy_score(val_labels.numpy(), val_predictions.numpy())
        AUC = roc_auc_score(val_labels, val_predictions)
        if accuracy > best_val_acc:
                best_val_acc = accuracy
                #best_model = model.state_dict()
                #torch.save(best_model, f'best_model_fold_{fold + 1}.pt')
                #torch.save(model, f'CNN_model_fold_{fold + 1}_{accuracy:.4f}.h5')
                torch.save(model, f'/content/drive/MyDrive/MACSynDCR/saveModel/CNN_model_fold_{fold + 1}.h5')
                #logging.info(f"CNN_model saved with Val_ACC: {accuracy:.4f}")
                print(f"CNN_model saved with Val_ACC: {accuracy:.4f}")
                logging.info("-" * n_delimiter)
                if savefile!="yes":
                    os.remove(savefile)
                #savefile=f'CNN_model_fold_{fold + 1}_{accuracy:.4f}.h5'
        if epoch%10==0:
            print(f'CNN fold_{fold+1}: Epoch [{epoch + 1}/{num_epochs}], Loss: {loss.item():.4f}, Val ACC: {accuracy:.4f}, , Val AUC: {AUC:.4f}')
            logging.info(f'CNN fold_{fold+1}: Epoch [{epoch + 1}/{num_epochs}], Loss: {loss.item():.4f}, Val ACC: {accuracy:.4f}, ,Val AUC: {AUC:.4f}')

    return model




#Keras models:

def Train_and_Validation_MACSynDCR_ANN(X_train,X_test,y_train,y_test,intTestData):
    print("Data processing and Training of MACSynDCR_ANN model:")
    #num_epochs =epoch
    batch_size = 128
   # learning_rate = 0.001
    #print(X_train.shape)
    #print(X_test.shape)

    scaler = MinMaxScaler()
    x_train = scaler.fit_transform(X_train)
    x_test = scaler.fit_transform(X_test)

    intTestData = scaler.fit_transform(intTestData)



    #label encoding y_train
    testy=y_test
    label_encoder = preprocessing.LabelEncoder()
    y_train = label_encoder.fit_transform(y_train)
    y_test = label_encoder.fit_transform(y_test)

    y_test_cat = to_categorical(y_test,  num_classes = 2)
    y_train_cat = to_categorical(y_train, num_classes = 2)
    #print(y_test_cat.shape, y_train_cat.shape)


    model=MACSynDCR_ANN_model()
    model.save(f'/content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_ANN_model.keras')
    model.compile(loss ='categorical_crossentropy', optimizer='adam',metrics =['acc','auc'])
    checkpoint_ann = ModelCheckpoint(
        '/content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_ANN_model.keras',  # Filepath to save the model
        monitor='val_auc',  # Monitor validation accuracy
        save_best_only=True,  # Save only the best model
        mode='max',  # Maximize the monitored value
        verbose=1)

    os.remove(f'/content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_ANN_model.keras')
    model.fit(x_train, y_train_cat, epochs=num_epochs, batch_size=batch_size,validation_data=(x_test, y_test_cat),callbacks=[checkpoint_ann])
    # Load the Keras model
    ANN = load_model('/content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_ANN_model.keras')
    #model.save('MACSynDCR_ANN_model.hdf5')
    pred = ANN.predict(x_test)
    ann_pred=pred[:,1]
    ann_label=np.argmax(pred,axis=1)
    y_pred_prob=ann_pred
    y_pred=ann_label
    auc = roc_auc_score(y_test_cat, pred)
    accuracy = accuracy_score(y_test, y_pred)
    auc_pr = average_precision_score(y_test_cat,pred)
    precision = precision_score(y_test, y_pred)
    recall = recall_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)
    yp=torch.tensor(y_pred.astype(float))
    rmse = np.sqrt(loss_func(testy.float(), yp))
    #rmse = np.sqrt(mean_squared_error(y_test, y_pred))
    pcc, _ = pearsonr(y_test_cat, pred)

    ipred = ANN.predict(intTestData)
    ann_ipred=ipred[:,1]

    print(f'ANN: Accuracy: {accuracy:.4f}, AUC-ROC: {auc:.4f} \nANN: AUC-PR: {auc_pr:.4f}, Precision: {precision:.4f}, \nANN Recall: {recall:.4f}, F1 Score: {f1:.4f}')
    print(f'\ANN:RMSE: {rmse:.4f} , PCC: {pcc[1]:.4f}')
    return ann_ipred



def Train_and_Validation_MACSynDCR_Ensemble(X_train,X_test,y_train,y_val):
    print("Data processing and Training of MACSynDCR_CNN model:")
    #num_epochs = 200
    batch_size = 128
    #learning_rate = 0.001

    scaler = MinMaxScaler()
    x_train = scaler.fit_transform(X_train)
    x_test = scaler.fit_transform(X_test)

    #intTestData = scaler.fit_transform(intTestData)

    model=Model5()
    history = model.fit(x_train, y_train,
                    validation_data=(x_test, y_val),
                    epochs=num_epochs,
                    batch_size=128)

    X_train = x_train.reshape(-1, 64, 38)
    X_val = x_test.reshape(-1, 64, 38)
    model=MACSynDCR_Hybrid()
    model.compile(loss ='binary_crossentropy', optimizer='adam',metrics =['acc','auc'])
    checkpoint_ensemble = ModelCheckpoint(
        'best_MACSynDCR_Ensemble_model.keras',  # Filepath to save the model
        monitor='val_auc',  # Monitor validation accuracy
        save_best_only=True,  # Save only the best model
        mode='max',  # Maximize the monitored value
        verbose=1)
    history = model.fit(X_train, y_train,
                    validation_data=(X_val, y_val),
                    epochs=num_epochs,
                    batch_size=128,
                    callbacks=[checkpoint_ensemble])

    Ensemble = load_model('best_MACSynDCR_Ensemble_model.keras')
    # Evaluate the model on validation data
    loss, accuracy, AUC = Ensemble.evaluate(X_val, y_val)
    print(f'Evaluate->  Loss: {loss:.4f}, Accuracy: {accuracy:.4f},Accuracy: {AUC:.4f}')

    pred = Ensemble.predict(X_val).flatten()

    print(pred.shape,pred)
    #lstm_pred=pred[:,1]
    #ylabel=np.argmax(pred,axis=1)
    #y_pred_prob=cnn_pred
    #print(type(y_val),type(pred))
    y_test=y_val
    y_pred=(pred> 0.5).astype(int)
    auc = roc_auc_score(y_test, pred)
    accuracy = accuracy_score(y_test, y_pred)
    auc_pr = average_precision_score(y_test,pred)
    precision = precision_score(y_test, y_pred)
    recall = recall_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)
    #rmse = np.sqrt(mean_squared_error(y_test, pred))
    y_test=np.array(y_val).astype(float)
    #print(y_test.shape)
    #print(pred.shape)
    val_outputs = Ensemble.predict(X_val).squeeze()
    val_predictions = (val_outputs > 0.5).astype(float)
    rmse = np.sqrt(loss_func(y_test, val_predictions))

    #rmse = np.sqrt(mean_squared_error(train_labels.float(), outputs.detach().numpy()))

    pcc, _ = pearsonr(y_test, pred)
    #print(f'LSTM2: Accuracy: {accuracy:.4f}, AUC-ROC: {auc:.4f} \nLSTM: AUC-PR: {auc_pr:.4f}, Precision: {precision:.4f}, \nLSTM2 Recall: {recall:.4f}, F1 Score: {f1:.4f},\nLSTM:RMSE: {rmse:.4f} , PCC: {pcc:.4f}')
    #print(f'\nLSTM:RMSE: {rmse:.4f} ')
    with np.printoptions(precision=4, suppress=True):
        print(f'Ensemble: Accuracy: {accuracy}, AUC-ROC: {auc} \nLSTM: AUC-PR: {auc_pr}, Precision: {precision}, \nLSTM2 Recall: {recall}, F1 Score: {f1},\nLSTM:RMSE: {rmse} , PCC: {pcc}')
    return pred, auc, accuracy, auc_pr, f1, precision, recall, rmse, pcc[1]


# For keras


def Train_and_Validation_MACSynDCR_CNN(X_train,X_test,y_train,y_test,intTestData):
    print("Data processing and Training of MACSynDCR_CNN model:")
    #num_epochs = epoch
    batch_size = 128
    #learning_rate = 0.001

    scaler = MinMaxScaler()
    x_train = scaler.fit_transform(X_train)
    x_test = scaler.fit_transform(X_test)
    #print(x_train.shape)
    #print(x_test.shape)
    intTest = scaler.fit_transform(intTestData)

    #label encoding y_train
    testy=y_test
    label_encoder = preprocessing.LabelEncoder()
    y_train = label_encoder.fit_transform(y_train)
    y_test = label_encoder.fit_transform(y_test)

    y_test_cat = to_categorical(y_test,  num_classes = 2)
    y_train_cat = to_categorical(y_train, num_classes = 2)
   # print(y_test_cat.shape, y_train_cat.shape)

    x_train = x_train.reshape(-1, 64, 38,1)
    x_test = x_test.reshape(-1, 64, 38,1)
    model=MACSynDCR_CNN_model()
    model.save(f'/content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_CNN_model.keras')
    model.compile(loss ='categorical_crossentropy', optimizer='adam',metrics =['acc','auc'])
    checkpoint_cnn = ModelCheckpoint(
        '/content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_CNN_model.keras',  # Filepath to save the model
        monitor='val_acc',  # Monitor validation accuracy
        save_best_only=True,  # Save only the best model
        mode='max',  # Maximize the monitored value
        verbose=1)

    os.remove(f'/content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_CNN_model.keras')
    model.fit(x_train, y_train_cat, epochs=num_epochs, batch_size=batch_size,validation_data=(x_test, y_test_cat),callbacks=[checkpoint_cnn])
    # Load the Keras model
    CNN = load_model('/content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_CNN_model.keras')
    #model.save('MACSynDCR_CNN_model.hdf5')
    pred = CNN.predict(x_test)
    #print(pred.shape,pred)
    cnn_pred=pred[:,1]
    cnn_label=np.argmax(pred,axis=1)
    y_pred_prob=cnn_pred
    y_pred=cnn_label
    auc = roc_auc_score(y_test_cat, pred)
    accuracy = accuracy_score(y_test, y_pred)
    auc_pr = average_precision_score(y_test_cat,pred)
    precision = precision_score(y_test, y_pred)
    recall = recall_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)
    yp=torch.tensor(y_pred.astype(float))
    rmse = np.sqrt(loss_func(testy.float(), yp))
    #rmse = np.sqrt(mean_squared_error(y_test, y_pred))
    pcc, _ = pearsonr(y_test_cat, pred)

    intTest = intTest.reshape(-1, 64, 38,1)
    ipred = CNN.predict(intTest)
    #print(pred.shape,pred)
    cnn_ipred=ipred[:,1]

    print(f'CNN: Accuracy: {accuracy:.4f}, AUC-ROC: {auc:.4f} \nCNN: AUC-PR: {auc_pr:.4f}, Precision: {precision:.4f}, \nCNN Recall: {recall:.4f}, F1 Score: {f1:.4f}')
    print(f'CNN:RMSE: {rmse:.4f} , PCC: {pcc[1]:.4f}')
    return cnn_ipred

#MACSynDCR Evaluation

In [ ]:
import argparse
import os
import time
import torch
import torch.nn as nn
import pickle
import logging


import numpy as np
import pandas as pd
import csv
import glob
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf
from sklearn import preprocessing
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import MinMaxScaler
from collections import Counter
from sklearn.model_selection import train_test_split
from tensorflow.keras.utils import to_categorical


from sklearn.utils import class_weight
#from keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.models import Sequential,Model
from keras.layers import Dense, LSTM, Dropout, GRU, Bidirectional, Flatten, LSTM, Bidirectional
import numpy as np
import pandas as pd
import argparse
import os
import time
import pickle
import logging
import csv
import glob
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf
from sklearn import preprocessing
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import MinMaxScaler
from collections import Counter
from sklearn.model_selection import train_test_split
from tensorflow.keras.utils import to_categorical

import keras
from keras import backend as K

from tensorflow.keras.layers import Input
from tensorflow.keras.models import Sequential,Model
from keras.layers import Dense, LSTM, Dropout, GRU, Bidirectional, Flatten, LSTM, Bidirectional
from keras.layers import Conv2D, MaxPooling2D, BatchNormalization
# from tensorflow.keras.layers import BatchNormalization
#from keras.layers.advanced_activations import LeakyReLU
from keras.layers import ELU, PReLU, LeakyReLU
from tensorflow.keras.optimizers import RMSprop,Adam, SGD
from keras.models import load_model


import tensorflow as tf
from sklearn.utils import class_weight
#from keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.callbacks import ModelCheckpoint
from sklearn.model_selection import train_test_split

import torch
import torch.nn as nn
import torch.optim as optim
from sklearn.model_selection import KFold
from sklearn.metrics import (
    roc_auc_score,
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    average_precision_score,
    auc,
    precision_recall_curve,
    mean_squared_error
)
import numpy as np
import pandas as pd

from torch.utils.data import DataLoader, TensorDataset

import torch
import torch.nn as nn
import torch.optim as optim
from scipy.stats import pearsonr

import os
import pickle

import matplotlib.pyplot as plt
import torch
import json
import random



import warnings
warnings.filterwarnings("ignore")


from datetime import datetime

def calc_stat(numbers):
    mu = sum(numbers) / len(numbers)
    sigma = (sum([(x - mu) ** 2 for x in numbers]) / len(numbers)) ** 0.5
    return mu, sigma

def save_args(args, save_to: str):
    args_dict = args.__dict__
    with open(save_to, 'w') as f:
        json.dump(args_dict, f, indent=2)




OUTPUT_DIR = 'output'
if not os.path.exists(OUTPUT_DIR):
    os.makedirs(OUTPUT_DIR)

n_delimiter = 100


#batch_size = 256
#epochs = 500
#num_epochs=5
num_classes = 2



import numpy as np
from sklearn.preprocessing import normalize
def to01(array):
    a = array.min()
    # ignore the Runtime Warning
    with np.errstate(divide='ignore'):
        b = 1. /(array.max() - array.min())
    if not(np.isfinite(b)):
        b = 0
    return np.vectorize(lambda x: b * (x - a))(array)

loss_func = nn.MSELoss(reduction='sum')
def Eval_MACSynDCR_ANN(model, train_data,val_data,val_labels,fold):
    print("Evaluation of MACSynDCR_ANN:")
    logging.info("Evaluation of MACSynDCR_ANN model:")
    logging.info("-" * n_delimiter)
    print("-" * n_delimiter)
    vl=val_labels.float()
    model=torch.load(f'bestTANN_fold_{fold + 1}.h5')
    #model = torch.load(f'bestTANN_fold_{fold + 1}.h5')
    model.eval()
    with torch.no_grad():
            val_outputs = model(val_data).detach().numpy()
            val_predictions = np.argmax(val_outputs,axis=1)
            accuracy = accuracy_score(val_labels, val_predictions)
            AUC = roc_auc_score(val_labels, val_outputs[:,1])

            #val_outputs = model(val_data).squeeze()
            train_outputs = model(train_data).detach().numpy()[:,1]
            #val_predictions = (val_outputs > 0.5).float()
            precision = precision_score(val_labels, val_predictions)
            recall = recall_score(val_labels, val_predictions)
            f1 = f1_score(val_labels, val_predictions)
            #mlp_precision, mlp_recall, _ = precision_recall_curve(val_labels.numpy(), val_predictions.numpy())
            #AUC_PR = auc(mlp_precision, mlp_recall)
            AUC = roc_auc_score(val_labels, val_outputs[:,1])
            #print(val_labels.float(), val_predictions.float())
            #print(val_labels.shape,y_pred.shape)
            p=torch.tensor(val_predictions).float()
            #print(vl,p)
            vrmse = np.sqrt(loss_func(vl.float(),p.float() ))
            AUC_PR = average_precision_score(val_labels, val_outputs[:,1])
            pcc, _ = pearsonr(val_labels.float(), val_outputs[:,1])

            print(f'Accuracy: {accuracy:.4f}, AUC-ROC: {AUC:.4f} \n AUC-PR: {AUC_PR:.4f}, Precision: {precision:.4f}, Recall: {recall:.4f}, F1 Score: {f1:.4f}')
            print(f'\nRMSE: {vrmse:.4f} , PCC: {pcc:.4f}')
            logging.info(f'Accuracy: {accuracy:.4f}, AUC-ROC: {AUC:.4f}, \n AUC-PR: {AUC_PR:.4f}, Precision: {precision:.4f}, Recall: {recall:.4f}, F1 Score: {f1:.4f}, RMSE: {vrmse:.4f}')

    logging.info("-" * n_delimiter)
    print("-" * n_delimiter)
    return val_outputs,train_outputs, AUC, accuracy, AUC_PR, f1, precision, recall, vrmse, pcc



def Eval_MACSynDCR_CNN(model,train_data,val_data,val_labels,fold):
    print("Evaluation of MACSynDCR_CNN:")
    logging.info("Evaluation of MACSynDCR_CNN model:")
    logging.info("-" * n_delimiter)
    print("-" * n_delimiter)
    vl=val_labels.float()
    val_data = torch.tensor(val_data, dtype=torch.float32)
    val_labels = torch.tensor(val_labels, dtype=torch.float32)
    val_data=val_data.reshape(-1,64,38)

    model = torch.load(f'CNN_model_fold_{fold + 1}.h5', weights_only=False)
    model.eval()
    with torch.no_grad():
        val_outputs = model(val_data).squeeze()
        val_predictions = (val_outputs > 0.5).astype(float)
        accuracy = accuracy_score(val_labels.numpy(), val_predictions.numpy())
        precision = precision_score(val_labels.numpy(), val_predictions.numpy())
        recall = recall_score(val_labels.numpy(), val_predictions.numpy())
        f1 = f1_score(val_labels.numpy(), val_predictions.numpy())
        AUC_PR = average_precision_score(val_labels, val_outputs)
        AUC = roc_auc_score(val_labels, val_predictions)
        rmse = np.sqrt(loss_func(vl.float(), val_predictions.float()))
        #rmse = np.sqrt(mean_squared_error(val_labels, val_predictions.float()))
        pcc, _ = pearsonr(val_labels, val_predictions.float())
        #vrmse = np.sqrt(loss_func(val_labels.float(), val_predictions.float()))

        print(f'Accuracy: {accuracy:.4f}, AUC-ROC: {AUC:.4f} \n AUC-PR: {AUC_PR:.4f}, Precision: {precision:.4f}, Recall: {recall:.4f}, F1 Score: {f1:.4f}')
        print(f'\nRMSE: {rmse:.4f} , PCC: {pcc:.4f}')

        logging.info(f'Accuracy: {accuracy:.4f}, AUC-ROC: {AUC:.4f} \n AUC-PR: {AUC_PR:.4f}, Precision: {precision:.4f}, Recall: {recall:.4f}, F1 Score: {f1:.4f}')
        logging.info(f'\nRMSE: {rmse:.4f} , PCC: {pcc:.4f}')

    logging.info("-" * n_delimiter)
    print("-" * n_delimiter)

    return val_outputs, AUC, accuracy, AUC_PR, f1, precision, recall, rmse, pcc






def Eval_MACSynDCR_ANN_model(train_data,val_data,val_labels,fold):
    print("Evaluation of Keras MACSynDCR_ANN model:")

    scaler = MinMaxScaler()
    val_data = scaler.fit_transform(val_data)
    vl=val_labels.float()
    testy=val_labels
    label_encoder = preprocessing.LabelEncoder()
    y_test = label_encoder.fit_transform(val_labels)

    y_test_cat = to_categorical(y_test,  num_classes = 2)

    ANN = load_model('/content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_ANN_model.keras')
    loss, accuracy, AUC = ANN.evaluate(val_data, y_test_cat)
    print(f'Evaluate->  Loss: {loss:.4f}, Accuracy: {accuracy:.4f},AUC: {AUC:.4f}')
    #model.save('MACSynDCR_ANN_model.hdf5')
    #ANN.save(f'best_CV_MACSynDCR_ANN_model_Fold_{fold+1}_AUC_{AUC:.3f}_ACC_{accuracy:.3f}.keras')

    pred = ANN.predict(val_data)
    train_pred = ANN.predict(train_data)
    ann_pred=pred[:,1]
    ann_label=np.argmax(pred,axis=1)
    y_pred_prob=ann_pred
    y_pred=ann_label
    auc = roc_auc_score(y_test_cat, pred)
    accuracy = accuracy_score(y_test, y_pred)
    auc_pr = average_precision_score(y_test_cat,pred)
    precision = precision_score(y_test, y_pred)
    recall = recall_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)
    #rmse = np.sqrt(mean_squared_error(y_test, ann_pred))
    yp=torch.tensor(y_pred.astype(float))
    rmse = np.sqrt(loss_func(val_labels.float(), yp))
    pcc, _ = pearsonr(y_test_cat, pred)

    print(f'ANN: Accuracy: {accuracy:.4f}, AUC-ROC: {auc:.4f} \nANN: AUC-PR: {auc_pr:.4f}, Precision: {precision:.4f}, \nANN Recall: {recall:.4f}, F1 Score: {f1:.4f}')
    print(f'ANN:RMSE: {rmse:.4f} , PCC: {pcc[1]:.4f}')
    print("*"*100)
    return ann_pred, train_pred



def Eval_MACSynDCR_CNN_model(train_data,val_data,val_labels, fold):
    print("Evaluation of Keras MACSynDCR_CNN model:")

    scaler = MinMaxScaler()
    val_data = scaler.fit_transform(val_data)

    testy=val_labels
    label_encoder = preprocessing.LabelEncoder()
    y_test = label_encoder.fit_transform(val_labels)

    y_test_cat = to_categorical(y_test,  num_classes = 2)

    val_data = val_data.reshape(-1, 64, 38,1)
    CNN = load_model('/content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_CNN_model.keras')
    loss, accuracy, AUC = CNN.evaluate(val_data, y_test_cat)
    print(f'Evaluate->  Loss: {loss:.4f}, Accuracy: {accuracy:.4f},Accuracy: {AUC:.4f}')
    #CNN.save(f'best_CV_MACSynDCR_CNN_model_Fold_{fold+1}_AUC_{AUC:.3f}_ACC_{accuracy:.3f}.keras')
    #model.save('MACSynDCR_ANN_model.hdf5')
    pred = CNN.predict(val_data)
    train_data = train_data.reshape(-1, 64, 38,1)
    train_pred = CNN.predict(train_data)
    cnn_pred=pred[:,1]
    cnn_label=np.argmax(pred,axis=1)
    y_pred_prob=cnn_pred
    y_pred=cnn_label
    auc = roc_auc_score(y_test_cat, pred)
    accuracy = accuracy_score(y_test, y_pred)
    auc_pr = average_precision_score(y_test_cat,pred)
    precision = precision_score(y_test, y_pred)
    recall = recall_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)
    yp=torch.tensor(y_pred.astype(float))
    rmse = np.sqrt(loss_func(testy.float(), yp))
    #rmse = np.sqrt(mean_squared_error(y_test, cnn_pred))
    pcc, _ = pearsonr(y_test_cat, pred)

    print(f'CNN: Accuracy: {accuracy:.4f}, AUC-ROC: {auc:.4f} \nCNN: AUC-PR: {auc_pr:.4f}, Precision: {precision:.4f}, \nCNN Recall: {recall:.4f}, F1 Score: {f1:.4f}')
    print(f'CNN:RMSE: {rmse:.4f} , PCC: {pcc[1]:.4f}')
    print("*"*100)
    return cnn_pred, train_pred

# CV Train Main

In [ ]:
import argparse
import os
import time
import pickle
import logging


import numpy as np
import pandas as pd
import csv
import glob
import matplotlib.pyplot as plt
from scipy.stats import pearsonr
import os
import pickle
import json
import random

from sklearn import preprocessing
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import MinMaxScaler
from collections import Counter
from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold
from sklearn.metrics import (
    roc_auc_score,
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    average_precision_score,
    auc,
    precision_recall_curve,
    mean_squared_error
)


import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset

from sklearn.model_selection import train_test_split, KFold

#from models.MACSynDCR import DrugSynergyCNN,Model_ANN
#from models.MACSynDCR import MACSynDCR_CNN,MACSynDCR_LSTM
#from models.MACSynDCR_evaluation import Eval_MACSynDCR_CNN, Eval_MACSynDCR_LSTM



from tensorflow.keras.optimizers import RMSprop,Adam, SGD
from torchsummary import summary
#from models.MACSynDCR_model import Ensemble_MACSynDCR_model
from sklearn.linear_model import LogisticRegression

def Ensemble_MACSynDCR_model(out_dir,ann_preds,kann_preds, kcnn_preds,y_test, fold,val_index, indTest_pred,ind_y):

    ann_auc = roc_auc_score(y_test, ann_preds)
    ann_accuracy = accuracy_score(y_test, (ann_preds > 0.5).astype(int))
    print(f'Accuracy Score and AUC for ANN = AUC: {ann_auc:.4f}, Accuracy: {ann_accuracy:.4f}')

    kann_auc = roc_auc_score(y_test, kann_preds)
    kann_accuracy = accuracy_score(y_test, (kann_preds > 0.5).astype(int))
    print(f'Accuracy Score and AUC for KANN = AUC: {kann_auc:.4f}, Accuracy: {kann_accuracy:.4f}')

    kcnn_auc = roc_auc_score(y_test, kcnn_preds)
    kcnn_accuracy = accuracy_score(y_test, (kcnn_preds> 0.5).astype(int))
    print(f'Accuracy Score and AUC for KCNN = AUC: {kcnn_auc:.4f}, Accuracy: {kcnn_accuracy:.4f}')


    test_X = np.column_stack((ann_preds,kann_preds,kcnn_preds))
    #print(train_X.shape, type(test_X.shape))


    avg_pred=np.mean(test_X, axis=1)
    #mean_pred = np.mean(ensemble_pred, axis=1)
    df1 = pd.DataFrame({
    'sample_id': val_index,
    'probability': avg_pred
    })
    csv_file1 = os.path.join(out_dir, f'avg_prob{fold+1}.csv')
    df1.to_csv(csv_file1, index=False)

    max_pred=np.max(test_X, axis=1)
    df2 = pd.DataFrame({
    'sample_id': val_index,
    'probability': max_pred
    })

    csv_file2 = os.path.join(out_dir, f'max_prob{fold+1}.csv')
    df2.to_csv(csv_file2, index=False)

    avg_auc = roc_auc_score(y_test, avg_pred)
    avg_accuracy = accuracy_score(y_test, (avg_pred > 0.5).astype(int))
    print(f'Average AUC = AUC: {avg_auc:.4f}, Accuracy: {avg_accuracy:.4f}')

    max_auc = roc_auc_score(y_test, max_pred)
    max_accuracy = accuracy_score(y_test, (max_pred > 0.5).astype(int))
    print(f'MAX AUC = AUC: {max_auc:.4f}, Accuracy: {max_accuracy:.4f}')



    from sklearn.model_selection import GridSearchCV
    from sklearn.ensemble import RandomForestClassifier

    rf_model = RandomForestClassifier(random_state=42)
    param_grid = {
       'n_estimators': [50, 200],
       'max_depth': [None, 10, 30],
       'min_samples_split': [2, 10],
       'min_samples_leaf': [1, 4],
    }

    #grid_search = GridSearchCV(estimator=rf_model, param_grid=param_grid,
                              # scoring='accuracy', cv=3, verbose=0, n_jobs=-1)
    #grid_search.fit(train_X, train_labels)
   # best_rf_model = grid_search.best_estimator_
    #rf_ensemble_prob = best_rf_model.predict_proba(test_X)[:, 1]


    #{'C': [0.01, 0.1, 1, 10, 100]
    param_grid = {'C': [0.01,0.1, 1, 10,100,1000,10000], 'penalty': ['l1', 'l2']}
    grid_search = GridSearchCV(LogisticRegression(), param_grid, cv=5,verbose=1)
    grid_search.fit(test_X, y_test)
    best_model = grid_search.best_estimator_
    #meta_model = LogisticRegression()
    #meta_model.fit(stacked_X, y_test)
    lr_ensemble_prob = best_model.predict_proba(test_X)[:,1]
    ensemble_prob=lr_ensemble_prob
    ensemble_pred=(ensemble_prob > 0.5).astype(int)
    df3 = pd.DataFrame({
    'sample_id': val_index,
    'probability': ensemble_pred
    })
    csv_file3 = os.path.join(out_dir, f'ensemble_prob{fold+1}.csv')
    df3.to_csv(csv_file3, index=False)


    print(f"Finall ensemble results of fold_{fold+1} for MACSynDCR:")
    logging.info(f"Finall ensemble results of fold_{fold+1} for MACSynDCR:")
    logging.info("-" * 100)
    print("-" * 100)
    auc = roc_auc_score(y_test, ensemble_prob)
    accuracy = accuracy_score(y_test, ensemble_pred)
    auc_pr = average_precision_score(y_test,ensemble_prob)
    precision = precision_score(y_test, ensemble_pred)
    recall = recall_score(y_test, ensemble_pred)
    f1 = f1_score(y_test, ensemble_pred)
    yp=torch.tensor(ensemble_pred.astype(float))
    rmse = np.sqrt(loss_func(y_test.float(), yp))
    #rmse = np.sqrt(mean_squared_error(y_test, y_pred))
    pcc, _ = pearsonr(y_test, ensemble_prob)

    print(f'Ensemble Accuracy: {accuracy:.4f}, AUC-ROC: {auc:.4f} \nEnsemble AUC-PR: {auc_pr:.4f}, Precision: {precision:.4f}, \nEnsemble Recall: {recall:.4f}, F1 Score: {f1:.4f}')
    print(f'Ensemble RMSE: {rmse:.4f} , PCC: {pcc:.4f}')
    logging.info(f'Ensemble Accuracy: {accuracy:.4f}, AUC-ROC: {auc:.4f}, \nEnsemble AUC-PR: {auc_pr:.4f}, Precision: {precision:.4f}, \nEnsemble Recall: {recall:.4f}, F1 Score: {f1:.4f}, \nEnsemble RMSE: {rmse:.4f}')

    logging.info("-" * 100)
    print("-" * 100)

    ind_test_X = np.column_stack((indTest_pred[0],indTest_pred[1],indTest_pred[2]))
    grid_search2 = GridSearchCV(LogisticRegression(), param_grid, cv=5,verbose=1)
    grid_search2.fit(ind_test_X, ind_y)
    best_model2 = grid_search2.best_estimator_
    #meta_model = LogisticRegression()
    #meta_model.fit(stacked_X, y_test)
    ind_ensemble_prob = best_model2.predict_proba(ind_test_X)[:,1]
    ind_ensemble_pred=(ind_ensemble_prob > 0.5).astype(int)
    df4 = pd.DataFrame({
    'probability': ind_ensemble_prob,
    'prediction': ind_ensemble_pred,
    })
    csv_file4 = os.path.join(out_dir, f'ind_ensemble_prob{fold+1}.csv')
    df4.to_csv(csv_file4, index=False)
    ind_ensemble_results=[]
    auc = roc_auc_score(ind_y, ind_ensemble_prob)
    accuracy = accuracy_score(ind_y, ind_ensemble_pred)
    auc_pr = average_precision_score(ind_y,ind_ensemble_prob)
    precision = precision_score(ind_y, ind_ensemble_pred)
    recall = recall_score(ind_y, ind_ensemble_pred)
    f1 = f1_score(ind_y, ind_ensemble_pred)
    yp=torch.tensor(ind_ensemble_pred.astype(float))
    rmse = np.sqrt(loss_func(ind_y.float(), yp))
    #rmse = np.sqrt(mean_squared_error(y_test, y_pred))
    pcc, _ = pearsonr(ind_y, ind_ensemble_prob)

    ind_ensemble_results.append(auc)
    ind_ensemble_results.append(accuracy)
    ind_ensemble_results.append(auc_pr)
    ind_ensemble_results.append(f1)
    ind_ensemble_results.append(precision)
    ind_ensemble_results.append(recall)
    ind_ensemble_results.append(rmse)
    ind_ensemble_results.append(pcc)
    ind_ensemble_results=np.array(ind_ensemble_prob)

    return ensemble_prob, auc, accuracy, auc_pr, f1, precision, recall, rmse, pcc,ind_ensemble_results


import warnings
warnings.filterwarnings("ignore")


from datetime import datetime

def calc_stat(numbers):
    mu = sum(numbers) / len(numbers)
    sigma = (sum([(x - mu) ** 2 for x in numbers]) / len(numbers)) ** 0.5
    return mu, sigma

def save_args(args, save_to: str):
    args_dict = args.__dict__
    with open(save_to, 'w') as f:
        json.dump(args_dict, f, indent=2)




OUTPUT_DIR = '/content/drive/MyDrive/MACSynDCR/Data/output/CV_MACSynDCRP_0to10/'
if not os.path.exists(OUTPUT_DIR):
    os.makedirs(OUTPUT_DIR)

n_delimiter = 100


#batch_size = 256
#epochs = 500
#num_epochs=5
num_classes = 2



import numpy as np
from sklearn.preprocessing import normalize
def to01(array):
    a = array.min()
    # ignore the Runtime Warning
    with np.errstate(divide='ignore'):
        b = 1. /(array.max() - array.min())
    if not(np.isfinite(b)):
        b = 0
    return np.vectorize(lambda x: b * (x - a))(array)



time_str = str(datetime.now().strftime('%y%m%d%H%M'))

#Training and Evaluation Function

input_size=2432
input_shape = (64, 38)
loss_func = nn.MSELoss(reduction='sum')
from sklearn.model_selection import StratifiedKFold

def lists_elements(lofl,i):
    el=[]
    for l in lofl:
        el.append(l[i])
    return el

def train_and_evaluate_model(data, labels, out_dir,intTestData,ind_y):

    #num_epochs=200
    #learning_rate=.0005

    #kfold=StratifiedKFold(n_splits=5, *, shuffle=True, random_state=42)
    kfold = KFold(n_splits=5, shuffle=True, random_state=42)
    best_model = None
    best_accuracy = 0.0

    n_delimiter = 100


    fauc=[]
    facc=[]
    faucpr=[]
    ff1=[]
    fprec=[]
    frecall=[]
    frmse= []
    fpcc=[]
    ind_cv_results=[]

    pred_results = {
        'ann_pred': [],
        'cnn_pred': [],
        'lstm_pred': [],
        'Precision': [],
        'kann_pred': [],
        'kcnn_pred': [],
        'klstm_pred': [],
    }

    for fold, (train_index, val_index) in enumerate(kfold.split(data)):
        print(f'Fold {fold + 1}')
        logging.info(f'Fold {fold + 1}')
        logging.info("-" * n_delimiter)

        train_data, val_data = data[train_index], data[val_index]
        train_labels, val_labels = labels[train_index], labels[val_index]

        ANNmodel, best_preds, train_preds,ann_ipred=Train_MACSynDCR_ANN(train_data, train_labels,val_data,val_labels, fold,intTestData)
        print(ann_ipred)
        val_outputs = best_preds.astype(float)
        val_predictions = (val_outputs > 0.5).astype(float)
        #print(val_labels.numpy(),val_predictions,val_outputs)
        accuracy = accuracy_score(val_labels.numpy(), val_predictions)
        precision = precision_score(val_labels.numpy(), val_predictions)
        recall = recall_score(val_labels.numpy(), val_predictions)
        f1 = f1_score(val_labels.numpy(), val_predictions)
        auc_pr = average_precision_score(val_labels.float(), val_outputs.astype(float))
        auc = roc_auc_score(val_labels.float(), val_outputs.astype(float))
        rmse = np.sqrt(loss_func(val_labels.float(),torch.FloatTensor(val_outputs.squeeze())))
        #rmse = np.sqrt(mean_squared_error(val_labels, val_predictions.float()))
        #print(val_labels, torch.FloatTensor(val_outputs.squeeze()))
        pcc, _ = pearsonr(val_labels, torch.FloatTensor(val_outputs.squeeze()))
       # pcc, a = pearsonr([1,1,1], [1,1,4])
        #vrmse = np.sqrt(loss_func(val_labels.float(), val_predictions.float()))
        print(f'Accuracy: {accuracy:.4f}, AUC-ROC: {auc:.4f} \n AUC-PR: {auc_pr:.4f}, Precision: {precision:.4f}, Recall: {recall:.4f}, F1 Score: {f1:.4f}')
        print(f'RMSE: {rmse:.4f} , PCC: {pcc:.4f}')
        ann_pred=val_outputs
        ann_train_pred=train_preds

        kann_ipred=Train_and_Validation_MACSynDCR_ANN(train_data,val_data,train_labels,val_labels,intTestData)
        #print("KANN",kann_ipred)
        kcnn_ipred=Train_and_Validation_MACSynDCR_CNN(train_data,val_data,train_labels,val_labels,intTestData)
        #print("KCNN",kann_ipred)


        indTest_pred=[]
        #Eval_MACSynDCR_CNN(CNNmodel, train_data,val_data,val_labels,fold)
        #ann_pred, ann_train_pred,auc, accuracy, auc_pr, f1, precision, recall, rmse, pcc=Eval_MACSynDCR_ANN(ANNmodel, train_data,val_data,val_labels,fold)
        kann_pred, kann_train_pred=Eval_MACSynDCR_ANN_model(train_data,val_data,val_labels,fold)
        kcnn_pred, kcnn_train_pred=Eval_MACSynDCR_CNN_model(train_data,val_data,val_labels,fold)
        indTest_pred.append(ann_ipred)
        indTest_pred.append(kann_ipred)
        indTest_pred.append(kcnn_ipred)

        ensemble_pred, auc, accuracy, auc_pr, f1, precision, recall, rmse, pcc,ind_ensemble_results=Ensemble_MACSynDCR_model(out_dir,ann_pred,kann_pred, kcnn_pred,val_labels, fold,val_index,indTest_pred,ind_y)
        fauc.append(auc)
        facc.append(accuracy)
        faucpr.append(auc_pr)
        ff1.append(f1)
        fprec.append(precision)
        frecall.append(recall)
        frmse.append(rmse)
        fpcc.append(pcc)
        #ensemble_prob=np.array(ensemble_prob)
        ind_cv_results.append(ind_ensemble_results)


    #mu, sigma = calc_stat(test_losses)
    print("*"*n_delimiter)
    logging.info("*" * n_delimiter)
    print("*           Final MACSynCDR Results:")
    logging.info("*          Final MACSynCDR Results:")
    logging.info("*" * n_delimiter)
    print("*"*n_delimiter)
    mu, sigma = calc_stat(fauc)
    print(" AUC: {:.4f} ± {:.4f}".format(mu, sigma))
    logging.info(" AUC: {:.4f} ± {:.4f}".format(mu, sigma))

    mu, sigma = calc_stat(facc)
    print(" Accuracy: {:.4f} ± {:.4f}".format(mu, sigma))
    logging.info(" Accuracy: {:.4f} ± {:.4f}".format(mu, sigma))

    mu, sigma = calc_stat(faucpr)
    print(" AUC-PR: {:.4f} ± {:.4f}".format(mu, sigma))
    logging.info(" AUC-PR: {:.4f} ± {:.4f}".format(mu, sigma))

    mu, sigma = calc_stat(fprec)
    print(" Precision: {:.4f} ± {:.4f}".format(mu, sigma))
    logging.info(" Precision: {:.4f} ± {:.4f}".format(mu, sigma))

    mu, sigma = calc_stat(frecall)
    print(" Recall: {:.4f} ± {:.4f}".format(mu, sigma))
    logging.info(" Recall: {:.4f} ± {:.4f}".format(mu, sigma))

    mu, sigma = calc_stat(ff1)
    print(" F1: {:.4f} ± {:.4f}".format(mu, sigma))
    logging.info(" F1: {:.4f} ± {:.4f}".format(mu, sigma))

    mu, sigma = calc_stat(frmse)
    print(" RMSE: {:.4f} ± {:.4f}".format(mu, sigma))
    logging.info(" RMSE: {:.4f} ± {:.4f}".format(mu, sigma))

    mu, sigma = calc_stat(fpcc)
    print(" PCC: {:.4f} ± {:.4f}".format(mu, sigma))
    logging.info(" PCC: {:.4f} ± {:.4f}".format(mu, sigma))

    print("Max AUC: {:.4f}".format(max(fauc)))
    print("Max ACC: {:.4f}".format(max(facc)))
    print("Max AUC-PR: {:.4f}".format(max(faucpr)))
    print("Max Precision: {:.4f}".format(max(fprec)))
    print("Max Reacall: {:.4f}".format(max(frecall)))
    print("Max F1: {:.4f}".format(max(ff1)))
    print("MIN RMSE: {:.4f}".format(min(frmse)))
    print("Max PCC: {:.4f}".format(max(fpcc)))



    #### Test results



    print("*"*n_delimiter)
    logging.info("*" * n_delimiter)
    print("*           Independent MACSynCDR Testing Results:")
    logging.info("*          Independent MACSynCDR Testing Results:")
    logging.info("*" * n_delimiter)
    print("*"*n_delimiter)
    mu, sigma = calc_stat(lists_elements(ind_ensemble_results,0))
    print(" AUC: {:.4f} ± {:.4f}".format(mu, sigma))
    logging.info(" AUC: {:.4f} ± {:.4f}".format(mu, sigma))

    mu, sigma = calc_stat(lists_elements(ind_ensemble_results,1))
    print(" Accuracy: {:.4f} ± {:.4f}".format(mu, sigma))
    logging.info(" Accuracy: {:.4f} ± {:.4f}".format(mu, sigma))

    mu, sigma = calc_stat(lists_elements(ind_ensemble_results,2))
    print(" AUC-PR: {:.4f} ± {:.4f}".format(mu, sigma))
    logging.info(" AUC-PR: {:.4f} ± {:.4f}".format(mu, sigma))

    mu, sigma = calc_stat(lists_elements(ind_ensemble_results,3))
    print(" Precision: {:.4f} ± {:.4f}".format(mu, sigma))
    logging.info(" Precision: {:.4f} ± {:.4f}".format(mu, sigma))

    mu, sigma = calc_stat(lists_elements(ind_ensemble_results,4))
    print(" Recall: {:.4f} ± {:.4f}".format(mu, sigma))
    logging.info(" Recall: {:.4f} ± {:.4f}".format(mu, sigma))

    mu, sigma = calc_stat(lists_elements(ind_ensemble_results,5))
    print(" F1: {:.4f} ± {:.4f}".format(mu, sigma))
    logging.info(" F1: {:.4f} ± {:.4f}".format(mu, sigma))

    mu, sigma = calc_stat(lists_elements(ind_ensemble_results,6))
    print(" RMSE: {:.4f} ± {:.4f}".format(mu, sigma))
    logging.info(" RMSE: {:.4f} ± {:.4f}".format(mu, sigma))

    mu, sigma = calc_stat(lists_elements(ind_ensemble_results,7))
    print(" PCC: {:.4f} ± {:.4f}".format(mu, sigma))
    logging.info(" PCC: {:.4f} ± {:.4f}".format(mu, sigma))


    return best_model

In [ ]:
def Ensemble_MACSynDCR_model(out_dir,ann_preds,kann_preds, kcnn_preds,y_test, fold,val_index, indTest_pred,ind_y):

    ann_auc = roc_auc_score(y_test, ann_preds)
    ann_accuracy = accuracy_score(y_test, (ann_preds > 0.5).astype(int))
    print(f'Accuracy Score and AUC for ANN = AUC: {ann_auc:.4f}, Accuracy: {ann_accuracy:.4f}')

    kann_auc = roc_auc_score(y_test, kann_preds)
    kann_accuracy = accuracy_score(y_test, (kann_preds > 0.5).astype(int))
    print(f'Accuracy Score and AUC for KANN = AUC: {kann_auc:.4f}, Accuracy: {kann_accuracy:.4f}')

    kcnn_auc = roc_auc_score(y_test, kcnn_preds)
    kcnn_accuracy = accuracy_score(y_test, (kcnn_preds> 0.5).astype(int))
    print(f'Accuracy Score and AUC for KCNN = AUC: {kcnn_auc:.4f}, Accuracy: {kcnn_accuracy:.4f}')


    val_X = np.column_stack((ann_preds,kann_preds,kcnn_preds))
    #print(train_X.shape, type(test_X.shape))


    avg_preds=np.mean(val_X, axis=1)
    #mean_pred = np.mean(ensemble_pred, axis=1)
    df1 = pd.DataFrame({
    'sample_id': val_index,
    'probability': avg_preds
    })
    csv_file1 = os.path.join(out_dir, f'avg_prob{fold+1}.csv')
    df1.to_csv(csv_file1, index=False)

    max_preds=np.max(val_X, axis=1)
    df2 = pd.DataFrame({
    'sample_id': val_index,
    'probability': max_preds
    })

    csv_file2 = os.path.join(out_dir, f'max_prob{fold+1}.csv')
    df2.to_csv(csv_file2, index=False)

    avg_auc = roc_auc_score(y_test, avg_preds)
    avg_accuracy = accuracy_score(y_test, (avg_preds > 0.5).astype(int))
    print(f'Average AUC = AUC: {avg_auc:.4f}, Accuracy: {avg_accuracy:.4f}')

    max_auc = roc_auc_score(y_test, max_preds)
    max_accuracy = accuracy_score(y_test, (max_preds > 0.5).astype(int))
    print(f'MAX AUC = AUC: {max_auc:.4f}, Accuracy: {max_accuracy:.4f}')



    from sklearn.model_selection import GridSearchCV
    from sklearn.ensemble import RandomForestClassifier

    rf_model = RandomForestClassifier(random_state=42)
    param_grid = {
       'n_estimators': [50, 200],
       'max_depth': [None, 10, 30],
       'min_samples_split': [2, 10],
       'min_samples_leaf': [1, 4],
    }

    #grid_search = GridSearchCV(estimator=rf_model, param_grid=param_grid,
                              # scoring='accuracy', cv=3, verbose=0, n_jobs=-1)
    #grid_search.fit(train_X, train_labels)
   # best_rf_model = grid_search.best_estimator_
    #rf_ensemble_prob = best_rf_model.predict_proba(test_X)[:, 1]


    #{'C': [0.01, 0.1, 1, 10, 100]
    param_grid = {'C': [0.01,0.1, 1, 10,100,1000,10000], 'penalty': ['l1', 'l2']}
    grid_search = GridSearchCV(LogisticRegression(), param_grid, cv=5,verbose=1)
    grid_search.fit(val_X, y_test)
    best_model = grid_search.best_estimator_
    #meta_model = LogisticRegression()
    #meta_model.fit(stacked_X, y_test)
    lr_ensemble_prob = best_model.predict_proba(val_X)[:,1]
    ensemble_prob=lr_ensemble_prob
    ensemble_pred=(ensemble_prob > 0.5).astype(int)
    df3 = pd.DataFrame({
    'sample_id': val_index,
    'probability': ensemble_pred
    })
    csv_file3 = os.path.join(out_dir, f'ensemble_prob{fold+1}.csv')
    df3.to_csv(csv_file3, index=False)


    print(f"Finall ensemble results of fold_{fold+1} for MACSynDCR:")
    logging.info(f"Finall ensemble results of fold_{fold+1} for MACSynDCR:")
    logging.info("-" * 100)
    print("-" * 100)
    auc = roc_auc_score(y_test, ensemble_prob)
    accuracy = accuracy_score(y_test, ensemble_pred)
    auc_pr = average_precision_score(y_test,ensemble_prob)
    precision = precision_score(y_test, ensemble_pred)
    recall = recall_score(y_test, ensemble_pred)
    f1 = f1_score(y_test, ensemble_pred)
    yp=torch.tensor(ensemble_pred.astype(float))
    rmse = np.sqrt(loss_func(y_test.float(), yp))
    #rmse = np.sqrt(mean_squared_error(y_test, y_pred))
    pcc, _ = pearsonr(y_test, ensemble_prob)

    print(f'Ensemble Accuracy: {accuracy:.4f}, AUC-ROC: {auc:.4f} \nEnsemble AUC-PR: {auc_pr:.4f}, Precision: {precision:.4f}, \nEnsemble Recall: {recall:.4f}, F1 Score: {f1:.4f}')
    print(f'Ensemble RMSE: {rmse:.4f} , PCC: {pcc:.4f}')
    logging.info(f'Ensemble Accuracy: {accuracy:.4f}, AUC-ROC: {auc:.4f}, \nEnsemble AUC-PR: {auc_pr:.4f}, Precision: {precision:.4f}, \nEnsemble Recall: {recall:.4f}, F1 Score: {f1:.4f}, \nEnsemble RMSE: {rmse:.4f}')

    logging.info("-" * 100)
    print("-" * 100)

    ind_test_X = np.column_stack((indTest_pred[0],indTest_pred[1],indTest_pred[2]))
    grid_search2 = GridSearchCV(LogisticRegression(), param_grid, cv=5,verbose=1)
    grid_search2.fit(ind_test_X, ind_y)
    best_model2 = grid_search2.best_estimator_
    #meta_model = LogisticRegression()
    #meta_model.fit(stacked_X, y_test)
    ind_ensemble_prob = best_model2.predict_proba(ind_test_X)[:,1]
    ind_ensemble_pred=(ind_ensemble_prob > 0.5).astype(int)
    df4 = pd.DataFrame({
    'probability': ind_ensemble_prob,
    'prediction': ind_ensemble_pred,
    })
    csv_file4 = os.path.join(out_dir, f'ind_ensemble_prob{fold+1}.csv')
    df4.to_csv(csv_file4, index=False)
    ind_ensemble_results_metrics=[] # Renamed to avoid conflict
    iauc = roc_auc_score(ind_y, ind_ensemble_prob)
    iaccuracy = accuracy_score(ind_y, ind_ensemble_pred)
    iauc_pr = average_precision_score(ind_y,ind_ensemble_prob)
    iprecision = precision_score(ind_y, ind_ensemble_pred)
    irecall = recall_score(ind_y, ind_ensemble_pred)
    if1 = f1_score(ind_y, ind_ensemble_pred)
    yp=torch.tensor(ind_ensemble_pred.astype(float))
    irmse = np.sqrt(loss_func(ind_y.float(), yp))
    #rmse = np.sqrt(mean_squared_error(y_test, y_pred))
    ipcc, _ = pearsonr(ind_y, ind_ensemble_prob)

    # Append the metrics to the list
    ind_ensemble_results_metrics.append(iauc)
    ind_ensemble_results_metrics.append(iaccuracy)
    ind_ensemble_results_metrics.append(iauc_pr)
    ind_ensemble_results_metrics.append(if1)
    ind_ensemble_results_metrics.append(iprecision)
    ind_ensemble_results_metrics.append(irecall)
    ind_ensemble_results_metrics.append(irmse)
    ind_ensemble_results_metrics.append(ipcc)

    # Return both the ensemble probabilities and the metrics
    return ensemble_prob, auc, accuracy, auc_pr, f1, precision, recall, rmse, pcc, ind_ensemble_results_metrics

In [ ]:
def train_and_evaluate_model(data, labels, out_dir,intTestData,ind_y):
    #num_epochs=200
    #learning_rate=.0005

    #kfold=StratifiedKFold(n_splits=5, *, shuffle=True, random_state=42)
    kfold = KFold(n_splits=5, shuffle=True, random_state=42)
    best_model = None
    best_accuracy = 0.0

    n_delimiter = 100


    fauc=[]
    facc=[]
    faucpr=[]
    ff1=[]
    fprec=[]
    frecall=[]
    frmse= []
    fpcc=[]
    ind_cv_results=[]

    pred_results = {
        'ann_pred': [],
        'cnn_pred': [],
        'lstm_pred': [],
        'Precision': [],
        'kann_pred': [],
        'kcnn_pred': [],
        'klstm_pred': [],
    }

    for fold, (train_index, val_index) in enumerate(kfold.split(data)):
        print(f'Fold {fold + 1}')
        logging.info(f'Fold {fold + 1}')
        logging.info("-" * n_delimiter)

        train_data, val_data = data[train_index], data[val_index]
        train_labels, val_labels = labels[train_index], labels[val_index]

        ANNmodel, best_preds, train_preds,ann_ipred=Train_MACSynDCR_ANN(train_data, train_labels,val_data,val_labels, fold,intTestData)
        print("TANN", ann_ipred)
        val_outputs = best_preds.astype(float)
        val_predictions = (val_outputs > 0.5).astype(float)
        #print(val_labels.numpy(),val_predictions,val_outputs)
        accuracy = accuracy_score(val_labels.numpy(), val_predictions)
        precision = precision_score(val_labels.numpy(), val_predictions)
        recall = recall_score(val_labels.numpy(), val_predictions)
        f1 = f1_score(val_labels.numpy(), val_predictions)
        auc_pr = average_precision_score(val_labels.float(), val_outputs.astype(float))
        auc = roc_auc_score(val_labels.float(), val_outputs.astype(float))
        rmse = np.sqrt(loss_func(val_labels.float(),torch.FloatTensor(val_outputs.squeeze())))
        #rmse = np.sqrt(mean_squared_error(val_labels, val_predictions.float()))
        #print(val_labels, torch.FloatTensor(val_outputs.squeeze()))
        pcc, _ = pearsonr(val_labels, torch.FloatTensor(val_outputs.squeeze()))
       # pcc, a = pearsonr([1,1,1], [1,1,4])
        #vrmse = np.sqrt(loss_func(val_labels.float(), val_predictions.float()))
        print(f'Accuracy: {accuracy:.4f}, AUC-ROC: {auc:.4f} \n AUC-PR: {auc_pr:.4f}, Precision: {precision:.4f}, Recall: {recall:.4f}, F1 Score: {f1:.4f}')
        print(f'RMSE: {rmse:.4f} , PCC: {pcc:.4f}')
        ann_pred=val_outputs
        ann_train_pred=train_preds

        kann_ipred=Train_and_Validation_MACSynDCR_ANN(train_data,val_data,train_labels,val_labels,intTestData)
        print("KANN",kann_ipred)
        kcnn_ipred=Train_and_Validation_MACSynDCR_CNN(train_data,val_data,train_labels,val_labels,intTestData)
        print("KCNN",kann_ipred)


        indTest_pred=[]
        #Eval_MACSynDCR_CNN(CNNmodel, train_data,val_data,val_labels,fold)
        #ann_pred, ann_train_pred,auc, accuracy, auc_pr, f1, precision, recall, rmse, pcc=Eval_MACSynDCR_ANN(ANNmodel, train_data,val_data,val_labels,fold)
        kann_pred, kann_train_pred=Eval_MACSynDCR_ANN_model(train_data,val_data,val_labels,fold)
        kcnn_pred, kcnn_train_pred=Eval_MACSynDCR_CNN_model(train_data,val_data,val_labels,fold)
        indTest_pred.append(ann_ipred)
        indTest_pred.append(kann_ipred)
        indTest_pred.append(kcnn_ipred)

        # Capture the returned metrics list
        ensemble_prob, auc, accuracy, auc_pr, f1, precision, recall, rmse, pcc, ind_ensemble_results_metrics = Ensemble_MACSynDCR_model(out_dir,ann_pred,kann_pred, kcnn_pred,val_labels, fold,val_index,indTest_pred,ind_y)
        fauc.append(auc)
        facc.append(accuracy)
        faucpr.append(auc_pr)
        ff1.append(f1)
        fprec.append(precision)
        frecall.append(recall)
        frmse.append(rmse)
        fpcc.append(pcc)
        # Append the metrics list to ind_cv_results
        ind_cv_results.append(ind_ensemble_results_metrics)


    #mu, sigma = calc_stat(test_losses)
    print("*"*n_delimiter)
    logging.info("*" * n_delimiter)
    print("*           Final MACSynCDR Results:")
    logging.info("*          Final MACSynCDR Results:")
    logging.info("*" * n_delimiter)
    print("*"*n_delimiter)
    mu, sigma = calc_stat(fauc)
    print(" AUC: {:.4f} ± {:.4f}".format(mu, sigma))
    logging.info(" AUC: {:.4f} ± {:.4f}".format(mu, sigma))

    mu, sigma = calc_stat(facc)
    print(" Accuracy: {:.4f} ± {:.4f}".format(mu, sigma))
    logging.info(" Accuracy: {:.4f} ± {:.4f}".format(mu, sigma))

    mu, sigma = calc_stat(faucpr)
    print(" AUC-PR: {:.4f} ± {:.4f}".format(mu, sigma))
    logging.info(" AUC-PR: {:.4f} ± {:.4f}".format(mu, sigma))

    mu, sigma = calc_stat(fprec)
    print(" Precision: {:.4f} ± {:.4f}".format(mu, sigma))
    logging.info(" Precision: {:.4f} ± {:.4f}".format(mu, sigma))

    mu, sigma = calc_stat(frecall)
    print(" Recall: {:.4f} ± {:.4f}".format(mu, sigma))
    logging.info(" Recall: {:.4f} ± {:.4f}".format(mu, sigma))

    mu, sigma = calc_stat(ff1)
    print(" F1: {:.4f} ± {:.4f}".format(mu, sigma))
    logging.info(" F1: {:.4f} ± {:.4f}".format(mu, sigma))

    mu, sigma = calc_stat(frmse)
    print(" RMSE: {:.4f} ± {:.4f}".format(mu, sigma))
    logging.info(" RMSE: {:.4f} ± {:.4f}".format(mu, sigma))

    mu, sigma = calc_stat(fpcc)
    print(" PCC: {:.4f} ± {:.4f}".format(mu, sigma))
    logging.info(" PCC: {:.4f} ± {:.4f}".format(mu, sigma))

    print("Max AUC: {:.4f}".format(max(fauc)))
    print("Max ACC: {:.4f}".format(max(facc)))
    print("Max AUC-PR: {:.4f}".format(max(faucpr)))
    print("Max Precision: {:.4f}".format(max(fprec)))
    print("Max Reacall: {:.4f}".format(max(frecall)))
    print("Max F1: {:.4f}".format(max(ff1)))
    print("MIN RMSE: {:.4f}".format(min(frmse)))
    print("Max PCC: {:.4f}".format(max(fpcc)))



    #### Test results



    print("*"*n_delimiter)
    logging.info("*" * n_delimiter)
    print("*           Independent MACSynCDR Testing Results:")
    logging.info("*          Independent MACSynCDR Testing Results:")
    logging.info("*" * n_delimiter)
    print("*"*n_delimiter)
    mu, sigma = calc_stat(lists_elements(ind_cv_results,0))
    print(" AUC: {:.4f} ± {:.4f}".format(mu, sigma))
    logging.info(" AUC: {:.4f} ± {:.4f}".format(mu, sigma))

    mu, sigma = calc_stat(lists_elements(ind_cv_results,1))
    print(" Accuracy: {:.4f} ± {:.4f}".format(mu, sigma))
    logging.info(" Accuracy: {:.4f} ± {:.4f}".format(mu, sigma))

    mu, sigma = calc_stat(lists_elements(ind_cv_results,2))
    print(" AUC-PR: {:.4f} ± {:.4f}".format(mu, sigma))
    logging.info(" AUC-PR: {:.4f} ± {:.4f}".format(mu, sigma))

    mu, sigma = calc_stat(lists_elements(ind_cv_results,3))
    print(" Precision: {:.4f} ± {:.4f}".format(mu, sigma))
    logging.info(" Precision: {:.4f} ± {:.4f}".format(mu, sigma))

    mu, sigma = calc_stat(lists_elements(ind_cv_results,4))
    print(" Recall: {:.4f} ± {:.4f}".format(mu, sigma))
    logging.info(" Recall: {:.4f} ± {:.4f}".format(mu, sigma))

    mu, sigma = calc_stat(lists_elements(ind_cv_results,5))
    print(" F1: {:.4f} ± {:.4f}".format(mu, sigma))
    logging.info(" F1: {:.4f} ± {:.4f}".format(mu, sigma))

    mu, sigma = calc_stat(lists_elements(ind_cv_results,6))
    print(" RMSE: {:.4f} ± {:.4f}".format(mu, sigma))
    logging.info(" RMSE: {:.4f} ± {:.4f}".format(mu, sigma))

    mu, sigma = calc_stat(lists_elements(ind_cv_results,7))
    print(" PCC: {:.4f} ± {:.4f}".format(mu, sigma))
    logging.info(" PCC: {:.4f} ± {:.4f}".format(mu, sigma))

    return best_model

# Main function

In [ ]:
def main():
    out_dir = "/content/drive/MyDrive/MACSynDCR/Data/output/CV_MACSynDCRP_0to10/"
    a=os.path.join(OUTPUT_DIR, 'cv_{}'.format(""))
    if not os.path.exists(out_dir):
        os.makedirs(out_dir)
    log_file = os.path.join(out_dir, 'cv.log')
    logging.basicConfig(filename=log_file,
                        format='%(asctime)s %(message)s',
                        datefmt='[%Y-%m-%d %H:%M:%S]',
                        level=logging.INFO)

    # Convert DataFrame to NumPy
    #dataset
    #drugdata = pd.read_csv('OneilProcessDataset30_dti.csv')
    #drugdata = pd.read_csv('OneilProcessDataset_0to10_2176_dti.csv')
    #drugdata = pd.read_csv('OneilProcessDataset_20to20_2176_dti.csv')
    #drugdata = pd.read_csv('OneilProcessDataset_all_2432_d1d2.csv')
    #drugdata = pd.read_csv('OneilProcessDataset_2176_d1cd2.csv')
    #drugdata = pd.read_csv('MFSynDCP_ProcessDataset_2176_d1cd2-10to10-Z.csv')
    drugdata = pd.read_csv('/content/drive/MyDrive/MACSynDCR/Data/MACSynDCRP_ProcessData_0to10.csv')
    drugdata = pd.DataFrame(data=drugdata)
    xdata=drugdata.iloc[:,1:2433]
    ydata=drugdata.iloc[:,2433]
    Y = ydata
    X = xdata
    Y.value_counts()
    #xdata=to01(xdata.values)

    from sklearn import datasets
    from sklearn.tree import DecisionTreeClassifier
    from sklearn.model_selection import StratifiedKFold, cross_val_score

# -------- Step 1: 80-20 Split --------
    X_trainval, X_test, y_trainval, y_test = train_test_split(
    X, Y, test_size=0.2, random_state=42)



    data = torch.FloatTensor(X_trainval.values)
    labels = torch.FloatTensor(y_trainval.values)

    X_test = torch.FloatTensor(X_test.values)
    y_test = torch.FloatTensor(y_test.values)

    best_model = train_and_evaluate_model(data, labels, out_dir,X_test,y_test) ##CV

if __name__ == "__main__":
    main()

Fold 1
Data processing and Training of MACSynDCR_ANN model:
ANN_model saved with Val_ACC: 0.5310 Val_AUC: 0.5130
fold_1: Epoch [1/200], Loss: 0.7040, Val_ACC: 0.5310, Val_AUC: 0.5130
ANN_model saved with Val_ACC: 0.7539 Val_AUC: 0.8708
ANN_model saved with Val_ACC: 0.8073 Val_AUC: 0.8944
ANN_model saved with Val_ACC: 0.8228 Val_AUC: 0.9056
ANN_model saved with Val_ACC: 0.8328 Val_AUC: 0.9146
ANN_model saved with Val_ACC: 0.8398 Val_AUC: 0.9215
ANN_model saved with Val_ACC: 0.8498 Val_AUC: 0.9280
ANN_model saved with Val_ACC: 0.8591 Val_AUC: 0.9333
ANN_model saved with Val_ACC: 0.8646 Val_AUC: 0.9382
ANN_model saved with Val_ACC: 0.8746 Val_AUC: 0.9423
ANN_model saved with Val_ACC: 0.8777 Val_AUC: 0.9454
ANN_model saved with Val_ACC: 0.8785 Val_AUC: 0.9473
ANN_model saved with Val_ACC: 0.8800 Val_AUC: 0.9499
ANN_model saved with Val_ACC: 0.8831 Val_AUC: 0.9513
ANN_model saved with Val_ACC: 0.8878 Val_AUC: 0.9521
ANN_model saved with Val_ACC: 0.8893 Val_AUC: 0.9556
fold_1: Epoch [21/200], Loss: 0.3681, Val_ACC: 0.8893, Val_AUC: 0.9556
ANN_model saved with Val_ACC: 0.8940 Val_AUC: 0.9565
ANN_model saved with Val_ACC: 0.8947 Val_AUC: 0.9569
ANN_model saved with Val_ACC: 0.8986 Val_AUC: 0.9589
fold_1: Epoch [41/200], Loss: 0.3381, Val_ACC: 0.8947, Val_AUC: 0.9589
fold_1: Epoch [61/200], Loss: 0.3289, Val_ACC: 0.8963, Val_AUC: 0.9588
fold_1: Epoch [81/200], Loss: 0.3244, Val_ACC: 0.8955, Val_AUC: 0.9588
fold_1: Epoch [101/200], Loss: 0.3217, Val_ACC: 0.8916, Val_AUC: 0.9586
fold_1: Epoch [121/200], Loss: 0.3200, Val_ACC: 0.8924, Val_AUC: 0.9586
fold_1: Epoch [141/200], Loss: 0.3187, Val_ACC: 0.8924, Val_AUC: 0.9585
fold_1: Epoch [161/200], Loss: 0.3178, Val_ACC: 0.8909, Val_AUC: 0.9584
fold_1: Epoch [181/200], Loss: 0.3171, Val_ACC: 0.8909, Val_AUC: 0.9584
TANN [0.3724229  0.00399106 0.9112192  ... 0.02692126 0.9458559  0.02267432]
Accuracy: 0.8986, AUC-ROC: 0.9589
 AUC-PR: 0.9545, Precision: 0.8959, Recall: 0.8973, F1 Score: 0.8966
RMSE: 10.0044 , PCC: 0.8324
Data processing and Training of MACSynDCR_ANN model:
MACSynDCR_ANN model:

Model: "sequential_50"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_200 (Dense)               │ (None, 2048)           │     4,982,784 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_125         │ (None, 2048)           │         8,192 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_201 (Dense)               │ (None, 1024)           │     2,098,176 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_126         │ (None, 1024)           │         4,096 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_202 (Dense)               │ (None, 512)            │       524,800 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_127         │ (None, 512)            │         2,048 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_203 (Dense)               │ (None, 256)            │       131,328 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_128         │ (None, 256)            │         1,024 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_204 (Dense)               │ (None, 128)            │        32,896 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_129         │ (None, 128)            │           512 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_205 (Dense)               │ (None, 2)              │           258 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 7,786,114 (29.70 MB)

 Trainable params: 7,778,178 (29.67 MB)

 Non-trainable params: 7,936 (31.00 KB)

Epoch 1/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step - acc: 0.7420 - auc: 0.8224 - loss: 0.5594
Epoch 1: val_auc improved from -inf to 0.68596, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_ANN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 13s 160ms/step - acc: 0.7431 - auc: 0.8235 - loss: 0.5573 - val_acc: 0.5820 - val_auc: 0.6860 - val_loss: 0.9920
Epoch 2/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step - acc: 0.8964 - auc: 0.9584 - loss: 0.2648
Epoch 2: val_auc improved from 0.68596 to 0.83042, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_ANN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 10s 147ms/step - acc: 0.8964 - auc: 0.9584 - loss: 0.2646 - val_acc: 0.7477 - val_auc: 0.8304 - val_loss: 0.5103
Epoch 3/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 167ms/step - acc: 0.9350 - auc: 0.9805 - loss: 0.1786
Epoch 3: val_auc improved from 0.83042 to 0.83485, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_ANN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 15s 263ms/step - acc: 0.9348 - auc: 0.9804 - loss: 0.1789 - val_acc: 0.7469 - val_auc: 0.8349 - val_loss: 0.5241
Epoch 4/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 171ms/step - acc: 0.9469 - auc: 0.9871 - loss: 0.1446
Epoch 4: val_auc improved from 0.83485 to 0.85302, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_ANN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 18s 193ms/step - acc: 0.9469 - auc: 0.9870 - loss: 0.1448 - val_acc: 0.7763 - val_auc: 0.8530 - val_loss: 0.5452
Epoch 5/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 132ms/step - acc: 0.9541 - auc: 0.9905 - loss: 0.1233
Epoch 5: val_auc improved from 0.85302 to 0.88490, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_ANN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 9s 163ms/step - acc: 0.9540 - auc: 0.9904 - loss: 0.1237 - val_acc: 0.7980 - val_auc: 0.8849 - val_loss: 0.4797
Epoch 6/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 142ms/step - acc: 0.9609 - auc: 0.9930 - loss: 0.1083
Epoch 6: val_auc improved from 0.88490 to 0.91685, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_ANN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 12s 201ms/step - acc: 0.9607 - auc: 0.9930 - loss: 0.1086 - val_acc: 0.8429 - val_auc: 0.9168 - val_loss: 0.4460
Epoch 7/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 165ms/step - acc: 0.9664 - auc: 0.9953 - loss: 0.0897
Epoch 7: val_auc improved from 0.91685 to 0.91861, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_ANN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 10s 190ms/step - acc: 0.9663 - auc: 0.9953 - loss: 0.0898 - val_acc: 0.8398 - val_auc: 0.9186 - val_loss: 0.4797
Epoch 8/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 151ms/step - acc: 0.9747 - auc: 0.9967 - loss: 0.0726
Epoch 8: val_auc improved from 0.91861 to 0.92782, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_ANN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 10s 177ms/step - acc: 0.9745 - auc: 0.9967 - loss: 0.0729 - val_acc: 0.8615 - val_auc: 0.9278 - val_loss: 0.4624
Epoch 9/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 141ms/step - acc: 0.9708 - auc: 0.9950 - loss: 0.0864
Epoch 9: val_auc improved from 0.92782 to 0.94096, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_ANN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 10s 163ms/step - acc: 0.9707 - auc: 0.9950 - loss: 0.0865 - val_acc: 0.8676 - val_auc: 0.9410 - val_loss: 0.4211
Epoch 10/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step - acc: 0.9721 - auc: 0.9965 - loss: 0.0738
Epoch 10: val_auc did not improve from 0.94096
41/41 ━━━━━━━━━━━━━━━━━━━━ 6s 139ms/step - acc: 0.9721 - auc: 0.9965 - loss: 0.0737 - val_acc: 0.8746 - val_auc: 0.9394 - val_loss: 0.3995
Epoch 11/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 142ms/step - acc: 0.9781 - auc: 0.9973 - loss: 0.0637
Epoch 11: val_auc improved from 0.94096 to 0.94705, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_ANN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 11s 169ms/step - acc: 0.9780 - auc: 0.9973 - loss: 0.0639 - val_acc: 0.8816 - val_auc: 0.9471 - val_loss: 0.3981
Epoch 12/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 138ms/step - acc: 0.9786 - auc: 0.9973 - loss: 0.0599
Epoch 12: val_auc did not improve from 0.94705
41/41 ━━━━━━━━━━━━━━━━━━━━ 6s 147ms/step - acc: 0.9786 - auc: 0.9973 - loss: 0.0600 - val_acc: 0.8669 - val_auc: 0.9250 - val_loss: 0.5219
Epoch 13/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 138ms/step - acc: 0.9858 - auc: 0.9986 - loss: 0.0450
Epoch 13: val_auc did not improve from 0.94705
41/41 ━━━━━━━━━━━━━━━━━━━━ 11s 155ms/step - acc: 0.9857 - auc: 0.9986 - loss: 0.0451 - val_acc: 0.8839 - val_auc: 0.9390 - val_loss: 0.4742
Epoch 14/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step - acc: 0.9874 - auc: 0.9984 - loss: 0.0391
Epoch 14: val_auc did not improve from 0.94705
41/41 ━━━━━━━━━━━━━━━━━━━━ 10s 142ms/step - acc: 0.9873 - auc: 0.9984 - loss: 0.0393 - val_acc: 0.8793 - val_auc: 0.9325 - val_loss: 0.5018
Epoch 15/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step - acc: 0.9866 - auc: 0.9985 - loss: 0.0388
Epoch 15: val_auc did not improve from 0.94705
41/41 ━━━━━━━━━━━━━━━━━━━━ 10s 139ms/step - acc: 0.9865 - auc: 0.9985 - loss: 0.0389 - val_acc: 0.8731 - val_auc: 0.9351 - val_loss: 0.4796
Epoch 16/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 124ms/step - acc: 0.9908 - auc: 0.9993 - loss: 0.0304
Epoch 16: val_auc did not improve from 0.94705
41/41 ━━━━━━━━━━━━━━━━━━━━ 10s 141ms/step - acc: 0.9907 - auc: 0.9992 - loss: 0.0305 - val_acc: 0.8707 - val_auc: 0.9345 - val_loss: 0.4743
Epoch 17/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 150ms/step - acc: 0.9886 - auc: 0.9990 - loss: 0.0352
Epoch 17: val_auc did not improve from 0.94705
41/41 ━━━━━━━━━━━━━━━━━━━━ 7s 167ms/step - acc: 0.9886 - auc: 0.9990 - loss: 0.0354 - val_acc: 0.8715 - val_auc: 0.9296 - val_loss: 0.5384
Epoch 18/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 131ms/step - acc: 0.9846 - auc: 0.9991 - loss: 0.0396
Epoch 18: val_auc did not improve from 0.94705
41/41 ━━━━━━━━━━━━━━━━━━━━ 6s 147ms/step - acc: 0.9845 - auc: 0.9990 - loss: 0.0399 - val_acc: 0.8676 - val_auc: 0.9311 - val_loss: 0.5179
Epoch 19/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step - acc: 0.9831 - auc: 0.9972 - loss: 0.0585
Epoch 19: val_auc did not improve from 0.94705
41/41 ━━━━━━━━━━━━━━━━━━━━ 10s 137ms/step - acc: 0.9831 - auc: 0.9972 - loss: 0.0585 - val_acc: 0.8731 - val_auc: 0.9350 - val_loss: 0.4779
Epoch 20/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 135ms/step - acc: 0.9838 - auc: 0.9981 - loss: 0.0467
Epoch 20: val_auc did not improve from 0.94705
41/41 ━━━━━━━━━━━━━━━━━━━━ 11s 152ms/step - acc: 0.9836 - auc: 0.9980 - loss: 0.0469 - val_acc: 0.8731 - val_auc: 0.9352 - val_loss: 0.4930
Epoch 21/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 145ms/step - acc: 0.9808 - auc: 0.9980 - loss: 0.0496
Epoch 21: val_auc did not improve from 0.94705
41/41 ━━━━━━━━━━━━━━━━━━━━ 10s 155ms/step - acc: 0.9809 - auc: 0.9980 - loss: 0.0496 - val_acc: 0.8870 - val_auc: 0.9368 - val_loss: 0.4731
Epoch 22/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 124ms/step - acc: 0.9875 - auc: 0.9979 - loss: 0.0408
Epoch 22: val_auc did not improve from 0.94705
41/41 ━━━━━━━━━━━━━━━━━━━━ 6s 141ms/step - acc: 0.9874 - auc: 0.9979 - loss: 0.0408 - val_acc: 0.8808 - val_auc: 0.9375 - val_loss: 0.4560
Epoch 23/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 142ms/step - acc: 0.9916 - auc: 0.9987 - loss: 0.0309
Epoch 23: val_auc did not improve from 0.94705
41/41 ━━━━━━━━━━━━━━━━━━━━ 6s 158ms/step - acc: 0.9916 - auc: 0.9987 - loss: 0.0309 - val_acc: 0.8808 - val_auc: 0.9349 - val_loss: 0.4965
Epoch 24/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 126ms/step - acc: 0.9884 - auc: 0.9989 - loss: 0.0350
Epoch 24: val_auc did not improve from 0.94705
41/41 ━━━━━━━━━━━━━━━━━━━━ 9s 139ms/step - acc: 0.9885 - auc: 0.9989 - loss: 0.0350 - val_acc: 0.8754 - val_auc: 0.9403 - val_loss: 0.4939
Epoch 25/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 126ms/step - acc: 0.9879 - auc: 0.9984 - loss: 0.0373
Epoch 25: val_auc did not improve from 0.94705
41/41 ━━━━━━━━━━━━━━━━━━━━ 10s 135ms/step - acc: 0.9879 - auc: 0.9984 - loss: 0.0374 - val_acc: 0.8707 - val_auc: 0.9314 - val_loss: 0.5277
Epoch 26/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 124ms/step - acc: 0.9829 - auc: 0.9979 - loss: 0.0500
Epoch 26: val_auc did not improve from 0.94705
41/41 ━━━━━━━━━━━━━━━━━━━━ 10s 134ms/step - acc: 0.9829 - auc: 0.9979 - loss: 0.0500 - val_acc: 0.8785 - val_auc: 0.9309 - val_loss: 0.5334
Epoch 27/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 144ms/step - acc: 0.9832 - auc: 0.9984 - loss: 0.0447
Epoch 27: val_auc did not improve from 0.94705
41/41 ━━━━━━━━━━━━━━━━━━━━ 7s 160ms/step - acc: 0.9833 - auc: 0.9984 - loss: 0.0447 - val_acc: 0.8824 - val_auc: 0.9436 - val_loss: 0.4485
Epoch 28/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 132ms/step - acc: 0.9858 - auc: 0.9983 - loss: 0.0432
Epoch 28: val_auc did not improve from 0.94705
41/41 ━━━━━━━━━━━━━━━━━━━━ 6s 150ms/step - acc: 0.9858 - auc: 0.9983 - loss: 0.0433 - val_acc: 0.8746 - val_auc: 0.9280 - val_loss: 0.5753
Epoch 29/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 124ms/step - acc: 0.9819 - auc: 0.9974 - loss: 0.0540
Epoch 29: val_auc did not improve from 0.94705
41/41 ━━━━━━━━━━━━━━━━━━━━ 10s 141ms/step - acc: 0.9819 - auc: 0.9974 - loss: 0.0540 - val_acc: 0.8769 - val_auc: 0.9337 - val_loss: 0.5263
Epoch 30/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 126ms/step - acc: 0.9894 - auc: 0.9992 - loss: 0.0319
Epoch 30: val_auc did not improve from 0.94705
41/41 ━━━━━━━━━━━━━━━━━━━━ 10s 143ms/step - acc: 0.9894 - auc: 0.9992 - loss: 0.0319 - val_acc: 0.8777 - val_auc: 0.9355 - val_loss: 0.5059
Epoch 31/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 140ms/step - acc: 0.9922 - auc: 0.9995 - loss: 0.0236
Epoch 31: val_auc did not improve from 0.94705
41/41 ━━━━━━━━━━━━━━━━━━━━ 11s 156ms/step - acc: 0.9922 - auc: 0.9995 - loss: 0.0237 - val_acc: 0.8816 - val_auc: 0.9388 - val_loss: 0.4949
Epoch 32/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step - acc: 0.9886 - auc: 0.9975 - loss: 0.0412
Epoch 32: val_auc did not improve from 0.94705
41/41 ━━━━━━━━━━━━━━━━━━━━ 5s 132ms/step - acc: 0.9886 - auc: 0.9976 - loss: 0.0411 - val_acc: 0.8808 - val_auc: 0.9411 - val_loss: 0.4945
Epoch 33/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 141ms/step - acc: 0.9917 - auc: 0.9991 - loss: 0.0262
Epoch 33: val_auc did not improve from 0.94705
41/41 ━━━━━━━━━━━━━━━━━━━━ 6s 151ms/step - acc: 0.9917 - auc: 0.9991 - loss: 0.0262 - val_acc: 0.8777 - val_auc: 0.9339 - val_loss: 0.5311
Epoch 34/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 124ms/step - acc: 0.9917 - auc: 0.9997 - loss: 0.0229
Epoch 34: val_auc did not improve from 0.94705
41/41 ━━━━━━━━━━━━━━━━━━━━ 5s 133ms/step - acc: 0.9917 - auc: 0.9997 - loss: 0.0229 - val_acc: 0.8940 - val_auc: 0.9433 - val_loss: 0.4921
Epoch 35/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 139ms/step - acc: 0.9936 - auc: 0.9991 - loss: 0.0194
Epoch 35: val_auc did not improve from 0.94705
41/41 ━━━━━━━━━━━━━━━━━━━━ 6s 155ms/step - acc: 0.9935 - auc: 0.9992 - loss: 0.0194 - val_acc: 0.8800 - val_auc: 0.9338 - val_loss: 0.5277
Epoch 36/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 131ms/step - acc: 0.9929 - auc: 0.9997 - loss: 0.0191
Epoch 36: val_auc did not improve from 0.94705
41/41 ━━━━━━━━━━━━━━━━━━━━ 10s 149ms/step - acc: 0.9930 - auc: 0.9997 - loss: 0.0190 - val_acc: 0.8824 - val_auc: 0.9411 - val_loss: 0.4939
Epoch 37/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 124ms/step - acc: 0.9932 - auc: 0.9992 - loss: 0.0195
Epoch 37: val_auc did not improve from 0.94705
41/41 ━━━━━━━━━━━━━━━━━━━━ 10s 141ms/step - acc: 0.9932 - auc: 0.9992 - loss: 0.0195 - val_acc: 0.8800 - val_auc: 0.9459 - val_loss: 0.4652
Epoch 38/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step - acc: 0.9983 - auc: 0.9997 - loss: 0.0091
Epoch 38: val_auc improved from 0.94705 to 0.94885, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_ANN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 10s 141ms/step - acc: 0.9982 - auc: 0.9997 - loss: 0.0092 - val_acc: 0.8909 - val_auc: 0.9489 - val_loss: 0.4324
Epoch 39/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 142ms/step - acc: 0.9954 - auc: 0.9995 - loss: 0.0172
Epoch 39: val_auc did not improve from 0.94885
41/41 ━━━━━━━━━━━━━━━━━━━━ 6s 152ms/step - acc: 0.9954 - auc: 0.9995 - loss: 0.0173 - val_acc: 0.8878 - val_auc: 0.9388 - val_loss: 0.4825
Epoch 40/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 173ms/step - acc: 0.9925 - auc: 0.9992 - loss: 0.0213
Epoch 40: val_auc did not improve from 0.94885
41/41 ━━━━━━━━━━━━━━━━━━━━ 12s 190ms/step - acc: 0.9924 - auc: 0.9992 - loss: 0.0214 - val_acc: 0.8785 - val_auc: 0.9372 - val_loss: 0.5112
Epoch 41/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step - acc: 0.9943 - auc: 0.9996 - loss: 0.0228
Epoch 41: val_auc did not improve from 0.94885
41/41 ━━━━━━━━━━━━━━━━━━━━ 8s 142ms/step - acc: 0.9943 - auc: 0.9996 - loss: 0.0228 - val_acc: 0.8847 - val_auc: 0.9393 - val_loss: 0.5170
Epoch 42/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 140ms/step - acc: 0.9857 - auc: 0.9982 - loss: 0.0418
Epoch 42: val_auc did not improve from 0.94885
41/41 ━━━━━━━━━━━━━━━━━━━━ 6s 150ms/step - acc: 0.9857 - auc: 0.9982 - loss: 0.0419 - val_acc: 0.8661 - val_auc: 0.9230 - val_loss: 0.6156
Epoch 43/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step - acc: 0.9879 - auc: 0.9987 - loss: 0.0376
Epoch 43: val_auc did not improve from 0.94885
41/41 ━━━━━━━━━━━━━━━━━━━━ 5s 131ms/step - acc: 0.9878 - auc: 0.9987 - loss: 0.0376 - val_acc: 0.8762 - val_auc: 0.9308 - val_loss: 0.5584
Epoch 44/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 142ms/step - acc: 0.9907 - auc: 0.9991 - loss: 0.0305
Epoch 44: val_auc did not improve from 0.94885
41/41 ━━━━━━━━━━━━━━━━━━━━ 6s 152ms/step - acc: 0.9906 - auc: 0.9991 - loss: 0.0306 - val_acc: 0.8700 - val_auc: 0.9277 - val_loss: 0.5880
Epoch 45/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step - acc: 0.9777 - auc: 0.9952 - loss: 0.0736
Epoch 45: val_auc did not improve from 0.94885
41/41 ━━━━━━━━━━━━━━━━━━━━ 6s 137ms/step - acc: 0.9777 - auc: 0.9952 - loss: 0.0736 - val_acc: 0.8854 - val_auc: 0.9341 - val_loss: 0.5058
Epoch 46/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 138ms/step - acc: 0.9890 - auc: 0.9987 - loss: 0.0392
Epoch 46: val_auc did not improve from 0.94885
41/41 ━━━━━━━━━━━━━━━━━━━━ 6s 155ms/step - acc: 0.9890 - auc: 0.9987 - loss: 0.0390 - val_acc: 0.8916 - val_auc: 0.9399 - val_loss: 0.4864
Epoch 47/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step - acc: 0.9967 - auc: 0.9999 - loss: 0.0130
Epoch 47: val_auc did not improve from 0.94885
41/41 ━━━━━━━━━━━━━━━━━━━━ 5s 130ms/step - acc: 0.9967 - auc: 0.9999 - loss: 0.0130 - val_acc: 0.8839 - val_auc: 0.9352 - val_loss: 0.5163
Epoch 48/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step - acc: 0.9944 - auc: 0.9997 - loss: 0.0154
Epoch 48: val_auc did not improve from 0.94885
41/41 ━━━━━━━━━━━━━━━━━━━━ 11s 138ms/step - acc: 0.9944 - auc: 0.9997 - loss: 0.0153 - val_acc: 0.8947 - val_auc: 0.9451 - val_loss: 0.4543
Epoch 49/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step - acc: 0.9972 - auc: 0.9999 - loss: 0.0110
Epoch 49: val_auc did not improve from 0.94885
41/41 ━━━━━━━━━━━━━━━━━━━━ 6s 145ms/step - acc: 0.9972 - auc: 0.9999 - loss: 0.0110 - val_acc: 0.8831 - val_auc: 0.9445 - val_loss: 0.4819
Epoch 50/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step - acc: 0.9972 - auc: 0.9988 - loss: 0.0164
Epoch 50: val_auc did not improve from 0.94885
41/41 ━━━━━━━━━━━━━━━━━━━━ 10s 139ms/step - acc: 0.9972 - auc: 0.9988 - loss: 0.0164 - val_acc: 0.8854 - val_auc: 0.9391 - val_loss: 0.5198
Epoch 51/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 145ms/step - acc: 0.9973 - auc: 0.9998 - loss: 0.0084
Epoch 51: val_auc did not improve from 0.94885
41/41 ━━━━━━━━━━━━━━━━━━━━ 7s 162ms/step - acc: 0.9973 - auc: 0.9998 - loss: 0.0084 - val_acc: 0.8901 - val_auc: 0.9445 - val_loss: 0.4831
Epoch 52/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 147ms/step - acc: 0.9989 - auc: 0.9999 - loss: 0.0054
Epoch 52: val_auc did not improve from 0.94885
41/41 ━━━━━━━━━━━━━━━━━━━━ 10s 164ms/step - acc: 0.9989 - auc: 0.9999 - loss: 0.0054 - val_acc: 0.8847 - val_auc: 0.9336 - val_loss: 0.5289
Epoch 53/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step - acc: 0.9941 - auc: 0.9989 - loss: 0.0195
Epoch 53: val_auc did not improve from 0.94885
41/41 ━━━━━━━━━━━━━━━━━━━━ 6s 141ms/step - acc: 0.9941 - auc: 0.9989 - loss: 0.0195 - val_acc: 0.8847 - val_auc: 0.9382 - val_loss: 0.5259
Epoch 54/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 167ms/step - acc: 0.9970 - auc: 0.9998 - loss: 0.0100
Epoch 54: val_auc did not improve from 0.94885
41/41 ━━━━━━━━━━━━━━━━━━━━ 8s 204ms/step - acc: 0.9969 - auc: 0.9998 - loss: 0.0102 - val_acc: 0.8785 - val_auc: 0.9400 - val_loss: 0.5096
Epoch 55/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step - acc: 0.9978 - auc: 0.9995 - loss: 0.0110
Epoch 55: val_auc did not improve from 0.94885
41/41 ━━━━━━━━━━━━━━━━━━━━ 8s 139ms/step - acc: 0.9977 - auc: 0.9995 - loss: 0.0111 - val_acc: 0.8924 - val_auc: 0.9379 - val_loss: 0.5116
Epoch 56/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step - acc: 0.9926 - auc: 0.9986 - loss: 0.0264
Epoch 56: val_auc did not improve from 0.94885
41/41 ━━━━━━━━━━━━━━━━━━━━ 10s 135ms/step - acc: 0.9925 - auc: 0.9986 - loss: 0.0265 - val_acc: 0.8762 - val_auc: 0.9301 - val_loss: 0.5939
Epoch 57/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step - acc: 0.9937 - auc: 0.9989 - loss: 0.0235
Epoch 57: val_auc did not improve from 0.94885
41/41 ━━━━━━━━━━━━━━━━━━━━ 10s 133ms/step - acc: 0.9937 - auc: 0.9989 - loss: 0.0235 - val_acc: 0.8785 - val_auc: 0.9333 - val_loss: 0.5671
Epoch 58/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 126ms/step - acc: 0.9901 - auc: 0.9987 - loss: 0.0299
Epoch 58: val_auc did not improve from 0.94885
41/41 ━━━━━━━━━━━━━━━━━━━━ 11s 143ms/step - acc: 0.9901 - auc: 0.9986 - loss: 0.0300 - val_acc: 0.8839 - val_auc: 0.9381 - val_loss: 0.5260
Epoch 59/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 133ms/step - acc: 0.9936 - auc: 0.9976 - loss: 0.0298
Epoch 59: val_auc did not improve from 0.94885
41/41 ━━━━━━━━━━━━━━━━━━━━ 6s 151ms/step - acc: 0.9936 - auc: 0.9977 - loss: 0.0296 - val_acc: 0.8854 - val_auc: 0.9440 - val_loss: 0.4857
Epoch 60/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step - acc: 0.9972 - auc: 1.0000 - loss: 0.0094
Epoch 60: val_auc did not improve from 0.94885
41/41 ━━━━━━━━━━━━━━━━━━━━ 10s 139ms/step - acc: 0.9972 - auc: 1.0000 - loss: 0.0094 - val_acc: 0.8831 - val_auc: 0.9374 - val_loss: 0.5428
Epoch 61/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step - acc: 0.9932 - auc: 0.9997 - loss: 0.0199
Epoch 61: val_auc did not improve from 0.94885
41/41 ━━━━━━━━━━━━━━━━━━━━ 10s 140ms/step - acc: 0.9932 - auc: 0.9997 - loss: 0.0199 - val_acc: 0.8839 - val_auc: 0.9338 - val_loss: 0.5681
Epoch 62/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 140ms/step - acc: 0.9920 - auc: 0.9990 - loss: 0.0273
Epoch 62: val_auc did not improve from 0.94885
41/41 ━━━━━━━━━━━━━━━━━━━━ 6s 157ms/step - acc: 0.9920 - auc: 0.9990 - loss: 0.0274 - val_acc: 0.8777 - val_auc: 0.9319 - val_loss: 0.5847
Epoch 63/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 132ms/step - acc: 0.9904 - auc: 0.9986 - loss: 0.0295
Epoch 63: val_auc did not improve from 0.94885
41/41 ━━━━━━━━━━━━━━━━━━━━ 10s 149ms/step - acc: 0.9904 - auc: 0.9986 - loss: 0.0296 - val_acc: 0.8839 - val_auc: 0.9329 - val_loss: 0.5370
Epoch 64/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step - acc: 0.9939 - auc: 0.9994 - loss: 0.0196
Epoch 64: val_auc did not improve from 0.94885
41/41 ━━━━━━━━━━━━━━━━━━━━ 10s 143ms/step - acc: 0.9939 - auc: 0.9994 - loss: 0.0197 - val_acc: 0.8808 - val_auc: 0.9282 - val_loss: 0.5990
Epoch 65/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step - acc: 0.9900 - auc: 0.9996 - loss: 0.0251
Epoch 65: val_auc did not improve from 0.94885
41/41 ━━━━━━━━━━━━━━━━━━━━ 10s 140ms/step - acc: 0.9901 - auc: 0.9996 - loss: 0.0250 - val_acc: 0.8777 - val_auc: 0.9240 - val_loss: 0.6629
Epoch 66/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step - acc: 0.9942 - auc: 0.9998 - loss: 0.0176
Epoch 66: val_auc did not improve from 0.94885
41/41 ━━━━━━━━━━━━━━━━━━━━ 10s 131ms/step - acc: 0.9941 - auc: 0.9997 - loss: 0.0177 - val_acc: 0.8684 - val_auc: 0.9246 - val_loss: 0.6787
Epoch 67/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 144ms/step - acc: 0.9898 - auc: 0.9988 - loss: 0.0306
Epoch 67: val_auc did not improve from 0.94885

Model: "sequential_51"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv2d_75 (Conv2D)              │ (None, 62, 36, 32)     │           320 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_75 (MaxPooling2D) │ (None, 31, 18, 32)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_75 (Dropout)            │ (None, 31, 18, 32)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_76 (Conv2D)              │ (None, 29, 16, 64)     │        18,496 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_76 (MaxPooling2D) │ (None, 14, 8, 64)      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_76 (Dropout)            │ (None, 14, 8, 64)      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_77 (Conv2D)              │ (None, 12, 6, 128)     │        73,856 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_77 (MaxPooling2D) │ (None, 6, 3, 128)      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_77 (Dropout)            │ (None, 6, 3, 128)      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_25 (Flatten)            │ (None, 2304)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_206 (Dense)               │ (None, 128)            │       295,040 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_207 (Dense)               │ (None, 2)              │           258 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 387,970 (1.48 MB)

 Trainable params: 387,970 (1.48 MB)

 Non-trainable params: 0 (0.00 B)

Epoch 1/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 329ms/step - acc: 0.5142 - auc: 0.5194 - loss: 0.7091
Epoch 1: val_acc improved from -inf to 0.51006, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_CNN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 18s 372ms/step - acc: 0.5143 - auc: 0.5195 - loss: 0.7088 - val_acc: 0.5101 - val_auc: 0.5963 - val_loss: 0.6912
Epoch 2/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 313ms/step - acc: 0.5077 - auc: 0.5265 - loss: 0.6921
Epoch 2: val_acc improved from 0.51006 to 0.57663, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_CNN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 19s 347ms/step - acc: 0.5082 - auc: 0.5270 - loss: 0.6921 - val_acc: 0.5766 - val_auc: 0.6952 - val_loss: 0.6768
Epoch 3/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 319ms/step - acc: 0.5797 - auc: 0.6207 - loss: 0.6738
Epoch 3: val_acc improved from 0.57663 to 0.76393, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_CNN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 15s 353ms/step - acc: 0.5807 - auc: 0.6222 - loss: 0.6733 - val_acc: 0.7639 - val_auc: 0.8246 - val_loss: 0.5569
Epoch 4/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 309ms/step - acc: 0.7393 - auc: 0.8065 - loss: 0.5452
Epoch 4: val_acc improved from 0.76393 to 0.77167, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_CNN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 14s 343ms/step - acc: 0.7395 - auc: 0.8068 - loss: 0.5447 - val_acc: 0.7717 - val_auc: 0.8498 - val_loss: 0.4845
Epoch 5/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 302ms/step - acc: 0.7738 - auc: 0.8550 - loss: 0.4757
Epoch 5: val_acc improved from 0.77167 to 0.77554, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_CNN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 20s 336ms/step - acc: 0.7736 - auc: 0.8548 - loss: 0.4759 - val_acc: 0.7755 - val_auc: 0.8615 - val_loss: 0.4791
Epoch 6/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 305ms/step - acc: 0.7864 - auc: 0.8675 - loss: 0.4574
Epoch 6: val_acc improved from 0.77554 to 0.80108, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_CNN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 21s 340ms/step - acc: 0.7863 - auc: 0.8674 - loss: 0.4574 - val_acc: 0.8011 - val_auc: 0.8793 - val_loss: 0.4379
Epoch 7/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 309ms/step - acc: 0.7880 - auc: 0.8679 - loss: 0.4555
Epoch 7: val_acc did not improve from 0.80108
41/41 ━━━━━━━━━━━━━━━━━━━━ 14s 329ms/step - acc: 0.7880 - auc: 0.8679 - loss: 0.4555 - val_acc: 0.7817 - val_auc: 0.8777 - val_loss: 0.4411
Epoch 8/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 308ms/step - acc: 0.8013 - auc: 0.8879 - loss: 0.4214
Epoch 8: val_acc improved from 0.80108 to 0.81037, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_CNN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 21s 342ms/step - acc: 0.8012 - auc: 0.8878 - loss: 0.4216 - val_acc: 0.8104 - val_auc: 0.8913 - val_loss: 0.4166
Epoch 9/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 302ms/step - acc: 0.8018 - auc: 0.8866 - loss: 0.4236
Epoch 9: val_acc improved from 0.81037 to 0.81424, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_CNN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 13s 324ms/step - acc: 0.8019 - auc: 0.8866 - loss: 0.4236 - val_acc: 0.8142 - val_auc: 0.8941 - val_loss: 0.4148
Epoch 10/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 303ms/step - acc: 0.8114 - auc: 0.8923 - loss: 0.4161
Epoch 10: val_acc improved from 0.81424 to 0.81579, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_CNN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 14s 337ms/step - acc: 0.8113 - auc: 0.8923 - loss: 0.4160 - val_acc: 0.8158 - val_auc: 0.8946 - val_loss: 0.4116
Epoch 11/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 303ms/step - acc: 0.8089 - auc: 0.8914 - loss: 0.4159
Epoch 11: val_acc improved from 0.81579 to 0.81656, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_CNN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 20s 337ms/step - acc: 0.8090 - auc: 0.8915 - loss: 0.4158 - val_acc: 0.8166 - val_auc: 0.8995 - val_loss: 0.4009
Epoch 12/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 322ms/step - acc: 0.8232 - auc: 0.8999 - loss: 0.3998
Epoch 12: val_acc improved from 0.81656 to 0.81734, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_CNN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 21s 357ms/step - acc: 0.8232 - auc: 0.8999 - loss: 0.3998 - val_acc: 0.8173 - val_auc: 0.9044 - val_loss: 0.3918
Epoch 13/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 300ms/step - acc: 0.8255 - auc: 0.9037 - loss: 0.3925
Epoch 13: val_acc did not improve from 0.81734
41/41 ━━━━━━━━━━━━━━━━━━━━ 20s 334ms/step - acc: 0.8253 - auc: 0.9035 - loss: 0.3927 - val_acc: 0.8166 - val_auc: 0.9034 - val_loss: 0.4003
Epoch 14/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 302ms/step - acc: 0.8260 - auc: 0.9035 - loss: 0.3934
Epoch 14: val_acc improved from 0.81734 to 0.82430, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_CNN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 20s 336ms/step - acc: 0.8261 - auc: 0.9036 - loss: 0.3932 - val_acc: 0.8243 - val_auc: 0.9054 - val_loss: 0.3904
Epoch 15/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 303ms/step - acc: 0.8338 - auc: 0.9090 - loss: 0.3840
Epoch 15: val_acc improved from 0.82430 to 0.82817, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_CNN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 21s 337ms/step - acc: 0.8338 - auc: 0.9090 - loss: 0.3840 - val_acc: 0.8282 - val_auc: 0.9131 - val_loss: 0.3808
Epoch 16/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 304ms/step - acc: 0.8236 - auc: 0.9120 - loss: 0.3780
Epoch 16: val_acc did not improve from 0.82817
41/41 ━━━━━━━━━━━━━━━━━━━━ 20s 337ms/step - acc: 0.8236 - auc: 0.9120 - loss: 0.3780 - val_acc: 0.8181 - val_auc: 0.9119 - val_loss: 0.3789
Epoch 17/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 303ms/step - acc: 0.8265 - auc: 0.9124 - loss: 0.3753
Epoch 17: val_acc improved from 0.82817 to 0.83591, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_CNN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 20s 337ms/step - acc: 0.8267 - auc: 0.9125 - loss: 0.3751 - val_acc: 0.8359 - val_auc: 0.9184 - val_loss: 0.3637
Epoch 18/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 306ms/step - acc: 0.8461 - auc: 0.9265 - loss: 0.3454
Epoch 18: val_acc improved from 0.83591 to 0.84598, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_CNN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 21s 341ms/step - acc: 0.8460 - auc: 0.9263 - loss: 0.3457 - val_acc: 0.8460 - val_auc: 0.9213 - val_loss: 0.3609
Epoch 19/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 312ms/step - acc: 0.8469 - auc: 0.9216 - loss: 0.3577
Epoch 19: val_acc improved from 0.84598 to 0.85604, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_CNN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 21s 346ms/step - acc: 0.8469 - auc: 0.9216 - loss: 0.3577 - val_acc: 0.8560 - val_auc: 0.9270 - val_loss: 0.3510
Epoch 20/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 302ms/step - acc: 0.8402 - auc: 0.9236 - loss: 0.3518
Epoch 20: val_acc did not improve from 0.85604
41/41 ━━━━━━━━━━━━━━━━━━━━ 20s 335ms/step - acc: 0.8404 - auc: 0.9236 - loss: 0.3517 - val_acc: 0.8491 - val_auc: 0.9274 - val_loss: 0.3441
Epoch 21/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 323ms/step - acc: 0.8595 - auc: 0.9325 - loss: 0.3313
Epoch 21: val_acc did not improve from 0.85604
41/41 ━━━━━━━━━━━━━━━━━━━━ 21s 356ms/step - acc: 0.8595 - auc: 0.9325 - loss: 0.3314 - val_acc: 0.8537 - val_auc: 0.9272 - val_loss: 0.3457
Epoch 22/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 306ms/step - acc: 0.8494 - auc: 0.9278 - loss: 0.3426
Epoch 22: val_acc improved from 0.85604 to 0.86687, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_CNN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 20s 341ms/step - acc: 0.8495 - auc: 0.9278 - loss: 0.3425 - val_acc: 0.8669 - val_auc: 0.9331 - val_loss: 0.3306
Epoch 23/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 307ms/step - acc: 0.8701 - auc: 0.9367 - loss: 0.3207
Epoch 23: val_acc improved from 0.86687 to 0.86997, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_CNN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 20s 341ms/step - acc: 0.8700 - auc: 0.9367 - loss: 0.3209 - val_acc: 0.8700 - val_auc: 0.9352 - val_loss: 0.3343
Epoch 24/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 311ms/step - acc: 0.8590 - auc: 0.9330 - loss: 0.3311
Epoch 24: val_acc did not improve from 0.86997
41/41 ━━━━━━━━━━━━━━━━━━━━ 21s 344ms/step - acc: 0.8592 - auc: 0.9331 - loss: 0.3309 - val_acc: 0.8630 - val_auc: 0.9363 - val_loss: 0.3227
Epoch 25/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 309ms/step - acc: 0.8652 - auc: 0.9427 - loss: 0.3067
Epoch 25: val_acc did not improve from 0.86997
41/41 ━━━━━━━━━━━━━━━━━━━━ 20s 341ms/step - acc: 0.8650 - auc: 0.9426 - loss: 0.3069 - val_acc: 0.8700 - val_auc: 0.9374 - val_loss: 0.3194
Epoch 26/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 313ms/step - acc: 0.8754 - auc: 0.9453 - loss: 0.2993
Epoch 26: val_acc did not improve from 0.86997
41/41 ━━━━━━━━━━━━━━━━━━━━ 21s 345ms/step - acc: 0.8752 - auc: 0.9452 - loss: 0.2995 - val_acc: 0.8669 - val_auc: 0.9364 - val_loss: 0.3225
Epoch 27/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 311ms/step - acc: 0.8633 - auc: 0.9385 - loss: 0.3167
Epoch 27: val_acc did not improve from 0.86997
41/41 ━━━━━━━━━━━━━━━━━━━━ 14s 343ms/step - acc: 0.8635 - auc: 0.9386 - loss: 0.3164 - val_acc: 0.8653 - val_auc: 0.9369 - val_loss: 0.3209
Epoch 28/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 314ms/step - acc: 0.8730 - auc: 0.9425 - loss: 0.3055
Epoch 28: val_acc improved from 0.86997 to 0.87616, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_CNN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 21s 348ms/step - acc: 0.8732 - auc: 0.9426 - loss: 0.3052 - val_acc: 0.8762 - val_auc: 0.9405 - val_loss: 0.3114
Epoch 29/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 305ms/step - acc: 0.8774 - auc: 0.9480 - loss: 0.2919
Epoch 29: val_acc did not improve from 0.87616
41/41 ━━━━━━━━━━━━━━━━━━━━ 20s 338ms/step - acc: 0.8773 - auc: 0.9479 - loss: 0.2920 - val_acc: 0.8731 - val_auc: 0.9386 - val_loss: 0.3188
Epoch 30/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 307ms/step - acc: 0.8813 - auc: 0.9484 - loss: 0.2917
Epoch 30: val_acc did not improve from 0.87616
41/41 ━━━━━━━━━━━━━━━━━━━━ 21s 339ms/step - acc: 0.8813 - auc: 0.9485 - loss: 0.2916 - val_acc: 0.8692 - val_auc: 0.9426 - val_loss: 0.3053
Epoch 31/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 332ms/step - acc: 0.8901 - auc: 0.9546 - loss: 0.2713
Epoch 31: val_acc did not improve from 0.87616
41/41 ━━━━━━━━━━━━━━━━━━━━ 21s 365ms/step - acc: 0.8899 - auc: 0.9546 - loss: 0.2715 - val_acc: 0.8661 - val_auc: 0.9404 - val_loss: 0.3119
Epoch 32/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 304ms/step - acc: 0.8855 - auc: 0.9516 - loss: 0.2813
Epoch 32: val_acc did not improve from 0.87616
41/41 ━━━━━━━━━━━━━━━━━━━━ 19s 325ms/step - acc: 0.8854 - auc: 0.9516 - loss: 0.2814 - val_acc: 0.8746 - val_auc: 0.9426 - val_loss: 0.3092
Epoch 33/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 309ms/step - acc: 0.8822 - auc: 0.9539 - loss: 0.2764
Epoch 33: val_acc did not improve from 0.87616
41/41 ━━━━━━━━━━━━━━━━━━━━ 14s 341ms/step - acc: 0.8823 - auc: 0.9539 - loss: 0.2764 - val_acc: 0.8715 - val_auc: 0.9400 - val_loss: 0.3119
Epoch 34/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 310ms/step - acc: 0.8876 - auc: 0.9552 - loss: 0.2708
Epoch 34: val_acc did not improve from 0.87616
41/41 ━━━━━━━━━━━━━━━━━━━━ 20s 339ms/step - acc: 0.8875 - auc: 0.9552 - loss: 0.2709 - val_acc: 0.8731 - val_auc: 0.9409 - val_loss: 0.3103
Epoch 35/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 305ms/step - acc: 0.8840 - auc: 0.9524 - loss: 0.2792
Epoch 35: val_acc did not improve from 0.87616
41/41 ━━━━━━━━━━━━━━━━━━━━ 20s 338ms/step - acc: 0.8840 - auc: 0.9525 - loss: 0.2791 - val_acc: 0.8746 - val_auc: 0.9418 - val_loss: 0.3074
Epoch 36/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 302ms/step - acc: 0.8836 - auc: 0.9559 - loss: 0.2696
Epoch 36: val_acc improved from 0.87616 to 0.87694, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_CNN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 20s 337ms/step - acc: 0.8836 - auc: 0.9559 - loss: 0.2696 - val_acc: 0.8769 - val_auc: 0.9458 - val_loss: 0.2995
Epoch 37/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 318ms/step - acc: 0.8874 - auc: 0.9570 - loss: 0.2653
Epoch 37: val_acc did not improve from 0.87694
41/41 ━━━━━━━━━━━━━━━━━━━━ 14s 341ms/step - acc: 0.8874 - auc: 0.9570 - loss: 0.2654 - val_acc: 0.8738 - val_auc: 0.9426 - val_loss: 0.3052
Epoch 38/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 313ms/step - acc: 0.9001 - auc: 0.9629 - loss: 0.2466
Epoch 38: val_acc improved from 0.87694 to 0.87771, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_CNN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 14s 347ms/step - acc: 0.8999 - auc: 0.9628 - loss: 0.2468 - val_acc: 0.8777 - val_auc: 0.9454 - val_loss: 0.2978
Epoch 39/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 304ms/step - acc: 0.8870 - auc: 0.9559 - loss: 0.2689
Epoch 39: val_acc did not improve from 0.87771
41/41 ━━━━━━━━━━━━━━━━━━━━ 20s 325ms/step - acc: 0.8870 - auc: 0.9559 - loss: 0.2688 - val_acc: 0.8777 - val_auc: 0.9424 - val_loss: 0.3059
Epoch 40/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 298ms/step - acc: 0.8947 - auc: 0.9618 - loss: 0.2506
Epoch 40: val_acc did not improve from 0.87771
41/41 ━━━━━━━━━━━━━━━━━━━━ 21s 332ms/step - acc: 0.8948 - auc: 0.9618 - loss: 0.2506 - val_acc: 0.8646 - val_auc: 0.9434 - val_loss: 0.3045
Epoch 41/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 303ms/step - acc: 0.8947 - auc: 0.9611 - loss: 0.2529
Epoch 41: val_acc did not improve from 0.87771
41/41 ━━━━━━━━━━━━━━━━━━━━ 14s 336ms/step - acc: 0.8947 - auc: 0.9611 - loss: 0.2530 - val_acc: 0.8669 - val_auc: 0.9426 - val_loss: 0.3085
Epoch 42/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 307ms/step - acc: 0.9150 - auc: 0.9697 - loss: 0.2235
Epoch 42: val_acc did not improve from 0.87771
41/41 ━━━━━━━━━━━━━━━━━━━━ 21s 340ms/step - acc: 0.9147 - auc: 0.9696 - loss: 0.2239 - val_acc: 0.8746 - val_auc: 0.9445 - val_loss: 0.3013
Epoch 43/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 304ms/step - acc: 0.8926 - auc: 0.9638 - loss: 0.2439
Epoch 43: val_acc did not improve from 0.87771
41/41 ━━━━━━━━━━━━━━━━━━━━ 20s 336ms/step - acc: 0.8927 - auc: 0.9638 - loss: 0.2438 - val_acc: 0.8715 - val_auc: 0.9444 - val_loss: 0.3031
Epoch 44/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 304ms/step - acc: 0.9010 - auc: 0.9660 - loss: 0.2362
Epoch 44: val_acc did not improve from 0.87771
41/41 ━━━━━━━━━━━━━━━━━━━━ 20s 336ms/step - acc: 0.9011 - auc: 0.9661 - loss: 0.2360 - val_acc: 0.8746 - val_auc: 0.9452 - val_loss: 0.3039
Epoch 45/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 307ms/step - acc: 0.9025 - auc: 0.9659 - loss: 0.2361
Epoch 45: val_acc did not improve from 0.87771
41/41 ━━━━━━━━━━━━━━━━━━━━ 21s 340ms/step - acc: 0.9023 - auc: 0.9659 - loss: 0.2363 - val_acc: 0.8762 - val_auc: 0.9464 - val_loss: 0.2970
Epoch 46/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 307ms/step - acc: 0.9056 - auc: 0.9692 - loss: 0.2253
Epoch 46: val_acc did not improve from 0.87771
41/41 ━━━━━━━━━━━━━━━━━━━━ 20s 329ms/step - acc: 0.9056 - auc: 0.9693 - loss: 0.2252 - val_acc: 0.8707 - val_auc: 0.9434 - val_loss: 0.3142
Epoch 47/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 304ms/step - acc: 0.9084 - auc: 0.9704 - loss: 0.2200
Epoch 47: val_acc did not improve from 0.87771
41/41 ━━━━━━━━━━━━━━━━━━━━ 21s 336ms/step - acc: 0.9083 - auc: 0.9703 - loss: 0.2202 - val_acc: 0.8769 - val_auc: 0.9447 - val_loss: 0.3019
Epoch 48/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 308ms/step - acc: 0.9140 - auc: 0.9744 - loss: 0.2065
Epoch 48: val_acc did not improve from 0.87771
41/41 ━━━━━━━━━━━━━━━━━━━━ 21s 340ms/step - acc: 0.9140 - auc: 0.9744 - loss: 0.2067 - val_acc: 0.8707 - val_auc: 0.9433 - val_loss: 0.3137
Epoch 49/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 311ms/step - acc: 0.9187 - auc: 0.9746 - loss: 0.2037
Epoch 49: val_acc did not improve from 0.87771
41/41 ━━━━━━━━━━━━━━━━━━━━ 14s 344ms/step - acc: 0.9185 - auc: 0.9745 - loss: 0.2040 - val_acc: 0.8723 - val_auc: 0.9457 - val_loss: 0.3041
Epoch 50/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 311ms/step - acc: 0.9206 - auc: 0.9737 - loss: 0.2070
Epoch 50: val_acc did not improve from 0.87771
41/41 ━━━━━━━━━━━━━━━━━━━━ 20s 344ms/step - acc: 0.9204 - auc: 0.9737 - loss: 0.2069 - val_acc: 0.8769 - val_auc: 0.9439 - val_loss: 0.3145
Epoch 51/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 329ms/step - acc: 0.9156 - auc: 0.9742 - loss: 0.2055
Epoch 51: val_acc did not improve from 0.87771
41/41 ━━━━━━━━━━━━━━━━━━━━ 21s 351ms/step - acc: 0.9157 - auc: 0.9742 - loss: 0.2055 - val_acc: 0.8715 - val_auc: 0.9446 - val_loss: 0.3124
Epoch 52/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 309ms/step - acc: 0.9105 - auc: 0.9712 - loss: 0.2169
Epoch 52: val_acc did not improve from 0.87771
41/41 ━━━━━━━━━━━━━━━━━━━━ 14s 342ms/step - acc: 0.9106 - auc: 0.9713 - loss: 0.2166 - val_acc: 0.8684 - val_auc: 0.9438 - val_loss: 0.3096
Epoch 53/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 314ms/step - acc: 0.9177 - auc: 0.9756 - loss: 0.2013
Epoch 53: val_acc improved from 0.87771 to 0.87848, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_CNN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 21s 349ms/step - acc: 0.9177 - auc: 0.9756 - loss: 0.2014 - val_acc: 0.8785 - val_auc: 0.9463 - val_loss: 0.3027
Epoch 54/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 310ms/step - acc: 0.9112 - auc: 0.9759 - loss: 0.2005
Epoch 54: val_acc did not improve from 0.87848
41/41 ━━━━━━━━━━━━━━━━━━━━ 20s 342ms/step - acc: 0.9112 - auc: 0.9759 - loss: 0.2006 - val_acc: 0.8777 - val_auc: 0.9443 - val_loss: 0.3069
Epoch 55/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 317ms/step - acc: 0.9230 - auc: 0.9773 - loss: 0.1927
Epoch 55: val_acc improved from 0.87848 to 0.87926, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_CNN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 21s 351ms/step - acc: 0.9229 - auc: 0.9773 - loss: 0.1929 - val_acc: 0.8793 - val_auc: 0.9445 - val_loss: 0.3077
Epoch 56/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 309ms/step - acc: 0.9255 - auc: 0.9775 - loss: 0.1908
Epoch 56: val_acc did not improve from 0.87926
41/41 ━━━━━━━━━━━━━━━━━━━━ 14s 331ms/step - acc: 0.9254 - auc: 0.9775 - loss: 0.1908 - val_acc: 0.8731 - val_auc: 0.9445 - val_loss: 0.3099
Epoch 57/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 303ms/step - acc: 0.9250 - auc: 0.9809 - loss: 0.1786
Epoch 57: val_acc did not improve from 0.87926
41/41 ━━━━━━━━━━━━━━━━━━━━ 13s 324ms/step - acc: 0.9251 - auc: 0.9809 - loss: 0.1786 - val_acc: 0.8715 - val_auc: 0.9451 - val_loss: 0.3152
Epoch 58/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 308ms/step - acc: 0.9269 - auc: 0.9810 - loss: 0.1776
Epoch 58: val_acc did not improve from 0.87926
41/41 ━━━━━━━━━━━━━━━━━━━━ 21s 340ms/step - acc: 0.9269 - auc: 0.9810 - loss: 0.1777 - val_acc: 0.8738 - val_auc: 0.9434 - val_loss: 0.3221
Epoch 59/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 309ms/step - acc: 0.9262 - auc: 0.9801 - loss: 0.1791
Epoch 59: val_acc improved from 0.87926 to 0.88390, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_CNN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 14s 343ms/step - acc: 0.9262 - auc: 0.9801 - loss: 0.1791 - val_acc: 0.8839 - val_auc: 0.9461 - val_loss: 0.3113
Epoch 60/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 312ms/step - acc: 0.9342 - auc: 0.9803 - loss: 0.1797
Epoch 60: val_acc did not improve from 0.88390
41/41 ━━━━━━━━━━━━━━━━━━━━ 14s 345ms/step - acc: 0.9341 - auc: 0.9803 - loss: 0.1796 - val_acc: 0.8769 - val_auc: 0.9422 - val_loss: 0.3302
Epoch 61/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 320ms/step - acc: 0.9200 - auc: 0.9784 - loss: 0.1874
Epoch 61: val_acc did not improve from 0.88390
41/41 ━━━━━━━━━━━━━━━━━━━━ 21s 354ms/step - acc: 0.9201 - auc: 0.9784 - loss: 0.1873 - val_acc: 0.8785 - val_auc: 0.9467 - val_loss: 0.3195
Epoch 62/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 310ms/step - acc: 0.9324 - auc: 0.9833 - loss: 0.1668
Epoch 62: val_acc did not improve from 0.88390
41/41 ━━━━━━━━━━━━━━━━━━━━ 14s 342ms/step - acc: 0.9323 - auc: 0.9832 - loss: 0.1669 - val_acc: 0.8746 - val_auc: 0.9451 - val_loss: 0.3164
Epoch 63/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 311ms/step - acc: 0.9332 - auc: 0.9827 - loss: 0.1667

Model: "sequential_52"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_208 (Dense)               │ (None, 2048)           │     4,982,784 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_130         │ (None, 2048)           │         8,192 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_209 (Dense)               │ (None, 1024)           │     2,098,176 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_131         │ (None, 1024)           │         4,096 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_210 (Dense)               │ (None, 512)            │       524,800 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_132         │ (None, 512)            │         2,048 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_211 (Dense)               │ (None, 256)            │       131,328 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_133         │ (None, 256)            │         1,024 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_212 (Dense)               │ (None, 128)            │        32,896 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_134         │ (None, 128)            │           512 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_213 (Dense)               │ (None, 2)              │           258 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 7,786,114 (29.70 MB)

 Trainable params: 7,778,178 (29.67 MB)

 Non-trainable params: 7,936 (31.00 KB)

Epoch 1/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 136ms/step - acc: 0.7412 - auc: 0.8057 - loss: 0.6011
Epoch 1: val_auc improved from -inf to 0.83148, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_ANN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 12s 192ms/step - acc: 0.7426 - auc: 0.8072 - loss: 0.5980 - val_acc: 0.7454 - val_auc: 0.8315 - val_loss: 0.5025
Epoch 2/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 134ms/step - acc: 0.8945 - auc: 0.9600 - loss: 0.2587
Epoch 2: val_auc did not improve from 0.83148
41/41 ━━━━━━━━━━━━━━━━━━━━ 9s 150ms/step - acc: 0.8945 - auc: 0.9600 - loss: 0.2587 - val_acc: 0.6819 - val_auc: 0.7513 - val_loss: 0.6836
Epoch 3/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 164ms/step - acc: 0.9360 - auc: 0.9815 - loss: 0.1771
Epoch 3: val_auc did not improve from 0.83148
41/41 ━━━━━━━━━━━━━━━━━━━━ 11s 181ms/step - acc: 0.9359 - auc: 0.9814 - loss: 0.1773 - val_acc: 0.7299 - val_auc: 0.8220 - val_loss: 0.6071
Epoch 4/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 153ms/step - acc: 0.9534 - auc: 0.9906 - loss: 0.1299
Epoch 4: val_auc improved from 0.83148 to 0.87283, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_ANN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 10s 181ms/step - acc: 0.9532 - auc: 0.9906 - loss: 0.1301 - val_acc: 0.7786 - val_auc: 0.8728 - val_loss: 0.5038
Epoch 5/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 138ms/step - acc: 0.9616 - auc: 0.9924 - loss: 0.1094
Epoch 5: val_auc improved from 0.87283 to 0.89035, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_ANN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 7s 161ms/step - acc: 0.9614 - auc: 0.9923 - loss: 0.1099 - val_acc: 0.8189 - val_auc: 0.8903 - val_loss: 0.5235
Epoch 6/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 149ms/step - acc: 0.9547 - auc: 0.9917 - loss: 0.1158
Epoch 6: val_auc improved from 0.89035 to 0.91277, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_ANN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 7s 176ms/step - acc: 0.9546 - auc: 0.9917 - loss: 0.1161 - val_acc: 0.8491 - val_auc: 0.9128 - val_loss: 0.5387
Epoch 7/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 160ms/step - acc: 0.9552 - auc: 0.9917 - loss: 0.1147
Epoch 7: val_auc improved from 0.91277 to 0.93529, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_ANN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 11s 197ms/step - acc: 0.9551 - auc: 0.9917 - loss: 0.1150 - val_acc: 0.8746 - val_auc: 0.9353 - val_loss: 0.4264
Epoch 8/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 132ms/step - acc: 0.9733 - auc: 0.9948 - loss: 0.0882
Epoch 8: val_auc improved from 0.93529 to 0.93995, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_ANN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 9s 159ms/step - acc: 0.9732 - auc: 0.9947 - loss: 0.0883 - val_acc: 0.8916 - val_auc: 0.9400 - val_loss: 0.4218
Epoch 9/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 154ms/step - acc: 0.9734 - auc: 0.9951 - loss: 0.0804
Epoch 9: val_auc did not improve from 0.93995
41/41 ━━━━━━━━━━━━━━━━━━━━ 11s 172ms/step - acc: 0.9734 - auc: 0.9951 - loss: 0.0805 - val_acc: 0.8824 - val_auc: 0.9390 - val_loss: 0.4357
Epoch 10/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 154ms/step - acc: 0.9742 - auc: 0.9966 - loss: 0.0713
Epoch 10: val_auc did not improve from 0.93995
41/41 ━━━━━━━━━━━━━━━━━━━━ 10s 164ms/step - acc: 0.9741 - auc: 0.9966 - loss: 0.0715 - val_acc: 0.8785 - val_auc: 0.9390 - val_loss: 0.4330
Epoch 11/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 133ms/step - acc: 0.9740 - auc: 0.9964 - loss: 0.0727
Epoch 11: val_auc improved from 0.93995 to 0.94916, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_ANN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 10s 162ms/step - acc: 0.9740 - auc: 0.9964 - loss: 0.0727 - val_acc: 0.8854 - val_auc: 0.9492 - val_loss: 0.3805
Epoch 12/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 153ms/step - acc: 0.9825 - auc: 0.9977 - loss: 0.0536
Epoch 12: val_auc improved from 0.94916 to 0.95075, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_ANN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 7s 181ms/step - acc: 0.9825 - auc: 0.9977 - loss: 0.0536 - val_acc: 0.8878 - val_auc: 0.9507 - val_loss: 0.3923
Epoch 13/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 139ms/step - acc: 0.9882 - auc: 0.9992 - loss: 0.0350
Epoch 13: val_auc did not improve from 0.95075
41/41 ━━━━━━━━━━━━━━━━━━━━ 9s 156ms/step - acc: 0.9882 - auc: 0.9992 - loss: 0.0350 - val_acc: 0.8785 - val_auc: 0.9468 - val_loss: 0.3976
Epoch 14/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 134ms/step - acc: 0.9883 - auc: 0.9988 - loss: 0.0376
Epoch 14: val_auc did not improve from 0.95075
41/41 ━━━━━━━━━━━━━━━━━━━━ 10s 151ms/step - acc: 0.9883 - auc: 0.9988 - loss: 0.0377 - val_acc: 0.8707 - val_auc: 0.9436 - val_loss: 0.4633
Epoch 15/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 145ms/step - acc: 0.9881 - auc: 0.9981 - loss: 0.0397
Epoch 15: val_auc did not improve from 0.95075
41/41 ━━━━━━━━━━━━━━━━━━━━ 7s 162ms/step - acc: 0.9880 - auc: 0.9981 - loss: 0.0399 - val_acc: 0.8824 - val_auc: 0.9412 - val_loss: 0.4682
Epoch 16/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 132ms/step - acc: 0.9830 - auc: 0.9975 - loss: 0.0525
Epoch 16: val_auc did not improve from 0.95075
41/41 ━━━━━━━━━━━━━━━━━━━━ 6s 149ms/step - acc: 0.9829 - auc: 0.9975 - loss: 0.0527 - val_acc: 0.8932 - val_auc: 0.9473 - val_loss: 0.3908
Epoch 17/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 136ms/step - acc: 0.9750 - auc: 0.9976 - loss: 0.0599
Epoch 17: val_auc did not improve from 0.95075
41/41 ━━━━━━━━━━━━━━━━━━━━ 10s 153ms/step - acc: 0.9750 - auc: 0.9976 - loss: 0.0601 - val_acc: 0.8723 - val_auc: 0.9397 - val_loss: 0.4640
Epoch 18/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 145ms/step - acc: 0.9793 - auc: 0.9978 - loss: 0.0543
Epoch 18: val_auc did not improve from 0.95075
41/41 ━━━━━━━━━━━━━━━━━━━━ 11s 162ms/step - acc: 0.9793 - auc: 0.9978 - loss: 0.0543 - val_acc: 0.8793 - val_auc: 0.9398 - val_loss: 0.4683
Epoch 19/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 148ms/step - acc: 0.9860 - auc: 0.9985 - loss: 0.0445
Epoch 19: val_auc did not improve from 0.95075
41/41 ━━━━━━━━━━━━━━━━━━━━ 7s 165ms/step - acc: 0.9860 - auc: 0.9985 - loss: 0.0445 - val_acc: 0.8854 - val_auc: 0.9412 - val_loss: 0.4555
Epoch 20/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 130ms/step - acc: 0.9849 - auc: 0.9987 - loss: 0.0423
Epoch 20: val_auc did not improve from 0.95075
41/41 ━━━━━━━━━━━━━━━━━━━━ 6s 146ms/step - acc: 0.9848 - auc: 0.9987 - loss: 0.0425 - val_acc: 0.8916 - val_auc: 0.9363 - val_loss: 0.4798
Epoch 21/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 138ms/step - acc: 0.9874 - auc: 0.9989 - loss: 0.0375
Epoch 21: val_auc did not improve from 0.95075
41/41 ━━━━━━━━━━━━━━━━━━━━ 10s 150ms/step - acc: 0.9874 - auc: 0.9989 - loss: 0.0377 - val_acc: 0.8932 - val_auc: 0.9472 - val_loss: 0.4499
Epoch 22/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 142ms/step - acc: 0.9880 - auc: 0.9986 - loss: 0.0344
Epoch 22: val_auc did not improve from 0.95075
41/41 ━━━━━━━━━━━━━━━━━━━━ 11s 159ms/step - acc: 0.9880 - auc: 0.9986 - loss: 0.0344 - val_acc: 0.8885 - val_auc: 0.9502 - val_loss: 0.4234
Epoch 23/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 149ms/step - acc: 0.9919 - auc: 0.9992 - loss: 0.0312
Epoch 23: val_auc did not improve from 0.95075
41/41 ━━━━━━━━━━━━━━━━━━━━ 10s 167ms/step - acc: 0.9919 - auc: 0.9992 - loss: 0.0313 - val_acc: 0.8854 - val_auc: 0.9400 - val_loss: 0.5271
Epoch 24/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 147ms/step - acc: 0.9850 - auc: 0.9985 - loss: 0.0439
Epoch 24: val_auc did not improve from 0.95075
41/41 ━━━━━━━━━━━━━━━━━━━━ 10s 164ms/step - acc: 0.9849 - auc: 0.9985 - loss: 0.0440 - val_acc: 0.8785 - val_auc: 0.9367 - val_loss: 0.5202
Epoch 25/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 134ms/step - acc: 0.9916 - auc: 0.9996 - loss: 0.0242
Epoch 25: val_auc did not improve from 0.95075
41/41 ━━━━━━━━━━━━━━━━━━━━ 10s 151ms/step - acc: 0.9916 - auc: 0.9996 - loss: 0.0242 - val_acc: 0.8862 - val_auc: 0.9473 - val_loss: 0.4675
Epoch 26/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 139ms/step - acc: 0.9909 - auc: 0.9991 - loss: 0.0273
Epoch 26: val_auc did not improve from 0.95075
41/41 ━━━━━━━━━━━━━━━━━━━━ 6s 149ms/step - acc: 0.9909 - auc: 0.9991 - loss: 0.0272 - val_acc: 0.8909 - val_auc: 0.9419 - val_loss: 0.5359
Epoch 27/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 130ms/step - acc: 0.9933 - auc: 0.9989 - loss: 0.0255
Epoch 27: val_auc did not improve from 0.95075
41/41 ━━━━━━━━━━━━━━━━━━━━ 6s 147ms/step - acc: 0.9932 - auc: 0.9989 - loss: 0.0256 - val_acc: 0.8885 - val_auc: 0.9481 - val_loss: 0.4433
Epoch 28/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 137ms/step - acc: 0.9967 - auc: 0.9995 - loss: 0.0162
Epoch 28: val_auc did not improve from 0.95075
41/41 ━━━━━━━━━━━━━━━━━━━━ 6s 154ms/step - acc: 0.9966 - auc: 0.9995 - loss: 0.0163 - val_acc: 0.8878 - val_auc: 0.9409 - val_loss: 0.5038
Epoch 29/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 131ms/step - acc: 0.9932 - auc: 0.9993 - loss: 0.0207
Epoch 29: val_auc improved from 0.95075 to 0.95221, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_ANN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 6s 157ms/step - acc: 0.9932 - auc: 0.9992 - loss: 0.0206 - val_acc: 0.8994 - val_auc: 0.9522 - val_loss: 0.4253
Epoch 30/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 140ms/step - acc: 0.9961 - auc: 0.9998 - loss: 0.0138
Epoch 30: val_auc did not improve from 0.95221
41/41 ━━━━━━━━━━━━━━━━━━━━ 6s 156ms/step - acc: 0.9960 - auc: 0.9998 - loss: 0.0139 - val_acc: 0.8831 - val_auc: 0.9431 - val_loss: 0.4807
Epoch 31/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 185ms/step - acc: 0.9906 - auc: 0.9990 - loss: 0.0282
Epoch 31: val_auc did not improve from 0.95221
41/41 ━━━━━━━━━━━━━━━━━━━━ 12s 202ms/step - acc: 0.9905 - auc: 0.9990 - loss: 0.0283 - val_acc: 0.8878 - val_auc: 0.9378 - val_loss: 0.5241
Epoch 32/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 149ms/step - acc: 0.9886 - auc: 0.9990 - loss: 0.0313
Epoch 32: val_auc did not improve from 0.95221
41/41 ━━━━━━━━━━━━━━━━━━━━ 8s 158ms/step - acc: 0.9886 - auc: 0.9990 - loss: 0.0312 - val_acc: 0.8746 - val_auc: 0.9389 - val_loss: 0.5428
Epoch 33/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 133ms/step - acc: 0.9932 - auc: 0.9995 - loss: 0.0231
Epoch 33: val_auc did not improve from 0.95221
41/41 ━━━━━━━━━━━━━━━━━━━━ 6s 149ms/step - acc: 0.9932 - auc: 0.9995 - loss: 0.0232 - val_acc: 0.8932 - val_auc: 0.9398 - val_loss: 0.5498
Epoch 34/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 129ms/step - acc: 0.9949 - auc: 0.9998 - loss: 0.0158
Epoch 34: val_auc did not improve from 0.95221
41/41 ━━━━━━━━━━━━━━━━━━━━ 10s 146ms/step - acc: 0.9949 - auc: 0.9998 - loss: 0.0158 - val_acc: 0.8932 - val_auc: 0.9307 - val_loss: 0.5843
Epoch 35/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 142ms/step - acc: 0.9955 - auc: 0.9991 - loss: 0.0173
Epoch 35: val_auc did not improve from 0.95221
41/41 ━━━━━━━━━━━━━━━━━━━━ 7s 159ms/step - acc: 0.9955 - auc: 0.9991 - loss: 0.0174 - val_acc: 0.8901 - val_auc: 0.9364 - val_loss: 0.5631
Epoch 36/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 131ms/step - acc: 0.9869 - auc: 0.9975 - loss: 0.0416
Epoch 36: val_auc did not improve from 0.95221
41/41 ━━━━━━━━━━━━━━━━━━━━ 10s 148ms/step - acc: 0.9869 - auc: 0.9975 - loss: 0.0416 - val_acc: 0.8769 - val_auc: 0.9302 - val_loss: 0.5426
Epoch 37/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 133ms/step - acc: 0.9854 - auc: 0.9983 - loss: 0.0401
Epoch 37: val_auc did not improve from 0.95221
41/41 ━━━━━━━━━━━━━━━━━━━━ 10s 143ms/step - acc: 0.9853 - auc: 0.9983 - loss: 0.0405 - val_acc: 0.8762 - val_auc: 0.9370 - val_loss: 0.5460
Epoch 38/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 154ms/step - acc: 0.9805 - auc: 0.9973 - loss: 0.0597
Epoch 38: val_auc did not improve from 0.95221
41/41 ━━━━━━━━━━━━━━━━━━━━ 11s 171ms/step - acc: 0.9806 - auc: 0.9973 - loss: 0.0596 - val_acc: 0.8893 - val_auc: 0.9388 - val_loss: 0.5344
Epoch 39/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 136ms/step - acc: 0.9901 - auc: 0.9995 - loss: 0.0257
Epoch 39: val_auc did not improve from 0.95221
41/41 ━━━━━━━━━━━━━━━━━━━━ 10s 153ms/step - acc: 0.9900 - auc: 0.9995 - loss: 0.0258 - val_acc: 0.8909 - val_auc: 0.9389 - val_loss: 0.5847
Epoch 40/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 139ms/step - acc: 0.9899 - auc: 0.9989 - loss: 0.0283
Epoch 40: val_auc did not improve from 0.95221
41/41 ━━━━━━━━━━━━━━━━━━━━ 10s 155ms/step - acc: 0.9899 - auc: 0.9989 - loss: 0.0283 - val_acc: 0.8854 - val_auc: 0.9420 - val_loss: 0.5403
Epoch 41/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 150ms/step - acc: 0.9898 - auc: 0.9988 - loss: 0.0327
Epoch 41: val_auc did not improve from 0.95221
41/41 ━━━━━━━━━━━━━━━━━━━━ 11s 167ms/step - acc: 0.9898 - auc: 0.9988 - loss: 0.0328 - val_acc: 0.8916 - val_auc: 0.9404 - val_loss: 0.5269
Epoch 42/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 133ms/step - acc: 0.9898 - auc: 0.9988 - loss: 0.0332
Epoch 42: val_auc did not improve from 0.95221
41/41 ━━━━━━━━━━━━━━━━━━━━ 6s 150ms/step - acc: 0.9898 - auc: 0.9988 - loss: 0.0331 - val_acc: 0.8924 - val_auc: 0.9358 - val_loss: 0.5282
Epoch 43/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 150ms/step - acc: 0.9919 - auc: 0.9996 - loss: 0.0205
Epoch 43: val_auc did not improve from 0.95221
41/41 ━━━━━━━━━━━━━━━━━━━━ 7s 161ms/step - acc: 0.9919 - auc: 0.9996 - loss: 0.0205 - val_acc: 0.8916 - val_auc: 0.9379 - val_loss: 0.5519
Epoch 44/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 132ms/step - acc: 0.9941 - auc: 0.9991 - loss: 0.0210
Epoch 44: val_auc did not improve from 0.95221
41/41 ━━━━━━━━━━━━━━━━━━━━ 6s 149ms/step - acc: 0.9941 - auc: 0.9991 - loss: 0.0210 - val_acc: 0.8901 - val_auc: 0.9430 - val_loss: 0.4987
Epoch 45/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 135ms/step - acc: 0.9959 - auc: 0.9991 - loss: 0.0173
Epoch 45: val_auc did not improve from 0.95221
41/41 ━━━━━━━━━━━━━━━━━━━━ 10s 146ms/step - acc: 0.9959 - auc: 0.9991 - loss: 0.0173 - val_acc: 0.8885 - val_auc: 0.9415 - val_loss: 0.4871
Epoch 46/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 158ms/step - acc: 0.9965 - auc: 0.9993 - loss: 0.0161
Epoch 46: val_auc did not improve from 0.95221
41/41 ━━━━━━━━━━━━━━━━━━━━ 7s 175ms/step - acc: 0.9965 - auc: 0.9993 - loss: 0.0160 - val_acc: 0.8901 - val_auc: 0.9416 - val_loss: 0.5085
Epoch 47/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 150ms/step - acc: 0.9947 - auc: 0.9997 - loss: 0.0146
Epoch 47: val_auc did not improve from 0.95221
41/41 ━━━━━━━━━━━━━━━━━━━━ 10s 167ms/step - acc: 0.9947 - auc: 0.9997 - loss: 0.0146 - val_acc: 0.9009 - val_auc: 0.9438 - val_loss: 0.4535
Epoch 48/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 132ms/step - acc: 0.9985 - auc: 0.9999 - loss: 0.0064
Epoch 48: val_auc did not improve from 0.95221
41/41 ━━━━━━━━━━━━━━━━━━━━ 6s 149ms/step - acc: 0.9985 - auc: 0.9999 - loss: 0.0064 - val_acc: 0.8994 - val_auc: 0.9460 - val_loss: 0.4573
Epoch 49/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 148ms/step - acc: 0.9959 - auc: 0.9999 - loss: 0.0098
Epoch 49: val_auc did not improve from 0.95221
41/41 ━━━━━━━━━━━━━━━━━━━━ 7s 165ms/step - acc: 0.9960 - auc: 0.9999 - loss: 0.0098 - val_acc: 0.8947 - val_auc: 0.9411 - val_loss: 0.5044
Epoch 50/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 132ms/step - acc: 0.9964 - auc: 0.9994 - loss: 0.0171
Epoch 50: val_auc did not improve from 0.95221
41/41 ━━━━━━━━━━━━━━━━━━━━ 6s 149ms/step - acc: 0.9964 - auc: 0.9994 - loss: 0.0172 - val_acc: 0.8955 - val_auc: 0.9418 - val_loss: 0.5096
Epoch 51/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 136ms/step - acc: 0.9951 - auc: 0.9994 - loss: 0.0165
Epoch 51: val_auc did not improve from 0.95221
41/41 ━━━━━━━━━━━━━━━━━━━━ 10s 153ms/step - acc: 0.9951 - auc: 0.9994 - loss: 0.0166 - val_acc: 0.8916 - val_auc: 0.9395 - val_loss: 0.5416
Epoch 52/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 142ms/step - acc: 0.9924 - auc: 0.9993 - loss: 0.0193
Epoch 52: val_auc did not improve from 0.95221
41/41 ━━━━━━━━━━━━━━━━━━━━ 7s 159ms/step - acc: 0.9924 - auc: 0.9993 - loss: 0.0195 - val_acc: 0.8854 - val_auc: 0.9358 - val_loss: 0.6118
Epoch 53/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 132ms/step - acc: 0.9886 - auc: 0.9984 - loss: 0.0385
Epoch 53: val_auc did not improve from 0.95221
41/41 ━━━━━━━━━━━━━━━━━━━━ 10s 149ms/step - acc: 0.9885 - auc: 0.9984 - loss: 0.0385 - val_acc: 0.8994 - val_auc: 0.9445 - val_loss: 0.4963
Epoch 54/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 135ms/step - acc: 0.9902 - auc: 0.9989 - loss: 0.0316
Epoch 54: val_auc did not improve from 0.95221
41/41 ━━━━━━━━━━━━━━━━━━━━ 10s 153ms/step - acc: 0.9902 - auc: 0.9989 - loss: 0.0317 - val_acc: 0.8777 - val_auc: 0.9362 - val_loss: 0.6091
Epoch 55/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 134ms/step - acc: 0.9922 - auc: 0.9992 - loss: 0.0257
Epoch 55: val_auc did not improve from 0.95221
41/41 ━━━━━━━━━━━━━━━━━━━━ 10s 150ms/step - acc: 0.9921 - auc: 0.9992 - loss: 0.0258 - val_acc: 0.8824 - val_auc: 0.9341 - val_loss: 0.5709
Epoch 56/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 150ms/step - acc: 0.9904 - auc: 0.9985 - loss: 0.0310
Epoch 56: val_auc did not improve from 0.95221
41/41 ━━━━━━━━━━━━━━━━━━━━ 7s 167ms/step - acc: 0.9904 - auc: 0.9985 - loss: 0.0310 - val_acc: 0.8808 - val_auc: 0.9349 - val_loss: 0.5901
Epoch 57/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 142ms/step - acc: 0.9949 - auc: 0.9987 - loss: 0.0241
Epoch 57: val_auc did not improve from 0.95221
41/41 ━━━━━━━━━━━━━━━━━━━━ 10s 157ms/step - acc: 0.9949 - auc: 0.9988 - loss: 0.0241 - val_acc: 0.8816 - val_auc: 0.9388 - val_loss: 0.5818
Epoch 58/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 157ms/step - acc: 0.9957 - auc: 0.9999 - loss: 0.0117
Epoch 58: val_auc did not improve from 0.95221
41/41 ━━━━━━━━━━━━━━━━━━━━ 11s 174ms/step - acc: 0.9957 - auc: 0.9999 - loss: 0.0117 - val_acc: 0.8901 - val_auc: 0.9385 - val_loss: 0.5576
Epoch 59/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 150ms/step - acc: 0.9926 - auc: 0.9995 - loss: 0.0176
Epoch 59: val_auc did not improve from 0.95221
41/41 ━━━━━━━━━━━━━━━━━━━━ 7s 167ms/step - acc: 0.9926 - auc: 0.9995 - loss: 0.0177 - val_acc: 0.8932 - val_auc: 0.9424 - val_loss: 0.5185
Epoch 60/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 159ms/step - acc: 0.9911 - auc: 0.9988 - loss: 0.0278
Epoch 60: val_auc did not improve from 0.95221
41/41 ━━━━━━━━━━━━━━━━━━━━ 10s 175ms/step - acc: 0.9911 - auc: 0.9988 - loss: 0.0278 - val_acc: 0.8885 - val_auc: 0.9439 - val_loss: 0.5085
Epoch 61/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 150ms/step - acc: 0.9948 - auc: 0.9998 - loss: 0.0165
Epoch 61: val_auc did not improve from 0.95221
41/41 ━━━━━━━━━━━━━━━━━━━━ 10s 167ms/step - acc: 0.9948 - auc: 0.9998 - loss: 0.0165 - val_acc: 0.8808 - val_auc: 0.9404 - val_loss: 0.5518
Epoch 62/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 135ms/step - acc: 0.9945 - auc: 0.9994 - loss: 0.0216
Epoch 62: val_auc did not improve from 0.95221
41/41 ━━━━━━━━━━━━━━━━━━━━ 10s 152ms/step - acc: 0.9945 - auc: 0.9994 - loss: 0.0217 - val_acc: 0.8947 - val_auc: 0.9375 - val_loss: 0.5634
Epoch 63/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 136ms/step - acc: 0.9932 - auc: 0.9991 - loss: 0.0217
Epoch 63: val_auc did not improve from 0.95221
41/41 ━━━━━━━━━━━━━━━━━━━━ 10s 153ms/step - acc: 0.9932 - auc: 0.9991 - loss: 0.0216 - val_acc: 0.8963 - val_auc: 0.9452 - val_loss: 0.4967
Epoch 64/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 152ms/step - acc: 0.9956 - auc: 0.9999 - loss: 0.0113
Epoch 64: val_auc did not improve from 0.95221
41/41 ━━━━━━━━━━━━━━━━━━━━ 7s 169ms/step - acc: 0.9956 - auc: 0.9999 - loss: 0.0113 - val_acc: 0.8916 - val_auc: 0.9352 - val_loss: 0.5490
Epoch 65/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 131ms/step - acc: 0.9990 - auc: 0.9998 - loss: 0.0071
Epoch 65: val_auc did not improve from 0.95221
41/41 ━━━━━━━━━━━━━━━━━━━━ 6s 147ms/step - acc: 0.9990 - auc: 0.9998 - loss: 0.0071 - val_acc: 0.8893 - val_auc: 0.9419 - val_loss: 0.5028
Epoch 66/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 133ms/step - acc: 0.9952 - auc: 0.9983 - loss: 0.0232
Epoch 66: val_auc did not improve from 0.95221
41/41 ━━━━━━━━━━━━━━━━━━━━ 10s 143ms/step - acc: 0.9952 - auc: 0.9983 - loss: 0.0231 - val_acc: 0.8816 - val_auc: 0.9384 - val_loss: 0.5459
Epoch 67/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 149ms/step - acc: 0.9901 - auc: 0.9986 - loss: 0.0320
Epoch 67: val_auc did not improve from 0.95221
41/41 ━━━━━━━━━━━━━━━━━━━━ 7s 165ms/step - acc: 0.9901 - auc: 0.9986 - loss: 0.0320 - val_acc: 0.8738 - val_auc: 0.9226 - val_loss: 0.6273
Epoch 68/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 133ms/step - acc: 0.9919 - auc: 0.9992 - loss: 0.0235
Epoch 68: val_auc did not improve from 0.95221

Model: "sequential_53"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv2d_78 (Conv2D)              │ (None, 62, 36, 32)     │           320 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_78 (MaxPooling2D) │ (None, 31, 18, 32)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_78 (Dropout)            │ (None, 31, 18, 32)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_79 (Conv2D)              │ (None, 29, 16, 64)     │        18,496 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_79 (MaxPooling2D) │ (None, 14, 8, 64)      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_79 (Dropout)            │ (None, 14, 8, 64)      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_80 (Conv2D)              │ (None, 12, 6, 128)     │        73,856 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_80 (MaxPooling2D) │ (None, 6, 3, 128)      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_80 (Dropout)            │ (None, 6, 3, 128)      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_26 (Flatten)            │ (None, 2304)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_214 (Dense)               │ (None, 128)            │       295,040 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_215 (Dense)               │ (None, 2)              │           258 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 387,970 (1.48 MB)

 Trainable params: 387,970 (1.48 MB)

 Non-trainable params: 0 (0.00 B)

Epoch 1/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 309ms/step - acc: 0.5001 - auc: 0.5011 - loss: 0.7079
Epoch 1: val_acc improved from -inf to 0.50232, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_CNN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 17s 351ms/step - acc: 0.5003 - auc: 0.5013 - loss: 0.7077 - val_acc: 0.5023 - val_auc: 0.5849 - val_loss: 0.6922
Epoch 2/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 310ms/step - acc: 0.5247 - auc: 0.5364 - loss: 0.6917
Epoch 2: val_acc improved from 0.50232 to 0.53947, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_CNN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 14s 345ms/step - acc: 0.5250 - auc: 0.5367 - loss: 0.6916 - val_acc: 0.5395 - val_auc: 0.6723 - val_loss: 0.6841
Epoch 3/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 313ms/step - acc: 0.5815 - auc: 0.6277 - loss: 0.6772
Epoch 3: val_acc improved from 0.53947 to 0.62694, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_CNN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 21s 347ms/step - acc: 0.5821 - auc: 0.6283 - loss: 0.6768 - val_acc: 0.6269 - val_auc: 0.7342 - val_loss: 0.6171
Epoch 4/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 308ms/step - acc: 0.7024 - auc: 0.7726 - loss: 0.5751
Epoch 4: val_acc improved from 0.62694 to 0.78328, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_CNN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 20s 343ms/step - acc: 0.7030 - auc: 0.7732 - loss: 0.5744 - val_acc: 0.7833 - val_auc: 0.8543 - val_loss: 0.4771
Epoch 5/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 311ms/step - acc: 0.7659 - auc: 0.8486 - loss: 0.4832
Epoch 5: val_acc improved from 0.78328 to 0.79412, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_CNN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 21s 345ms/step - acc: 0.7659 - auc: 0.8486 - loss: 0.4832 - val_acc: 0.7941 - val_auc: 0.8818 - val_loss: 0.4334
Epoch 6/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 311ms/step - acc: 0.7884 - auc: 0.8712 - loss: 0.4484
Epoch 6: val_acc did not improve from 0.79412
41/41 ━━━━━━━━━━━━━━━━━━━━ 14s 343ms/step - acc: 0.7884 - auc: 0.8711 - loss: 0.4486 - val_acc: 0.7879 - val_auc: 0.8655 - val_loss: 0.4592
Epoch 7/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 312ms/step - acc: 0.7935 - auc: 0.8811 - loss: 0.4340
Epoch 7: val_acc improved from 0.79412 to 0.79954, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_CNN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 21s 347ms/step - acc: 0.7934 - auc: 0.8810 - loss: 0.4341 - val_acc: 0.7995 - val_auc: 0.8882 - val_loss: 0.4261
Epoch 8/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 312ms/step - acc: 0.7939 - auc: 0.8800 - loss: 0.4362
Epoch 8: val_acc improved from 0.79954 to 0.81579, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_CNN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 20s 335ms/step - acc: 0.7939 - auc: 0.8799 - loss: 0.4362 - val_acc: 0.8158 - val_auc: 0.8972 - val_loss: 0.4053
Epoch 9/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 311ms/step - acc: 0.8133 - auc: 0.8995 - loss: 0.3995
Epoch 9: val_acc did not improve from 0.81579
41/41 ━━━━━━━━━━━━━━━━━━━━ 21s 344ms/step - acc: 0.8131 - auc: 0.8992 - loss: 0.3999 - val_acc: 0.8119 - val_auc: 0.8997 - val_loss: 0.4014
Epoch 10/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 311ms/step - acc: 0.8027 - auc: 0.8879 - loss: 0.4210
Epoch 10: val_acc improved from 0.81579 to 0.82043, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_CNN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 14s 338ms/step - acc: 0.8027 - auc: 0.8879 - loss: 0.4210 - val_acc: 0.8204 - val_auc: 0.9024 - val_loss: 0.3962
Epoch 11/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 310ms/step - acc: 0.8226 - auc: 0.9008 - loss: 0.3985
Epoch 11: val_acc did not improve from 0.82043
41/41 ━━━━━━━━━━━━━━━━━━━━ 14s 343ms/step - acc: 0.8224 - auc: 0.9007 - loss: 0.3987 - val_acc: 0.8189 - val_auc: 0.9008 - val_loss: 0.3993
Epoch 12/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 308ms/step - acc: 0.8217 - auc: 0.9024 - loss: 0.3950
Epoch 12: val_acc improved from 0.82043 to 0.82740, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_CNN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 14s 342ms/step - acc: 0.8216 - auc: 0.9023 - loss: 0.3952 - val_acc: 0.8274 - val_auc: 0.9096 - val_loss: 0.3820
Epoch 13/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 314ms/step - acc: 0.8139 - auc: 0.8929 - loss: 0.4120
Epoch 13: val_acc improved from 0.82740 to 0.83282, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_CNN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 14s 348ms/step - acc: 0.8139 - auc: 0.8929 - loss: 0.4118 - val_acc: 0.8328 - val_auc: 0.9100 - val_loss: 0.3809
Epoch 14/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 313ms/step - acc: 0.8229 - auc: 0.9036 - loss: 0.3934
Epoch 14: val_acc improved from 0.83282 to 0.83591, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_CNN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 20s 347ms/step - acc: 0.8228 - auc: 0.9035 - loss: 0.3934 - val_acc: 0.8359 - val_auc: 0.9051 - val_loss: 0.3909
Epoch 15/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 307ms/step - acc: 0.8313 - auc: 0.9085 - loss: 0.3846
Epoch 15: val_acc did not improve from 0.83591
41/41 ━━━━━━━━━━━━━━━━━━━━ 20s 335ms/step - acc: 0.8312 - auc: 0.9085 - loss: 0.3846 - val_acc: 0.8351 - val_auc: 0.9063 - val_loss: 0.3899
Epoch 16/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 305ms/step - acc: 0.8280 - auc: 0.9102 - loss: 0.3813
Epoch 16: val_acc improved from 0.83591 to 0.84443, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_CNN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 14s 340ms/step - acc: 0.8280 - auc: 0.9101 - loss: 0.3814 - val_acc: 0.8444 - val_auc: 0.9178 - val_loss: 0.3642
Epoch 17/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 310ms/step - acc: 0.8420 - auc: 0.9161 - loss: 0.3683
Epoch 17: val_acc improved from 0.84443 to 0.84675, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_CNN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 14s 345ms/step - acc: 0.8419 - auc: 0.9160 - loss: 0.3685 - val_acc: 0.8467 - val_auc: 0.9203 - val_loss: 0.3607
Epoch 18/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 311ms/step - acc: 0.8551 - auc: 0.9283 - loss: 0.3435
Epoch 18: val_acc improved from 0.84675 to 0.85139, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_CNN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 20s 345ms/step - acc: 0.8548 - auc: 0.9281 - loss: 0.3439 - val_acc: 0.8514 - val_auc: 0.9209 - val_loss: 0.3598
Epoch 19/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 309ms/step - acc: 0.8449 - auc: 0.9206 - loss: 0.3591
Epoch 19: val_acc improved from 0.85139 to 0.85604, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_CNN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 20s 331ms/step - acc: 0.8450 - auc: 0.9206 - loss: 0.3589 - val_acc: 0.8560 - val_auc: 0.9249 - val_loss: 0.3477
Epoch 20/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 307ms/step - acc: 0.8437 - auc: 0.9257 - loss: 0.3470
Epoch 20: val_acc did not improve from 0.85604
41/41 ━━━━━━━━━━━━━━━━━━━━ 20s 328ms/step - acc: 0.8438 - auc: 0.9257 - loss: 0.3471 - val_acc: 0.8560 - val_auc: 0.9281 - val_loss: 0.3404
Epoch 21/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 307ms/step - acc: 0.8583 - auc: 0.9295 - loss: 0.3383
Epoch 21: val_acc did not improve from 0.85604
41/41 ━━━━━━━━━━━━━━━━━━━━ 21s 340ms/step - acc: 0.8583 - auc: 0.9295 - loss: 0.3384 - val_acc: 0.8545 - val_auc: 0.9276 - val_loss: 0.3418
Epoch 22/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 310ms/step - acc: 0.8585 - auc: 0.9314 - loss: 0.3348
Epoch 22: val_acc improved from 0.85604 to 0.85913, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_CNN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 14s 332ms/step - acc: 0.8585 - auc: 0.9314 - loss: 0.3348 - val_acc: 0.8591 - val_auc: 0.9298 - val_loss: 0.3369
Epoch 23/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 311ms/step - acc: 0.8703 - auc: 0.9384 - loss: 0.3168
Epoch 23: val_acc improved from 0.85913 to 0.87616, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_CNN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 14s 333ms/step - acc: 0.8702 - auc: 0.9383 - loss: 0.3170 - val_acc: 0.8762 - val_auc: 0.9344 - val_loss: 0.3248
Epoch 24/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 303ms/step - acc: 0.8704 - auc: 0.9411 - loss: 0.3103
Epoch 24: val_acc did not improve from 0.87616
41/41 ━━━━━━━━━━━━━━━━━━━━ 21s 336ms/step - acc: 0.8703 - auc: 0.9410 - loss: 0.3105 - val_acc: 0.8700 - val_auc: 0.9335 - val_loss: 0.3287
Epoch 25/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 305ms/step - acc: 0.8652 - auc: 0.9398 - loss: 0.3149
Epoch 25: val_acc did not improve from 0.87616
41/41 ━━━━━━━━━━━━━━━━━━━━ 14s 338ms/step - acc: 0.8653 - auc: 0.9398 - loss: 0.3149 - val_acc: 0.8676 - val_auc: 0.9351 - val_loss: 0.3229
Epoch 26/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 305ms/step - acc: 0.8714 - auc: 0.9395 - loss: 0.3138
Epoch 26: val_acc did not improve from 0.87616
41/41 ━━━━━━━━━━━━━━━━━━━━ 13s 325ms/step - acc: 0.8714 - auc: 0.9395 - loss: 0.3138 - val_acc: 0.8754 - val_auc: 0.9393 - val_loss: 0.3130
Epoch 27/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 333ms/step - acc: 0.8711 - auc: 0.9429 - loss: 0.3056
Epoch 27: val_acc did not improve from 0.87616
41/41 ━━━━━━━━━━━━━━━━━━━━ 22s 366ms/step - acc: 0.8710 - auc: 0.9429 - loss: 0.3057 - val_acc: 0.8684 - val_auc: 0.9373 - val_loss: 0.3168
Epoch 28/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 307ms/step - acc: 0.8729 - auc: 0.9421 - loss: 0.3072
Epoch 28: val_acc improved from 0.87616 to 0.88467, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_CNN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 19s 341ms/step - acc: 0.8730 - auc: 0.9422 - loss: 0.3070 - val_acc: 0.8847 - val_auc: 0.9421 - val_loss: 0.3047
Epoch 29/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 306ms/step - acc: 0.8795 - auc: 0.9485 - loss: 0.2902
Epoch 29: val_acc did not improve from 0.88467
41/41 ━━━━━━━━━━━━━━━━━━━━ 20s 338ms/step - acc: 0.8794 - auc: 0.9485 - loss: 0.2903 - val_acc: 0.8785 - val_auc: 0.9418 - val_loss: 0.3044
Epoch 30/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 304ms/step - acc: 0.8861 - auc: 0.9524 - loss: 0.2798
Epoch 30: val_acc did not improve from 0.88467
41/41 ━━━━━━━━━━━━━━━━━━━━ 21s 337ms/step - acc: 0.8861 - auc: 0.9524 - loss: 0.2799 - val_acc: 0.8831 - val_auc: 0.9443 - val_loss: 0.2994
Epoch 31/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 315ms/step - acc: 0.8771 - auc: 0.9496 - loss: 0.2869
Epoch 31: val_acc did not improve from 0.88467
41/41 ━━━━━━━━━━━━━━━━━━━━ 14s 348ms/step - acc: 0.8771 - auc: 0.9496 - loss: 0.2869 - val_acc: 0.8692 - val_auc: 0.9369 - val_loss: 0.3173
Epoch 32/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 312ms/step - acc: 0.8921 - auc: 0.9529 - loss: 0.2777
Epoch 32: val_acc did not improve from 0.88467
41/41 ━━━━━━━━━━━━━━━━━━━━ 20s 334ms/step - acc: 0.8920 - auc: 0.9528 - loss: 0.2778 - val_acc: 0.8762 - val_auc: 0.9418 - val_loss: 0.3073
Epoch 33/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 318ms/step - acc: 0.8716 - auc: 0.9415 - loss: 0.3095
Epoch 33: val_acc did not improve from 0.88467
41/41 ━━━━━━━━━━━━━━━━━━━━ 14s 352ms/step - acc: 0.8719 - auc: 0.9417 - loss: 0.3089 - val_acc: 0.8831 - val_auc: 0.9436 - val_loss: 0.2992
Epoch 34/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 339ms/step - acc: 0.8946 - auc: 0.9603 - loss: 0.2555
Epoch 34: val_acc improved from 0.88467 to 0.88545, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_CNN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 15s 373ms/step - acc: 0.8945 - auc: 0.9602 - loss: 0.2557 - val_acc: 0.8854 - val_auc: 0.9420 - val_loss: 0.3039
Epoch 35/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 311ms/step - acc: 0.8908 - auc: 0.9596 - loss: 0.2586
Epoch 35: val_acc improved from 0.88545 to 0.88854, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_CNN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 19s 335ms/step - acc: 0.8907 - auc: 0.9595 - loss: 0.2589 - val_acc: 0.8885 - val_auc: 0.9451 - val_loss: 0.2967
Epoch 36/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 330ms/step - acc: 0.8823 - auc: 0.9526 - loss: 0.2798
Epoch 36: val_acc did not improve from 0.88854
41/41 ━━━━━━━━━━━━━━━━━━━━ 21s 352ms/step - acc: 0.8825 - auc: 0.9527 - loss: 0.2795 - val_acc: 0.8824 - val_auc: 0.9466 - val_loss: 0.2914
Epoch 37/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 321ms/step - acc: 0.8879 - auc: 0.9575 - loss: 0.2644
Epoch 37: val_acc did not improve from 0.88854
41/41 ━━━━━━━━━━━━━━━━━━━━ 21s 354ms/step - acc: 0.8880 - auc: 0.9575 - loss: 0.2644 - val_acc: 0.8831 - val_auc: 0.9442 - val_loss: 0.2977
Epoch 38/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 386ms/step - acc: 0.8914 - auc: 0.9600 - loss: 0.2569
Epoch 38: val_acc improved from 0.88854 to 0.89009, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_CNN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 23s 421ms/step - acc: 0.8913 - auc: 0.9599 - loss: 0.2570 - val_acc: 0.8901 - val_auc: 0.9455 - val_loss: 0.2949
Epoch 39/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 348ms/step - acc: 0.8967 - auc: 0.9623 - loss: 0.2488
Epoch 39: val_acc did not improve from 0.89009
41/41 ━━━━━━━━━━━━━━━━━━━━ 18s 371ms/step - acc: 0.8966 - auc: 0.9623 - loss: 0.2489 - val_acc: 0.8808 - val_auc: 0.9430 - val_loss: 0.3073
Epoch 40/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 348ms/step - acc: 0.8972 - auc: 0.9635 - loss: 0.2444
Epoch 40: val_acc did not improve from 0.89009
41/41 ━━━━━━━━━━━━━━━━━━━━ 17s 413ms/step - acc: 0.8973 - auc: 0.9635 - loss: 0.2443 - val_acc: 0.8831 - val_auc: 0.9457 - val_loss: 0.2984
Epoch 41/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 349ms/step - acc: 0.9065 - auc: 0.9682 - loss: 0.2288
Epoch 41: val_acc did not improve from 0.89009
41/41 ━━━━━━━━━━━━━━━━━━━━ 19s 382ms/step - acc: 0.9064 - auc: 0.9681 - loss: 0.2291 - val_acc: 0.8800 - val_auc: 0.9457 - val_loss: 0.2980
Epoch 42/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 333ms/step - acc: 0.9097 - auc: 0.9679 - loss: 0.2296
Epoch 42: val_acc did not improve from 0.89009
41/41 ━━━━━━━━━━━━━━━━━━━━ 20s 366ms/step - acc: 0.9096 - auc: 0.9679 - loss: 0.2298 - val_acc: 0.8847 - val_auc: 0.9437 - val_loss: 0.3061
Epoch 43/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 349ms/step - acc: 0.9050 - auc: 0.9657 - loss: 0.2372
Epoch 43: val_acc did not improve from 0.89009
41/41 ━━━━━━━━━━━━━━━━━━━━ 16s 382ms/step - acc: 0.9051 - auc: 0.9657 - loss: 0.2373 - val_acc: 0.8769 - val_auc: 0.9427 - val_loss: 0.3105
Epoch 44/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 343ms/step - acc: 0.9145 - auc: 0.9694 - loss: 0.2238
Epoch 44: val_acc did not improve from 0.89009
41/41 ━━━━━━━━━━━━━━━━━━━━ 15s 376ms/step - acc: 0.9144 - auc: 0.9694 - loss: 0.2238 - val_acc: 0.8847 - val_auc: 0.9441 - val_loss: 0.3068
Epoch 45/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 340ms/step - acc: 0.9117 - auc: 0.9676 - loss: 0.2301
Epoch 45: val_acc did not improve from 0.89009
41/41 ━━━━━━━━━━━━━━━━━━━━ 20s 363ms/step - acc: 0.9117 - auc: 0.9677 - loss: 0.2299 - val_acc: 0.8885 - val_auc: 0.9480 - val_loss: 0.2928
Epoch 46/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 345ms/step - acc: 0.9044 - auc: 0.9691 - loss: 0.2261
Epoch 46: val_acc did not improve from 0.89009
41/41 ━━━━━━━━━━━━━━━━━━━━ 21s 379ms/step - acc: 0.9045 - auc: 0.9691 - loss: 0.2261 - val_acc: 0.8816 - val_auc: 0.9504 - val_loss: 0.2858
Epoch 47/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 330ms/step - acc: 0.9150 - auc: 0.9730 - loss: 0.2113
Epoch 47: val_acc did not improve from 0.89009
41/41 ━━━━━━━━━━━━━━━━━━━━ 15s 363ms/step - acc: 0.9149 - auc: 0.9729 - loss: 0.2115 - val_acc: 0.8824 - val_auc: 0.9500 - val_loss: 0.2909
Epoch 48/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 342ms/step - acc: 0.9100 - auc: 0.9702 - loss: 0.2207
Epoch 48: val_acc did not improve from 0.89009
41/41 ━━━━━━━━━━━━━━━━━━━━ 21s 378ms/step - acc: 0.9100 - auc: 0.9701 - loss: 0.2208 - val_acc: 0.8831 - val_auc: 0.9487 - val_loss: 0.3000
Epoch 49/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 329ms/step - acc: 0.9159 - auc: 0.9722 - loss: 0.2129
Epoch 49: val_acc did not improve from 0.89009
41/41 ━━━━━━━━━━━━━━━━━━━━ 20s 361ms/step - acc: 0.9158 - auc: 0.9722 - loss: 0.2129 - val_acc: 0.8777 - val_auc: 0.9475 - val_loss: 0.2991
Epoch 50/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 349ms/step - acc: 0.9200 - auc: 0.9769 - loss: 0.1959
Epoch 50: val_acc did not improve from 0.89009
41/41 ━━━━━━━━━━━━━━━━━━━━ 21s 382ms/step - acc: 0.9198 - auc: 0.9768 - loss: 0.1962 - val_acc: 0.8816 - val_auc: 0.9467 - val_loss: 0.2975
Epoch 51/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 354ms/step - acc: 0.9158 - auc: 0.9755 - loss: 0.2025
Epoch 51: val_acc did not improve from 0.89009
41/41 ━━━━━━━━━━━━━━━━━━━━ 16s 387ms/step - acc: 0.9158 - auc: 0.9755 - loss: 0.2025 - val_acc: 0.8854 - val_auc: 0.9483 - val_loss: 0.3006
Epoch 52/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 338ms/step - acc: 0.9098 - auc: 0.9708 - loss: 0.2190
Epoch 52: val_acc did not improve from 0.89009
41/41 ━━━━━━━━━━━━━━━━━━━━ 19s 361ms/step - acc: 0.9099 - auc: 0.9709 - loss: 0.2189 - val_acc: 0.8885 - val_auc: 0.9472 - val_loss: 0.3033
Epoch 53/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 403ms/step - acc: 0.9161 - auc: 0.9765 - loss: 0.1979
Epoch 53: val_acc did not improve from 0.89009
41/41 ━━━━━━━━━━━━━━━━━━━━ 23s 436ms/step - acc: 0.9161 - auc: 0.9765 - loss: 0.1980 - val_acc: 0.8839 - val_auc: 0.9448 - val_loss: 0.3060
Epoch 54/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 344ms/step - acc: 0.9274 - auc: 0.9799 - loss: 0.1820
Epoch 54: val_acc did not improve from 0.89009
41/41 ━━━━━━━━━━━━━━━━━━━━ 18s 377ms/step - acc: 0.9271 - auc: 0.9798 - loss: 0.1824 - val_acc: 0.8893 - val_auc: 0.9493 - val_loss: 0.2905
Epoch 55/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 350ms/step - acc: 0.9225 - auc: 0.9794 - loss: 0.1861
Epoch 55: val_acc did not improve from 0.89009
41/41 ━━━━━━━━━━━━━━━━━━━━ 21s 383ms/step - acc: 0.9226 - auc: 0.9794 - loss: 0.1860 - val_acc: 0.8824 - val_auc: 0.9469 - val_loss: 0.3121
Epoch 56/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 360ms/step - acc: 0.9274 - auc: 0.9797 - loss: 0.1826
Epoch 56: val_acc did not improve from 0.89009
41/41 ━━━━━━━━━━━━━━━━━━━━ 16s 386ms/step - acc: 0.9273 - auc: 0.9797 - loss: 0.1828 - val_acc: 0.8793 - val_auc: 0.9467 - val_loss: 0.3010
Epoch 57/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 445ms/step - acc: 0.9271 - auc: 0.9803 - loss: 0.1805
Epoch 57: val_acc did not improve from 0.89009
41/41 ━━━━━━━━━━━━━━━━━━━━ 24s 478ms/step - acc: 0.9271 - auc: 0.9802 - loss: 0.1806 - val_acc: 0.8839 - val_auc: 0.9485 - val_loss: 0.2984
Epoch 58/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 475ms/step - acc: 0.9249 - auc: 0.9794 - loss: 0.1835
Epoch 58: val_acc did not improve from 0.89009
41/41 ━━━━━━━━━━━━━━━━━━━━ 22s 509ms/step - acc: 0.9250 - auc: 0.9794 - loss: 0.1834 - val_acc: 0.8754 - val_auc: 0.9440 - val_loss: 0.3193
Epoch 59/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 454ms/step - acc: 0.9312 - auc: 0.9819 - loss: 0.1714
Epoch 59: val_acc did not improve from 0.89009
41/41 ━━━━━━━━━━━━━━━━━━━━ 40s 488ms/step - acc: 0.9312 - auc: 0.9819 - loss: 0.1715 - val_acc: 0.8746 - val_auc: 0.9417 - val_loss: 0.3303
Epoch 60/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 491ms/step - acc: 0.9272 - auc: 0.9816 - loss: 0.1741
Epoch 60: val_acc did not improve from 0.89009
41/41 ━━━━━━━━━━━━━━━━━━━━ 21s 524ms/step - acc: 0.9270 - auc: 0.9815 - loss: 0.1745 - val_acc: 0.8800 - val_auc: 0.9458 - val_loss: 0.3182
Epoch 61/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 436ms/step - acc: 0.9254 - auc: 0.9802 - loss: 0.1804
Epoch 61: val_acc did not improve from 0.89009
41/41 ━━━━━━━━━━━━━━━━━━━━ 39s 469ms/step - acc: 0.9255 - auc: 0.9802 - loss: 0.1803 - val_acc: 0.8731 - val_auc: 0.9435 - val_loss: 0.3364
Epoch 62/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 444ms/step - acc: 0.9288 - auc: 0.9815 - loss: 0.1750
Epoch 62: val_acc did not improve from 0.89009
41/41 ━━━━━━━━━━━━━━━━━━━━ 22s 510ms/step - acc: 0.9289 - auc: 0.9815 - loss: 0.1749 - val_acc: 0.8762 - val_auc: 0.9460 - val_loss: 0.3222
Epoch 63/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 442ms/step - acc: 0.9292 - auc: 0.9812 - loss: 0.1751
Epoch 63: val_acc did not improve from 0.89009
41/41 ━━━━━━━━━━━━━━━━━━━━ 19s 475ms/step - acc: 0.9293 - auc: 0.9812 - loss: 0.1750 - val_acc: 0.8746 - val_auc: 0.9444 - val_loss: 0.3259
Epoch 64/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 475ms/step - acc: 0.9278 - auc: 0.9798 - loss: 0.1820

Model: "sequential_54"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_216 (Dense)               │ (None, 2048)           │     4,982,784 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_135         │ (None, 2048)           │         8,192 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_217 (Dense)               │ (None, 1024)           │     2,098,176 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_136         │ (None, 1024)           │         4,096 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_218 (Dense)               │ (None, 512)            │       524,800 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_137         │ (None, 512)            │         2,048 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_219 (Dense)               │ (None, 256)            │       131,328 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_138         │ (None, 256)            │         1,024 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_220 (Dense)               │ (None, 128)            │        32,896 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_139         │ (None, 128)            │           512 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_221 (Dense)               │ (None, 2)              │           258 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 7,786,114 (29.70 MB)

 Trainable params: 7,778,178 (29.67 MB)

 Non-trainable params: 7,936 (31.00 KB)

Epoch 1/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 154ms/step - acc: 0.7362 - auc: 0.8132 - loss: 0.5988
Epoch 1: val_auc improved from -inf to 0.66293, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_ANN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 13s 215ms/step - acc: 0.7374 - auc: 0.8145 - loss: 0.5960 - val_acc: 0.5263 - val_auc: 0.6629 - val_loss: 1.1050
Epoch 2/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 163ms/step - acc: 0.8914 - auc: 0.9562 - loss: 0.2733
Epoch 2: val_auc improved from 0.66293 to 0.76934, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_ANN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 11s 241ms/step - acc: 0.8914 - auc: 0.9563 - loss: 0.2730 - val_acc: 0.6889 - val_auc: 0.7693 - val_loss: 0.6559
Epoch 3/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 155ms/step - acc: 0.9329 - auc: 0.9826 - loss: 0.1758
Epoch 3: val_auc did not improve from 0.76934
41/41 ━━━━━━━━━━━━━━━━━━━━ 7s 168ms/step - acc: 0.9328 - auc: 0.9825 - loss: 0.1761 - val_acc: 0.6873 - val_auc: 0.7662 - val_loss: 0.6836
Epoch 4/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 200ms/step - acc: 0.9536 - auc: 0.9916 - loss: 0.1242
Epoch 4: val_auc improved from 0.76934 to 0.85727, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_ANN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 13s 228ms/step - acc: 0.9535 - auc: 0.9915 - loss: 0.1245 - val_acc: 0.7686 - val_auc: 0.8573 - val_loss: 0.5187
Epoch 5/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 172ms/step - acc: 0.9530 - auc: 0.9894 - loss: 0.1279
Epoch 5: val_auc improved from 0.85727 to 0.90516, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_ANN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 9s 228ms/step - acc: 0.9527 - auc: 0.9893 - loss: 0.1285 - val_acc: 0.8313 - val_auc: 0.9052 - val_loss: 0.4887
Epoch 6/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 151ms/step - acc: 0.9544 - auc: 0.9899 - loss: 0.1253
Epoch 6: val_auc did not improve from 0.90516
41/41 ━━━━━━━━━━━━━━━━━━━━ 7s 169ms/step - acc: 0.9544 - auc: 0.9900 - loss: 0.1253 - val_acc: 0.8189 - val_auc: 0.8962 - val_loss: 0.5309
Epoch 7/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 146ms/step - acc: 0.9755 - auc: 0.9963 - loss: 0.0781
Epoch 7: val_auc improved from 0.90516 to 0.93382, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_ANN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 11s 177ms/step - acc: 0.9753 - auc: 0.9962 - loss: 0.0783 - val_acc: 0.8607 - val_auc: 0.9338 - val_loss: 0.4218
Epoch 8/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 150ms/step - acc: 0.9760 - auc: 0.9961 - loss: 0.0749
Epoch 8: val_auc improved from 0.93382 to 0.93583, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_ANN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 11s 191ms/step - acc: 0.9758 - auc: 0.9961 - loss: 0.0751 - val_acc: 0.8707 - val_auc: 0.9358 - val_loss: 0.4036
Epoch 9/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 151ms/step - acc: 0.9801 - auc: 0.9970 - loss: 0.0671
Epoch 9: val_auc did not improve from 0.93583
41/41 ━━━━━━━━━━━━━━━━━━━━ 9s 168ms/step - acc: 0.9801 - auc: 0.9970 - loss: 0.0671 - val_acc: 0.8630 - val_auc: 0.9306 - val_loss: 0.4578
Epoch 10/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 198ms/step - acc: 0.9820 - auc: 0.9982 - loss: 0.0517
Epoch 10: val_auc did not improve from 0.93583
41/41 ━━━━━━━━━━━━━━━━━━━━ 9s 215ms/step - acc: 0.9819 - auc: 0.9982 - loss: 0.0520 - val_acc: 0.8746 - val_auc: 0.9317 - val_loss: 0.4683
Epoch 11/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 156ms/step - acc: 0.9839 - auc: 0.9979 - loss: 0.0523
Epoch 11: val_auc did not improve from 0.93583
41/41 ━━━━━━━━━━━━━━━━━━━━ 9s 190ms/step - acc: 0.9838 - auc: 0.9979 - loss: 0.0527 - val_acc: 0.8808 - val_auc: 0.9324 - val_loss: 0.4725
Epoch 12/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 145ms/step - acc: 0.9648 - auc: 0.9916 - loss: 0.1061
Epoch 12: val_auc did not improve from 0.93583
41/41 ━━━━━━━━━━━━━━━━━━━━ 9s 162ms/step - acc: 0.9648 - auc: 0.9916 - loss: 0.1061 - val_acc: 0.8615 - val_auc: 0.9302 - val_loss: 0.5235
Epoch 13/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 142ms/step - acc: 0.9818 - auc: 0.9975 - loss: 0.0600
Epoch 13: val_auc improved from 0.93583 to 0.93836, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_ANN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 11s 173ms/step - acc: 0.9817 - auc: 0.9975 - loss: 0.0601 - val_acc: 0.8847 - val_auc: 0.9384 - val_loss: 0.5010
Epoch 14/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 152ms/step - acc: 0.9797 - auc: 0.9974 - loss: 0.0567
Epoch 14: val_auc did not improve from 0.93836
41/41 ━━━━━━━━━━━━━━━━━━━━ 10s 168ms/step - acc: 0.9797 - auc: 0.9974 - loss: 0.0568 - val_acc: 0.8669 - val_auc: 0.9350 - val_loss: 0.5053
Epoch 15/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 179ms/step - acc: 0.9801 - auc: 0.9965 - loss: 0.0613
Epoch 15: val_auc did not improve from 0.93836
41/41 ━━━━━━━━━━━━━━━━━━━━ 11s 191ms/step - acc: 0.9800 - auc: 0.9965 - loss: 0.0614 - val_acc: 0.8777 - val_auc: 0.9368 - val_loss: 0.4727
Epoch 16/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 167ms/step - acc: 0.9836 - auc: 0.9981 - loss: 0.0497
Epoch 16: val_auc did not improve from 0.93836
41/41 ━━━━━━━━━━━━━━━━━━━━ 10s 178ms/step - acc: 0.9834 - auc: 0.9981 - loss: 0.0500 - val_acc: 0.8700 - val_auc: 0.9336 - val_loss: 0.4996
Epoch 17/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 138ms/step - acc: 0.9847 - auc: 0.9988 - loss: 0.0439
Epoch 17: val_auc improved from 0.93836 to 0.94052, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_ANN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 7s 165ms/step - acc: 0.9847 - auc: 0.9988 - loss: 0.0439 - val_acc: 0.8800 - val_auc: 0.9405 - val_loss: 0.4489
Epoch 18/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 162ms/step - acc: 0.9883 - auc: 0.9981 - loss: 0.0407
Epoch 18: val_auc did not improve from 0.94052
41/41 ━━━━━━━━━━━━━━━━━━━━ 7s 179ms/step - acc: 0.9882 - auc: 0.9981 - loss: 0.0407 - val_acc: 0.8731 - val_auc: 0.9301 - val_loss: 0.5103
Epoch 19/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 151ms/step - acc: 0.9841 - auc: 0.9976 - loss: 0.0508
Epoch 19: val_auc did not improve from 0.94052
41/41 ━━━━━━━━━━━━━━━━━━━━ 7s 168ms/step - acc: 0.9840 - auc: 0.9976 - loss: 0.0509 - val_acc: 0.8785 - val_auc: 0.9262 - val_loss: 0.5674
Epoch 20/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 170ms/step - acc: 0.9868 - auc: 0.9992 - loss: 0.0341
Epoch 20: val_auc did not improve from 0.94052
41/41 ━━━━━━━━━━━━━━━━━━━━ 8s 187ms/step - acc: 0.9868 - auc: 0.9992 - loss: 0.0342 - val_acc: 0.8793 - val_auc: 0.9350 - val_loss: 0.5002
Epoch 21/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 168ms/step - acc: 0.9899 - auc: 0.9982 - loss: 0.0351
Epoch 21: val_auc did not improve from 0.94052
41/41 ━━━━━━━━━━━━━━━━━━━━ 10s 185ms/step - acc: 0.9899 - auc: 0.9982 - loss: 0.0350 - val_acc: 0.8831 - val_auc: 0.9395 - val_loss: 0.4834
Epoch 22/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 154ms/step - acc: 0.9954 - auc: 0.9995 - loss: 0.0187
Epoch 22: val_auc did not improve from 0.94052
41/41 ━━━━━━━━━━━━━━━━━━━━ 10s 171ms/step - acc: 0.9954 - auc: 0.9995 - loss: 0.0186 - val_acc: 0.8854 - val_auc: 0.9378 - val_loss: 0.4932
Epoch 23/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 147ms/step - acc: 0.9948 - auc: 0.9999 - loss: 0.0141
Epoch 23: val_auc did not improve from 0.94052
41/41 ━━━━━━━━━━━━━━━━━━━━ 10s 164ms/step - acc: 0.9948 - auc: 0.9998 - loss: 0.0141 - val_acc: 0.8777 - val_auc: 0.9367 - val_loss: 0.4991
Epoch 24/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 145ms/step - acc: 0.9957 - auc: 0.9995 - loss: 0.0141
Epoch 24: val_auc improved from 0.94052 to 0.94131, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_ANN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 11s 174ms/step - acc: 0.9957 - auc: 0.9995 - loss: 0.0142 - val_acc: 0.8924 - val_auc: 0.9413 - val_loss: 0.4611
Epoch 25/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 147ms/step - acc: 0.9983 - auc: 0.9999 - loss: 0.0093
Epoch 25: val_auc did not improve from 0.94131
41/41 ━━━━━━━━━━━━━━━━━━━━ 10s 165ms/step - acc: 0.9983 - auc: 0.9999 - loss: 0.0094 - val_acc: 0.8847 - val_auc: 0.9372 - val_loss: 0.5213
Epoch 26/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 198ms/step - acc: 0.9901 - auc: 0.9977 - loss: 0.0347
Epoch 26: val_auc did not improve from 0.94131
41/41 ━━━━━━━━━━━━━━━━━━━━ 9s 210ms/step - acc: 0.9900 - auc: 0.9977 - loss: 0.0350 - val_acc: 0.8723 - val_auc: 0.9309 - val_loss: 0.5677
Epoch 27/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 150ms/step - acc: 0.9861 - auc: 0.9978 - loss: 0.0427
Epoch 27: val_auc did not improve from 0.94131
41/41 ━━━━━━━━━━━━━━━━━━━━ 7s 167ms/step - acc: 0.9860 - auc: 0.9978 - loss: 0.0428 - val_acc: 0.8746 - val_auc: 0.9298 - val_loss: 0.5902
Epoch 28/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 161ms/step - acc: 0.9809 - auc: 0.9973 - loss: 0.0532
Epoch 28: val_auc did not improve from 0.94131
41/41 ━━━━━━━━━━━━━━━━━━━━ 7s 178ms/step - acc: 0.9809 - auc: 0.9973 - loss: 0.0533 - val_acc: 0.8715 - val_auc: 0.9283 - val_loss: 0.5984
Epoch 29/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 169ms/step - acc: 0.9880 - auc: 0.9990 - loss: 0.0354
Epoch 29: val_auc did not improve from 0.94131
41/41 ━━━━━━━━━━━━━━━━━━━━ 11s 188ms/step - acc: 0.9879 - auc: 0.9990 - loss: 0.0355 - val_acc: 0.8738 - val_auc: 0.9255 - val_loss: 0.6415
Epoch 30/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 161ms/step - acc: 0.9871 - auc: 0.9975 - loss: 0.0435
Epoch 30: val_auc did not improve from 0.94131
41/41 ━━━━━━━━━━━━━━━━━━━━ 10s 176ms/step - acc: 0.9870 - auc: 0.9975 - loss: 0.0437 - val_acc: 0.8808 - val_auc: 0.9377 - val_loss: 0.5603
Epoch 31/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 149ms/step - acc: 0.9845 - auc: 0.9986 - loss: 0.0426
Epoch 31: val_auc did not improve from 0.94131
41/41 ━━━━━━━━━━━━━━━━━━━━ 10s 166ms/step - acc: 0.9845 - auc: 0.9986 - loss: 0.0425 - val_acc: 0.8808 - val_auc: 0.9320 - val_loss: 0.5565
Epoch 32/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 147ms/step - acc: 0.9882 - auc: 0.9992 - loss: 0.0323
Epoch 32: val_auc did not improve from 0.94131
41/41 ━━━━━━━━━━━━━━━━━━━━ 10s 164ms/step - acc: 0.9882 - auc: 0.9992 - loss: 0.0324 - val_acc: 0.8824 - val_auc: 0.9289 - val_loss: 0.5925
Epoch 33/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 151ms/step - acc: 0.9883 - auc: 0.9990 - loss: 0.0312
Epoch 33: val_auc did not improve from 0.94131
41/41 ━━━━━━━━━━━━━━━━━━━━ 10s 168ms/step - acc: 0.9883 - auc: 0.9990 - loss: 0.0313 - val_acc: 0.8862 - val_auc: 0.9363 - val_loss: 0.5201
Epoch 34/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 172ms/step - acc: 0.9940 - auc: 0.9995 - loss: 0.0194
Epoch 34: val_auc did not improve from 0.94131
41/41 ━━━━━━━━━━━━━━━━━━━━ 8s 189ms/step - acc: 0.9940 - auc: 0.9995 - loss: 0.0194 - val_acc: 0.8893 - val_auc: 0.9399 - val_loss: 0.4834
Epoch 35/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 145ms/step - acc: 0.9956 - auc: 0.9999 - loss: 0.0122
Epoch 35: val_auc improved from 0.94131 to 0.94161, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_ANN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 7s 175ms/step - acc: 0.9956 - auc: 0.9999 - loss: 0.0123 - val_acc: 0.8955 - val_auc: 0.9416 - val_loss: 0.4781
Epoch 36/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 142ms/step - acc: 0.9942 - auc: 0.9980 - loss: 0.0259
Epoch 36: val_auc did not improve from 0.94161
41/41 ━━━━━━━━━━━━━━━━━━━━ 10s 159ms/step - acc: 0.9942 - auc: 0.9980 - loss: 0.0258 - val_acc: 0.8893 - val_auc: 0.9381 - val_loss: 0.5084
Epoch 37/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 204ms/step - acc: 0.9965 - auc: 0.9998 - loss: 0.0133
Epoch 37: val_auc did not improve from 0.94161
41/41 ━━━━━━━━━━━━━━━━━━━━ 9s 221ms/step - acc: 0.9964 - auc: 0.9998 - loss: 0.0134 - val_acc: 0.8839 - val_auc: 0.9401 - val_loss: 0.5432
Epoch 38/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 153ms/step - acc: 0.9927 - auc: 0.9990 - loss: 0.0207
Epoch 38: val_auc did not improve from 0.94161
41/41 ━━━━━━━━━━━━━━━━━━━━ 8s 171ms/step - acc: 0.9927 - auc: 0.9990 - loss: 0.0209 - val_acc: 0.8746 - val_auc: 0.9342 - val_loss: 0.5608
Epoch 39/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 147ms/step - acc: 0.9914 - auc: 0.9985 - loss: 0.0277
Epoch 39: val_auc did not improve from 0.94161
41/41 ━━━━━━━━━━━━━━━━━━━━ 7s 158ms/step - acc: 0.9913 - auc: 0.9985 - loss: 0.0278 - val_acc: 0.8669 - val_auc: 0.9236 - val_loss: 0.6218
Epoch 40/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 165ms/step - acc: 0.9910 - auc: 0.9992 - loss: 0.0247
Epoch 40: val_auc did not improve from 0.94161
41/41 ━━━━━━━━━━━━━━━━━━━━ 11s 182ms/step - acc: 0.9909 - auc: 0.9992 - loss: 0.0248 - val_acc: 0.8816 - val_auc: 0.9393 - val_loss: 0.5404
Epoch 41/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 167ms/step - acc: 0.9890 - auc: 0.9975 - loss: 0.0403
Epoch 41: val_auc did not improve from 0.94161
41/41 ━━━━━━━━━━━━━━━━━━━━ 10s 178ms/step - acc: 0.9890 - auc: 0.9975 - loss: 0.0401 - val_acc: 0.8831 - val_auc: 0.9271 - val_loss: 0.5693
Epoch 42/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 150ms/step - acc: 0.9926 - auc: 0.9997 - loss: 0.0190
Epoch 42: val_auc did not improve from 0.94161
41/41 ━━━━━━━━━━━━━━━━━━━━ 10s 168ms/step - acc: 0.9926 - auc: 0.9997 - loss: 0.0190 - val_acc: 0.8793 - val_auc: 0.9271 - val_loss: 0.5852
Epoch 43/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 149ms/step - acc: 0.9899 - auc: 0.9981 - loss: 0.0325
Epoch 43: val_auc did not improve from 0.94161
41/41 ━━━━━━━━━━━━━━━━━━━━ 10s 166ms/step - acc: 0.9899 - auc: 0.9981 - loss: 0.0324 - val_acc: 0.8762 - val_auc: 0.9229 - val_loss: 0.6222
Epoch 44/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 145ms/step - acc: 0.9946 - auc: 0.9997 - loss: 0.0163
Epoch 44: val_auc did not improve from 0.94161
41/41 ━━━━━━━━━━━━━━━━━━━━ 10s 161ms/step - acc: 0.9946 - auc: 0.9997 - loss: 0.0163 - val_acc: 0.8831 - val_auc: 0.9386 - val_loss: 0.5399
Epoch 45/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 152ms/step - acc: 0.9908 - auc: 0.9984 - loss: 0.0322
Epoch 45: val_auc did not improve from 0.94161
41/41 ━━━━━━━━━━━━━━━━━━━━ 11s 169ms/step - acc: 0.9909 - auc: 0.9984 - loss: 0.0321 - val_acc: 0.8839 - val_auc: 0.9342 - val_loss: 0.5437
Epoch 46/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 160ms/step - acc: 0.9957 - auc: 0.9993 - loss: 0.0142
Epoch 46: val_auc did not improve from 0.94161
41/41 ━━━━━━━━━━━━━━━━━━━━ 7s 177ms/step - acc: 0.9957 - auc: 0.9993 - loss: 0.0143 - val_acc: 0.8839 - val_auc: 0.9414 - val_loss: 0.4977
Epoch 47/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 182ms/step - acc: 0.9970 - auc: 0.9994 - loss: 0.0144
Epoch 47: val_auc did not improve from 0.94161
41/41 ━━━━━━━━━━━━━━━━━━━━ 11s 200ms/step - acc: 0.9969 - auc: 0.9994 - loss: 0.0144 - val_acc: 0.8893 - val_auc: 0.9384 - val_loss: 0.5168
Epoch 48/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 145ms/step - acc: 0.9943 - auc: 0.9992 - loss: 0.0218
Epoch 48: val_auc did not improve from 0.94161
41/41 ━━━━━━━━━━━━━━━━━━━━ 9s 162ms/step - acc: 0.9943 - auc: 0.9991 - loss: 0.0219 - val_acc: 0.8893 - val_auc: 0.9352 - val_loss: 0.5640
Epoch 49/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 164ms/step - acc: 0.9916 - auc: 0.9991 - loss: 0.0278
Epoch 49: val_auc did not improve from 0.94161
41/41 ━━━━━━━━━━━━━━━━━━━━ 7s 176ms/step - acc: 0.9916 - auc: 0.9991 - loss: 0.0278 - val_acc: 0.8854 - val_auc: 0.9301 - val_loss: 0.5680
Epoch 50/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 144ms/step - acc: 0.9920 - auc: 0.9991 - loss: 0.0274
Epoch 50: val_auc did not improve from 0.94161
41/41 ━━━━━━━━━━━━━━━━━━━━ 7s 162ms/step - acc: 0.9920 - auc: 0.9991 - loss: 0.0274 - val_acc: 0.8878 - val_auc: 0.9349 - val_loss: 0.5535
Epoch 51/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 147ms/step - acc: 0.9944 - auc: 0.9994 - loss: 0.0152
Epoch 51: val_auc did not improve from 0.94161
41/41 ━━━━━━━━━━━━━━━━━━━━ 10s 164ms/step - acc: 0.9944 - auc: 0.9994 - loss: 0.0153 - val_acc: 0.8854 - val_auc: 0.9310 - val_loss: 0.5655
Epoch 52/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 153ms/step - acc: 0.9948 - auc: 0.9991 - loss: 0.0186
Epoch 52: val_auc did not improve from 0.94161
41/41 ━━━━━━━━━━━━━━━━━━━━ 10s 170ms/step - acc: 0.9948 - auc: 0.9991 - loss: 0.0186 - val_acc: 0.8916 - val_auc: 0.9406 - val_loss: 0.5011
Epoch 53/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 151ms/step - acc: 0.9958 - auc: 0.9999 - loss: 0.0128
Epoch 53: val_auc did not improve from 0.94161
41/41 ━━━━━━━━━━━━━━━━━━━━ 10s 163ms/step - acc: 0.9958 - auc: 0.9999 - loss: 0.0128 - val_acc: 0.8808 - val_auc: 0.9365 - val_loss: 0.5364
Epoch 54/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 165ms/step - acc: 0.9953 - auc: 0.9997 - loss: 0.0148
Epoch 54: val_auc did not improve from 0.94161
41/41 ━━━━━━━━━━━━━━━━━━━━ 11s 182ms/step - acc: 0.9953 - auc: 0.9997 - loss: 0.0149 - val_acc: 0.8808 - val_auc: 0.9329 - val_loss: 0.5742
Epoch 55/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 168ms/step - acc: 0.9938 - auc: 0.9998 - loss: 0.0173
Epoch 55: val_auc did not improve from 0.94161
41/41 ━━━━━━━━━━━━━━━━━━━━ 10s 185ms/step - acc: 0.9938 - auc: 0.9998 - loss: 0.0174 - val_acc: 0.8738 - val_auc: 0.9287 - val_loss: 0.6188
Epoch 56/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 149ms/step - acc: 0.9890 - auc: 0.9980 - loss: 0.0361
Epoch 56: val_auc did not improve from 0.94161
41/41 ━━━━━━━━━━━━━━━━━━━━ 7s 166ms/step - acc: 0.9889 - auc: 0.9980 - loss: 0.0362 - val_acc: 0.8800 - val_auc: 0.9295 - val_loss: 0.6426
Epoch 57/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 155ms/step - acc: 0.9878 - auc: 0.9984 - loss: 0.0362
Epoch 57: val_auc did not improve from 0.94161
41/41 ━━━━━━━━━━━━━━━━━━━━ 10s 172ms/step - acc: 0.9878 - auc: 0.9984 - loss: 0.0362 - val_acc: 0.8800 - val_auc: 0.9298 - val_loss: 0.5956
Epoch 58/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 151ms/step - acc: 0.9943 - auc: 0.9992 - loss: 0.0187
Epoch 58: val_auc did not improve from 0.94161
41/41 ━━━━━━━━━━━━━━━━━━━━ 10s 168ms/step - acc: 0.9943 - auc: 0.9992 - loss: 0.0186 - val_acc: 0.8762 - val_auc: 0.9320 - val_loss: 0.5617
Epoch 59/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 156ms/step - acc: 0.9973 - auc: 0.9996 - loss: 0.0112
Epoch 59: val_auc did not improve from 0.94161
41/41 ━━━━━━━━━━━━━━━━━━━━ 10s 173ms/step - acc: 0.9973 - auc: 0.9996 - loss: 0.0112 - val_acc: 0.8862 - val_auc: 0.9333 - val_loss: 0.5676
Epoch 60/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 166ms/step - acc: 0.9962 - auc: 0.9992 - loss: 0.0162
Epoch 60: val_auc did not improve from 0.94161
41/41 ━━━━━━━━━━━━━━━━━━━━ 11s 183ms/step - acc: 0.9961 - auc: 0.9992 - loss: 0.0163 - val_acc: 0.8808 - val_auc: 0.9342 - val_loss: 0.5610
Epoch 61/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 166ms/step - acc: 0.9951 - auc: 0.9998 - loss: 0.0140
Epoch 61: val_auc did not improve from 0.94161
41/41 ━━━━━━━━━━━━━━━━━━━━ 10s 177ms/step - acc: 0.9951 - auc: 0.9998 - loss: 0.0141 - val_acc: 0.8762 - val_auc: 0.9327 - val_loss: 0.5842
Epoch 62/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 152ms/step - acc: 0.9925 - auc: 0.9992 - loss: 0.0249
Epoch 62: val_auc did not improve from 0.94161
41/41 ━━━━━━━━━━━━━━━━━━━━ 11s 186ms/step - acc: 0.9924 - auc: 0.9992 - loss: 0.0250 - val_acc: 0.8762 - val_auc: 0.9336 - val_loss: 0.5409
Epoch 63/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 176ms/step - acc: 0.9923 - auc: 0.9987 - loss: 0.0237
Epoch 63: val_auc did not improve from 0.94161
41/41 ━━━━━━━━━━━━━━━━━━━━ 8s 193ms/step - acc: 0.9924 - auc: 0.9987 - loss: 0.0236 - val_acc: 0.8808 - val_auc: 0.9411 - val_loss: 0.5011
Epoch 64/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 199ms/step - acc: 0.9978 - auc: 0.9997 - loss: 0.0092
Epoch 64: val_auc did not improve from 0.94161
41/41 ━━━━━━━━━━━━━━━━━━━━ 11s 210ms/step - acc: 0.9978 - auc: 0.9997 - loss: 0.0092 - val_acc: 0.8754 - val_auc: 0.9367 - val_loss: 0.5266
Epoch 65/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 168ms/step - acc: 0.9964 - auc: 0.9994 - loss: 0.0147
Epoch 65: val_auc did not improve from 0.94161
41/41 ━━━━━━━━━━━━━━━━━━━━ 9s 181ms/step - acc: 0.9964 - auc: 0.9994 - loss: 0.0148 - val_acc: 0.8692 - val_auc: 0.9255 - val_loss: 0.6028
Epoch 66/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 158ms/step - acc: 0.9970 - auc: 0.9997 - loss: 0.0112
Epoch 66: val_auc did not improve from 0.94161
41/41 ━━━━━━━━━━━━━━━━━━━━ 10s 175ms/step - acc: 0.9969 - auc: 0.9997 - loss: 0.0113 - val_acc: 0.8839 - val_auc: 0.9380 - val_loss: 0.5372
Epoch 67/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 162ms/step - acc: 0.9968 - auc: 1.0000 - loss: 0.0089
Epoch 67: val_auc did not improve from 0.94161
41/41 ━━━━━━━━━━━━━━━━━━━━ 7s 174ms/step - acc: 0.9969 - auc: 1.0000 - loss: 0.0089 - val_acc: 0.8700 - val_auc: 0.9222 - val_loss: 0.6881
Epoch 68/200

Model: "sequential_55"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv2d_81 (Conv2D)              │ (None, 62, 36, 32)     │           320 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_81 (MaxPooling2D) │ (None, 31, 18, 32)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_81 (Dropout)            │ (None, 31, 18, 32)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_82 (Conv2D)              │ (None, 29, 16, 64)     │        18,496 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_82 (MaxPooling2D) │ (None, 14, 8, 64)      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_82 (Dropout)            │ (None, 14, 8, 64)      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_83 (Conv2D)              │ (None, 12, 6, 128)     │        73,856 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_83 (MaxPooling2D) │ (None, 6, 3, 128)      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_83 (Dropout)            │ (None, 6, 3, 128)      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_27 (Flatten)            │ (None, 2304)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_222 (Dense)               │ (None, 128)            │       295,040 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_223 (Dense)               │ (None, 2)              │           258 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 387,970 (1.48 MB)

 Trainable params: 387,970 (1.48 MB)

 Non-trainable params: 0 (0.00 B)

Epoch 1/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 330ms/step - acc: 0.5081 - auc: 0.5085 - loss: 0.7033
Epoch 1: val_acc improved from -inf to 0.49381, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_CNN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 17s 373ms/step - acc: 0.5082 - auc: 0.5087 - loss: 0.7032 - val_acc: 0.4938 - val_auc: 0.6116 - val_loss: 0.6904
Epoch 2/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 342ms/step - acc: 0.5325 - auc: 0.5504 - loss: 0.6899
Epoch 2: val_acc improved from 0.49381 to 0.75464, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_CNN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 17s 410ms/step - acc: 0.5326 - auc: 0.5507 - loss: 0.6898 - val_acc: 0.7546 - val_auc: 0.8196 - val_loss: 0.6606
Epoch 3/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 342ms/step - acc: 0.6558 - auc: 0.7241 - loss: 0.6288
Epoch 3: val_acc did not improve from 0.75464
41/41 ━━━━━━━━━━━━━━━━━━━━ 15s 363ms/step - acc: 0.6568 - auc: 0.7253 - loss: 0.6278 - val_acc: 0.7508 - val_auc: 0.8214 - val_loss: 0.5218
Epoch 4/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 365ms/step - acc: 0.7402 - auc: 0.8246 - loss: 0.5142
Epoch 4: val_acc improved from 0.75464 to 0.77786, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_CNN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 22s 398ms/step - acc: 0.7407 - auc: 0.8250 - loss: 0.5137 - val_acc: 0.7779 - val_auc: 0.8634 - val_loss: 0.4678
Epoch 5/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 336ms/step - acc: 0.7892 - auc: 0.8716 - loss: 0.4509
Epoch 5: val_acc improved from 0.77786 to 0.80341, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_CNN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 15s 371ms/step - acc: 0.7892 - auc: 0.8715 - loss: 0.4510 - val_acc: 0.8034 - val_auc: 0.8768 - val_loss: 0.4416
Epoch 6/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 338ms/step - acc: 0.7905 - auc: 0.8733 - loss: 0.4445
Epoch 6: val_acc improved from 0.80341 to 0.80418, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_CNN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 22s 406ms/step - acc: 0.7906 - auc: 0.8733 - loss: 0.4445 - val_acc: 0.8042 - val_auc: 0.8804 - val_loss: 0.4363
Epoch 7/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 359ms/step - acc: 0.8046 - auc: 0.8866 - loss: 0.4243
Epoch 7: val_acc improved from 0.80418 to 0.81115, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_CNN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 16s 395ms/step - acc: 0.8046 - auc: 0.8866 - loss: 0.4244 - val_acc: 0.8111 - val_auc: 0.8918 - val_loss: 0.4153
Epoch 8/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 349ms/step - acc: 0.8076 - auc: 0.8916 - loss: 0.4151
Epoch 8: val_acc improved from 0.81115 to 0.81966, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_CNN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 16s 383ms/step - acc: 0.8075 - auc: 0.8915 - loss: 0.4153 - val_acc: 0.8197 - val_auc: 0.8947 - val_loss: 0.4218
Epoch 9/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 341ms/step - acc: 0.8066 - auc: 0.8869 - loss: 0.4239
Epoch 9: val_acc did not improve from 0.81966
41/41 ━━━━━━━━━━━━━━━━━━━━ 20s 373ms/step - acc: 0.8067 - auc: 0.8870 - loss: 0.4237 - val_acc: 0.8158 - val_auc: 0.8959 - val_loss: 0.4081
Epoch 10/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 336ms/step - acc: 0.8113 - auc: 0.8881 - loss: 0.4211
Epoch 10: val_acc did not improve from 0.81966
41/41 ━━━━━━━━━━━━━━━━━━━━ 22s 402ms/step - acc: 0.8114 - auc: 0.8882 - loss: 0.4209 - val_acc: 0.8197 - val_auc: 0.8985 - val_loss: 0.4041
Epoch 11/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 331ms/step - acc: 0.8067 - auc: 0.8916 - loss: 0.4147
Epoch 11: val_acc improved from 0.81966 to 0.83282, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_CNN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 15s 365ms/step - acc: 0.8069 - auc: 0.8917 - loss: 0.4145 - val_acc: 0.8328 - val_auc: 0.9055 - val_loss: 0.3902
Epoch 12/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 344ms/step - acc: 0.8269 - auc: 0.9036 - loss: 0.3929
Epoch 12: val_acc did not improve from 0.83282
41/41 ━━━━━━━━━━━━━━━━━━━━ 15s 376ms/step - acc: 0.8267 - auc: 0.9036 - loss: 0.3930 - val_acc: 0.8259 - val_auc: 0.9037 - val_loss: 0.3935
Epoch 13/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 340ms/step - acc: 0.8219 - auc: 0.9033 - loss: 0.3943
Epoch 13: val_acc improved from 0.83282 to 0.83824, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_CNN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 20s 375ms/step - acc: 0.8220 - auc: 0.9033 - loss: 0.3941 - val_acc: 0.8382 - val_auc: 0.9105 - val_loss: 0.3799
Epoch 14/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 336ms/step - acc: 0.8246 - auc: 0.9097 - loss: 0.3810
Epoch 14: val_acc did not improve from 0.83824
41/41 ━━━━━━━━━━━━━━━━━━━━ 15s 368ms/step - acc: 0.8247 - auc: 0.9097 - loss: 0.3810 - val_acc: 0.8289 - val_auc: 0.9078 - val_loss: 0.3863
Epoch 15/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 340ms/step - acc: 0.8303 - auc: 0.9104 - loss: 0.3800
Epoch 15: val_acc did not improve from 0.83824
41/41 ━━━━━━━━━━━━━━━━━━━━ 21s 373ms/step - acc: 0.8303 - auc: 0.9104 - loss: 0.3799 - val_acc: 0.8359 - val_auc: 0.9077 - val_loss: 0.3859
Epoch 16/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 340ms/step - acc: 0.8223 - auc: 0.9057 - loss: 0.3893
Epoch 16: val_acc did not improve from 0.83824
41/41 ━━━━━━━━━━━━━━━━━━━━ 20s 373ms/step - acc: 0.8225 - auc: 0.9058 - loss: 0.3892 - val_acc: 0.8382 - val_auc: 0.9127 - val_loss: 0.3754
Epoch 17/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 330ms/step - acc: 0.8389 - auc: 0.9135 - loss: 0.3740
Epoch 17: val_acc improved from 0.83824 to 0.85217, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_CNN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 20s 365ms/step - acc: 0.8390 - auc: 0.9136 - loss: 0.3738 - val_acc: 0.8522 - val_auc: 0.9223 - val_loss: 0.3552
Epoch 18/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 336ms/step - acc: 0.8438 - auc: 0.9208 - loss: 0.3583
Epoch 18: val_acc improved from 0.85217 to 0.85449, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_CNN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 20s 364ms/step - acc: 0.8439 - auc: 0.9208 - loss: 0.3582 - val_acc: 0.8545 - val_auc: 0.9226 - val_loss: 0.3536
Epoch 19/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 332ms/step - acc: 0.8560 - auc: 0.9270 - loss: 0.3459
Epoch 19: val_acc improved from 0.85449 to 0.85759, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_CNN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 21s 368ms/step - acc: 0.8558 - auc: 0.9270 - loss: 0.3459 - val_acc: 0.8576 - val_auc: 0.9253 - val_loss: 0.3480
Epoch 20/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 343ms/step - acc: 0.8535 - auc: 0.9248 - loss: 0.3500
Epoch 20: val_acc improved from 0.85759 to 0.85913, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_CNN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 16s 378ms/step - acc: 0.8535 - auc: 0.9248 - loss: 0.3499 - val_acc: 0.8591 - val_auc: 0.9250 - val_loss: 0.3482
Epoch 21/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 330ms/step - acc: 0.8542 - auc: 0.9316 - loss: 0.3347
Epoch 21: val_acc improved from 0.85913 to 0.85991, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_CNN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 20s 364ms/step - acc: 0.8542 - auc: 0.9315 - loss: 0.3348 - val_acc: 0.8599 - val_auc: 0.9294 - val_loss: 0.3373
Epoch 22/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 347ms/step - acc: 0.8593 - auc: 0.9325 - loss: 0.3315
Epoch 22: val_acc improved from 0.85991 to 0.86146, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_CNN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 21s 381ms/step - acc: 0.8593 - auc: 0.9325 - loss: 0.3316 - val_acc: 0.8615 - val_auc: 0.9323 - val_loss: 0.3309
Epoch 23/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 421ms/step - acc: 0.8669 - auc: 0.9378 - loss: 0.3190
Epoch 23: val_acc improved from 0.86146 to 0.86920, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_CNN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 20s 488ms/step - acc: 0.8668 - auc: 0.9378 - loss: 0.3190 - val_acc: 0.8692 - val_auc: 0.9331 - val_loss: 0.3281
Epoch 24/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 409ms/step - acc: 0.8597 - auc: 0.9346 - loss: 0.3260
Epoch 24: val_acc did not improve from 0.86920
41/41 ━━━━━━━━━━━━━━━━━━━━ 18s 442ms/step - acc: 0.8599 - auc: 0.9347 - loss: 0.3258 - val_acc: 0.8684 - val_auc: 0.9353 - val_loss: 0.3234
Epoch 25/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 333ms/step - acc: 0.8628 - auc: 0.9362 - loss: 0.3218
Epoch 25: val_acc improved from 0.86920 to 0.87539, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_CNN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 17s 370ms/step - acc: 0.8629 - auc: 0.9363 - loss: 0.3215 - val_acc: 0.8754 - val_auc: 0.9355 - val_loss: 0.3224
Epoch 26/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 334ms/step - acc: 0.8742 - auc: 0.9479 - loss: 0.2916
Epoch 26: val_acc did not improve from 0.87539
41/41 ━━━━━━━━━━━━━━━━━━━━ 20s 356ms/step - acc: 0.8740 - auc: 0.9478 - loss: 0.2920 - val_acc: 0.8638 - val_auc: 0.9335 - val_loss: 0.3272
Epoch 27/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 334ms/step - acc: 0.8661 - auc: 0.9434 - loss: 0.3045
Epoch 27: val_acc did not improve from 0.87539
41/41 ━━━━━━━━━━━━━━━━━━━━ 21s 367ms/step - acc: 0.8662 - auc: 0.9434 - loss: 0.3045 - val_acc: 0.8676 - val_auc: 0.9369 - val_loss: 0.3199
Epoch 28/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 328ms/step - acc: 0.8799 - auc: 0.9414 - loss: 0.3077
Epoch 28: val_acc did not improve from 0.87539
41/41 ━━━━━━━━━━━━━━━━━━━━ 14s 349ms/step - acc: 0.8799 - auc: 0.9415 - loss: 0.3075 - val_acc: 0.8754 - val_auc: 0.9366 - val_loss: 0.3190
Epoch 29/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 331ms/step - acc: 0.8770 - auc: 0.9488 - loss: 0.2901
Epoch 29: val_acc improved from 0.87539 to 0.88235, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_CNN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 21s 366ms/step - acc: 0.8771 - auc: 0.9487 - loss: 0.2901 - val_acc: 0.8824 - val_auc: 0.9409 - val_loss: 0.3096
Epoch 30/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 398ms/step - acc: 0.8820 - auc: 0.9527 - loss: 0.2792
Epoch 30: val_acc did not improve from 0.88235
41/41 ━━━━━━━━━━━━━━━━━━━━ 23s 425ms/step - acc: 0.8821 - auc: 0.9527 - loss: 0.2792 - val_acc: 0.8692 - val_auc: 0.9298 - val_loss: 0.3417
Epoch 31/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 378ms/step - acc: 0.8745 - auc: 0.9487 - loss: 0.2891
Epoch 31: val_acc did not improve from 0.88235
41/41 ━━━━━━━━━━━━━━━━━━━━ 20s 411ms/step - acc: 0.8745 - auc: 0.9487 - loss: 0.2890 - val_acc: 0.8754 - val_auc: 0.9378 - val_loss: 0.3164
Epoch 32/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 364ms/step - acc: 0.9001 - auc: 0.9598 - loss: 0.2584
Epoch 32: val_acc did not improve from 0.88235
41/41 ━━━━━━━━━━━━━━━━━━━━ 19s 389ms/step - acc: 0.9001 - auc: 0.9597 - loss: 0.2585 - val_acc: 0.8754 - val_auc: 0.9392 - val_loss: 0.3176
Epoch 33/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 383ms/step - acc: 0.8879 - auc: 0.9581 - loss: 0.2626
Epoch 33: val_acc did not improve from 0.88235
41/41 ━━━━━━━━━━━━━━━━━━━━ 22s 416ms/step - acc: 0.8879 - auc: 0.9581 - loss: 0.2627 - val_acc: 0.8669 - val_auc: 0.9367 - val_loss: 0.3272
Epoch 34/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 333ms/step - acc: 0.8883 - auc: 0.9518 - loss: 0.2803
Epoch 34: val_acc did not improve from 0.88235
41/41 ━━━━━━━━━━━━━━━━━━━━ 15s 366ms/step - acc: 0.8883 - auc: 0.9519 - loss: 0.2800 - val_acc: 0.8769 - val_auc: 0.9403 - val_loss: 0.3180
Epoch 35/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 330ms/step - acc: 0.8883 - auc: 0.9566 - loss: 0.2664
Epoch 35: val_acc did not improve from 0.88235
41/41 ━━━━━━━━━━━━━━━━━━━━ 20s 363ms/step - acc: 0.8883 - auc: 0.9565 - loss: 0.2667 - val_acc: 0.8754 - val_auc: 0.9399 - val_loss: 0.3113
Epoch 36/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 332ms/step - acc: 0.9024 - auc: 0.9641 - loss: 0.2429
Epoch 36: val_acc did not improve from 0.88235
41/41 ━━━━━━━━━━━━━━━━━━━━ 21s 365ms/step - acc: 0.9023 - auc: 0.9640 - loss: 0.2432 - val_acc: 0.8808 - val_auc: 0.9404 - val_loss: 0.3099
Epoch 37/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 332ms/step - acc: 0.9035 - auc: 0.9638 - loss: 0.2440
Epoch 37: val_acc did not improve from 0.88235
41/41 ━━━━━━━━━━━━━━━━━━━━ 21s 365ms/step - acc: 0.9033 - auc: 0.9636 - loss: 0.2444 - val_acc: 0.8723 - val_auc: 0.9375 - val_loss: 0.3176
Epoch 38/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 337ms/step - acc: 0.8990 - auc: 0.9627 - loss: 0.2482
Epoch 38: val_acc did not improve from 0.88235
41/41 ━━━━━━━━━━━━━━━━━━━━ 22s 402ms/step - acc: 0.8990 - auc: 0.9627 - loss: 0.2484 - val_acc: 0.8754 - val_auc: 0.9403 - val_loss: 0.3133
Epoch 39/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 333ms/step - acc: 0.9055 - auc: 0.9643 - loss: 0.2412
Epoch 39: val_acc did not improve from 0.88235
41/41 ━━━━━━━━━━━━━━━━━━━━ 15s 355ms/step - acc: 0.9054 - auc: 0.9643 - loss: 0.2413 - val_acc: 0.8785 - val_auc: 0.9416 - val_loss: 0.3100
Epoch 40/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 320ms/step - acc: 0.8961 - auc: 0.9641 - loss: 0.2434
Epoch 40: val_acc did not improve from 0.88235
41/41 ━━━━━━━━━━━━━━━━━━━━ 14s 342ms/step - acc: 0.8961 - auc: 0.9641 - loss: 0.2434 - val_acc: 0.8785 - val_auc: 0.9412 - val_loss: 0.3137
Epoch 41/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 333ms/step - acc: 0.9025 - auc: 0.9645 - loss: 0.2407
Epoch 41: val_acc did not improve from 0.88235
41/41 ━━━━━━━━━━━━━━━━━━━━ 22s 366ms/step - acc: 0.9025 - auc: 0.9645 - loss: 0.2406 - val_acc: 0.8777 - val_auc: 0.9420 - val_loss: 0.3142
Epoch 42/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 325ms/step - acc: 0.8989 - auc: 0.9652 - loss: 0.2387
Epoch 42: val_acc did not improve from 0.88235
41/41 ━━━━━━━━━━━━━━━━━━━━ 20s 358ms/step - acc: 0.8990 - auc: 0.9652 - loss: 0.2386 - val_acc: 0.8785 - val_auc: 0.9412 - val_loss: 0.3167
Epoch 43/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 338ms/step - acc: 0.9087 - auc: 0.9665 - loss: 0.2334
Epoch 43: val_acc did not improve from 0.88235
41/41 ━━━━━━━━━━━━━━━━━━━━ 21s 370ms/step - acc: 0.9086 - auc: 0.9665 - loss: 0.2334 - val_acc: 0.8762 - val_auc: 0.9415 - val_loss: 0.3160
Epoch 44/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 335ms/step - acc: 0.9084 - auc: 0.9715 - loss: 0.2159
Epoch 44: val_acc did not improve from 0.88235
41/41 ━━━━━━━━━━━━━━━━━━━━ 15s 368ms/step - acc: 0.9083 - auc: 0.9714 - loss: 0.2162 - val_acc: 0.8808 - val_auc: 0.9430 - val_loss: 0.3076
Epoch 45/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 334ms/step - acc: 0.9069 - auc: 0.9678 - loss: 0.2296
Epoch 45: val_acc improved from 0.88235 to 0.88313, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_CNN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 20s 358ms/step - acc: 0.9070 - auc: 0.9679 - loss: 0.2293 - val_acc: 0.8831 - val_auc: 0.9411 - val_loss: 0.3268
Epoch 46/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 334ms/step - acc: 0.9129 - auc: 0.9718 - loss: 0.2148
Epoch 46: val_acc did not improve from 0.88313
41/41 ━━━━━━━━━━━━━━━━━━━━ 21s 367ms/step - acc: 0.9128 - auc: 0.9718 - loss: 0.2149 - val_acc: 0.8707 - val_auc: 0.9354 - val_loss: 0.3448
Epoch 47/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 333ms/step - acc: 0.9178 - auc: 0.9740 - loss: 0.2052
Epoch 47: val_acc did not improve from 0.88313
41/41 ━━━━━━━━━━━━━━━━━━━━ 20s 360ms/step - acc: 0.9177 - auc: 0.9739 - loss: 0.2055 - val_acc: 0.8700 - val_auc: 0.9351 - val_loss: 0.3324
Epoch 48/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 357ms/step - acc: 0.9063 - auc: 0.9717 - loss: 0.2162
Epoch 48: val_acc did not improve from 0.88313
41/41 ━━━━━━━━━━━━━━━━━━━━ 22s 390ms/step - acc: 0.9063 - auc: 0.9717 - loss: 0.2162 - val_acc: 0.8684 - val_auc: 0.9391 - val_loss: 0.3296
Epoch 49/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 339ms/step - acc: 0.9181 - auc: 0.9731 - loss: 0.2104
Epoch 49: val_acc did not improve from 0.88313
41/41 ━━━━━━━━━━━━━━━━━━━━ 20s 372ms/step - acc: 0.9180 - auc: 0.9731 - loss: 0.2106 - val_acc: 0.8746 - val_auc: 0.9385 - val_loss: 0.3322
Epoch 50/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 336ms/step - acc: 0.9222 - auc: 0.9766 - loss: 0.1955
Epoch 50: val_acc did not improve from 0.88313
41/41 ━━━━━━━━━━━━━━━━━━━━ 15s 369ms/step - acc: 0.9220 - auc: 0.9765 - loss: 0.1958 - val_acc: 0.8715 - val_auc: 0.9394 - val_loss: 0.3273
Epoch 51/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 331ms/step - acc: 0.9279 - auc: 0.9790 - loss: 0.1868
Epoch 51: val_acc did not improve from 0.88313
41/41 ━━━━━━━━━━━━━━━━━━━━ 20s 364ms/step - acc: 0.9278 - auc: 0.9790 - loss: 0.1870 - val_acc: 0.8754 - val_auc: 0.9401 - val_loss: 0.3348
Epoch 52/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 333ms/step - acc: 0.9146 - auc: 0.9736 - loss: 0.2082
Epoch 52: val_acc did not improve from 0.88313
41/41 ━━━━━━━━━━━━━━━━━━━━ 22s 399ms/step - acc: 0.9147 - auc: 0.9736 - loss: 0.2080 - val_acc: 0.8754 - val_auc: 0.9402 - val_loss: 0.3354
Epoch 53/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 339ms/step - acc: 0.9268 - auc: 0.9786 - loss: 0.1873
Epoch 53: val_acc did not improve from 0.88313
41/41 ━━━━━━━━━━━━━━━━━━━━ 19s 371ms/step - acc: 0.9268 - auc: 0.9786 - loss: 0.1874 - val_acc: 0.8824 - val_auc: 0.9412 - val_loss: 0.3367
Epoch 54/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 335ms/step - acc: 0.9171 - auc: 0.9751 - loss: 0.2014
Epoch 54: val_acc did not improve from 0.88313
41/41 ━━━━━━━━━━━━━━━━━━━━ 20s 368ms/step - acc: 0.9172 - auc: 0.9751 - loss: 0.2011 - val_acc: 0.8723 - val_auc: 0.9396 - val_loss: 0.3523
Epoch 55/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 343ms/step - acc: 0.9273 - auc: 0.9790 - loss: 0.1841
Epoch 55: val_acc did not improve from 0.88313
41/41 ━━━━━━━━━━━━━━━━━━━━ 21s 377ms/step - acc: 0.9272 - auc: 0.9789 - loss: 0.1843 - val_acc: 0.8731 - val_auc: 0.9438 - val_loss: 0.3197
Epoch 56/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 340ms/step - acc: 0.9218 - auc: 0.9780 - loss: 0.1900
Epoch 56: val_acc did not improve from 0.88313
41/41 ━━━━━━━━━━━━━━━━━━━━ 15s 374ms/step - acc: 0.9218 - auc: 0.9780 - loss: 0.1899 - val_acc: 0.8731 - val_auc: 0.9376 - val_loss: 0.3398
Epoch 57/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 334ms/step - acc: 0.9299 - auc: 0.9802 - loss: 0.1799
Epoch 57: val_acc did not improve from 0.88313
41/41 ━━━━━━━━━━━━━━━━━━━━ 15s 367ms/step - acc: 0.9300 - auc: 0.9802 - loss: 0.1799 - val_acc: 0.8707 - val_auc: 0.9428 - val_loss: 0.3359
Epoch 58/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 345ms/step - acc: 0.9261 - auc: 0.9812 - loss: 0.1749
Epoch 58: val_acc did not improve from 0.88313
41/41 ━━━━━━━━━━━━━━━━━━━━ 21s 378ms/step - acc: 0.9260 - auc: 0.9812 - loss: 0.1751 - val_acc: 0.8723 - val_auc: 0.9382 - val_loss: 0.3381
Epoch 59/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 342ms/step - acc: 0.9265 - auc: 0.9822 - loss: 0.1721
Epoch 59: val_acc did not improve from 0.88313
41/41 ━━━━━━━━━━━━━━━━━━━━ 15s 375ms/step - acc: 0.9265 - auc: 0.9822 - loss: 0.1722 - val_acc: 0.8723 - val_auc: 0.9455 - val_loss: 0.3195
Epoch 60/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 340ms/step - acc: 0.9280 - auc: 0.9822 - loss: 0.1721
Epoch 60: val_acc did not improve from 0.88313
41/41 ━━━━━━━━━━━━━━━━━━━━ 15s 373ms/step - acc: 0.9280 - auc: 0.9821 - loss: 0.1722 - val_acc: 0.8762 - val_auc: 0.9417 - val_loss: 0.3354
Epoch 61/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 340ms/step - acc: 0.9306 - auc: 0.9831 - loss: 0.1673
Epoch 61: val_acc did not improve from 0.88313
41/41 ━━━━━━━━━━━━━━━━━━━━ 15s 373ms/step - acc: 0.9305 - auc: 0.9830 - loss: 0.1676 - val_acc: 0.8661 - val_auc: 0.9409 - val_loss: 0.3367
Epoch 62/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 339ms/step - acc: 0.9370 - auc: 0.9850 - loss: 0.1568
Epoch 62: val_acc did not improve from 0.88313
41/41 ━━━━━━━━━━━━━━━━━━━━ 15s 362ms/step - acc: 0.9370 - auc: 0.9850 - loss: 0.1569 - val_acc: 0.8746 - val_auc: 0.9439 - val_loss: 0.3336
Epoch 63/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 335ms/step - acc: 0.9389 - auc: 0.9850 - loss: 0.1556
Epoch 63: val_acc did not improve from 0.88313
41/41 ━━━━━━━━━━━━━━━━━━━━ 20s 368ms/step - acc: 0.9388 - auc: 0.9850 - loss: 0.1558 - val_acc: 0.8746 - val_auc: 0.9455 - val_loss: 0.3401
Epoch 64/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 346ms/step - acc: 0.9370 - auc: 0.9837 - loss: 0.1619
Epoch 64: val_acc did not improve from 0.88313
41/41 ━━━━━━━━━━━━━━━━━━━━ 17s 411ms/step - acc: 0.9369 - auc: 0.9837 - loss: 0.1620 - val_acc: 0.8715 - val_auc: 0.9428 - val_loss: 0.3390
Epoch 65/200

Model: "sequential_56"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_224 (Dense)               │ (None, 2048)           │     4,982,784 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_140         │ (None, 2048)           │         8,192 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_225 (Dense)               │ (None, 1024)           │     2,098,176 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_141         │ (None, 1024)           │         4,096 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_226 (Dense)               │ (None, 512)            │       524,800 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_142         │ (None, 512)            │         2,048 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_227 (Dense)               │ (None, 256)            │       131,328 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_143         │ (None, 256)            │         1,024 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_228 (Dense)               │ (None, 128)            │        32,896 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_144         │ (None, 128)            │           512 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_229 (Dense)               │ (None, 2)              │           258 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 7,786,114 (29.70 MB)

 Trainable params: 7,778,178 (29.67 MB)

 Non-trainable params: 7,936 (31.00 KB)

Epoch 1/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 172ms/step - acc: 0.7405 - auc: 0.8154 - loss: 0.6324
Epoch 1: val_auc improved from -inf to 0.69041, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_ANN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 15s 219ms/step - acc: 0.7418 - auc: 0.8166 - loss: 0.6293 - val_acc: 0.5410 - val_auc: 0.6904 - val_loss: 1.9572
Epoch 2/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 161ms/step - acc: 0.9080 - auc: 0.9669 - loss: 0.2381
Epoch 2: val_auc improved from 0.69041 to 0.72381, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_ANN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 9s 196ms/step - acc: 0.9079 - auc: 0.9669 - loss: 0.2382 - val_acc: 0.5960 - val_auc: 0.7238 - val_loss: 1.0706
Epoch 3/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 196ms/step - acc: 0.9379 - auc: 0.9831 - loss: 0.1667
Epoch 3: val_auc improved from 0.72381 to 0.84141, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_ANN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 12s 229ms/step - acc: 0.9377 - auc: 0.9830 - loss: 0.1671 - val_acc: 0.7430 - val_auc: 0.8414 - val_loss: 0.5496
Epoch 4/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 168ms/step - acc: 0.9498 - auc: 0.9887 - loss: 0.1359
Epoch 4: val_auc improved from 0.84141 to 0.86825, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_ANN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 9s 195ms/step - acc: 0.9496 - auc: 0.9886 - loss: 0.1363 - val_acc: 0.7755 - val_auc: 0.8683 - val_loss: 0.4878
Epoch 5/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 172ms/step - acc: 0.9516 - auc: 0.9906 - loss: 0.1249
Epoch 5: val_auc improved from 0.86825 to 0.90457, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_ANN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 11s 222ms/step - acc: 0.9514 - auc: 0.9905 - loss: 0.1254 - val_acc: 0.8235 - val_auc: 0.9046 - val_loss: 0.4168
Epoch 6/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 153ms/step - acc: 0.9578 - auc: 0.9915 - loss: 0.1200
Epoch 6: val_auc improved from 0.90457 to 0.91843, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_ANN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 9s 184ms/step - acc: 0.9578 - auc: 0.9915 - loss: 0.1201 - val_acc: 0.8406 - val_auc: 0.9184 - val_loss: 0.4265
Epoch 7/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 184ms/step - acc: 0.9656 - auc: 0.9944 - loss: 0.0939
Epoch 7: val_auc improved from 0.91843 to 0.92796, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_ANN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 12s 221ms/step - acc: 0.9655 - auc: 0.9943 - loss: 0.0943 - val_acc: 0.8475 - val_auc: 0.9280 - val_loss: 0.4282
Epoch 8/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 176ms/step - acc: 0.9626 - auc: 0.9943 - loss: 0.0944
Epoch 8: val_auc improved from 0.92796 to 0.93650, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_ANN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 8s 205ms/step - acc: 0.9626 - auc: 0.9943 - loss: 0.0943 - val_acc: 0.8715 - val_auc: 0.9365 - val_loss: 0.4306
Epoch 9/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 183ms/step - acc: 0.9799 - auc: 0.9969 - loss: 0.0626
Epoch 9: val_auc improved from 0.93650 to 0.94917, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_ANN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 10s 213ms/step - acc: 0.9799 - auc: 0.9969 - loss: 0.0626 - val_acc: 0.8808 - val_auc: 0.9492 - val_loss: 0.3608
Epoch 10/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 166ms/step - acc: 0.9802 - auc: 0.9970 - loss: 0.0595
Epoch 10: val_auc did not improve from 0.94917
41/41 ━━━━━━━━━━━━━━━━━━━━ 9s 184ms/step - acc: 0.9802 - auc: 0.9970 - loss: 0.0597 - val_acc: 0.8723 - val_auc: 0.9393 - val_loss: 0.3870
Epoch 11/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 174ms/step - acc: 0.9798 - auc: 0.9978 - loss: 0.0577
Epoch 11: val_auc did not improve from 0.94917
41/41 ━━━━━━━━━━━━━━━━━━━━ 11s 192ms/step - acc: 0.9798 - auc: 0.9977 - loss: 0.0580 - val_acc: 0.8839 - val_auc: 0.9443 - val_loss: 0.3982
Epoch 12/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 145ms/step - acc: 0.9765 - auc: 0.9969 - loss: 0.0651
Epoch 12: val_auc did not improve from 0.94917
41/41 ━━━━━━━━━━━━━━━━━━━━ 9s 162ms/step - acc: 0.9764 - auc: 0.9969 - loss: 0.0653 - val_acc: 0.8700 - val_auc: 0.9441 - val_loss: 0.4049
Epoch 13/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 155ms/step - acc: 0.9830 - auc: 0.9961 - loss: 0.0623
Epoch 13: val_auc did not improve from 0.94917
41/41 ━━━━━━━━━━━━━━━━━━━━ 11s 173ms/step - acc: 0.9830 - auc: 0.9961 - loss: 0.0623 - val_acc: 0.8963 - val_auc: 0.9474 - val_loss: 0.3995
Epoch 14/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 185ms/step - acc: 0.9801 - auc: 0.9976 - loss: 0.0563
Epoch 14: val_auc did not improve from 0.94917
41/41 ━━━━━━━━━━━━━━━━━━━━ 8s 202ms/step - acc: 0.9800 - auc: 0.9976 - loss: 0.0566 - val_acc: 0.8723 - val_auc: 0.9348 - val_loss: 0.4565
Epoch 15/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 153ms/step - acc: 0.9849 - auc: 0.9985 - loss: 0.0461
Epoch 15: val_auc improved from 0.94917 to 0.95328, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_ANN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 7s 179ms/step - acc: 0.9848 - auc: 0.9985 - loss: 0.0462 - val_acc: 0.8978 - val_auc: 0.9533 - val_loss: 0.3521
Epoch 16/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 174ms/step - acc: 0.9868 - auc: 0.9986 - loss: 0.0403
Epoch 16: val_auc did not improve from 0.95328
41/41 ━━━━━━━━━━━━━━━━━━━━ 11s 192ms/step - acc: 0.9867 - auc: 0.9986 - loss: 0.0406 - val_acc: 0.8707 - val_auc: 0.9350 - val_loss: 0.4530
Epoch 17/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 179ms/step - acc: 0.9841 - auc: 0.9983 - loss: 0.0456
Epoch 17: val_auc did not improve from 0.95328
41/41 ━━━━━━━━━━━━━━━━━━━━ 8s 190ms/step - acc: 0.9840 - auc: 0.9983 - loss: 0.0457 - val_acc: 0.8839 - val_auc: 0.9443 - val_loss: 0.4447
Epoch 18/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 185ms/step - acc: 0.9842 - auc: 0.9984 - loss: 0.0454
Epoch 18: val_auc did not improve from 0.95328
41/41 ━━━━━━━━━━━━━━━━━━━━ 11s 202ms/step - acc: 0.9841 - auc: 0.9983 - loss: 0.0455 - val_acc: 0.8824 - val_auc: 0.9370 - val_loss: 0.4463
Epoch 19/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 159ms/step - acc: 0.9848 - auc: 0.9987 - loss: 0.0444
Epoch 19: val_auc did not improve from 0.95328
41/41 ━━━━━━━━━━━━━━━━━━━━ 7s 173ms/step - acc: 0.9848 - auc: 0.9987 - loss: 0.0445 - val_acc: 0.8754 - val_auc: 0.9405 - val_loss: 0.4751
Epoch 20/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 175ms/step - acc: 0.9826 - auc: 0.9978 - loss: 0.0498
Epoch 20: val_auc did not improve from 0.95328
41/41 ━━━━━━━━━━━━━━━━━━━━ 8s 185ms/step - acc: 0.9826 - auc: 0.9978 - loss: 0.0499 - val_acc: 0.8824 - val_auc: 0.9435 - val_loss: 0.4497
Epoch 21/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 191ms/step - acc: 0.9880 - auc: 0.9993 - loss: 0.0349
Epoch 21: val_auc did not improve from 0.95328
41/41 ━━━━━━━━━━━━━━━━━━━━ 11s 208ms/step - acc: 0.9879 - auc: 0.9993 - loss: 0.0350 - val_acc: 0.8769 - val_auc: 0.9377 - val_loss: 0.5093
Epoch 22/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 169ms/step - acc: 0.9924 - auc: 0.9994 - loss: 0.0265
Epoch 22: val_auc did not improve from 0.95328
41/41 ━━━━━━━━━━━━━━━━━━━━ 9s 186ms/step - acc: 0.9924 - auc: 0.9994 - loss: 0.0265 - val_acc: 0.8793 - val_auc: 0.9450 - val_loss: 0.4394
Epoch 23/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 161ms/step - acc: 0.9944 - auc: 0.9998 - loss: 0.0181
Epoch 23: val_auc did not improve from 0.95328
41/41 ━━━━━━━━━━━━━━━━━━━━ 7s 177ms/step - acc: 0.9944 - auc: 0.9998 - loss: 0.0181 - val_acc: 0.8816 - val_auc: 0.9388 - val_loss: 0.4747
Epoch 24/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 162ms/step - acc: 0.9894 - auc: 0.9993 - loss: 0.0320
Epoch 24: val_auc did not improve from 0.95328
41/41 ━━━━━━━━━━━━━━━━━━━━ 10s 179ms/step - acc: 0.9894 - auc: 0.9993 - loss: 0.0321 - val_acc: 0.8777 - val_auc: 0.9373 - val_loss: 0.5100
Epoch 25/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 160ms/step - acc: 0.9867 - auc: 0.9978 - loss: 0.0487
Epoch 25: val_auc did not improve from 0.95328
41/41 ━━━━━━━━━━━━━━━━━━━━ 10s 177ms/step - acc: 0.9867 - auc: 0.9978 - loss: 0.0486 - val_acc: 0.8785 - val_auc: 0.9323 - val_loss: 0.5315
Epoch 26/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 150ms/step - acc: 0.9897 - auc: 0.9986 - loss: 0.0314
Epoch 26: val_auc did not improve from 0.95328
41/41 ━━━━━━━━━━━━━━━━━━━━ 10s 167ms/step - acc: 0.9897 - auc: 0.9986 - loss: 0.0313 - val_acc: 0.8947 - val_auc: 0.9371 - val_loss: 0.5180
Epoch 27/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 157ms/step - acc: 0.9951 - auc: 0.9995 - loss: 0.0195
Epoch 27: val_auc did not improve from 0.95328
41/41 ━━━━━━━━━━━━━━━━━━━━ 11s 174ms/step - acc: 0.9951 - auc: 0.9995 - loss: 0.0195 - val_acc: 0.8893 - val_auc: 0.9452 - val_loss: 0.4387
Epoch 28/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 160ms/step - acc: 0.9958 - auc: 0.9997 - loss: 0.0139
Epoch 28: val_auc did not improve from 0.95328
41/41 ━━━━━━━━━━━━━━━━━━━━ 10s 178ms/step - acc: 0.9958 - auc: 0.9997 - loss: 0.0140 - val_acc: 0.8862 - val_auc: 0.9404 - val_loss: 0.4888
Epoch 29/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 155ms/step - acc: 0.9924 - auc: 0.9989 - loss: 0.0234
Epoch 29: val_auc did not improve from 0.95328
41/41 ━━━━━━━━━━━━━━━━━━━━ 10s 168ms/step - acc: 0.9924 - auc: 0.9989 - loss: 0.0234 - val_acc: 0.8947 - val_auc: 0.9504 - val_loss: 0.4240
Epoch 30/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 172ms/step - acc: 0.9902 - auc: 0.9990 - loss: 0.0297
Epoch 30: val_auc did not improve from 0.95328
41/41 ━━━━━━━━━━━━━━━━━━━━ 11s 189ms/step - acc: 0.9902 - auc: 0.9990 - loss: 0.0298 - val_acc: 0.8885 - val_auc: 0.9388 - val_loss: 0.4929
Epoch 31/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 158ms/step - acc: 0.9879 - auc: 0.9983 - loss: 0.0402
Epoch 31: val_auc did not improve from 0.95328
41/41 ━━━━━━━━━━━━━━━━━━━━ 7s 173ms/step - acc: 0.9878 - auc: 0.9983 - loss: 0.0403 - val_acc: 0.8870 - val_auc: 0.9396 - val_loss: 0.4804
Epoch 32/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 150ms/step - acc: 0.9757 - auc: 0.9960 - loss: 0.0649
Epoch 32: val_auc did not improve from 0.95328
41/41 ━━━━━━━━━━━━━━━━━━━━ 7s 160ms/step - acc: 0.9757 - auc: 0.9960 - loss: 0.0649 - val_acc: 0.8669 - val_auc: 0.9239 - val_loss: 0.5951
Epoch 33/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 186ms/step - acc: 0.9826 - auc: 0.9980 - loss: 0.0517
Epoch 33: val_auc did not improve from 0.95328
41/41 ━━━━━━━━━━━━━━━━━━━━ 12s 203ms/step - acc: 0.9826 - auc: 0.9980 - loss: 0.0518 - val_acc: 0.8947 - val_auc: 0.9431 - val_loss: 0.4570
Epoch 34/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 184ms/step - acc: 0.9799 - auc: 0.9979 - loss: 0.0549
Epoch 34: val_auc did not improve from 0.95328
41/41 ━━━━━━━━━━━━━━━━━━━━ 10s 198ms/step - acc: 0.9800 - auc: 0.9980 - loss: 0.0547 - val_acc: 0.8839 - val_auc: 0.9399 - val_loss: 0.5028
Epoch 35/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 156ms/step - acc: 0.9920 - auc: 0.9990 - loss: 0.0279
Epoch 35: val_auc did not improve from 0.95328
41/41 ━━━━━━━━━━━━━━━━━━━━ 9s 174ms/step - acc: 0.9919 - auc: 0.9990 - loss: 0.0280 - val_acc: 0.8870 - val_auc: 0.9456 - val_loss: 0.4611
Epoch 36/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 163ms/step - acc: 0.9916 - auc: 0.9997 - loss: 0.0233
Epoch 36: val_auc did not improve from 0.95328
41/41 ━━━━━━━━━━━━━━━━━━━━ 7s 180ms/step - acc: 0.9916 - auc: 0.9997 - loss: 0.0233 - val_acc: 0.8878 - val_auc: 0.9390 - val_loss: 0.4810
Epoch 37/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 175ms/step - acc: 0.9972 - auc: 0.9999 - loss: 0.0131
Epoch 37: val_auc did not improve from 0.95328
41/41 ━━━━━━━━━━━━━━━━━━━━ 11s 192ms/step - acc: 0.9972 - auc: 0.9999 - loss: 0.0132 - val_acc: 0.8870 - val_auc: 0.9477 - val_loss: 0.4479
Epoch 38/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 177ms/step - acc: 0.9978 - auc: 0.9998 - loss: 0.0106
Epoch 38: val_auc did not improve from 0.95328
41/41 ━━━━━━━━━━━━━━━━━━━━ 10s 194ms/step - acc: 0.9978 - auc: 0.9998 - loss: 0.0106 - val_acc: 0.8816 - val_auc: 0.9447 - val_loss: 0.4586
Epoch 39/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 156ms/step - acc: 0.9979 - auc: 0.9999 - loss: 0.0085
Epoch 39: val_auc did not improve from 0.95328
41/41 ━━━━━━━━━━━━━━━━━━━━ 9s 168ms/step - acc: 0.9979 - auc: 0.9999 - loss: 0.0085 - val_acc: 0.9002 - val_auc: 0.9515 - val_loss: 0.4287
Epoch 40/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 160ms/step - acc: 0.9963 - auc: 0.9997 - loss: 0.0141
Epoch 40: val_auc did not improve from 0.95328
41/41 ━━━━━━━━━━━━━━━━━━━━ 11s 177ms/step - acc: 0.9963 - auc: 0.9997 - loss: 0.0142 - val_acc: 0.9009 - val_auc: 0.9462 - val_loss: 0.4449
Epoch 41/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 184ms/step - acc: 0.9919 - auc: 0.9995 - loss: 0.0214
Epoch 41: val_auc did not improve from 0.95328
41/41 ━━━━━━━━━━━━━━━━━━━━ 8s 202ms/step - acc: 0.9919 - auc: 0.9995 - loss: 0.0214 - val_acc: 0.8793 - val_auc: 0.9365 - val_loss: 0.4780
Epoch 42/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 174ms/step - acc: 0.9898 - auc: 0.9995 - loss: 0.0265
Epoch 42: val_auc did not improve from 0.95328
41/41 ━━━━━━━━━━━━━━━━━━━━ 8s 207ms/step - acc: 0.9898 - auc: 0.9994 - loss: 0.0266 - val_acc: 0.8615 - val_auc: 0.9233 - val_loss: 0.6307
Epoch 43/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 162ms/step - acc: 0.9873 - auc: 0.9992 - loss: 0.0344
Epoch 43: val_auc did not improve from 0.95328
41/41 ━━━━━━━━━━━━━━━━━━━━ 7s 179ms/step - acc: 0.9872 - auc: 0.9992 - loss: 0.0345 - val_acc: 0.8615 - val_auc: 0.9263 - val_loss: 0.5514
Epoch 44/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 171ms/step - acc: 0.9892 - auc: 0.9988 - loss: 0.0377
Epoch 44: val_auc did not improve from 0.95328
41/41 ━━━━━━━━━━━━━━━━━━━━ 11s 189ms/step - acc: 0.9893 - auc: 0.9988 - loss: 0.0377 - val_acc: 0.8676 - val_auc: 0.9214 - val_loss: 0.6413
Epoch 45/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 193ms/step - acc: 0.9909 - auc: 0.9982 - loss: 0.0348
Epoch 45: val_auc did not improve from 0.95328
41/41 ━━━━━━━━━━━━━━━━━━━━ 9s 210ms/step - acc: 0.9909 - auc: 0.9982 - loss: 0.0348 - val_acc: 0.8808 - val_auc: 0.9350 - val_loss: 0.5158
Epoch 46/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 170ms/step - acc: 0.9920 - auc: 0.9995 - loss: 0.0237
Epoch 46: val_auc did not improve from 0.95328
41/41 ━━━━━━━━━━━━━━━━━━━━ 8s 187ms/step - acc: 0.9919 - auc: 0.9995 - loss: 0.0238 - val_acc: 0.8785 - val_auc: 0.9330 - val_loss: 0.5398
Epoch 47/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 186ms/step - acc: 0.9942 - auc: 0.9988 - loss: 0.0260
Epoch 47: val_auc did not improve from 0.95328
41/41 ━━━━━━━━━━━━━━━━━━━━ 8s 203ms/step - acc: 0.9942 - auc: 0.9989 - loss: 0.0259 - val_acc: 0.8909 - val_auc: 0.9434 - val_loss: 0.4557
Epoch 48/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 169ms/step - acc: 0.9968 - auc: 1.0000 - loss: 0.0095
Epoch 48: val_auc did not improve from 0.95328
41/41 ━━━━━━━━━━━━━━━━━━━━ 8s 186ms/step - acc: 0.9967 - auc: 1.0000 - loss: 0.0096 - val_acc: 0.9009 - val_auc: 0.9530 - val_loss: 0.4045
Epoch 49/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 162ms/step - acc: 0.9964 - auc: 0.9996 - loss: 0.0146
Epoch 49: val_auc did not improve from 0.95328
41/41 ━━━━━━━━━━━━━━━━━━━━ 7s 179ms/step - acc: 0.9964 - auc: 0.9996 - loss: 0.0147 - val_acc: 0.9002 - val_auc: 0.9499 - val_loss: 0.4446
Epoch 50/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 177ms/step - acc: 0.9982 - auc: 0.9999 - loss: 0.0086
Epoch 50: val_auc did not improve from 0.95328
41/41 ━━━━━━━━━━━━━━━━━━━━ 8s 195ms/step - acc: 0.9982 - auc: 0.9999 - loss: 0.0086 - val_acc: 0.8994 - val_auc: 0.9442 - val_loss: 0.4570
Epoch 51/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 164ms/step - acc: 0.9957 - auc: 0.9996 - loss: 0.0129
Epoch 51: val_auc did not improve from 0.95328
41/41 ━━━━━━━━━━━━━━━━━━━━ 10s 182ms/step - acc: 0.9957 - auc: 0.9996 - loss: 0.0129 - val_acc: 0.8878 - val_auc: 0.9399 - val_loss: 0.4957
Epoch 52/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 165ms/step - acc: 0.9982 - auc: 0.9997 - loss: 0.0088
Epoch 52: val_auc did not improve from 0.95328
41/41 ━━━━━━━━━━━━━━━━━━━━ 7s 176ms/step - acc: 0.9982 - auc: 0.9997 - loss: 0.0089 - val_acc: 0.8916 - val_auc: 0.9424 - val_loss: 0.4739
Epoch 53/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 181ms/step - acc: 0.9979 - auc: 0.9997 - loss: 0.0090
Epoch 53: val_auc did not improve from 0.95328
41/41 ━━━━━━━━━━━━━━━━━━━━ 11s 198ms/step - acc: 0.9979 - auc: 0.9997 - loss: 0.0090 - val_acc: 0.9002 - val_auc: 0.9381 - val_loss: 0.4872
Epoch 54/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 190ms/step - acc: 0.9945 - auc: 0.9995 - loss: 0.0173
Epoch 54: val_auc did not improve from 0.95328
41/41 ━━━━━━━━━━━━━━━━━━━━ 11s 208ms/step - acc: 0.9944 - auc: 0.9995 - loss: 0.0173 - val_acc: 0.8793 - val_auc: 0.9354 - val_loss: 0.5334
Epoch 55/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 187ms/step - acc: 0.9930 - auc: 0.9993 - loss: 0.0206
Epoch 55: val_auc did not improve from 0.95328
41/41 ━━━━━━━━━━━━━━━━━━━━ 10s 206ms/step - acc: 0.9930 - auc: 0.9993 - loss: 0.0205 - val_acc: 0.8870 - val_auc: 0.9383 - val_loss: 0.4966
Epoch 56/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 175ms/step - acc: 0.9972 - auc: 1.0000 - loss: 0.0086
Epoch 56: val_auc did not improve from 0.95328
41/41 ━━━━━━━━━━━━━━━━━━━━ 10s 193ms/step - acc: 0.9972 - auc: 1.0000 - loss: 0.0087 - val_acc: 0.8893 - val_auc: 0.9359 - val_loss: 0.5459
Epoch 57/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 163ms/step - acc: 0.9939 - auc: 0.9993 - loss: 0.0201
Epoch 57: val_auc did not improve from 0.95328
41/41 ━━━━━━━━━━━━━━━━━━━━ 10s 180ms/step - acc: 0.9938 - auc: 0.9993 - loss: 0.0202 - val_acc: 0.8878 - val_auc: 0.9339 - val_loss: 0.5445
Epoch 58/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 169ms/step - acc: 0.9864 - auc: 0.9978 - loss: 0.0396
Epoch 58: val_auc did not improve from 0.95328
41/41 ━━━━━━━━━━━━━━━━━━━━ 10s 186ms/step - acc: 0.9865 - auc: 0.9978 - loss: 0.0395 - val_acc: 0.8909 - val_auc: 0.9357 - val_loss: 0.5583
Epoch 59/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 184ms/step - acc: 0.9842 - auc: 0.9984 - loss: 0.0380
Epoch 59: val_auc did not improve from 0.95328
41/41 ━━━━━━━━━━━━━━━━━━━━ 8s 202ms/step - acc: 0.9843 - auc: 0.9984 - loss: 0.0379 - val_acc: 0.8916 - val_auc: 0.9433 - val_loss: 0.4994
Epoch 60/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 173ms/step - acc: 0.9928 - auc: 0.9988 - loss: 0.0256
Epoch 60: val_auc did not improve from 0.95328
41/41 ━━━━━━━━━━━━━━━━━━━━ 10s 190ms/step - acc: 0.9928 - auc: 0.9988 - loss: 0.0258 - val_acc: 0.8885 - val_auc: 0.9375 - val_loss: 0.5338
Epoch 61/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 176ms/step - acc: 0.9935 - auc: 0.9996 - loss: 0.0210
Epoch 61: val_auc did not improve from 0.95328
41/41 ━━━━━━━━━━━━━━━━━━━━ 8s 190ms/step - acc: 0.9935 - auc: 0.9996 - loss: 0.0209 - val_acc: 0.8916 - val_auc: 0.9422 - val_loss: 0.5230
Epoch 62/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 178ms/step - acc: 0.9923 - auc: 0.9992 - loss: 0.0223
Epoch 62: val_auc did not improve from 0.95328
41/41 ━━━━━━━━━━━━━━━━━━━━ 10s 195ms/step - acc: 0.9923 - auc: 0.9992 - loss: 0.0223 - val_acc: 0.8862 - val_auc: 0.9381 - val_loss: 0.5319
Epoch 63/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 173ms/step - acc: 0.9925 - auc: 0.9995 - loss: 0.0202
Epoch 63: val_auc did not improve from 0.95328
41/41 ━━━━━━━━━━━━━━━━━━━━ 10s 191ms/step - acc: 0.9925 - auc: 0.9995 - loss: 0.0203 - val_acc: 0.8808 - val_auc: 0.9384 - val_loss: 0.5219
Epoch 64/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 159ms/step - acc: 0.9905 - auc: 0.9988 - loss: 0.0297
Epoch 64: val_auc did not improve from 0.95328
41/41 ━━━━━━━━━━━━━━━━━━━━ 10s 177ms/step - acc: 0.9905 - auc: 0.9988 - loss: 0.0297 - val_acc: 0.8870 - val_auc: 0.9327 - val_loss: 0.5515
Epoch 65/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 172ms/step - acc: 0.9945 - auc: 0.9996 - loss: 0.0171
Epoch 65: val_auc did not improve from 0.95328
41/41 ━━━━━━━━━━━━━━━━━━━━ 11s 190ms/step - acc: 0.9945 - auc: 0.9996 - loss: 0.0172 - val_acc: 0.8731 - val_auc: 0.9283 - val_loss: 0.6259
Epoch 66/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 179ms/step - acc: 0.9942 - auc: 0.9986 - loss: 0.0215
Epoch 66: val_auc did not improve from 0.95328
41/41 ━━━━━━━━━━━━━━━━━━━━ 8s 196ms/step - acc: 0.9942 - auc: 0.9986 - loss: 0.0215 - val_acc: 0.8854 - val_auc: 0.9405 - val_loss: 0.5039
Epoch 67/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 159ms/step - acc: 0.9934 - auc: 0.9991 - loss: 0.0190
Epoch 67: val_auc did not improve from 0.95328
41/41 ━━━━━━━━━━━━━━━━━━━━ 7s 177ms/step - acc: 0.9934 - auc: 0.9991 - loss: 0.0189 - val_acc: 0.8824 - val_auc: 0.9402 - val_loss: 0.5336
Epoch 68/200

Model: "sequential_57"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv2d_84 (Conv2D)              │ (None, 62, 36, 32)     │           320 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_84 (MaxPooling2D) │ (None, 31, 18, 32)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_84 (Dropout)            │ (None, 31, 18, 32)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_85 (Conv2D)              │ (None, 29, 16, 64)     │        18,496 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_85 (MaxPooling2D) │ (None, 14, 8, 64)      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_85 (Dropout)            │ (None, 14, 8, 64)      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_86 (Conv2D)              │ (None, 12, 6, 128)     │        73,856 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_86 (MaxPooling2D) │ (None, 6, 3, 128)      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_86 (Dropout)            │ (None, 6, 3, 128)      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_28 (Flatten)            │ (None, 2304)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_230 (Dense)               │ (None, 128)            │       295,040 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_231 (Dense)               │ (None, 2)              │           258 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 387,970 (1.48 MB)

 Trainable params: 387,970 (1.48 MB)

 Non-trainable params: 0 (0.00 B)

Epoch 1/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 376ms/step - acc: 0.4943 - auc: 0.4967 - loss: 0.7182
Epoch 1: val_acc improved from -inf to 0.55960, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_CNN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 24s 427ms/step - acc: 0.4943 - auc: 0.4967 - loss: 0.7178 - val_acc: 0.5596 - val_auc: 0.5000 - val_loss: 0.6927
Epoch 2/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 377ms/step - acc: 0.5067 - auc: 0.5003 - loss: 0.6932
Epoch 2: val_acc did not improve from 0.55960
41/41 ━━━━━━━━━━━━━━━━━━━━ 17s 407ms/step - acc: 0.5069 - auc: 0.5006 - loss: 0.6932 - val_acc: 0.5062 - val_auc: 0.6272 - val_loss: 0.6922
Epoch 3/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 358ms/step - acc: 0.5338 - auc: 0.5649 - loss: 0.6908
Epoch 3: val_acc improved from 0.55960 to 0.62616, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_CNN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 20s 396ms/step - acc: 0.5343 - auc: 0.5655 - loss: 0.6907 - val_acc: 0.6262 - val_auc: 0.7195 - val_loss: 0.6670
Epoch 4/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 388ms/step - acc: 0.6282 - auc: 0.6900 - loss: 0.6509
Epoch 4: val_acc improved from 0.62616 to 0.71207, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_CNN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 22s 423ms/step - acc: 0.6291 - auc: 0.6908 - loss: 0.6502 - val_acc: 0.7121 - val_auc: 0.8154 - val_loss: 0.5385
Epoch 5/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 352ms/step - acc: 0.7400 - auc: 0.8084 - loss: 0.5384
Epoch 5: val_acc improved from 0.71207 to 0.78019, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_CNN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 19s 387ms/step - acc: 0.7401 - auc: 0.8086 - loss: 0.5382 - val_acc: 0.7802 - val_auc: 0.8587 - val_loss: 0.4890
Epoch 6/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 382ms/step - acc: 0.7700 - auc: 0.8416 - loss: 0.4986
Epoch 6: val_acc improved from 0.78019 to 0.79721, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_CNN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 22s 418ms/step - acc: 0.7700 - auc: 0.8417 - loss: 0.4983 - val_acc: 0.7972 - val_auc: 0.8844 - val_loss: 0.4303
Epoch 7/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 466ms/step - acc: 0.7732 - auc: 0.8575 - loss: 0.4705
Epoch 7: val_acc improved from 0.79721 to 0.81579, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_CNN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 24s 500ms/step - acc: 0.7733 - auc: 0.8576 - loss: 0.4704 - val_acc: 0.8158 - val_auc: 0.8960 - val_loss: 0.4091
Epoch 8/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 387ms/step - acc: 0.7957 - auc: 0.8806 - loss: 0.4347
Epoch 8: val_acc improved from 0.81579 to 0.81811, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_CNN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 37s 415ms/step - acc: 0.7956 - auc: 0.8806 - loss: 0.4348 - val_acc: 0.8181 - val_auc: 0.8981 - val_loss: 0.4060
Epoch 9/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 423ms/step - acc: 0.7941 - auc: 0.8707 - loss: 0.4505
Epoch 9: val_acc did not improve from 0.81811
41/41 ━━━━━━━━━━━━━━━━━━━━ 22s 457ms/step - acc: 0.7941 - auc: 0.8708 - loss: 0.4503 - val_acc: 0.8158 - val_auc: 0.9001 - val_loss: 0.4015
Epoch 10/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 376ms/step - acc: 0.8121 - auc: 0.8899 - loss: 0.4197
Epoch 10: val_acc did not improve from 0.81811
41/41 ━━━━━━━━━━━━━━━━━━━━ 19s 410ms/step - acc: 0.8119 - auc: 0.8898 - loss: 0.4198 - val_acc: 0.8127 - val_auc: 0.8953 - val_loss: 0.4087
Epoch 11/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 409ms/step - acc: 0.8007 - auc: 0.8860 - loss: 0.4261
Epoch 11: val_acc improved from 0.81811 to 0.81966, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_CNN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 18s 445ms/step - acc: 0.8009 - auc: 0.8861 - loss: 0.4259 - val_acc: 0.8197 - val_auc: 0.9036 - val_loss: 0.3934
Epoch 12/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 376ms/step - acc: 0.8185 - auc: 0.8984 - loss: 0.4033
Epoch 12: val_acc did not improve from 0.81966
41/41 ━━━━━━━━━━━━━━━━━━━━ 19s 411ms/step - acc: 0.8184 - auc: 0.8983 - loss: 0.4035 - val_acc: 0.8173 - val_auc: 0.9044 - val_loss: 0.3978
Epoch 13/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 380ms/step - acc: 0.8267 - auc: 0.8986 - loss: 0.4050
Epoch 13: val_acc did not improve from 0.81966
41/41 ━━━━━━━━━━━━━━━━━━━━ 21s 414ms/step - acc: 0.8265 - auc: 0.8985 - loss: 0.4051 - val_acc: 0.8197 - val_auc: 0.9075 - val_loss: 0.3852
Epoch 14/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 378ms/step - acc: 0.8214 - auc: 0.8997 - loss: 0.4001
Epoch 14: val_acc improved from 0.81966 to 0.82585, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_CNN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 21s 419ms/step - acc: 0.8212 - auc: 0.8996 - loss: 0.4004 - val_acc: 0.8259 - val_auc: 0.9096 - val_loss: 0.3821
Epoch 15/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 359ms/step - acc: 0.8231 - auc: 0.9024 - loss: 0.3962
Epoch 15: val_acc improved from 0.82585 to 0.83591, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_CNN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 19s 394ms/step - acc: 0.8231 - auc: 0.9024 - loss: 0.3962 - val_acc: 0.8359 - val_auc: 0.9118 - val_loss: 0.3803
Epoch 16/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 360ms/step - acc: 0.8274 - auc: 0.9060 - loss: 0.3898
Epoch 16: val_acc did not improve from 0.83591
41/41 ━━━━━━━━━━━━━━━━━━━━ 16s 394ms/step - acc: 0.8272 - auc: 0.9059 - loss: 0.3900 - val_acc: 0.8344 - val_auc: 0.9109 - val_loss: 0.3785
Epoch 17/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 369ms/step - acc: 0.8240 - auc: 0.9018 - loss: 0.3975
Epoch 17: val_acc did not improve from 0.83591
41/41 ━━━━━━━━━━━━━━━━━━━━ 21s 403ms/step - acc: 0.8239 - auc: 0.9018 - loss: 0.3975 - val_acc: 0.8297 - val_auc: 0.9143 - val_loss: 0.3720
Epoch 18/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 408ms/step - acc: 0.8260 - auc: 0.9049 - loss: 0.3905
Epoch 18: val_acc improved from 0.83591 to 0.83901, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_CNN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 22s 444ms/step - acc: 0.8259 - auc: 0.9049 - loss: 0.3906 - val_acc: 0.8390 - val_auc: 0.9159 - val_loss: 0.3684
Epoch 19/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 388ms/step - acc: 0.8371 - auc: 0.9069 - loss: 0.3877
Epoch 19: val_acc improved from 0.83901 to 0.84288, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_CNN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 17s 414ms/step - acc: 0.8371 - auc: 0.9070 - loss: 0.3876 - val_acc: 0.8429 - val_auc: 0.9167 - val_loss: 0.3668
Epoch 20/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 390ms/step - acc: 0.8331 - auc: 0.9075 - loss: 0.3866
Epoch 20: val_acc did not improve from 0.84288
41/41 ━━━━━━━━━━━━━━━━━━━━ 21s 423ms/step - acc: 0.8332 - auc: 0.9076 - loss: 0.3864 - val_acc: 0.8313 - val_auc: 0.9164 - val_loss: 0.3676
Epoch 21/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 380ms/step - acc: 0.8405 - auc: 0.9154 - loss: 0.3700
Epoch 21: val_acc improved from 0.84288 to 0.84598, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_CNN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 20s 415ms/step - acc: 0.8404 - auc: 0.9153 - loss: 0.3702 - val_acc: 0.8460 - val_auc: 0.9219 - val_loss: 0.3554
Epoch 22/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 358ms/step - acc: 0.8499 - auc: 0.9213 - loss: 0.3581
Epoch 22: val_acc improved from 0.84598 to 0.84985, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_CNN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 16s 393ms/step - acc: 0.8498 - auc: 0.9212 - loss: 0.3583 - val_acc: 0.8498 - val_auc: 0.9248 - val_loss: 0.3532
Epoch 23/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 358ms/step - acc: 0.8477 - auc: 0.9180 - loss: 0.3640
Epoch 23: val_acc improved from 0.84985 to 0.85139, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_CNN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 16s 394ms/step - acc: 0.8477 - auc: 0.9181 - loss: 0.3639 - val_acc: 0.8514 - val_auc: 0.9286 - val_loss: 0.3408
Epoch 24/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 366ms/step - acc: 0.8455 - auc: 0.9249 - loss: 0.3492
Epoch 24: val_acc improved from 0.85139 to 0.85913, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_CNN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 21s 402ms/step - acc: 0.8455 - auc: 0.9248 - loss: 0.3494 - val_acc: 0.8591 - val_auc: 0.9300 - val_loss: 0.3383
Epoch 25/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 384ms/step - acc: 0.8573 - auc: 0.9296 - loss: 0.3396
Epoch 25: val_acc did not improve from 0.85913
41/41 ━━━━━━━━━━━━━━━━━━━━ 21s 417ms/step - acc: 0.8572 - auc: 0.9295 - loss: 0.3399 - val_acc: 0.8584 - val_auc: 0.9306 - val_loss: 0.3382
Epoch 26/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 348ms/step - acc: 0.8468 - auc: 0.9206 - loss: 0.3582
Epoch 26: val_acc did not improve from 0.85913
41/41 ━━━━━━━━━━━━━━━━━━━━ 19s 372ms/step - acc: 0.8469 - auc: 0.9207 - loss: 0.3579 - val_acc: 0.8576 - val_auc: 0.9313 - val_loss: 0.3343
Epoch 27/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 369ms/step - acc: 0.8525 - auc: 0.9289 - loss: 0.3398
Epoch 27: val_acc improved from 0.85913 to 0.86533, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_CNN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 18s 437ms/step - acc: 0.8526 - auc: 0.9289 - loss: 0.3398 - val_acc: 0.8653 - val_auc: 0.9333 - val_loss: 0.3365
Epoch 28/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 365ms/step - acc: 0.8567 - auc: 0.9325 - loss: 0.3334
Epoch 28: val_acc did not improve from 0.86533
41/41 ━━━━━━━━━━━━━━━━━━━━ 16s 398ms/step - acc: 0.8568 - auc: 0.9325 - loss: 0.3332 - val_acc: 0.8413 - val_auc: 0.9223 - val_loss: 0.3569
Epoch 29/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 378ms/step - acc: 0.8714 - auc: 0.9327 - loss: 0.3302
Epoch 29: val_acc did not improve from 0.86533
41/41 ━━━━━━━━━━━━━━━━━━━━ 21s 408ms/step - acc: 0.8714 - auc: 0.9327 - loss: 0.3301 - val_acc: 0.8568 - val_auc: 0.9260 - val_loss: 0.3473
Epoch 30/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 383ms/step - acc: 0.8534 - auc: 0.9308 - loss: 0.3359
Epoch 30: val_acc did not improve from 0.86533
41/41 ━━━━━━━━━━━━━━━━━━━━ 21s 417ms/step - acc: 0.8536 - auc: 0.9309 - loss: 0.3356 - val_acc: 0.8653 - val_auc: 0.9395 - val_loss: 0.3158
Epoch 31/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 363ms/step - acc: 0.8681 - auc: 0.9406 - loss: 0.3112
Epoch 31: val_acc did not improve from 0.86533
41/41 ━━━━━━━━━━━━━━━━━━━━ 20s 396ms/step - acc: 0.8680 - auc: 0.9405 - loss: 0.3113 - val_acc: 0.8646 - val_auc: 0.9358 - val_loss: 0.3249
Epoch 32/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 360ms/step - acc: 0.8683 - auc: 0.9387 - loss: 0.3159
Epoch 32: val_acc did not improve from 0.86533
41/41 ━━━━━━━━━━━━━━━━━━━━ 16s 384ms/step - acc: 0.8685 - auc: 0.9388 - loss: 0.3157 - val_acc: 0.8615 - val_auc: 0.9417 - val_loss: 0.3123
Epoch 33/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 356ms/step - acc: 0.8741 - auc: 0.9411 - loss: 0.3104
Epoch 33: val_acc improved from 0.86533 to 0.87306, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_CNN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 20s 385ms/step - acc: 0.8741 - auc: 0.9410 - loss: 0.3104 - val_acc: 0.8731 - val_auc: 0.9446 - val_loss: 0.3028
Epoch 34/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 405ms/step - acc: 0.8741 - auc: 0.9367 - loss: 0.3202
Epoch 34: val_acc did not improve from 0.87306
41/41 ━━━━━━━━━━━━━━━━━━━━ 23s 438ms/step - acc: 0.8741 - auc: 0.9369 - loss: 0.3198 - val_acc: 0.8638 - val_auc: 0.9414 - val_loss: 0.3123
Epoch 35/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 386ms/step - acc: 0.8818 - auc: 0.9466 - loss: 0.2952
Epoch 35: val_acc did not improve from 0.87306
41/41 ━━━━━━━━━━━━━━━━━━━━ 20s 420ms/step - acc: 0.8817 - auc: 0.9465 - loss: 0.2954 - val_acc: 0.8684 - val_auc: 0.9417 - val_loss: 0.3113
Epoch 36/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 397ms/step - acc: 0.8808 - auc: 0.9487 - loss: 0.2886
Epoch 36: val_acc did not improve from 0.87306
41/41 ━━━━━━━━━━━━━━━━━━━━ 18s 432ms/step - acc: 0.8808 - auc: 0.9487 - loss: 0.2886 - val_acc: 0.8676 - val_auc: 0.9451 - val_loss: 0.3021
Epoch 37/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 374ms/step - acc: 0.8846 - auc: 0.9499 - loss: 0.2862
Epoch 37: val_acc improved from 0.87306 to 0.87539, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_CNN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 20s 410ms/step - acc: 0.8846 - auc: 0.9499 - loss: 0.2863 - val_acc: 0.8754 - val_auc: 0.9477 - val_loss: 0.2963
Epoch 38/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 374ms/step - acc: 0.8911 - auc: 0.9530 - loss: 0.2782
Epoch 38: val_acc improved from 0.87539 to 0.87926, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_CNN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 18s 443ms/step - acc: 0.8910 - auc: 0.9530 - loss: 0.2782 - val_acc: 0.8793 - val_auc: 0.9499 - val_loss: 0.2907
Epoch 39/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 380ms/step - acc: 0.8797 - auc: 0.9530 - loss: 0.2779
Epoch 39: val_acc did not improve from 0.87926
41/41 ━━━━━━━━━━━━━━━━━━━━ 19s 413ms/step - acc: 0.8798 - auc: 0.9530 - loss: 0.2779 - val_acc: 0.8754 - val_auc: 0.9505 - val_loss: 0.2868
Epoch 40/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 370ms/step - acc: 0.8881 - auc: 0.9478 - loss: 0.2890
Epoch 40: val_acc did not improve from 0.87926
41/41 ━━━━━━━━━━━━━━━━━━━━ 20s 403ms/step - acc: 0.8881 - auc: 0.9479 - loss: 0.2889 - val_acc: 0.8746 - val_auc: 0.9492 - val_loss: 0.2921
Epoch 41/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 392ms/step - acc: 0.8986 - auc: 0.9600 - loss: 0.2557
Epoch 41: val_acc did not improve from 0.87926
41/41 ━━━━━━━━━━━━━━━━━━━━ 22s 428ms/step - acc: 0.8984 - auc: 0.9599 - loss: 0.2559 - val_acc: 0.8762 - val_auc: 0.9504 - val_loss: 0.2875
Epoch 42/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 386ms/step - acc: 0.8943 - auc: 0.9593 - loss: 0.2582
Epoch 42: val_acc did not improve from 0.87926
41/41 ━━━━━━━━━━━━━━━━━━━━ 20s 420ms/step - acc: 0.8942 - auc: 0.9592 - loss: 0.2585 - val_acc: 0.8769 - val_auc: 0.9491 - val_loss: 0.2921
Epoch 43/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 408ms/step - acc: 0.8914 - auc: 0.9561 - loss: 0.2677
Epoch 43: val_acc did not improve from 0.87926
41/41 ━━━━━━━━━━━━━━━━━━━━ 21s 443ms/step - acc: 0.8915 - auc: 0.9561 - loss: 0.2675 - val_acc: 0.8785 - val_auc: 0.9504 - val_loss: 0.2888
Epoch 44/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 394ms/step - acc: 0.8950 - auc: 0.9604 - loss: 0.2546
Epoch 44: val_acc did not improve from 0.87926
41/41 ━━━━━━━━━━━━━━━━━━━━ 20s 436ms/step - acc: 0.8948 - auc: 0.9603 - loss: 0.2548 - val_acc: 0.8785 - val_auc: 0.9498 - val_loss: 0.2892
Epoch 45/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 371ms/step - acc: 0.8967 - auc: 0.9592 - loss: 0.2575
Epoch 45: val_acc improved from 0.87926 to 0.88003, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_CNN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 17s 410ms/step - acc: 0.8968 - auc: 0.9592 - loss: 0.2575 - val_acc: 0.8800 - val_auc: 0.9506 - val_loss: 0.2867
Epoch 46/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 377ms/step - acc: 0.9009 - auc: 0.9635 - loss: 0.2438
Epoch 46: val_acc did not improve from 0.88003
41/41 ━━━━━━━━━━━━━━━━━━━━ 17s 410ms/step - acc: 0.9008 - auc: 0.9634 - loss: 0.2441 - val_acc: 0.8731 - val_auc: 0.9509 - val_loss: 0.2866
Epoch 47/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 364ms/step - acc: 0.8982 - auc: 0.9638 - loss: 0.2454
Epoch 47: val_acc did not improve from 0.88003
41/41 ━━━━━━━━━━━━━━━━━━━━ 20s 398ms/step - acc: 0.8982 - auc: 0.9638 - loss: 0.2453 - val_acc: 0.8769 - val_auc: 0.9518 - val_loss: 0.2836
Epoch 48/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 388ms/step - acc: 0.8999 - auc: 0.9649 - loss: 0.2396
Epoch 48: val_acc improved from 0.88003 to 0.88467, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_CNN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 21s 425ms/step - acc: 0.8998 - auc: 0.9649 - loss: 0.2397 - val_acc: 0.8847 - val_auc: 0.9529 - val_loss: 0.2791
Epoch 49/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 361ms/step - acc: 0.8976 - auc: 0.9639 - loss: 0.2436
Epoch 49: val_acc did not improve from 0.88467
41/41 ━━━━━━━━━━━━━━━━━━━━ 19s 394ms/step - acc: 0.8977 - auc: 0.9639 - loss: 0.2435 - val_acc: 0.8769 - val_auc: 0.9535 - val_loss: 0.2877
Epoch 50/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 366ms/step - acc: 0.9017 - auc: 0.9649 - loss: 0.2396
Epoch 50: val_acc did not improve from 0.88467
41/41 ━━━━━━━━━━━━━━━━━━━━ 21s 399ms/step - acc: 0.9017 - auc: 0.9649 - loss: 0.2396 - val_acc: 0.8769 - val_auc: 0.9503 - val_loss: 0.2929
Epoch 51/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 364ms/step - acc: 0.9045 - auc: 0.9673 - loss: 0.2318
Epoch 51: val_acc did not improve from 0.88467
41/41 ━━━━━━━━━━━━━━━━━━━━ 22s 431ms/step - acc: 0.9045 - auc: 0.9672 - loss: 0.2320 - val_acc: 0.8715 - val_auc: 0.9502 - val_loss: 0.2910
Epoch 52/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 368ms/step - acc: 0.9092 - auc: 0.9684 - loss: 0.2276
Epoch 52: val_acc did not improve from 0.88467
41/41 ━━━━━━━━━━━━━━━━━━━━ 17s 401ms/step - acc: 0.9092 - auc: 0.9684 - loss: 0.2276 - val_acc: 0.8731 - val_auc: 0.9496 - val_loss: 0.2970
Epoch 53/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 375ms/step - acc: 0.9118 - auc: 0.9703 - loss: 0.2213
Epoch 53: val_acc did not improve from 0.88467
41/41 ━━━━━━━━━━━━━━━━━━━━ 21s 410ms/step - acc: 0.9116 - auc: 0.9702 - loss: 0.2216 - val_acc: 0.8738 - val_auc: 0.9483 - val_loss: 0.2964
Epoch 54/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 374ms/step - acc: 0.9043 - auc: 0.9673 - loss: 0.2324
Epoch 54: val_acc did not improve from 0.88467
41/41 ━━━━━━━━━━━━━━━━━━━━ 17s 408ms/step - acc: 0.9043 - auc: 0.9673 - loss: 0.2323 - val_acc: 0.8808 - val_auc: 0.9523 - val_loss: 0.2842
Epoch 55/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 378ms/step - acc: 0.9081 - auc: 0.9696 - loss: 0.2238
Epoch 55: val_acc did not improve from 0.88467
41/41 ━━━━━━━━━━━━━━━━━━━━ 17s 412ms/step - acc: 0.9080 - auc: 0.9695 - loss: 0.2239 - val_acc: 0.8793 - val_auc: 0.9492 - val_loss: 0.2941
Epoch 56/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 451ms/step - acc: 0.9072 - auc: 0.9712 - loss: 0.2189
Epoch 56: val_acc did not improve from 0.88467
41/41 ━━━━━━━━━━━━━━━━━━━━ 20s 484ms/step - acc: 0.9073 - auc: 0.9711 - loss: 0.2191 - val_acc: 0.8723 - val_auc: 0.9526 - val_loss: 0.2821
Epoch 57/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 472ms/step - acc: 0.9068 - auc: 0.9722 - loss: 0.2143
Epoch 57: val_acc did not improve from 0.88467
41/41 ━━━━━━━━━━━━━━━━━━━━ 23s 540ms/step - acc: 0.9069 - auc: 0.9722 - loss: 0.2142 - val_acc: 0.8731 - val_auc: 0.9492 - val_loss: 0.2991
Epoch 58/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 389ms/step - acc: 0.9120 - auc: 0.9733 - loss: 0.2091
Epoch 58: val_acc did not improve from 0.88467
41/41 ━━━━━━━━━━━━━━━━━━━━ 37s 455ms/step - acc: 0.9120 - auc: 0.9733 - loss: 0.2092 - val_acc: 0.8676 - val_auc: 0.9474 - val_loss: 0.2986
Epoch 59/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 387ms/step - acc: 0.9172 - auc: 0.9744 - loss: 0.2056
Epoch 59: val_acc did not improve from 0.88467
41/41 ━━━━━━━━━━━━━━━━━━━━ 17s 422ms/step - acc: 0.9171 - auc: 0.9743 - loss: 0.2058 - val_acc: 0.8669 - val_auc: 0.9452 - val_loss: 0.3087
Epoch 60/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 358ms/step - acc: 0.9191 - auc: 0.9750 - loss: 0.2023
Epoch 60: val_acc did not improve from 0.88467
41/41 ━━━━━━━━━━━━━━━━━━━━ 16s 382ms/step - acc: 0.9191 - auc: 0.9750 - loss: 0.2024 - val_acc: 0.8692 - val_auc: 0.9474 - val_loss: 0.2998
Epoch 61/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 355ms/step - acc: 0.9115 - auc: 0.9734 - loss: 0.2099
Epoch 61: val_acc did not improve from 0.88467
41/41 ━━━━━━━━━━━━━━━━━━━━ 21s 389ms/step - acc: 0.9116 - auc: 0.9734 - loss: 0.2098 - val_acc: 0.8707 - val_auc: 0.9492 - val_loss: 0.3000
Epoch 62/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 364ms/step - acc: 0.9192 - auc: 0.9762 - loss: 0.1977
Epoch 62: val_acc did not improve from 0.88467
41/41 ━━━━━━━━━━━━━━━━━━━━ 21s 389ms/step - acc: 0.9191 - auc: 0.9762 - loss: 0.1978 - val_acc: 0.8746 - val_auc: 0.9480 - val_loss: 0.3015
Epoch 63/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 361ms/step - acc: 0.9214 - auc: 0.9793 - loss: 0.1851
Epoch 63: val_acc did not improve from 0.88467
41/41 ━━━━━━━━━━━━━━━━━━━━ 20s 394ms/step - acc: 0.9214 - auc: 0.9793 - loss: 0.1851 - val_acc: 0.8762 - val_auc: 0.9486 - val_loss: 0.3056
Epoch 64/200

Model: "sequential_58"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_232 (Dense)               │ (None, 2048)           │     4,982,784 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_145         │ (None, 2048)           │         8,192 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_233 (Dense)               │ (None, 1024)           │     2,098,176 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_146         │ (None, 1024)           │         4,096 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_234 (Dense)               │ (None, 512)            │       524,800 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_147         │ (None, 512)            │         2,048 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_235 (Dense)               │ (None, 256)            │       131,328 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_148         │ (None, 256)            │         1,024 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_236 (Dense)               │ (None, 128)            │        32,896 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_149         │ (None, 128)            │           512 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_237 (Dense)               │ (None, 2)              │           258 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 7,786,114 (29.70 MB)

 Trainable params: 7,778,178 (29.67 MB)

 Non-trainable params: 7,936 (31.00 KB)

Epoch 1/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 194ms/step - acc: 0.7352 - auc: 0.8107 - loss: 0.6287
Epoch 1: val_auc improved from -inf to 0.80772, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_ANN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 15s 238ms/step - acc: 0.7365 - auc: 0.8121 - loss: 0.6252 - val_acc: 0.7214 - val_auc: 0.8077 - val_loss: 0.5335
Epoch 2/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 173ms/step - acc: 0.9043 - auc: 0.9638 - loss: 0.2473
Epoch 2: val_auc did not improve from 0.80772
41/41 ━━━━━━━━━━━━━━━━━━━━ 8s 190ms/step - acc: 0.9042 - auc: 0.9637 - loss: 0.2474 - val_acc: 0.7051 - val_auc: 0.7941 - val_loss: 0.5828
Epoch 3/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 198ms/step - acc: 0.9351 - auc: 0.9835 - loss: 0.1688
Epoch 3: val_auc improved from 0.80772 to 0.83925, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_ANN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 12s 231ms/step - acc: 0.9349 - auc: 0.9834 - loss: 0.1691 - val_acc: 0.7601 - val_auc: 0.8392 - val_loss: 0.5163
Epoch 4/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 152ms/step - acc: 0.9559 - auc: 0.9915 - loss: 0.1225
Epoch 4: val_auc improved from 0.83925 to 0.84758, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_ANN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 8s 181ms/step - acc: 0.9557 - auc: 0.9914 - loss: 0.1229 - val_acc: 0.7616 - val_auc: 0.8476 - val_loss: 0.5303
Epoch 5/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 172ms/step - acc: 0.9509 - auc: 0.9913 - loss: 0.1217
Epoch 5: val_auc improved from 0.84758 to 0.90017, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_ANN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 10s 237ms/step - acc: 0.9509 - auc: 0.9913 - loss: 0.1218 - val_acc: 0.8119 - val_auc: 0.9002 - val_loss: 0.4331
Epoch 6/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 174ms/step - acc: 0.9642 - auc: 0.9928 - loss: 0.1068
Epoch 6: val_auc improved from 0.90017 to 0.91922, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_ANN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 9s 204ms/step - acc: 0.9641 - auc: 0.9928 - loss: 0.1071 - val_acc: 0.8429 - val_auc: 0.9192 - val_loss: 0.4273
Epoch 7/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 169ms/step - acc: 0.9686 - auc: 0.9936 - loss: 0.0970
Epoch 7: val_auc improved from 0.91922 to 0.92681, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_ANN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 11s 221ms/step - acc: 0.9686 - auc: 0.9936 - loss: 0.0970 - val_acc: 0.8498 - val_auc: 0.9268 - val_loss: 0.4638
Epoch 8/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 148ms/step - acc: 0.9746 - auc: 0.9957 - loss: 0.0807
Epoch 8: val_auc improved from 0.92681 to 0.93554, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_ANN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 7s 179ms/step - acc: 0.9744 - auc: 0.9957 - loss: 0.0810 - val_acc: 0.8646 - val_auc: 0.9355 - val_loss: 0.4346
Epoch 9/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 173ms/step - acc: 0.9691 - auc: 0.9945 - loss: 0.0861
Epoch 9: val_auc did not improve from 0.93554
41/41 ━━━━━━━━━━━━━━━━━━━━ 11s 191ms/step - acc: 0.9690 - auc: 0.9945 - loss: 0.0862 - val_acc: 0.8576 - val_auc: 0.9207 - val_loss: 0.5253
Epoch 10/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 196ms/step - acc: 0.9725 - auc: 0.9963 - loss: 0.0771
Epoch 10: val_auc did not improve from 0.93554
41/41 ━━━━━━━━━━━━━━━━━━━━ 11s 208ms/step - acc: 0.9725 - auc: 0.9962 - loss: 0.0772 - val_acc: 0.8661 - val_auc: 0.9302 - val_loss: 0.4948
Epoch 11/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 173ms/step - acc: 0.9812 - auc: 0.9980 - loss: 0.0551
Epoch 11: val_auc did not improve from 0.93554
41/41 ━━━━━━━━━━━━━━━━━━━━ 10s 192ms/step - acc: 0.9812 - auc: 0.9980 - loss: 0.0551 - val_acc: 0.8591 - val_auc: 0.9280 - val_loss: 0.5113
Epoch 12/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 157ms/step - acc: 0.9848 - auc: 0.9988 - loss: 0.0439
Epoch 12: val_auc did not improve from 0.93554
41/41 ━━━━━━━━━━━━━━━━━━━━ 9s 174ms/step - acc: 0.9847 - auc: 0.9987 - loss: 0.0440 - val_acc: 0.8630 - val_auc: 0.9207 - val_loss: 0.5503
Epoch 13/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 168ms/step - acc: 0.9830 - auc: 0.9985 - loss: 0.0495
Epoch 13: val_auc did not improve from 0.93554
41/41 ━━━━━━━━━━━━━━━━━━━━ 8s 186ms/step - acc: 0.9830 - auc: 0.9984 - loss: 0.0496 - val_acc: 0.8638 - val_auc: 0.9323 - val_loss: 0.5143
Epoch 14/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 163ms/step - acc: 0.9846 - auc: 0.9984 - loss: 0.0475
Epoch 14: val_auc improved from 0.93554 to 0.93619, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_ANN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 8s 195ms/step - acc: 0.9846 - auc: 0.9984 - loss: 0.0474 - val_acc: 0.8746 - val_auc: 0.9362 - val_loss: 0.4915
Epoch 15/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 151ms/step - acc: 0.9832 - auc: 0.9971 - loss: 0.0561
Epoch 15: val_auc did not improve from 0.93619
41/41 ━━━━━━━━━━━━━━━━━━━━ 9s 168ms/step - acc: 0.9832 - auc: 0.9971 - loss: 0.0561 - val_acc: 0.8692 - val_auc: 0.9263 - val_loss: 0.5378
Epoch 16/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 166ms/step - acc: 0.9847 - auc: 0.9981 - loss: 0.0468
Epoch 16: val_auc did not improve from 0.93619
41/41 ━━━━━━━━━━━━━━━━━━━━ 11s 183ms/step - acc: 0.9846 - auc: 0.9981 - loss: 0.0470 - val_acc: 0.8669 - val_auc: 0.9206 - val_loss: 0.5865
Epoch 17/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 148ms/step - acc: 0.9870 - auc: 0.9988 - loss: 0.0431
Epoch 17: val_auc did not improve from 0.93619
41/41 ━━━━━━━━━━━━━━━━━━━━ 9s 165ms/step - acc: 0.9870 - auc: 0.9988 - loss: 0.0431 - val_acc: 0.8746 - val_auc: 0.9319 - val_loss: 0.4974
Epoch 18/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 154ms/step - acc: 0.9902 - auc: 0.9990 - loss: 0.0315
Epoch 18: val_auc did not improve from 0.93619
41/41 ━━━━━━━━━━━━━━━━━━━━ 11s 171ms/step - acc: 0.9902 - auc: 0.9990 - loss: 0.0316 - val_acc: 0.8553 - val_auc: 0.9242 - val_loss: 0.5516
Epoch 19/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 172ms/step - acc: 0.9853 - auc: 0.9988 - loss: 0.0408
Epoch 19: val_auc did not improve from 0.93619
41/41 ━━━━━━━━━━━━━━━━━━━━ 8s 189ms/step - acc: 0.9852 - auc: 0.9987 - loss: 0.0410 - val_acc: 0.8522 - val_auc: 0.9132 - val_loss: 0.6104
Epoch 20/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 152ms/step - acc: 0.9815 - auc: 0.9984 - loss: 0.0487
Epoch 20: val_auc did not improve from 0.93619
41/41 ━━━━━━━━━━━━━━━━━━━━ 7s 169ms/step - acc: 0.9815 - auc: 0.9984 - loss: 0.0488 - val_acc: 0.8622 - val_auc: 0.9317 - val_loss: 0.5455
Epoch 21/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 167ms/step - acc: 0.9834 - auc: 0.9983 - loss: 0.0459
Epoch 21: val_auc did not improve from 0.93619
41/41 ━━━━━━━━━━━━━━━━━━━━ 7s 180ms/step - acc: 0.9834 - auc: 0.9983 - loss: 0.0460 - val_acc: 0.8824 - val_auc: 0.9317 - val_loss: 0.5366
Epoch 22/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 156ms/step - acc: 0.9886 - auc: 0.9988 - loss: 0.0364
Epoch 22: val_auc did not improve from 0.93619
41/41 ━━━━━━━━━━━━━━━━━━━━ 7s 173ms/step - acc: 0.9886 - auc: 0.9988 - loss: 0.0363 - val_acc: 0.8800 - val_auc: 0.9306 - val_loss: 0.5666
Epoch 23/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 157ms/step - acc: 0.9917 - auc: 0.9993 - loss: 0.0242
Epoch 23: val_auc did not improve from 0.93619
41/41 ━━━━━━━━━━━━━━━━━━━━ 10s 168ms/step - acc: 0.9917 - auc: 0.9993 - loss: 0.0243 - val_acc: 0.8762 - val_auc: 0.9307 - val_loss: 0.5342
Epoch 24/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 177ms/step - acc: 0.9903 - auc: 0.9987 - loss: 0.0321
Epoch 24: val_auc did not improve from 0.93619
41/41 ━━━━━━━━━━━━━━━━━━━━ 8s 188ms/step - acc: 0.9903 - auc: 0.9987 - loss: 0.0322 - val_acc: 0.8584 - val_auc: 0.9219 - val_loss: 0.5724
Epoch 25/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 170ms/step - acc: 0.9849 - auc: 0.9983 - loss: 0.0405
Epoch 25: val_auc did not improve from 0.93619
41/41 ━━━━━━━━━━━━━━━━━━━━ 10s 188ms/step - acc: 0.9849 - auc: 0.9983 - loss: 0.0406 - val_acc: 0.8754 - val_auc: 0.9349 - val_loss: 0.5549
Epoch 26/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 152ms/step - acc: 0.9890 - auc: 0.9988 - loss: 0.0325
Epoch 26: val_auc did not improve from 0.93619
41/41 ━━━━━━━━━━━━━━━━━━━━ 10s 170ms/step - acc: 0.9890 - auc: 0.9988 - loss: 0.0326 - val_acc: 0.8692 - val_auc: 0.9288 - val_loss: 0.5664
Epoch 27/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 156ms/step - acc: 0.9896 - auc: 0.9979 - loss: 0.0409
Epoch 27: val_auc did not improve from 0.93619
41/41 ━━━━━━━━━━━━━━━━━━━━ 10s 173ms/step - acc: 0.9896 - auc: 0.9979 - loss: 0.0409 - val_acc: 0.8777 - val_auc: 0.9289 - val_loss: 0.5696
Epoch 28/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 173ms/step - acc: 0.9906 - auc: 0.9995 - loss: 0.0278
Epoch 28: val_auc did not improve from 0.93619
41/41 ━━━━━━━━━━━━━━━━━━━━ 8s 190ms/step - acc: 0.9905 - auc: 0.9995 - loss: 0.0279 - val_acc: 0.8684 - val_auc: 0.9291 - val_loss: 0.5601
Epoch 29/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 168ms/step - acc: 0.9889 - auc: 0.9992 - loss: 0.0330
Epoch 29: val_auc did not improve from 0.93619
41/41 ━━━━━━━━━━━━━━━━━━━━ 10s 185ms/step - acc: 0.9889 - auc: 0.9992 - loss: 0.0330 - val_acc: 0.8676 - val_auc: 0.9284 - val_loss: 0.5578
Epoch 30/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 148ms/step - acc: 0.9906 - auc: 0.9995 - loss: 0.0239
Epoch 30: val_auc did not improve from 0.93619
41/41 ━━━━━━━━━━━━━━━━━━━━ 7s 159ms/step - acc: 0.9906 - auc: 0.9995 - loss: 0.0240 - val_acc: 0.8599 - val_auc: 0.9144 - val_loss: 0.6711
Epoch 31/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 145ms/step - acc: 0.9924 - auc: 0.9995 - loss: 0.0209
Epoch 31: val_auc did not improve from 0.93619
41/41 ━━━━━━━━━━━━━━━━━━━━ 10s 162ms/step - acc: 0.9923 - auc: 0.9995 - loss: 0.0210 - val_acc: 0.8676 - val_auc: 0.9211 - val_loss: 0.6158
Epoch 32/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 166ms/step - acc: 0.9915 - auc: 0.9994 - loss: 0.0238
Epoch 32: val_auc did not improve from 0.93619
41/41 ━━━━━━━━━━━━━━━━━━━━ 11s 181ms/step - acc: 0.9915 - auc: 0.9994 - loss: 0.0239 - val_acc: 0.8707 - val_auc: 0.9260 - val_loss: 0.6168
Epoch 33/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 171ms/step - acc: 0.9905 - auc: 0.9986 - loss: 0.0310
Epoch 33: val_auc did not improve from 0.93619
41/41 ━━━━━━━━━━━━━━━━━━━━ 10s 189ms/step - acc: 0.9905 - auc: 0.9985 - loss: 0.0311 - val_acc: 0.8754 - val_auc: 0.9315 - val_loss: 0.5675
Epoch 34/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 151ms/step - acc: 0.9877 - auc: 0.9986 - loss: 0.0352
Epoch 34: val_auc did not improve from 0.93619
41/41 ━━━━━━━━━━━━━━━━━━━━ 7s 168ms/step - acc: 0.9877 - auc: 0.9986 - loss: 0.0351 - val_acc: 0.8754 - val_auc: 0.9237 - val_loss: 0.6521
Epoch 35/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 152ms/step - acc: 0.9915 - auc: 0.9994 - loss: 0.0251
Epoch 35: val_auc did not improve from 0.93619
41/41 ━━━━━━━━━━━━━━━━━━━━ 10s 163ms/step - acc: 0.9915 - auc: 0.9994 - loss: 0.0252 - val_acc: 0.8924 - val_auc: 0.9344 - val_loss: 0.5679
Epoch 36/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 171ms/step - acc: 0.9892 - auc: 0.9978 - loss: 0.0408
Epoch 36: val_auc did not improve from 0.93619
41/41 ━━━━━━━━━━━━━━━━━━━━ 8s 188ms/step - acc: 0.9892 - auc: 0.9978 - loss: 0.0408 - val_acc: 0.8568 - val_auc: 0.9207 - val_loss: 0.6270
Epoch 37/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 171ms/step - acc: 0.9868 - auc: 0.9978 - loss: 0.0408
Epoch 37: val_auc did not improve from 0.93619
41/41 ━━━━━━━━━━━━━━━━━━━━ 10s 189ms/step - acc: 0.9869 - auc: 0.9978 - loss: 0.0405 - val_acc: 0.8700 - val_auc: 0.9298 - val_loss: 0.5692
Epoch 38/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 148ms/step - acc: 0.9959 - auc: 0.9999 - loss: 0.0132
Epoch 38: val_auc did not improve from 0.93619
41/41 ━━━━━━━━━━━━━━━━━━━━ 7s 166ms/step - acc: 0.9959 - auc: 0.9999 - loss: 0.0132 - val_acc: 0.8800 - val_auc: 0.9309 - val_loss: 0.5522
Epoch 39/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 169ms/step - acc: 0.9961 - auc: 1.0000 - loss: 0.0094
Epoch 39: val_auc did not improve from 0.93619
41/41 ━━━━━━━━━━━━━━━━━━━━ 8s 186ms/step - acc: 0.9961 - auc: 1.0000 - loss: 0.0094 - val_acc: 0.8793 - val_auc: 0.9345 - val_loss: 0.5736
Epoch 40/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 165ms/step - acc: 0.9978 - auc: 0.9995 - loss: 0.0102
Epoch 40: val_auc did not improve from 0.93619
41/41 ━━━━━━━━━━━━━━━━━━━━ 10s 186ms/step - acc: 0.9978 - auc: 0.9995 - loss: 0.0103 - val_acc: 0.8700 - val_auc: 0.9339 - val_loss: 0.5490
Epoch 41/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 153ms/step - acc: 0.9958 - auc: 0.9991 - loss: 0.0192
Epoch 41: val_auc did not improve from 0.93619
41/41 ━━━━━━━━━━━━━━━━━━━━ 7s 164ms/step - acc: 0.9958 - auc: 0.9991 - loss: 0.0192 - val_acc: 0.8723 - val_auc: 0.9280 - val_loss: 0.5683
Epoch 42/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 170ms/step - acc: 0.9940 - auc: 0.9990 - loss: 0.0208
Epoch 42: val_auc improved from 0.93619 to 0.93649, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_ANN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 8s 198ms/step - acc: 0.9940 - auc: 0.9990 - loss: 0.0208 - val_acc: 0.8793 - val_auc: 0.9365 - val_loss: 0.5376
Epoch 43/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 158ms/step - acc: 0.9920 - auc: 0.9983 - loss: 0.0284
Epoch 43: val_auc did not improve from 0.93649
41/41 ━━━━━━━━━━━━━━━━━━━━ 9s 176ms/step - acc: 0.9919 - auc: 0.9983 - loss: 0.0284 - val_acc: 0.8692 - val_auc: 0.9290 - val_loss: 0.6168
Epoch 44/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 158ms/step - acc: 0.9926 - auc: 0.9996 - loss: 0.0222
Epoch 44: val_auc did not improve from 0.93649
41/41 ━━━━━━━━━━━━━━━━━━━━ 10s 175ms/step - acc: 0.9925 - auc: 0.9996 - loss: 0.0222 - val_acc: 0.8700 - val_auc: 0.9237 - val_loss: 0.6277
Epoch 45/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 150ms/step - acc: 0.9895 - auc: 0.9985 - loss: 0.0302
Epoch 45: val_auc did not improve from 0.93649
41/41 ━━━━━━━━━━━━━━━━━━━━ 10s 168ms/step - acc: 0.9894 - auc: 0.9985 - loss: 0.0302 - val_acc: 0.8653 - val_auc: 0.9219 - val_loss: 0.6194
Epoch 46/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 151ms/step - acc: 0.9917 - auc: 0.9979 - loss: 0.0360
Epoch 46: val_auc did not improve from 0.93649
41/41 ━━━━━━━━━━━━━━━━━━━━ 10s 162ms/step - acc: 0.9917 - auc: 0.9978 - loss: 0.0361 - val_acc: 0.8762 - val_auc: 0.9364 - val_loss: 0.5695
Epoch 47/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 169ms/step - acc: 0.9897 - auc: 0.9984 - loss: 0.0357
Epoch 47: val_auc did not improve from 0.93649
41/41 ━━━━━━━━━━━━━━━━━━━━ 8s 186ms/step - acc: 0.9897 - auc: 0.9984 - loss: 0.0357 - val_acc: 0.8731 - val_auc: 0.9278 - val_loss: 0.6005
Epoch 48/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 147ms/step - acc: 0.9918 - auc: 0.9996 - loss: 0.0236
Epoch 48: val_auc did not improve from 0.93649
41/41 ━━━━━━━━━━━━━━━━━━━━ 7s 165ms/step - acc: 0.9918 - auc: 0.9996 - loss: 0.0236 - val_acc: 0.8754 - val_auc: 0.9297 - val_loss: 0.6115
Epoch 49/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 171ms/step - acc: 0.9945 - auc: 0.9992 - loss: 0.0175
Epoch 49: val_auc did not improve from 0.93649
41/41 ━━━━━━━━━━━━━━━━━━━━ 7s 181ms/step - acc: 0.9944 - auc: 0.9992 - loss: 0.0175 - val_acc: 0.8816 - val_auc: 0.9300 - val_loss: 0.5851
Epoch 50/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 156ms/step - acc: 0.9904 - auc: 0.9989 - loss: 0.0287
Epoch 50: val_auc did not improve from 0.93649
41/41 ━━━━━━━━━━━━━━━━━━━━ 7s 174ms/step - acc: 0.9905 - auc: 0.9989 - loss: 0.0287 - val_acc: 0.8692 - val_auc: 0.9265 - val_loss: 0.5846
Epoch 51/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 163ms/step - acc: 0.9912 - auc: 0.9996 - loss: 0.0241
Epoch 51: val_auc did not improve from 0.93649
41/41 ━━━━━━━━━━━━━━━━━━━━ 7s 180ms/step - acc: 0.9912 - auc: 0.9996 - loss: 0.0242 - val_acc: 0.8738 - val_auc: 0.9303 - val_loss: 0.5734
Epoch 52/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 157ms/step - acc: 0.9919 - auc: 0.9988 - loss: 0.0312
Epoch 52: val_auc did not improve from 0.93649
41/41 ━━━━━━━━━━━━━━━━━━━━ 7s 175ms/step - acc: 0.9918 - auc: 0.9988 - loss: 0.0313 - val_acc: 0.8615 - val_auc: 0.9222 - val_loss: 0.6249
Epoch 53/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 149ms/step - acc: 0.9923 - auc: 0.9995 - loss: 0.0208
Epoch 53: val_auc did not improve from 0.93649
41/41 ━━━━━━━━━━━━━━━━━━━━ 10s 160ms/step - acc: 0.9923 - auc: 0.9995 - loss: 0.0208 - val_acc: 0.8800 - val_auc: 0.9329 - val_loss: 0.5782
Epoch 54/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 147ms/step - acc: 0.9956 - auc: 0.9999 - loss: 0.0139
Epoch 54: val_auc did not improve from 0.93649
41/41 ━━━━━━━━━━━━━━━━━━━━ 10s 158ms/step - acc: 0.9955 - auc: 0.9999 - loss: 0.0140 - val_acc: 0.8684 - val_auc: 0.9292 - val_loss: 0.6252
Epoch 55/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 172ms/step - acc: 0.9921 - auc: 0.9998 - loss: 0.0171
Epoch 55: val_auc did not improve from 0.93649
41/41 ━━━━━━━━━━━━━━━━━━━━ 8s 189ms/step - acc: 0.9921 - auc: 0.9998 - loss: 0.0171 - val_acc: 0.8746 - val_auc: 0.9195 - val_loss: 0.6818
Epoch 56/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 173ms/step - acc: 0.9926 - auc: 0.9996 - loss: 0.0228
Epoch 56: val_auc did not improve from 0.93649
41/41 ━━━━━━━━━━━━━━━━━━━━ 10s 190ms/step - acc: 0.9926 - auc: 0.9996 - loss: 0.0228 - val_acc: 0.8762 - val_auc: 0.9245 - val_loss: 0.5930
Epoch 57/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 154ms/step - acc: 0.9966 - auc: 0.9997 - loss: 0.0125
Epoch 57: val_auc did not improve from 0.93649
41/41 ━━━━━━━━━━━━━━━━━━━━ 10s 188ms/step - acc: 0.9966 - auc: 0.9996 - loss: 0.0125 - val_acc: 0.8769 - val_auc: 0.9235 - val_loss: 0.6184
Epoch 58/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 181ms/step - acc: 0.9951 - auc: 0.9999 - loss: 0.0149
Epoch 58: val_auc did not improve from 0.93649
41/41 ━━━━━━━━━━━━━━━━━━━━ 8s 199ms/step - acc: 0.9951 - auc: 0.9999 - loss: 0.0150 - val_acc: 0.8738 - val_auc: 0.9275 - val_loss: 0.5882
Epoch 59/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 169ms/step - acc: 0.9914 - auc: 0.9993 - loss: 0.0214
Epoch 59: val_auc did not improve from 0.93649
41/41 ━━━━━━━━━━━━━━━━━━━━ 7s 182ms/step - acc: 0.9914 - auc: 0.9993 - loss: 0.0214 - val_acc: 0.8646 - val_auc: 0.9201 - val_loss: 0.6502
Epoch 60/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 159ms/step - acc: 0.9962 - auc: 0.9997 - loss: 0.0123
Epoch 60: val_auc did not improve from 0.93649
41/41 ━━━━━━━━━━━━━━━━━━━━ 10s 176ms/step - acc: 0.9961 - auc: 0.9997 - loss: 0.0123 - val_acc: 0.8862 - val_auc: 0.9296 - val_loss: 0.5942
Epoch 61/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 167ms/step - acc: 0.9929 - auc: 0.9988 - loss: 0.0256
Epoch 61: val_auc did not improve from 0.93649
41/41 ━━━━━━━━━━━━━━━━━━━━ 8s 184ms/step - acc: 0.9929 - auc: 0.9988 - loss: 0.0257 - val_acc: 0.8723 - val_auc: 0.9283 - val_loss: 0.6296
Epoch 62/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 170ms/step - acc: 0.9898 - auc: 0.9990 - loss: 0.0309
Epoch 62: val_auc did not improve from 0.93649
41/41 ━━━━━━━━━━━━━━━━━━━━ 10s 187ms/step - acc: 0.9897 - auc: 0.9990 - loss: 0.0310 - val_acc: 0.8777 - val_auc: 0.9263 - val_loss: 0.6495
Epoch 63/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 147ms/step - acc: 0.9914 - auc: 0.9995 - loss: 0.0241
Epoch 63: val_auc did not improve from 0.93649
41/41 ━━━━━━━━━━━━━━━━━━━━ 7s 164ms/step - acc: 0.9914 - auc: 0.9995 - loss: 0.0241 - val_acc: 0.8607 - val_auc: 0.9211 - val_loss: 0.6695
Epoch 64/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 169ms/step - acc: 0.9937 - auc: 0.9997 - loss: 0.0219
Epoch 64: val_auc did not improve from 0.93649
41/41 ━━━━━━━━━━━━━━━━━━━━ 8s 186ms/step - acc: 0.9937 - auc: 0.9997 - loss: 0.0219 - val_acc: 0.8816 - val_auc: 0.9259 - val_loss: 0.6243
Epoch 65/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 168ms/step - acc: 0.9956 - auc: 0.9993 - loss: 0.0132
Epoch 65: val_auc did not improve from 0.93649
41/41 ━━━━━━━━━━━━━━━━━━━━ 10s 185ms/step - acc: 0.9955 - auc: 0.9993 - loss: 0.0133 - val_acc: 0.8746 - val_auc: 0.9295 - val_loss: 0.5845
Epoch 66/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 151ms/step - acc: 0.9951 - auc: 0.9992 - loss: 0.0172
Epoch 66: val_auc did not improve from 0.93649
41/41 ━━━━━━━━━━━━━━━━━━━━ 7s 168ms/step - acc: 0.9950 - auc: 0.9992 - loss: 0.0172 - val_acc: 0.8684 - val_auc: 0.9245 - val_loss: 0.6349
Epoch 67/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 164ms/step - acc: 0.9981 - auc: 0.9999 - loss: 0.0089
Epoch 67: val_auc did not improve from 0.93649
41/41 ━━━━━━━━━━━━━━━━━━━━ 7s 182ms/step - acc: 0.9980 - auc: 0.9999 - loss: 0.0089 - val_acc: 0.8808 - val_auc: 0.9310 - val_loss: 0.6084
Epoch 68/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 165ms/step - acc: 0.9983 - auc: 0.9999 - loss: 0.0069
Epoch 68: val_auc did not improve from 0.93649

Model: "sequential_59"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv2d_87 (Conv2D)              │ (None, 62, 36, 32)     │           320 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_87 (MaxPooling2D) │ (None, 31, 18, 32)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_87 (Dropout)            │ (None, 31, 18, 32)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_88 (Conv2D)              │ (None, 29, 16, 64)     │        18,496 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_88 (MaxPooling2D) │ (None, 14, 8, 64)      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_88 (Dropout)            │ (None, 14, 8, 64)      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_89 (Conv2D)              │ (None, 12, 6, 128)     │        73,856 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_89 (MaxPooling2D) │ (None, 6, 3, 128)      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_89 (Dropout)            │ (None, 6, 3, 128)      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_29 (Flatten)            │ (None, 2304)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_238 (Dense)               │ (None, 128)            │       295,040 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_239 (Dense)               │ (None, 2)              │           258 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 387,970 (1.48 MB)

 Trainable params: 387,970 (1.48 MB)

 Non-trainable params: 0 (0.00 B)

Epoch 1/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 350ms/step - acc: 0.5283 - auc: 0.5384 - loss: 0.7379
Epoch 1: val_acc improved from -inf to 0.52090, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_CNN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 19s 395ms/step - acc: 0.5281 - auc: 0.5382 - loss: 0.7371 - val_acc: 0.5209 - val_auc: 0.5224 - val_loss: 0.6922
Epoch 2/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 344ms/step - acc: 0.5102 - auc: 0.5081 - loss: 0.6937
Epoch 2: val_acc did not improve from 0.52090
41/41 ━━━━━━━━━━━━━━━━━━━━ 20s 378ms/step - acc: 0.5101 - auc: 0.5081 - loss: 0.6937 - val_acc: 0.5209 - val_auc: 0.5401 - val_loss: 0.6919
Epoch 3/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 341ms/step - acc: 0.5212 - auc: 0.5342 - loss: 0.6914
Epoch 3: val_acc improved from 0.52090 to 0.55805, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_CNN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 15s 376ms/step - acc: 0.5212 - auc: 0.5340 - loss: 0.6914 - val_acc: 0.5580 - val_auc: 0.6861 - val_loss: 0.6907
Epoch 4/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 348ms/step - acc: 0.5489 - auc: 0.5758 - loss: 0.6895
Epoch 4: val_acc improved from 0.55805 to 0.71440, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_CNN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 20s 373ms/step - acc: 0.5492 - auc: 0.5763 - loss: 0.6895 - val_acc: 0.7144 - val_auc: 0.7766 - val_loss: 0.6693
Epoch 5/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 355ms/step - acc: 0.6282 - auc: 0.6868 - loss: 0.6542
Epoch 5: val_acc improved from 0.71440 to 0.74923, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_CNN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 21s 390ms/step - acc: 0.6288 - auc: 0.6875 - loss: 0.6536 - val_acc: 0.7492 - val_auc: 0.8253 - val_loss: 0.5360
Epoch 6/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 349ms/step - acc: 0.7421 - auc: 0.8056 - loss: 0.5410
Epoch 6: val_acc improved from 0.74923 to 0.75464, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_CNN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 20s 385ms/step - acc: 0.7423 - auc: 0.8058 - loss: 0.5408 - val_acc: 0.7546 - val_auc: 0.8341 - val_loss: 0.5045
Epoch 7/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 345ms/step - acc: 0.7730 - auc: 0.8483 - loss: 0.4844
Epoch 7: val_acc improved from 0.75464 to 0.77786, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_CNN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 15s 369ms/step - acc: 0.7730 - auc: 0.8483 - loss: 0.4844 - val_acc: 0.7779 - val_auc: 0.8645 - val_loss: 0.4645
Epoch 8/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 339ms/step - acc: 0.7720 - auc: 0.8525 - loss: 0.4799
Epoch 8: val_acc improved from 0.77786 to 0.78406, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_CNN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 20s 374ms/step - acc: 0.7721 - auc: 0.8527 - loss: 0.4797 - val_acc: 0.7841 - val_auc: 0.8746 - val_loss: 0.4446
Epoch 9/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 356ms/step - acc: 0.7828 - auc: 0.8617 - loss: 0.4646
Epoch 9: val_acc improved from 0.78406 to 0.79567, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_CNN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 16s 391ms/step - acc: 0.7831 - auc: 0.8620 - loss: 0.4642 - val_acc: 0.7957 - val_auc: 0.8688 - val_loss: 0.4540
Epoch 10/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 337ms/step - acc: 0.8003 - auc: 0.8790 - loss: 0.4370
Epoch 10: val_acc improved from 0.79567 to 0.80573, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_CNN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 19s 361ms/step - acc: 0.8002 - auc: 0.8790 - loss: 0.4370 - val_acc: 0.8057 - val_auc: 0.8864 - val_loss: 0.4263
Epoch 11/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 333ms/step - acc: 0.7955 - auc: 0.8815 - loss: 0.4336
Epoch 11: val_acc improved from 0.80573 to 0.81502, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_CNN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 20s 357ms/step - acc: 0.7956 - auc: 0.8815 - loss: 0.4335 - val_acc: 0.8150 - val_auc: 0.8870 - val_loss: 0.4280
Epoch 12/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 354ms/step - acc: 0.8044 - auc: 0.8862 - loss: 0.4250
Epoch 12: val_acc did not improve from 0.81502
41/41 ━━━━━━━━━━━━━━━━━━━━ 22s 388ms/step - acc: 0.8043 - auc: 0.8862 - loss: 0.4251 - val_acc: 0.8104 - val_auc: 0.8901 - val_loss: 0.4237
Epoch 13/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 337ms/step - acc: 0.8097 - auc: 0.8900 - loss: 0.4191
Epoch 13: val_acc did not improve from 0.81502
41/41 ━━━━━━━━━━━━━━━━━━━━ 20s 370ms/step - acc: 0.8097 - auc: 0.8900 - loss: 0.4192 - val_acc: 0.8135 - val_auc: 0.8880 - val_loss: 0.4226
Epoch 14/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 331ms/step - acc: 0.8233 - auc: 0.9042 - loss: 0.3919
Epoch 14: val_acc did not improve from 0.81502
41/41 ━━━━━━━━━━━━━━━━━━━━ 20s 364ms/step - acc: 0.8232 - auc: 0.9041 - loss: 0.3922 - val_acc: 0.8119 - val_auc: 0.8898 - val_loss: 0.4195
Epoch 15/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 331ms/step - acc: 0.8275 - auc: 0.9070 - loss: 0.3883
Epoch 15: val_acc improved from 0.81502 to 0.81966, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_CNN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 15s 366ms/step - acc: 0.8273 - auc: 0.9069 - loss: 0.3886 - val_acc: 0.8197 - val_auc: 0.8931 - val_loss: 0.4140
Epoch 16/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 337ms/step - acc: 0.8302 - auc: 0.9029 - loss: 0.3945
Epoch 16: val_acc improved from 0.81966 to 0.82198, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_CNN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 21s 372ms/step - acc: 0.8301 - auc: 0.9028 - loss: 0.3946 - val_acc: 0.8220 - val_auc: 0.8903 - val_loss: 0.4188
Epoch 17/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 362ms/step - acc: 0.8199 - auc: 0.9007 - loss: 0.3985
Epoch 17: val_acc improved from 0.82198 to 0.82663, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_CNN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 22s 399ms/step - acc: 0.8200 - auc: 0.9007 - loss: 0.3984 - val_acc: 0.8266 - val_auc: 0.8996 - val_loss: 0.4017
Epoch 18/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 338ms/step - acc: 0.8301 - auc: 0.9082 - loss: 0.3844
Epoch 18: val_acc improved from 0.82663 to 0.82972, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_CNN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 19s 373ms/step - acc: 0.8300 - auc: 0.9082 - loss: 0.3845 - val_acc: 0.8297 - val_auc: 0.8991 - val_loss: 0.4022
Epoch 19/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 331ms/step - acc: 0.8233 - auc: 0.9039 - loss: 0.3930
Epoch 19: val_acc did not improve from 0.82972
41/41 ━━━━━━━━━━━━━━━━━━━━ 15s 364ms/step - acc: 0.8235 - auc: 0.9041 - loss: 0.3928 - val_acc: 0.8274 - val_auc: 0.8982 - val_loss: 0.4044
Epoch 20/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 336ms/step - acc: 0.8303 - auc: 0.9090 - loss: 0.3827
Epoch 20: val_acc did not improve from 0.82972
41/41 ━━━━━━━━━━━━━━━━━━━━ 21s 369ms/step - acc: 0.8304 - auc: 0.9091 - loss: 0.3826 - val_acc: 0.8274 - val_auc: 0.9013 - val_loss: 0.3997
Epoch 21/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 335ms/step - acc: 0.8347 - auc: 0.9125 - loss: 0.3756
Epoch 21: val_acc did not improve from 0.82972
41/41 ━━━━━━━━━━━━━━━━━━━━ 15s 357ms/step - acc: 0.8347 - auc: 0.9125 - loss: 0.3755 - val_acc: 0.8251 - val_auc: 0.8986 - val_loss: 0.4028
Epoch 22/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 332ms/step - acc: 0.8427 - auc: 0.9163 - loss: 0.3688
Epoch 22: val_acc improved from 0.82972 to 0.83669, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_CNN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 21s 366ms/step - acc: 0.8427 - auc: 0.9163 - loss: 0.3688 - val_acc: 0.8367 - val_auc: 0.9089 - val_loss: 0.3833
Epoch 23/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 334ms/step - acc: 0.8485 - auc: 0.9236 - loss: 0.3519
Epoch 23: val_acc improved from 0.83669 to 0.83901, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_CNN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 15s 369ms/step - acc: 0.8485 - auc: 0.9236 - loss: 0.3521 - val_acc: 0.8390 - val_auc: 0.9113 - val_loss: 0.3803
Epoch 24/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 337ms/step - acc: 0.8455 - auc: 0.9257 - loss: 0.3482
Epoch 24: val_acc did not improve from 0.83901
41/41 ━━━━━━━━━━━━━━━━━━━━ 16s 403ms/step - acc: 0.8456 - auc: 0.9257 - loss: 0.3482 - val_acc: 0.8382 - val_auc: 0.9103 - val_loss: 0.3799
Epoch 25/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 348ms/step - acc: 0.8565 - auc: 0.9283 - loss: 0.3414
Epoch 25: val_acc improved from 0.83901 to 0.84365, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_CNN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 20s 382ms/step - acc: 0.8564 - auc: 0.9283 - loss: 0.3415 - val_acc: 0.8437 - val_auc: 0.9156 - val_loss: 0.3687
Epoch 26/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 366ms/step - acc: 0.8650 - auc: 0.9329 - loss: 0.3310
Epoch 26: val_acc improved from 0.84365 to 0.84598, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_CNN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 18s 434ms/step - acc: 0.8649 - auc: 0.9328 - loss: 0.3312 - val_acc: 0.8460 - val_auc: 0.9162 - val_loss: 0.3682
Epoch 27/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 331ms/step - acc: 0.8600 - auc: 0.9349 - loss: 0.3264
Epoch 27: val_acc improved from 0.84598 to 0.84752, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_CNN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 15s 366ms/step - acc: 0.8599 - auc: 0.9347 - loss: 0.3267 - val_acc: 0.8475 - val_auc: 0.9204 - val_loss: 0.3597
Epoch 28/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 331ms/step - acc: 0.8676 - auc: 0.9421 - loss: 0.3091
Epoch 28: val_acc did not improve from 0.84752
41/41 ━━━━━━━━━━━━━━━━━━━━ 15s 364ms/step - acc: 0.8673 - auc: 0.9419 - loss: 0.3096 - val_acc: 0.8452 - val_auc: 0.9206 - val_loss: 0.3641
Epoch 29/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 333ms/step - acc: 0.8663 - auc: 0.9412 - loss: 0.3133
Epoch 29: val_acc improved from 0.84752 to 0.84830, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_CNN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 21s 368ms/step - acc: 0.8662 - auc: 0.9411 - loss: 0.3136 - val_acc: 0.8483 - val_auc: 0.9227 - val_loss: 0.3542
Epoch 30/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 345ms/step - acc: 0.8653 - auc: 0.9393 - loss: 0.3144
Epoch 30: val_acc did not improve from 0.84830
41/41 ━━━━━━━━━━━━━━━━━━━━ 22s 412ms/step - acc: 0.8654 - auc: 0.9393 - loss: 0.3144 - val_acc: 0.8390 - val_auc: 0.9206 - val_loss: 0.3594
Epoch 31/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 346ms/step - acc: 0.8718 - auc: 0.9367 - loss: 0.3205
Epoch 31: val_acc did not improve from 0.84830
41/41 ━━━━━━━━━━━━━━━━━━━━ 19s 368ms/step - acc: 0.8717 - auc: 0.9367 - loss: 0.3206 - val_acc: 0.8483 - val_auc: 0.9242 - val_loss: 0.3512
Epoch 32/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 344ms/step - acc: 0.8703 - auc: 0.9437 - loss: 0.3035
Epoch 32: val_acc did not improve from 0.84830
41/41 ━━━━━━━━━━━━━━━━━━━━ 21s 377ms/step - acc: 0.8703 - auc: 0.9436 - loss: 0.3036 - val_acc: 0.8421 - val_auc: 0.9246 - val_loss: 0.3513
Epoch 33/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 335ms/step - acc: 0.8805 - auc: 0.9422 - loss: 0.3058
Epoch 33: val_acc improved from 0.84830 to 0.84907, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_CNN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 15s 369ms/step - acc: 0.8805 - auc: 0.9423 - loss: 0.3057 - val_acc: 0.8491 - val_auc: 0.9262 - val_loss: 0.3455
Epoch 34/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 346ms/step - acc: 0.8814 - auc: 0.9466 - loss: 0.2947
Epoch 34: val_acc improved from 0.84907 to 0.85449, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_CNN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 21s 382ms/step - acc: 0.8814 - auc: 0.9466 - loss: 0.2945 - val_acc: 0.8545 - val_auc: 0.9276 - val_loss: 0.3444
Epoch 35/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 356ms/step - acc: 0.8861 - auc: 0.9520 - loss: 0.2799
Epoch 35: val_acc did not improve from 0.85449
41/41 ━━━━━━━━━━━━━━━━━━━━ 22s 422ms/step - acc: 0.8861 - auc: 0.9520 - loss: 0.2800 - val_acc: 0.8491 - val_auc: 0.9273 - val_loss: 0.3437
Epoch 36/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 345ms/step - acc: 0.8862 - auc: 0.9494 - loss: 0.2878
Epoch 36: val_acc did not improve from 0.85449
41/41 ━━━━━━━━━━━━━━━━━━━━ 18s 369ms/step - acc: 0.8862 - auc: 0.9494 - loss: 0.2878 - val_acc: 0.8498 - val_auc: 0.9249 - val_loss: 0.3489
Epoch 37/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 345ms/step - acc: 0.8896 - auc: 0.9531 - loss: 0.2769
Epoch 37: val_acc did not improve from 0.85449
41/41 ━━━━━━━━━━━━━━━━━━━━ 20s 369ms/step - acc: 0.8896 - auc: 0.9531 - loss: 0.2769 - val_acc: 0.8529 - val_auc: 0.9270 - val_loss: 0.3499
Epoch 38/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 349ms/step - acc: 0.8860 - auc: 0.9518 - loss: 0.2798
Epoch 38: val_acc did not improve from 0.85449
41/41 ━━━━━━━━━━━━━━━━━━━━ 21s 385ms/step - acc: 0.8862 - auc: 0.9519 - loss: 0.2796 - val_acc: 0.8514 - val_auc: 0.9302 - val_loss: 0.3390
Epoch 39/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 338ms/step - acc: 0.8852 - auc: 0.9546 - loss: 0.2729
Epoch 39: val_acc improved from 0.85449 to 0.85913, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_CNN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 15s 373ms/step - acc: 0.8852 - auc: 0.9546 - loss: 0.2728 - val_acc: 0.8591 - val_auc: 0.9294 - val_loss: 0.3438
Epoch 40/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 336ms/step - acc: 0.8801 - auc: 0.9525 - loss: 0.2791
Epoch 40: val_acc did not improve from 0.85913
41/41 ━━━━━━━━━━━━━━━━━━━━ 20s 369ms/step - acc: 0.8802 - auc: 0.9526 - loss: 0.2789 - val_acc: 0.8498 - val_auc: 0.9294 - val_loss: 0.3497
Epoch 41/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 340ms/step - acc: 0.8978 - auc: 0.9561 - loss: 0.2675
Epoch 41: val_acc improved from 0.85913 to 0.86068, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_CNN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 16s 375ms/step - acc: 0.8976 - auc: 0.9561 - loss: 0.2675 - val_acc: 0.8607 - val_auc: 0.9315 - val_loss: 0.3380
Epoch 42/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 337ms/step - acc: 0.9000 - auc: 0.9641 - loss: 0.2423
Epoch 42: val_acc did not improve from 0.86068
41/41 ━━━━━━━━━━━━━━━━━━━━ 20s 370ms/step - acc: 0.8999 - auc: 0.9641 - loss: 0.2425 - val_acc: 0.8506 - val_auc: 0.9325 - val_loss: 0.3403
Epoch 43/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 354ms/step - acc: 0.8954 - auc: 0.9582 - loss: 0.2608
Epoch 43: val_acc did not improve from 0.86068
41/41 ━━━━━━━━━━━━━━━━━━━━ 16s 388ms/step - acc: 0.8955 - auc: 0.9583 - loss: 0.2607 - val_acc: 0.8568 - val_auc: 0.9334 - val_loss: 0.3371
Epoch 44/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 345ms/step - acc: 0.8962 - auc: 0.9617 - loss: 0.2505
Epoch 44: val_acc improved from 0.86068 to 0.86146, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_CNN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 20s 380ms/step - acc: 0.8962 - auc: 0.9617 - loss: 0.2505 - val_acc: 0.8615 - val_auc: 0.9341 - val_loss: 0.3328
Epoch 45/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 337ms/step - acc: 0.9040 - auc: 0.9670 - loss: 0.2329
Epoch 45: val_acc did not improve from 0.86146
41/41 ━━━━━━━━━━━━━━━━━━━━ 20s 370ms/step - acc: 0.9040 - auc: 0.9670 - loss: 0.2332 - val_acc: 0.8491 - val_auc: 0.9307 - val_loss: 0.3404
Epoch 46/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 354ms/step - acc: 0.9061 - auc: 0.9660 - loss: 0.2381
Epoch 46: val_acc did not improve from 0.86146
41/41 ━━━━━━━━━━━━━━━━━━━━ 22s 420ms/step - acc: 0.9061 - auc: 0.9660 - loss: 0.2380 - val_acc: 0.8584 - val_auc: 0.9338 - val_loss: 0.3427
Epoch 47/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 350ms/step - acc: 0.8968 - auc: 0.9621 - loss: 0.2492
Epoch 47: val_acc did not improve from 0.86146
41/41 ━━━━━━━━━━━━━━━━━━━━ 19s 375ms/step - acc: 0.8968 - auc: 0.9621 - loss: 0.2492 - val_acc: 0.8553 - val_auc: 0.9320 - val_loss: 0.3392
Epoch 48/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 345ms/step - acc: 0.9071 - auc: 0.9697 - loss: 0.2237
Epoch 48: val_acc did not improve from 0.86146
41/41 ━━━━━━━━━━━━━━━━━━━━ 16s 379ms/step - acc: 0.9070 - auc: 0.9697 - loss: 0.2239 - val_acc: 0.8553 - val_auc: 0.9337 - val_loss: 0.3354
Epoch 49/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 348ms/step - acc: 0.9153 - auc: 0.9725 - loss: 0.2139
Epoch 49: val_acc improved from 0.86146 to 0.86455, saving model to /content/drive/MyDrive/MACSynDCR/saveModel/best_MACSynDCR_CNN_model.keras
41/41 ━━━━━━━━━━━━━━━━━━━━ 20s 378ms/step - acc: 0.9151 - auc: 0.9724 - loss: 0.2142 - val_acc: 0.8646 - val_auc: 0.9362 - val_loss: 0.3300
Epoch 50/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 350ms/step - acc: 0.9039 - auc: 0.9673 - loss: 0.2310
Epoch 50: val_acc did not improve from 0.86455
41/41 ━━━━━━━━━━━━━━━━━━━━ 21s 383ms/step - acc: 0.9041 - auc: 0.9674 - loss: 0.2309 - val_acc: 0.8584 - val_auc: 0.9328 - val_loss: 0.3453
Epoch 51/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 332ms/step - acc: 0.9135 - auc: 0.9706 - loss: 0.2200
Epoch 51: val_acc did not improve from 0.86455
41/41 ━━━━━━━━━━━━━━━━━━━━ 20s 365ms/step - acc: 0.9134 - auc: 0.9706 - loss: 0.2200 - val_acc: 0.8591 - val_auc: 0.9342 - val_loss: 0.3353
Epoch 52/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 343ms/step - acc: 0.9088 - auc: 0.9700 - loss: 0.2216
Epoch 52: val_acc did not improve from 0.86455
41/41 ━━━━━━━━━━━━━━━━━━━━ 21s 376ms/step - acc: 0.9090 - auc: 0.9700 - loss: 0.2215 - val_acc: 0.8584 - val_auc: 0.9335 - val_loss: 0.3370
Epoch 53/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 331ms/step - acc: 0.9065 - auc: 0.9693 - loss: 0.2240
Epoch 53: val_acc did not improve from 0.86455
41/41 ━━━━━━━━━━━━━━━━━━━━ 20s 365ms/step - acc: 0.9064 - auc: 0.9693 - loss: 0.2240 - val_acc: 0.8591 - val_auc: 0.9320 - val_loss: 0.3415
Epoch 54/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 350ms/step - acc: 0.9054 - auc: 0.9711 - loss: 0.2175
Epoch 54: val_acc did not improve from 0.86455
41/41 ━━━━━━━━━━━━━━━━━━━━ 22s 416ms/step - acc: 0.9053 - auc: 0.9711 - loss: 0.2177 - val_acc: 0.8506 - val_auc: 0.9313 - val_loss: 0.3475
Epoch 55/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 351ms/step - acc: 0.9134 - auc: 0.9727 - loss: 0.2111
Epoch 55: val_acc did not improve from 0.86455
41/41 ━━━━━━━━━━━━━━━━━━━━ 19s 384ms/step - acc: 0.9135 - auc: 0.9728 - loss: 0.2109 - val_acc: 0.8576 - val_auc: 0.9320 - val_loss: 0.3489
Epoch 56/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 354ms/step - acc: 0.9220 - auc: 0.9760 - loss: 0.1984
Epoch 56: val_acc did not improve from 0.86455
41/41 ━━━━━━━━━━━━━━━━━━━━ 21s 387ms/step - acc: 0.9218 - auc: 0.9760 - loss: 0.1985 - val_acc: 0.8615 - val_auc: 0.9328 - val_loss: 0.3424
Epoch 57/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 355ms/step - acc: 0.9267 - auc: 0.9785 - loss: 0.1906
Epoch 57: val_acc did not improve from 0.86455
41/41 ━━━━━━━━━━━━━━━━━━━━ 16s 388ms/step - acc: 0.9265 - auc: 0.9784 - loss: 0.1907 - val_acc: 0.8452 - val_auc: 0.9314 - val_loss: 0.3492
Epoch 58/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 359ms/step - acc: 0.9146 - auc: 0.9735 - loss: 0.2076
Epoch 58: val_acc did not improve from 0.86455
41/41 ━━━━━━━━━━━━━━━━━━━━ 21s 392ms/step - acc: 0.9146 - auc: 0.9735 - loss: 0.2076 - val_acc: 0.8498 - val_auc: 0.9326 - val_loss: 0.3451
Epoch 59/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 352ms/step - acc: 0.9231 - auc: 0.9764 - loss: 0.1966
Epoch 59: val_acc did not improve from 0.86455
41/41 ━━━━━━━━━━━━━━━━━━━━ 16s 385ms/step - acc: 0.9230 - auc: 0.9764 - loss: 0.1968 - val_acc: 0.8529 - val_auc: 0.9342 - val_loss: 0.3377
Epoch 60/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 342ms/step - acc: 0.9196 - auc: 0.9772 - loss: 0.1951
Epoch 60: val_acc did not improve from 0.86455
41/41 ━━━━━━━━━━━━━━━━━━━━ 20s 376ms/step - acc: 0.9195 - auc: 0.9772 - loss: 0.1951 - val_acc: 0.8553 - val_auc: 0.9316 - val_loss: 0.3747
Epoch 61/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 337ms/step - acc: 0.9219 - auc: 0.9776 - loss: 0.1936
Epoch 61: val_acc did not improve from 0.86455
41/41 ━━━━━━━━━━━━━━━━━━━━ 15s 371ms/step - acc: 0.9219 - auc: 0.9776 - loss: 0.1936 - val_acc: 0.8553 - val_auc: 0.9360 - val_loss: 0.3488
Epoch 62/200
41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 342ms/step - acc: 0.9212 - auc: 0.9752 - loss: 0.2008
Epoch 62: val_acc did not improve from 0.86455

# External validation using Arestozeneca dataset:

In [ ]:
import pandas as pd
drugdata = pd.read_csv('/content/drive/MyDrive/MACSynDCR/Data/AstraZeneca independent set.csv')
drugdata = pd.DataFrame(data=drugdata)
smilesdata = pd.read_csv('/content/drive/MyDrive/MACSynDCR/Data/Drug/smiles.csv')
smilesdata = pd.DataFrame(data=smilesdata)
drugdata

,drug1,drug2,cell,label
0,CNC(=O)CN1CCC(CC1)Oc2cc3c(cc2OC)ncnc3Nc4cccc(c...,c1cc(ccc1[C@H](CCO)NC(=O)C2(CCN(CC2)c3c4cc[nH]...,J82,1
1,CNC(=O)CN1CCC(CC1)Oc2cc3c(cc2OC)ncnc3Nc4cccc(c...,c1cc(ccc1[C@H](CCO)NC(=O)C2(CCN(CC2)c3c4cc[nH]...,SW780,0
2,C[C@@H]1CN(C[C@@H](N1)C)c2ccc(cc2)C(=O)Nc3cc(n...,c1cc(ccc1[C@H](CCO)NC(=O)C2(CCN(CC2)c3c4cc[nH]...,SW780,0
3,C[C@@H]1CN(C[C@@H](N1)C)c2ccc(cc2)C(=O)Nc3cc(n...,c1cc(ccc1[C@H](CCO)NC(=O)C2(CCN(CC2)c3c4cc[nH]...,TCCSUP,1
4,CS(=O)(=O)N1CCN(CC1)Cc2cc3c(s2)c(nc(n3)c4cccc5...,c1ccc(cc1)c2cc3c(ccn4c3n[nH]c4=O)nc2c5ccc(cc5)...,HCC1187,1
...,...,...,...,...
663,CN1CCN(CC1)CCOc2cc3c(c(c2)OC4CCOCC4)c(ncn3)Nc5...,c1ccc(cc1)c2cccc(c2N3CCC[C@H](C3)N)/C=C\4/C(=O...,TCCSUP,1
664,CN1CCC(CC1)COc2cc3c(cc2OC)c(ncn3)Nc4ccc(cc4F)Br,CS(=O)(=O)c1ccc(cc1)Nc2cncc(n2)c3cnc4n3cccc4,SW48,1
665,CN1CCC(CC1)COc2cc3c(cc2OC)c(ncn3)Nc4ccc(cc4F)Br,CS(=O)(=O)c1ccc(cc1)Nc2cncc(n2)c3cnc4n3cccc4,SW48,1
666,c1cn(c(=O)nc1N)C2C(C(C(O2)CO)O)(F)F,C[C@@H]1COCCN1c2cc(nc(n2)c3ccnc4c3cc[nH]4)C5(C...,SW780,1
667,c1cn(c(=O)nc1N)C2C(C(C(O2)CO)O)(F)F,C[C@@H]1COCCN1c2cc(nc(n2)c3ccnc4c3cc[nH]4)C5(C...,TCCSUP,1

In [ ]:
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import DataLoader, TensorDataset
from sklearn.metrics import (roc_auc_score, accuracy_score, average_precision_score,
                             balanced_accuracy_score, precision_score, recall_score,
                             f1_score, cohen_kappa_score, mean_squared_error)
from scipy.stats import pearsonr
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras import layers
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dropout, Dense
from tensorflow.keras.utils import to_categorical

# -------------------------------
# 1. Load data
# -------------------------------
train_df = pd.read_csv("/content/drive/MyDrive/MACSynDCR/Data/TranData_Ind_AstraZeneca_dataset_1664.csv")
test_df = pd.read_csv("/content/drive/MyDrive/MACSynDCR/Data/Exyernel_Ind_AstraZeneca_feature_dataset_1664.csv")

#X_train = train_df.iloc[:, :-1].values.astype(np.float32)
#y_train = train_df.iloc[:, -1].values.astype(int)

#X_test = test_df.iloc[:, :-1].values.astype(np.float32)
#y_test = test_df.iloc[:, -1].values.astype(int)

#X_train = train_df.iloc[:, :-1].to_numpy()  # all columns except last → features
#y_train = train_df.iloc[:, -1].to_numpy()   # last column → label

#X_test = test_df.iloc[:, :-1].to_numpy()
#y_test = test_df.iloc[:, -1].to_numpy()

# Assuming train_data and test_data are DataFrames
X_train = train_df.iloc[:, :1664].to_numpy(dtype=np.float32)  # all columns except last
print(X_train.shape)
y_train = train_df.iloc[:,1665].to_numpy(dtype=np.int64)
print(y_train)

X_test = test_df.iloc[:, :1664].to_numpy(dtype=np.float32)
print(X_test.shape)
y_test = test_df.iloc[:,1665].to_numpy(dtype=np.int64)

# Now reshape for CNN
# 1664 features → 52 x 32 x 1


# Standardize features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# -------------------------------
# 2. PyTorch ANN
# -------------------------------
class MACSynDCR_ANN(nn.Module):
    def __init__(self, input_dim):
        super(MACSynDCR_ANN, self).__init__()
        self.fc1 = nn.Linear(input_dim, 1024)
        self.bn1 = nn.BatchNorm1d(1024)
        self.fc3 = nn.Linear(1024, 512)
        self.bn3 = nn.BatchNorm1d(512)
        self.fc4 = nn.Linear(512, 256)
        self.bn4 = nn.BatchNorm1d(256)
        self.fc5 = nn.Linear(256, 64)
        self.bn5 = nn.BatchNorm1d(64)
        self.fc6 = nn.Linear(64, 2)

    def forward(self, x):
        x = F.relu(self.bn1(self.fc1(x)))
        x = F.relu(self.bn3(self.fc3(x)))
        x = F.relu(self.bn4(self.fc4(x)))
        x = F.relu(self.bn5(self.fc5(x)))
        x = F.softmax(self.fc6(x), dim=1)
        return x

def train_pytorch_ann(X_train, y_train, epochs=20, batch_size=32, lr=1e-3):
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model = MACSynDCR_ANN(X_train.shape[1]).to(device)
    optimizer = torch.optim.Adam(model.parameters(), lr=lr)
    criterion = nn.CrossEntropyLoss()

    dataset = TensorDataset(torch.tensor(X_train, dtype=torch.float32),
                            torch.tensor(y_train, dtype=torch.long))
    loader = DataLoader(dataset, batch_size=batch_size, shuffle=True)

    model.train()
    for epoch in range(epochs):
        for xb, yb in loader:
            xb, yb = xb.to(device), yb.to(device)
            optimizer.zero_grad()
            outputs = model(xb)
            loss = criterion(outputs, yb)
            loss.backward()
            optimizer.step()
    return model, device

def predict_pytorch_ann(model, device, X):
    model.eval()
    with torch.no_grad():
        X_tensor = torch.tensor(X, dtype=torch.float32).to(device)
        probs = model(X_tensor).cpu().numpy()[:,1]  # probability of class 1
    return probs

# -------------------------------
# 3. Keras ANN
# -------------------------------
def build_KANN_model(input_dim):
    model = Sequential([
        layers.Input(shape=(input_dim,)),
        layers.Dense(2048, activation='relu'),
        layers.BatchNormalization(),
        layers.Dense(1024, activation='relu'),
        layers.BatchNormalization(),
        layers.Dense(512, activation='relu'),
        layers.BatchNormalization(),
        layers.Dense(256, activation='relu'),
        layers.BatchNormalization(),
        layers.Dense(128, activation='relu'),
        layers.BatchNormalization(),
        layers.Dense(2, activation='softmax')
    ])
    model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
    return model

# -------------------------------
# 4. Keras CNN
# -------------------------------
def build_KCNN_model(input_shape):
    model = Sequential([
        Conv2D(32, (3,3), activation='relu', input_shape=input_shape),
        MaxPooling2D((2,2)),
        Dropout(0.2),
        Conv2D(64, (3,3), activation='relu'),
        MaxPooling2D((2,2)),
        Dropout(0.2),
        Conv2D(128, (3,3), activation='relu'),
        MaxPooling2D((2,2)),
        Dropout(0.2),
        Flatten(),
        Dense(128, activation='relu'),
        Dense(2, activation='softmax')
    ])
    model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
    return model

# Reshape data for CNN (example, adapt if needed)
#X_train_cnn = X_train.reshape(-1, 52, 32, 1)
#X_test_cnn = X_test.reshape(-1, 52, 32, 1)
X_train_cnn = X_train.reshape(-1, 52, 32, 1)
X_test_cnn  = X_test.reshape(-1, 52, 32, 1)
y_train_cat = to_categorical(y_train, 2)
y_test_cat = to_categorical(y_test, 2)

# -------------------------------
# 5. Train all models
# -------------------------------
# PyTorch ANN
ann_model, device = train_pytorch_ann(X_train, y_train, epochs=20)
ann_probs_test = predict_pytorch_ann(ann_model, device, X_test)

# Keras ANN
kann_model = build_KANN_model(X_train.shape[1])
kann_model.fit(X_train, y_train_cat, epochs=20, batch_size=32, verbose=0)
kann_probs_test = kann_model.predict(X_test)[:,1]

# Keras CNN
kcnn_model = build_KCNN_model((52,32,1))
kcnn_model.fit(X_train_cnn, y_train_cat, epochs=20, batch_size=32, verbose=0)
kcnn_probs_test = kcnn_model.predict(X_test_cnn)[:,1]

# -------------------------------
# 6. Stacking Ensemble with Logistic Regression
# -------------------------------
stacked_test = np.column_stack((ann_probs_test, kann_probs_test, kcnn_probs_test))
meta_model = LogisticRegression()
meta_model.fit(stacked_test, y_test)  # Usually fit on OOF training preds
ensemble_probs = meta_model.predict_proba(stacked_test)[:,1]
ensemble_pred = (ensemble_probs > 0.5).astype(int)

# -------------------------------
# 7. Compute all metrics
# -------------------------------
def compute_metrics(y_true, y_prob):
    y_pred = (y_prob > 0.5).astype(int)
    auc = roc_auc_score(y_true, y_prob)
    acc = accuracy_score(y_true, y_pred)
    auc_pr = average_precision_score(y_true, y_prob)
    bacc = balanced_accuracy_score(y_true, y_pred)
    precision = precision_score(y_true, y_pred)
    recall = recall_score(y_true, y_pred)
    f1 = f1_score(y_true, y_pred)
    kappa = cohen_kappa_score(y_true, y_pred)
    rmse = np.sqrt(mean_squared_error(y_true, y_pred))
    pcc, _ = pearsonr(y_true, y_prob)
    return {"AUC-ROC": auc, "ACC": acc, "AUC-PR": auc_pr, "BACC": bacc,
            "Precision": precision, "Recall": recall, "F1": f1, "Kappa": kappa,
            "RMSE": rmse, "PCC": pcc}

metrics = compute_metrics(y_test, ensemble_probs)
print(metrics)

(12415, 1664)
[0 0 0 ... 1 1 1]
(665, 1664)
21/21 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step
21/21 ━━━━━━━━━━━━━━━━━━━━ 1s 39ms/step
{'AUC-ROC': np.float64(0.5543233418082876), 'ACC': 0.7172932330827068, 'AUC-PR': np.float64(0.7537061457830131), 'BACC': np.float64(0.5), 'Precision': 0.7172932330827068, 'Recall': 1.0, 'F1': 0.8353765323992994, 'Kappa': np.float64(0.0), 'RMSE': np.float64(0.5317017650123923), 'PCC': np.float64(0.09894571585121396)}

In [ ]:
df3 = pd.DataFrame({
    'actual_label': y_test,
    'probability': ensemble_probs
    })
df3.to_csv('/content/drive/MyDrive/MACSynDCR/Data/Externel_ArestaZenecaTest_ensemble_prob.csv', index=False)

In [ ]:
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import DataLoader, TensorDataset
from sklearn.metrics import (roc_auc_score, accuracy_score, average_precision_score,
                             balanced_accuracy_score, precision_score, recall_score,
                             f1_score, cohen_kappa_score, mean_squared_error)
from scipy.stats import pearsonr
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras import layers
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dropout, Dense
from tensorflow.keras.utils import to_categorical

In [ ]:
train_df = pd.read_csv("/content/drive/MyDrive/MACSynDCR/Data/MFSynDCPData.csv")
train_df

,drug1,drug2,cell,label
0,O=c1[nH]cc(F)c(=O)[nH]1,CC1(c2nc3c(C(N)=O)cccc3[nH]2)CCCN1,A375,0
1,O=c1[nH]cc(F)c(=O)[nH]1,CC1(c2nc3c(C(N)=O)cccc3[nH]2)CCCN1,CAOV3,0
2,O=c1[nH]cc(F)c(=O)[nH]1,CC1(c2nc3c(C(N)=O)cccc3[nH]2)CCCN1,HT144,0
3,O=c1[nH]cc(F)c(=O)[nH]1,CC1(c2nc3c(C(N)=O)cccc3[nH]2)CCCN1,HT29,1
4,O=c1[nH]cc(F)c(=O)[nH]1,CC1(c2nc3c(C(N)=O)cccc3[nH]2)CCCN1,LOVO,0
...,...,...,...,...
12410,O=C(CCCCCCC(=O)Nc1ccccc1)NO,CCC1(O)C(=O)OCc2c1cc1n(c2=O)Cc2cc3c(CN(C)C)c(O...,SKOV3,1
12411,O=C(CCCCCCC(=O)Nc1ccccc1)NO,CCC1(O)C(=O)OCc2c1cc1n(c2=O)Cc2cc3c(CN(C)C)c(O...,T47D,1
12412,O=C(CCCCCCC(=O)Nc1ccccc1)NO,CCC1(O)C(=O)OCc2c1cc1n(c2=O)Cc2cc3c(CN(C)C)c(O...,UACC62,1
12413,O=C(CCCCCCC(=O)Nc1ccccc1)NO,CCC1(O)C(=O)OCc2c1cc1n(c2=O)Cc2cc3c(CN(C)C)c(O...,VCAP,1
12414,O=C(CCCCCCC(=O)Nc1ccccc1)NO,CCC1(O)C(=O)OCc2c1cc1n(c2=O)Cc2cc3c(CN(C)C)c(O...,ZR751,1

In [ ]:
ext_df = pd.read_csv("/content/drive/MyDrive/MACSynDCR/Data/AstraZeneca independent set.csv")

In [ ]:
def pair_to_key(a, b):
    # unordered pair key, so (A,B) == (B,A)
    return tuple(sorted([a, b]))
# 1) Single-drug overlap
train_drugs = set(pd.unique(pd.concat([train_df['drug1'], train_df['drug1']])))
ext_drugs   = set(pd.unique(pd.concat([ext_df['drug1'],   ext_df['drug1']])))

overlap_drugs = train_drugs & ext_drugs
print("Overlapping drugs:", len(overlap_drugs))
# If this should be drug-LODO, expect 0 overlap.

# 2) Pair overlap (unordered)
train_pairs = set(train_df.apply(lambda r: pair_to_key(r['drug1'], r['drug2']), axis=1))
ext_pairs   = set(ext_df.apply(  lambda r: pair_to_key(r['drug1'], r['drug2']), axis=1))

overlap_pairs = train_pairs & ext_pairs
print("Overlapping drug pairs:", len(overlap_pairs))

# 3) Cell line overlap (only if you intended to hold out cells)
if 'cell' in train_df.columns and 'cell' in ext_df.columns:
    train_cells = set(train_df['cell'])
    ext_cells   = set(ext_df['cell'])
    overlap_cells = train_cells & ext_cells
    print("Overlapping cell lines:", len(overlap_cells))

Overlapping drugs: 0
Overlapping drug pairs: 0
Overlapping cell lines: 0